### PR TITLE
minor USB fixes

### LINKED ISSUE #2306: Delete empty parent directory when removing USB devices
When a USB device is removed (through hotplug or by removing the device entry), the parent directory in /dev/bus/usb isn't removed which makes it look a tiny bit different from what you'd see on the host.

LXD should attempt to rmdir the parent directory (/dev/bus/usb/XXX) and ignore failure which would reproduce the behavior we see on the host.

### LINKED ISSUE #2312: USB device entry leads to major/minor stored in device, causes start failure
@tych0 

So after playing with USB devices, I ended up having the following thing happen to me at startup time:

```
stgraber@castiana:~$ lxc start android
error: Invalid device configuration key for usb: major
Try `lxc info --show-log android` for more info
```

The container config is clearly wrong as it's storing what should be internal details:
```
stgraber@castiana:~$ lxc config show android
name: android
profiles:
- default
config:
  limits.cpu: "3"
  volatile.base_image: 34f838f28fd16387391e40de3a3efb16186b873384945eb908683d85cc042fec
  volatile.eth0.hwaddr: 00:16:3e:47:47:ab
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
  z5c:
    major: "189"
    minor: "4"
    path: /dev/bus/usb/001/005
    productid: 51da
    type: usb
    vendorid: 0fce
ephemeral: false
```

### PR DESCRIPTION
**Pull request by tych0**
* do a deep copy of the device entry so config doesn't accidentally get
  saved in the DB
* remember to remove the bus directory when a USB device goes away
* remove unused param to insertUnixDevice()

Closes #2306
Closes #2312

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -1130,12 +1130,17 @@ func (c *containerLXC) startCommon() (string, error) {
...
-				m["minor"] = fmt.Sprintf("%d", usb.minor)
-				m["path"] = usb.path
+				temp := shared.Device{}
+				if err := shared.DeepCopy(&m, &temp); err != nil {
+					return "", err
+				}
+
+				temp["major"] = fmt.Sprintf("%d", usb.major)
+				temp["minor"] = fmt.Sprintf("%d", usb.minor)
+				temp["path"] = usb.path
```
Comment (stgraber) [inline lxd/container_lxc.go]: I may be missing something, but this looks identical to createUSBDevice. Why not use it?

Comment (stgraber) [inline lxd/container_lxc.go]: Nevermind, that's because of insert vs create :)
