### PR TITLE
zfs: Make sure to allow devices, setuid and exec

### LINKED ISSUE #4084: zfs filesystems should have setuid/exec set to on
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info":
$ lxc info
config:
  core.proxy_http: http://apt.sdeziel.info:3142
  core.proxy_https: http://apt.sdeziel.info:3142
  storage.zfs_pool_name: data/lxd
api_extensions:
- id_map
- id_map_base
- resource_limits
api_status: stable
api_version: "1.0"
auth: trusted
auth_methods: []
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    [snip]
    -----END CERTIFICATE-----
  certificate_fingerprint: 7a03364b89f7b7a6e54174cfcd0781994bdde77b9ff7a6bfc7f6dcc96969d41b
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-103-generic
  server: lxd
  server_pid: 569
  server_version: 2.0.11
  storage: zfs
  storage_version: "5"

# Issue description

When initializing lxd, I used an existing zpool (data) so that containers would be stored under data/lxd. New containers would fail to start:

$ lxc launch ubuntu-daily:artful foo
Creating foo
Starting foo
error: Error calling 'lxd forkstart foo /var/lib/lxd/containers /var/log/lxd/foo/lxc.conf': err='Failed to run: /usr/bin/lxd forkstart foo /var/lib/lxd/containers /var/log/lxd/foo/lxc.conf: '

Setting exec=on on data/lxd/containers/foo worked around the above problem but lead to another one:

$ lxc start foo
$ lxc exec foo su - ubuntu
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@foo:~$ sudo -l
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

Setting setuid=on on data/lxd/containers/foo made it work.

Those 2 problems were cause by setuid=off and exec=off set on the data zpool/zfs. Creating a container should make the filesystem setuid/exec=on to avoid problem for those adopting existing storage backend that may have non-default configurations.

### PR DESCRIPTION
**Pull request by stgraber**
Closes #4084

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/storage_zfs.go [hunk 1]
```diff
@@ -238,6 +238,18 @@ func (s *storageZfs) zfsPoolCreate() error {
...
+
+			if err := zfsPoolVolumeSet(vdev, "", "setuid", "on"); err != nil {
+				return err
+			}
+
+			if err := zfsPoolVolumeSet(vdev, "", "exec", "on"); err != nil {
+				return err
+			}
+
+			if err := zfsPoolVolumeSet(vdev, "", "devices", "on"); err != nil {
```
Comment (brauner) [inline lxd/storage_zfs.go]: We should really have a method to set multiple properties at once if that is supported by zfs.

Comment (stgraber) [reply lxd/storage_zfs.go]: I don't think zfs supports modifying multiple properties at once.
