### PR TITLE
Remove subvolume in zfs.ImageCreate error flow

### LINKED ISSUE #2194: On image pull request - Not enough space problem
# Required information

 * Distribution:  Ubuntu Server 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
  * driver: lxc
  * driverversion: 2.0.1
  * kernel: Linux
  * kernelarchitecture: x86_64
  * kernelversion: 4.4.0-28-generic
  * server: lxd
  * serverpid: 2674
  * serverversion: 2.0.2
  * storage: zfs
  storageversion: "5"

# Issue description:
Not enough space in the zfs pool, makes LXD to stop the download process of the image with Fail message in "lxc monitor". However, the "incomplete" files that were downloaded in '/var/lib/lxd/images/'  are filling the zfs pool but since the "image copy" operation was not complete, they are not visible by lxd ("lxc image list"). So, LXD is not able to delete them with "lxc delete".
 
To solve this:
- LXD should check if there is enough space on the zfs pool before start the download process, and somehow reserve that space.
- When the image download process fails: either pause and then continue (if it is a connection problem) or delete the incomplete files (if the problem is not the connection).
 

# Steps to reproduce:

1. **Step one:** Make a few POST requests to https://**server**:**port**/1.0/images,  on LXD instance with  _**small**_ zfs pool:

Example:
```
{
"public": false,
"auto_update": true, 
"properties": {
                           "os": "...", 
},
"source": {
                      "type": "image",
                      "mode": "pull",  
                       "server": "...", 
                       "protocol": "lxd",
                       "alias": "..."      
    } 
}
```

2. **Step two**: Wait until the download process fails, because of "Not enough space".

3. **Step three**: Chack the zfs pool status with "zpool list", check how much images were copied with "lxc image list".

### PR DESCRIPTION
**Pull request by sean-jc**
Fixes #2194

Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

### CODE REVIEW

File: lxd/images.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func unpack(file string, path string) error {
 	if err != nil {
 		shared.Debugf("Unpacking failed")
 		shared.Debugf(string(output))
-		return err
+		return fmt.Errorf("Unpack failed, %s.", err)
```
Comment (tych0) [inline lxd/images.go]: Here it might be nice to include the output, since I think `err` is just some garbage golang gives us about the exit code of the command.

File: lxd/storage_zfs.go [hunk 2]
```diff
@@ -625,22 +625,31 @@ func (s *storageZfs) ImageCreate(fingerprint string) error {
 		return err
 	}
 
+	cleanup := func(err error) error {
+		if zerr := s.zfsDestroy(fs); zerr != nil {
+			err = fmt.Errorf("%s  During cleanup: %s", err, zerr)
+		}
+		if shared.PathExists(subvol) {
+			if oserr := os.Remove(subvol); oserr != nil {
```
Comment (tych0) [inline lxd/storage_zfs.go]: Doesn't this need to be a RemoveAll?

File: lxd/images.go (hunk 1 above)
Comment (sean-jc) [inline lxd/images.go]: Yeah, `err` isn't super helpful, but unfortunately `output` is often massive, like hundreds of lines.  I'll see what type of messages show up if I grab the first ~80 chars of the output.

Comment (tych0) [inline lxd/images.go]: On Wed, Jul 20, 2016 at 10:54:24AM -0700, Sean Christopherson wrote:
> > @@ -106,7 +106,7 @@ func unpack(file string, path string) error {
> >  	if err != nil {
> >  		shared.Debugf("Unpacking failed")
> >  		shared.Debugf(string(output))
> > -		return err
> > +		return fmt.Errorf("Unpack failed, %s.", err)
> 
> Yeah, `err` isn't super helpful, but unfortunately `output` is often massive, like hundreds of lines.  I'll see what type of messages show up if I grab the first ~80 chars of the output.

The last 20 lines or something may also be useful; that's probably
where there error happened. Do we have verbose on where we shouldn't?

File: lxd/storage_zfs.go (hunk 2 above)
Comment (sean-jc) [inline lxd/storage_zfs.go]: I don't think so?  I'm pretty sure the only way subvol would be non-empty is if zfsDestroy failed, in which case I think both Remove and RemoveAll would fail due to "resource busy".

Hold off on merging this for now, I'll follow-up with the submitter of #2194 to find out what exactly was left laying around after the failed image pull.

File: lxd/images.go (hunk 1 above)
Comment (sean-jc) [inline lxd/images.go]: > Do we have verbose on where we shouldn't?

I don't think so.  On my system tar complains about every single failure once the disk runs out of space, i.e. output has hundreds of lines complaining about "not enough space".  I'm hesitant to capture only the tail of the output in case the original failure was somehow different than subsequent failures.

Comment (tych0) [inline lxd/images.go]: On Wed, Jul 20, 2016 at 11:19:19AM -0700, Sean Christopherson wrote:
> > @@ -106,7 +106,7 @@ func unpack(file string, path string) error {
> >  	if err != nil {
> >  		shared.Debugf("Unpacking failed")
> >  		shared.Debugf(string(output))
> > -		return err
> > +		return fmt.Errorf("Unpack failed, %s.", err)
> 
> > Do we have verbose on where we shouldn't?
> 
> I don't think so.  On my system tar complains about every single failure once the disk runs out of space, i.e. output has hundreds of lines complaining about "not enough space".  I'm hesitant to capture only the tail of the output in case the original failure was somehow different than subsequent failures.

Ah, I see. The first few lines sounds good to me then too!

Tycho

File: lxd/storage_zfs.go (hunk 2 above)
Comment (tych0) [inline lxd/storage_zfs.go]: On Wed, Jul 20, 2016 at 11:16:19AM -0700, Sean Christopherson wrote:
> > @@ -625,22 +625,31 @@ func (s *storageZfs) ImageCreate(fingerprint string) error {
> >  		return err
> >  	}
> >  
> > +	cleanup := func(err error) error {
> > +		if zerr := s.zfsDestroy(fs); zerr != nil {
> > +			err = fmt.Errorf("%s  During cleanup: %s", err, zerr)
> > +		}
> > +		if shared.PathExists(subvol) {
> > +			if oserr := os.Remove(subvol); oserr != nil {
> 
> I don't think so?  I'm pretty sure the only way subvol would be non-empty is if zfsDestroy failed, in which case I think both Remove and RemoveAll would fail due to "resource busy".
> 
> Hold off on merging this for now, I'll follow-up with the submitter of #2194 to find out what exactly was left laying around after the failed image pull.

But if the directory is empty, then I don't see how this fixes the
problem in #2194; isn't that about leaving stuff around that actually
takes up space?

Comment (sean-jc) [inline lxd/storage_zfs.go]: > But if the directory is empty, then I don't see how this fixes the
> problem in #2194; isn't that about leaving stuff around that actually
> takes up space?
That's my understanding as well, hence my theory that zfsDestroy is failing.  If zfsDestroy fails I don't think there's much that can be done other than propagating the cleanup error to the user.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Doesn't look like the original reporter is particularly responsive, so I guess we can just go ahead with this branch, it won't make things any worse at least :)
