### PR TITLE
Fix AppArmor stack handling with nesting

### LINKED ISSUE #3172: Unable to create nested container in privileged
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-72-generic
   * LXC version: 2.12
   * LXD version: 2.12
   * Storage backend in use: btrfs

# Issue description
Unable to create nested container in privileged.
Create a privileged and nested container container and create containers in that container.
Without the setting the host container on privileged, will start the container _template_.

# Steps to reproduce

 1. Create container on host with security.privileged=true and security.nesting=true. Named it _web_.
 2. Create a subcontainer (nested container), named it _template_
 3. Start the template. That fails.

# Information to attach
```
root@web:~# cat /var/log/lxd/template/lxc.log
lxc 20170413120902.896 ERROR    lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:234 - No such file or directory - failed to change apparmor profile to lxd-template_</var/lib/lxd>//&:lxd-template_<var-lib-lxd>:
lxc 20170413120902.896 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
lxc 20170413120902.896 ERROR    lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "template". 
lxc 20170413120903.436 ERROR    lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
lxc 20170413120903.436 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "template". 
lxc 20170413120903.437 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
lxc 20170413120903.437 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.
```

### PR DESCRIPTION
**Pull request by stgraber**
This does the following
 - Re-work detection code to always fill all the various AppArmor variables
 - Add detection of LXD being run in an AppArmor stacked configuration
 - If running stacked (nesting), then load a per-container profile but
   don't attempt to setup a second level of stacking as this isn't
   supported by AppArmor.
 - Treat a security.privileged=true container inside an unprivileged
   container the same as running an unprivileged container.

Closes #3172

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/daemon.go [hunk 1]
```diff
@@ -545,90 +546,91 @@ func (d *Daemon) Init() error {
 	/* Detect user namespaces */
 	runningInUserns = shared.RunningInUserNS()
 
-	/* Detect AppArmor support */
-	if aaAvailable && os.Getenv("LXD_SECURITY_APPARMOR") == "false" {
-		aaAvailable = false
-		aaAdmin = false
+	/* Detect AppArmor availability */
+	_, err = exec.LookPath("apparmor_parser")
+	if os.Getenv("LXD_SECURITY_APPARMOR") == "false" {
```
Comment (brauner) [inline lxd/daemon.go]: Not a merge-blocker but do we describe this env variable somewhere already?

File: lxd/daemon.go [hunk 2]
```diff
@@ -545,90 +546,91 @@ func (d *Daemon) Init() error {
...
+		contentBytes, err := ioutil.ReadFile("/sys/kernel/security/apparmor/features/domain/stack")
+		if err != nil {
+			return false
+		}
 
-	if aaAdmin && runningInUserns {
-		aaAdmin = false
-		logger.Warnf("Per-container AppArmor profiles are disabled because LXD is running in an unprivileged container.")
-	}
+		if string(contentBytes) != "yes\n" {
```
Comment (brauner) [inline lxd/daemon.go]: Hm, so should we maybe trim whitespace on the output of `ReadFile()` to exclude any surprises like `  yes\n` or `yes\n\n`?

Comment (brauner) [inline lxd/daemon.go]: Like you're doing below for the domain lookup.

File: lxd/daemon.go [hunk 3]
```diff
@@ -545,90 +546,91 @@ func (d *Daemon) Init() error {
...
-				}
-			}
+		return major >= 1 && minor >= 2
+	}
+
+	aaStacking = aaCanStack()
+
+	/* Detect existing AppArmor stack */
+	if shared.PathExists("/sys/kernel/security/apparmor/.ns_stacked") {
+		contentBytes, err := ioutil.ReadFile("/sys/kernel/security/apparmor/.ns_stacked")
```
Comment (brauner) [inline lxd/daemon.go]: Same comment about trimming whitespace.

File: lxd/daemon.go (hunk 1 above)
Comment (stgraber) [inline lxd/daemon.go]: No and I don't really want to, it's only needed because of Snappy 15 and will die a horrible death as soon as we stop caring about that :)

Comment (brauner) [inline lxd/daemon.go]: lol :)
