### PR TITLE
api: Allow the selection of cluster groups when moving instances

### LINKED ISSUE #11666: Cluster groups - moving an instance does not allow one to specify a cluster group
# Required information

lxd 5.13

snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     latest/candidate
refresh-date: yesterday at 03:36 UTC

3 node cluster

# Issue description

Working with cluster groups, I can launch instances targeting cluster groups but the move command does not allow the same.

# Steps to reproduce
```
lxc cluster group create g1
lxc cluster group create g2
lxc cluster group assign node1 g1
lxc cluster group assign node2 g1
lxc cluster group assign node3 g2
lxc cluster group list
lxc launch images:ubuntu/22.04 c1 --target=@g1
lxc list 
lxc stop c1
lxc move c1 --target=@g2
==> error
lxc move c1 --target=node3
lxc list
==> works!
```
# Information to attach

The error I am getting:
Error: Migration API failure: Failed to get target node: Cluster member not found

### PR DESCRIPTION
**Pull request by roosterfish**
When launching new instances, the target node or cluster group can be defined by setting the `--target` flag. If specified the cluster members `scheduler.instance` or global `instances.placement.scriptlet` config setting gets evaluated to find a fitting target node. 

The same should apply when moving instances between cluster members. Especially when specifying `--target @group`, the scheduler mechanism can now pick up the right node from the list of cluster group members.

Since lots of the permission checking is done for both instance creation and movement, both endpoints should use the same functions for checking permissions when the `target` query parameter is set. The logic is now moved into the `lxd/project` package.

A new test suite is added for testing the movement of instances in clusters.

Fixes #11666

### CODE REVIEW

File: lxd/instance_post.go [hunk 1]
```diff
@@ -86,7 +91,19 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
 		return response.BadRequest(fmt.Errorf("Invalid instance name"))
 	}
 
-	targetNode := queryParam(r, "target")
+	target := queryParam(r, "target")
+	var targetNode, targetGroup string
```
Comment (monstermunchkin) [inline lxd/instance_post.go:98]: Please split this into 2 separate lines as we don't use a single lines for multiple declarations.

File: lxd/instance_post.go [hunk 2]
```diff
@@ -86,7 +91,19 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+	if strings.HasPrefix(target, "@") {
+		targetGroup = strings.TrimPrefix(target, "@")
+	} else {
+		targetNode = target
+	}
+
+	// Check if clustered.
+	clustered, err := cluster.Enabled(s.DB.Node)
+	if err != nil {
+		return response.InternalError(fmt.Errorf("Failed to check for cluster state: %w", err))
```
Comment (monstermunchkin) [inline lxd/instance_post.go:108]: `Failed checking cluster state`

File: lxd/instance_post.go [hunk 3]
```diff
@@ -95,6 +112,71 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
 	// online (only relevant if "?target=<node>" was given).
 	targetNodeOffline := false
 
+	// Resolve the target group to a valid node.
+	if targetGroup != "" && clustered && !clusterNotification {
+		err := s.DB.Cluster.Transaction(context.TODO(), func(ctx context.Context, tx *db.ClusterTx) error {
```
Comment (monstermunchkin) [inline lxd/instance_post.go:120]: Instead of passing `context.TODO()` we should pass `s.ShutdownCtx`.

File: lxd/instance_post.go [hunk 4]
```diff
@@ -157,24 +160,60 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
 			if err != nil {
-				return err
+				return response.InternalError(err)
 			}
 
-			// Reject moves to an empty cluster group.
-			if targetMemberInfo == nil {
-				return api.StatusErrorf(http.StatusBadRequest, "No suitable cluster member could be found")
+			// Fetch the instance
+			i, err := instance.LoadByProjectAndName(s, projectName, name)
```
Comment (monstermunchkin) [inline lxd/instance_post.go:177]: Please use `inst` instead of `i`.

File: lxd/instance_post.go [hunk 5]
```diff
@@ -157,24 +160,60 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+			}
 
-			return nil
+			targetMemberInfo, err = scriptlet.InstancePlacementRun(r.Context(), logger.Log, s, &req, candidateMembers, leaderAddress)
+			if err != nil {
+				return response.BadRequest(fmt.Errorf("Failed instance placement scriptlet: %w", err))
+			}
+		}
+
+		err = s.DB.Cluster.Transaction(context.TODO(), func(ctx context.Context, tx *db.ClusterTx) error {
```
Comment (monstermunchkin) [inline lxd/instance_post.go:202]: Please use `s.ShutdownCtx` instead of `context.TODO()`.

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

File: doc/howto/cluster_manage_instance.md [hunk 6]
```diff
@@ -37,3 +37,8 @@ For example, to move the instance `c1` to the cluster member `server1`, use the
     lxc start c1
 
 See {ref}`move-instances` for more information.
+
+To move an instance on a member of a cluster group, use the group name prefixed with `@` for the `--target` flag.
```
Comment (ru-fu) [inline doc/howto/cluster_manage_instance.md:41]:
```suggestion
To move an instance to a member of a cluster group, use the group name prefixed with `@` for the `--target` flag.
```
Just to avoid ambiguity. :)

Comment (roosterfish) [reply doc/howto/cluster_manage_instance.md:41]: Thanks, applied.

**Review by ru-fu — APPROVED** [review]
Doc update looks good. :)

File: lxd/instance_post.go [hunk 7]
```diff
@@ -95,6 +120,107 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
 	// online (only relevant if "?target=<node>" was given).
 	targetNodeOffline := false
 
+	if clustered && !clusterNotification {
```
Comment (roosterfish) [inline lxd/instance_post.go:123]: I have adapted this checking for cluster notifications from the instance creation endpoint. Is this even required here?

File: lxd/instance_post.go [hunk 8]
```diff
@@ -95,6 +120,107 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+					return api.StatusErrorf(http.StatusBadRequest, "Cluster group %q doesn't exist", targetGroup)
+				}
+
+				// Fetch all cluster group members.
+				allMembers, err := tx.GetNodes(s.ShutdownCtx)
+				if err != nil {
+					return err
+				}
+
+				candidateMembers, err = tx.GetCandidateMembers(s.ShutdownCtx, allMembers, []int{inst.Architecture()}, targetGroup, clusterGroupsAllowed, s.GlobalConfig.OfflineThreshold())
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/instance_post.go]: I think thats fine, as we wouldnt want it to select a candidate member that doesn't support the instance's architecture (as clusters can be made up of mixed architecture machines).

File: lxd/instance_post.go (hunk 7 above)
Comment (roosterfish) [reply lxd/instance_post.go:123]: @tomponline thanks, I appreciate the explanation, this makes it clear for me. Good that you mention it, I was trying to align the logic to what is written for the instance creation, but they both differ in a lot of places. I'll refactor them as you have suggested.

Comment (roosterfish) [reply lxd/instance_post.go]: After investigating the cluster notification for both instance creation and movement, I have put the placement logic for the movement after the potential redirect of the request so that it is only executed on the target machine. Unlike for the creation, I didn't see any cluster notification user agent in place for the movement.

File: shared/util.go [hunk 9]
```diff
@@ -1371,3 +1371,18 @@ func JoinTokenDecode(input string) (*api.ClusterMemberJoinToken, error) {
 
 	return &j, nil
 }
+
+// TargetDetect returns either target node or group based on the provided prefix:
+// An invocation with `target=h1` returns "h1", "" and
+// `target=@g1` returns "", "g1".
+func TargetDetect(target string) (string, string) {
```
Comment (tomponline) [inline shared/util.go:1378]: Given you're defining these vars at top of function, using named return vars in function definition would achieve the same effect but would be clearer to the reader in my view.

File: lxd/project/permissions.go [hunk 10]
```diff
@@ -1514,3 +1514,115 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+		if !found {
+			return fmt.Errorf("Project isn't allowed to use this cluster member")
+		}
+	}
+
+	return nil
+}
+
+// AllowClusterGroup returns nil if the given project is allowed to use the cluster group.
+func AllowClusterGroup(p *api.Project, group string) error {
```
Comment (tomponline) [inline lxd/project/permissions.go:1545]: Lets call `group` `groupName` to be explicit.

File: lxd/project/permissions.go [hunk 11]
```diff
@@ -1514,3 +1514,115 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+		return fmt.Errorf("Project isn't allowed to use this cluster group")
+	}
+
+	return nil
+}
+
+// CheckTargetMember checks if the given member is allowed for the project.
+// If nil it also returns the resolved target member node information.
+func CheckTargetMember(tx *db.ClusterTx, p *api.Project, targetMember string) (*db.NodeInfo, error) {
+	ctx := context.Background()
```
Comment (tomponline) [inline lxd/project/permissions.go:1563]: You should accept a ctx argument instead and leave it up to the caller what they provide.

File: lxd/project/permissions.go [hunk 12]
```diff
@@ -1514,3 +1514,115 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+	if err != nil {
+		return nil, api.StatusErrorf(http.StatusForbidden, err.Error())
+	}
+
+	return &member, nil
+}
+
+// CheckTargetGroup checks if the given group is allowed for the project.
+func CheckTargetGroup(tx *db.ClusterTx, p *api.Project, targetGroup string) error {
+	ctx := context.Background()
```
Comment (tomponline) [inline lxd/project/permissions.go:1582]: this should be an arg.

File: lxd/instances_post.go [hunk 13]
```diff
@@ -863,12 +862,7 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			return api.StatusErrorf(http.StatusBadRequest, "Target only allowed when clustered")
 		}
 
-		var targetMember, targetGroup string
-		if strings.HasPrefix(target, "@") {
-			targetGroup = strings.TrimPrefix(target, "@")
-		} else {
-			targetMember = target
-		}
+		_, targetGroup := shared.TargetDetect(queryParam(r, "target"))
```
Comment (tomponline) [inline lxd/instances_post.go:865]: The changes affecting instancesPost should be separated from the changes for instancePost, and come earlier in the PR.
This will aid with both reviewing and backporting into LTS branches.

File: test/suites/clustering_move.sh [hunk 14]
```diff
@@ -0,0 +1,198 @@
...
+  LXD_DIR="${LXD_ONE_DIR}" lxc cluster group create foobar3
+  LXD_DIR="${LXD_ONE_DIR}" lxc cluster group assign node3 foobar3,default
+
+  LXD_DIR="${LXD_ONE_DIR}" lxc init testimage c1 --target node1
+  LXD_DIR="${LXD_ONE_DIR}" lxc init testimage c2 --target node2
+  LXD_DIR="${LXD_ONE_DIR}" lxc init testimage c3 --target node3
+
+  # Perform default move tests falling back to the built in logic of choosing the node
+  # with the least number of instances when targeting a cluster group.
+
```
Comment (tomponline) [inline test/suites/clustering_move.sh:53]: extra newline not needed

File: test/suites/clustering_move.sh [hunk 15]
```diff
@@ -0,0 +1,198 @@
...
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target @foobar1
+  LXD_DIR="${LXD_ONE_DIR}" lxc info c1 | grep -q "Location: node1"
+
+  # c1 cannot be moved to the default group since it is already a member
+  ! LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target=@default || false
```
Comment (tomponline) [inline test/suites/clustering_move.sh:59]: Is this new behaviour in this PR?

File: test/suites/clustering_move.sh [hunk 16]
```diff
@@ -0,0 +1,198 @@
...
+
+  # Perform standard move tests using the `scheduler.instance` cluster member setting.
+  # At this stage we have:
```
Comment (tomponline) [inline test/suites/clustering_move.sh:62]: This comment through me a bit for 2 reasons:

1. It said "at this stage", which I read to be on the line it was at, and then got confused because on lines 70 and 71 it then proceed to set them up in that way.
2. The comment references "direct" targeting but the term used in the command is "manual", so would be good to be consistent here.

File: test/suites/clustering_move.sh [hunk 17]
```diff
@@ -0,0 +1,198 @@
...
+EOF
+
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target @foobar3
+  LXD_DIR="${LXD_ONE_DIR}" lxc info c1 | grep -q "Location: node3"
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c2 --target @foobar3
+  LXD_DIR="${LXD_ONE_DIR}" lxc info c2 | grep -q "Location: node3"
+
+  # Ensure that setting an invalid target won't interrupt the move and fall back to the built in behavior.
+  # Equally distribute the instances beforehand so that node1 will get selected.
+
```
Comment (tomponline) [inline test/suites/clustering_move.sh:120]: Lets lose these empty lines

File: test/suites/clustering_move.sh [hunk 18]
```diff
@@ -0,0 +1,198 @@
...
+        return
+EOF
+
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target @foobar1
+  LXD_DIR="${LXD_ONE_DIR}" lxc info c1 | grep -q "Location: node1"
+
+  # If the scriptlet produces a runtime error, the move fails.
+  cat << EOF | LXD_DIR="${LXD_ONE_DIR}" lxc config set instances.placement.scriptlet=-
+def instance_placement(request, candidate_members):
+        log_info("Accessing invalid field ", candidate_members[42])
```
[the remark this answers is not in the document]
Comment (tomponline) [reply test/suites/clustering_move.sh:138]: Oh I see you're targetting an invalid index. Could be made clearer I think.

[the remark this answers is not in the document]
Comment (roosterfish) [reply test/suites/clustering_move.sh:138]: The scriptlet tries to access index 42 which doesn't exist.

**Review by tomponline — APPROVED** [review]
Overall looks great, all suggested changes are nits/style/form really.

File: test/suites/clustering_move.sh (hunk 18 above)
[the remark this answers is not in the document]
Comment (tomponline) [reply test/suites/clustering_move.sh:138]: Yeah, when the comment said "runtime" I was expecting a `fail()` call.

[the remark this answers is not in the document]
Comment (roosterfish) [reply test/suites/clustering_move.sh:138]: I'll add a comment to clear things out :)

File: test/suites/clustering_move.sh (hunk 15 above)
Comment (roosterfish) [reply test/suites/clustering_move.sh:59]: Yes, I have added an explicit check for this. Otherwise  if a cluster group has multiple members, you can run `lxc move --target @group` infinite times and the instance will always be moved to another member (depending on the choosen scheduler configuration). Maybe it would be a good idea to add a hint in the docs?

Comment (tomponline) [reply test/suites/clustering_move.sh:59]: I'm not sure about this. One thing that may hint at a cause of confusion here is that I saw hints in some of the comments in this PR that an instance can be considered a "member" of a particular cluster group. I don't think that is really true.

Instances are not members of cluster groups. 

Instead when creating or moving an instance one can "prune" the potential candidates for the cluster member placement using a cluster group selector. So when thinking about it this way, as long as we always exclude the instance's current cluster member location from the list of candidates, then it could be totally valid to move an instance using the same cluster group multiple times.

Comment (roosterfish) [reply test/suites/clustering_move.sh:59]: Mhh yes, valid use case. It could be kind of a rescue mechanism to move all instances away from a member but still having them inside the same group. Otherwise you would need to create another group excluding a specific cluster member.

I'll add another test case for this behavior and remove the check.

Comment (tomponline) [reply test/suites/clustering_move.sh:59]: Well we do have `lxc cluster evacuate` for that, but it could be useful as a form of manual rebalancing.

File: shared/util.go (hunk 9 above)
Comment (roosterfish) [reply shared/util.go]: Changed to named return vars.

File: lxd/project/permissions.go (hunk 10 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Done, also for the function below to be consistent.

File: lxd/project/permissions.go (hunk 11 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Done for the entire call chain.

File: lxd/project/permissions.go (hunk 12 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Done.

File: test/suites/clustering_move.sh (hunk 14 above)
Comment (roosterfish) [reply test/suites/clustering_move.sh]: Removed.

File: test/suites/clustering_move.sh (hunk 15 above)
Comment (roosterfish) [reply test/suites/clustering_move.sh]: Check removed and additional test case added.

File: test/suites/clustering_move.sh (hunk 17 above)
Comment (roosterfish) [reply test/suites/clustering_move.sh]: Done.

File: test/suites/clustering_move.sh (hunk 18 above)
[the remark this answers is not in the document]
Comment (roosterfish) [reply test/suites/clustering_move.sh:140]: Done.

File: lxd/instance_post.go [hunk 19]
```diff
@@ -206,6 +196,87 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+					Project: projectName,
+					Reason:  apiScriptlet.InstancePlacementReasonRelocation,
+				}
+
+				targetMemberInfo, err = scriptlet.InstancePlacementRun(r.Context(), logger.Log, s, &req, candidateMembers, leaderAddress)
+				if err != nil {
+					return response.BadRequest(fmt.Errorf("Failed instance placement scriptlet: %w", err))
+				}
+			}
+		}
```
Comment (monstermunchkin) [inline lxd/instance_post.go:265]: This should be:
```go
if targetMemberInfo == nil && s.GlobalConfig.InstancesPlacementScriptlet() != "" {
```

File: test/suites/clustering_move.sh [hunk 20]
```diff
@@ -0,0 +1,199 @@
...
+  ! LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target @foobar3 || false
+  ! LXD_DIR="${LXD_ONE_DIR}" lxc move c2 --target node3 || false
+
+  # Moving instances in between the restricted groups
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target node2
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c2 --target @foobar1
+  LXD_DIR="${LXD_ONE_DIR}" lxc move c3 --target node1
+
+  # Cleanup
+  LXD_DIR="${LXD_ONE_DIR}" lxc delete c1 c2 c3
```
Comment (monstermunchkin) [inline test/suites/clustering_move.sh:183]: We tend to use the force flag (`-f`) when deleting instances.

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

File: test/suites/clustering_move.sh (hunk 20 above)
Comment (roosterfish) [reply test/suites/clustering_move.sh]: Added.

**Review by monstermunchkin — APPROVED** [review]

File: shared/util.go [hunk 21]
```diff
@@ -1371,3 +1371,16 @@ func JoinTokenDecode(input string) (*api.ClusterMemberJoinToken, error) {
 
 	return &j, nil
 }
+
+// TargetDetect returns either target node or group based on the provided prefix:
+// An invocation with `target=h1` returns "h1", "" and
+// `target=@g1` returns "", "g1".
+func TargetDetect(target string) (targetNode, targetGroup string) {
```
[the remark this answers is not in the document]
Comment (roosterfish) [reply shared/util.go:1378]: I'll fix it right away :) Tbh I didn't see this "pattern" somewhere else so I was wondering if this is a design decision.

File: lxd/instances_post.go [hunk 22]
```diff
@@ -880,65 +874,11 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
 		}
 
-		var allMembers []db.NodeInfo
-
 		if clustered && !clusterNotification {
-			clusterGroupsAllowed = shared.SplitNTrimSpace(targetProject.Config["restricted.cluster.groups"], ",", -1, true)
-
-			// Check manual cluster member targeting restrictions.
-			err = project.CheckClusterTargetRestriction(r, targetProject, target)
+			targetMemberInfo, err = project.CheckTarget(ctx, r, tx, targetProject, target)
```
Comment (tomponline) [inline lxd/instances_post.go:878]: This change caught my eye. Not because it doesn't clean up the code and improve the readability, it certainly does.

However, what caught by eye was the change of scope of allMembers var definition above, and the moving of the tx.GetNodes call to further down in the function.

On closer inspection, the reason you've been able to do this is because the `CheckTarget` function calls `CheckTargetMember` which in turn calls `tx.GetNodeByName`. 

This may seem harmless, but its important to remember that while dqlite is based upon sqlite, it does not have the same access characteristics. 

The key things to remember with dqlite are:

1. All queries are sent to the leader (which may not be this cluster member at the time) so can incur network latency.
2. Transactions can also incur network latency due to additional round trips (in order to start and commit them), so try and keep them to a minimal, which means doing as many queries as you can inside fewer transactions. Whilst also considering point 3...
3. Locking is at the database level (so don't keep transactions open longer than necessary).

So that extra call to `tx.GetNodeByName` is performing 4 extra queries (as that function loads the node info, node group info, node role info and node config).

Also this is all happening within the wider context of an instance creation request, which is something that occurs often and we should try and keep fast and lean (as opposed to some operation that happens only once in a blue moon).

So I think we should keep the tx.GetNodes where it is, and instead have `project.CheckTarget` accept a list of potential candidates which we can pass the list of nodes we already retrieved into.

File: lxd/instances_post.go [hunk 23]
```diff
@@ -1137,18 +1084,7 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
 		// If no target member was selected yet, pick the member with the least number of instances.
 		if targetMemberInfo == nil {
-			err = s.DB.Cluster.Transaction(r.Context(), func(ctx context.Context, tx *db.ClusterTx) error {
-				targetMemberInfo, err = tx.GetNodeWithLeastInstances(ctx, candidateMembers)
-				if err != nil {
-					return err
-				}
-
-				if targetMemberInfo == nil {
-					return api.StatusErrorf(http.StatusBadRequest, "No suitable cluster member could be found")
```
Comment (tomponline) [inline lxd/instances_post.go:1147]: Lets lose the `getNodeWithLeastInstances` function, as we are trying to move away from creating transactions inside lower level functions (for the reasons above that I described around doing as much as possible inside fewer transactions) so it helps to keep the transactions being created visible.

Instead lets push down the `return api.StatusErrorf(http.StatusBadRequest, "No suitable cluster member could be found")` error into the `GetNodeWithLeastInstances` function itself, so that `GetNodeWithLeastInstances` can never return a nil node info without a non-nil error.

We can then update the call sites of `GetNodeWithLeastInstances` to directly return the error or if needed to detect the specific not found error using `api.StatusErrorCheck(err, http.StatusNotFound)`

File: lxd/instance_post.go [hunk 24]
```diff
@@ -87,84 +90,71 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+	var targetMemberInfo *db.NodeInfo
+	var candidateMembers []db.NodeInfo
 
-			if address == "" {
-				// Local node.
-				sourceNodeOffline = false
-				return nil
-			}
+	// Load requested instance
+	inst, err = instance.LoadByProjectAndName(s, projectName, name)
```
[the remark this answers is not in the document]
Comment (roosterfish) [reply lxd/instance_post.go:108]: This happened because I moved `inst` up a few levels during refactoring. It's indeed not required anymore to define the var separately.

File: lxd/instance_post.go [hunk 25]
```diff
@@ -87,84 +90,71 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+			// Local node.
+			sourceNodeOffline = false
 			return nil
-		})
+		}
+
+		sourceMemberInfo, err := tx.GetNodeByAddress(ctx, sourceAddress)
 		if err != nil {
-			return response.SmartError(err)
+			return fmt.Errorf("Failed to get source member for %s: %w", sourceAddress, err)
```
Comment (tomponline) [inline lxd/instance_post.go:149]: Please can you use %q when putting string vars into errors, as it helps differentiate the value from the error itself.
Even more useful when/if the string is empty :)

File: lxd/instance_post.go [hunk 26]
```diff
@@ -87,84 +90,71 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
-			if err != nil {
-				return fmt.Errorf("Failed to get source member for %s: %w", address, err)
-			}
+	target := queryParam(r, "target")
+	if !clustered && target != "" {
+		return response.BadRequest(fmt.Errorf("Target only allowed when clustered"))
+	}
 
-			sourceNodeOffline = node.IsOffline(s.GlobalConfig.OfflineThreshold())
+	// A POST to /containers/<name>?target=<node> is meant to be used to
```
Comment (tomponline) [inline lxd/instance_post.go:118]: As we're moving this comment can we update it to use "instances" concept rather than "containers" to bring it inline with todays terminology. Also the API route is /instances/ now.

Comment (tomponline) [reply lxd/instance_post.go:118]: Also, we use the term "cluster member" or just "member" (if the context is inherently cluster related) in all user-facing messages/documentation rather than "node". I've found it helps for consistency to also use cluster member terminology in the code/comments too.

File: lxd/project/permissions.go [hunk 27]
```diff
@@ -1514,3 +1514,107 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+	return nil
+}
+
+// CheckTargetMember checks if the given member is allowed for the project.
+// If nil it also returns the resolved target member node information.
+func CheckTargetMember(ctx context.Context, tx *db.ClusterTx, p *api.Project, targetMember string) (*db.NodeInfo, error) {
+	// Find target member.
+	member, err := tx.GetNodeByName(ctx, targetMember)
+	if err != nil {
+		return nil, api.StatusErrorf(http.StatusNotFound, "Cluster member not found")
```
Comment (tomponline) [inline lxd/project/permissions.go:1562]: I know we are getting rid of this call now anyway, but for future reference we shouldn't do this sort of error handling.
DB queries can fail for a number of different reasons and so masking all errors as a "cluster member not found error" is not that helpful to identify the actual cause of the problem. Also this can be problematic because the caller may want to take different action depending on whether there was a not found error or an unexpected error.

Also the `GetNodeByName` function itself returns `api.StatusErrorf(http.StatusNotFound, "Cluster member not found")` if the member wasn't found so there's no need to mask it here.

Comment (roosterfish) [reply lxd/project/permissions.go:1562]: Just to get it right, you mean putting additional information in the error message without losing the actual cause:

```
api.StatusErrorf(http.StatusNotFound, "Cluster member not found: %q", err.Error())
```

Comment (tomponline) [reply lxd/project/permissions.go:1562]: No I mean just returning `err` here or, if you want to add context, doing something like `return fmt.Errorf("Failed loading cluster member: %w", err)` that way using `%w` means the `api.StatusError` type will still be propagated upwards and will then influence the HTTP response code and any upstream callers of `api.StatusErrorCheck()`. 

See https://go.dev/blog/go1.13-errors

So the two key points are:

- Don't mask errors with different meanings. E.g. don't say "Cluster member not found" unless you know that is the error (it maybe the network is down, for example, but that is not a cluster member not found error). The best place for detecting not found errors and returning them as such is in the actual DB function, not an upstream caller. So it looks like a code smell to me when I see it further up.
- Use %w for wrapping errors, not %v, %q or %s.

Comment (tomponline) [reply lxd/project/permissions.go:1562]: You only need to return an `api.StatusError` if you want to indicate a specific error code. Otherwise just return a normal error and the API handlers will convert that to a 500 HTTP error.

File: lxd/instance_post.go [hunk 28]
```diff
@@ -21,10 +21,13 @@ import (
 	"github.com/lxc/lxd/lxd/project"
```
Comment (tomponline) [inline lxd/instance_post.go:21]: The commit message seems to stop halfway through a sentence:

> When supplying --target use the @ character followed by a cluster group name like it is already implemented for .

File: lxd/instance_post.go [hunk 29]
```diff
@@ -206,6 +196,85 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+			return response.SmartError(err)
+		}
+
+		if targetMemberInfo == nil && s.GlobalConfig.InstancesPlacementScriptlet() != "" {
+			leaderAddress, err := d.gateway.LeaderAddress()
+			if err != nil {
+				return response.InternalError(err)
+			}
+
+			// Craft the request.
```
Comment (tomponline) [inline lxd/instance_post.go:245]: This comment isn't really needed IMHO.

File: lxd/instance_post.go [hunk 30]
```diff
@@ -206,6 +196,85 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
 		}
 	}
 
+	// Run the cluster placement after potentially forwarding the request to another member.
```
Comment (tomponline) [inline lxd/instance_post.go:199]: It looks like the changes to this function could probably be split into 2 logical changes:

1. Re-organisation to use the new helper functions and switching to using `targetMemberInfo` var.
2. Introducing of the cluster groups and placement script support.

It would be helpful if these could be split like that (or similar) as we need to move carefully here in order to keep things efficient and to ensure we are handling the different scenarios correctly.

When it lands as single big change like this it makes it more difficult to understand all the ramifications.

**Review by tomponline — CHANGES_REQUESTED** [review]
Lets make another pass at this addressing the DB query issues and breaking the commits down further and then I think we'll be in a better position to consider all of the ramifications better :)

File: lxd/instances_post.go (hunk 22 above)
Comment (roosterfish) [reply lxd/instances_post.go]: `tx.GetNodeByName` is now called once and the filtering is performed later on the already existing list of nodes.

File: lxd/instances_post.go (hunk 23 above)
Comment (roosterfish) [reply lxd/instances_post.go:1147]: The logic is now moved into `GetNodeWithLeastInstances`. I have intentionally tried to keep the first `.Transaction()` as small as possible, breaking out for other tasks and then starting a new one if this step is required (still no member found).

File: lxd/instance_post.go (hunk 24 above)
[the remark this answers is not in the document]
Comment (roosterfish) [reply lxd/instance_post.go]: Moved right above the first place were it is required.

File: lxd/instance_post.go (hunk 26 above)
Comment (roosterfish) [reply lxd/instance_post.go]: By keeping an eye on both scenarios clustered an non clustered, I have updated the comments to address the wording.

File: lxd/instance_post.go (hunk 28 above)
Comment (roosterfish) [reply lxd/instance_post.go:21]: Uups, that happened during the rebase. Updated in the respective commit.

File: lxd/instance_post.go (hunk 29 above)
Comment (roosterfish) [reply lxd/instance_post.go]: Removed

File: lxd/instance_post.go (hunk 30 above)
Comment (roosterfish) [reply lxd/instance_post.go:197]: I have split it it into two commits:

1. Restructuring (using central functions), simple scheduling and default behavior (least instances) including doc updates
2. Adding the scriptlet scheduler

File: lxd/instance_post.go (hunk 25 above)
Comment (tomponline) [reply lxd/instance_post.go]: thats fine.

File: lxd/instance_post.go [hunk 31]
```diff
@@ -199,13 +179,74 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
...
+				targetMemberInfo, err = tx.GetNodeWithLeastInstances(ctx, candidateMembers)
+				return err
+			})
+			if err != nil {
+				return response.SmartError(err)
+			}
+		}
+
+		if targetMemberInfo.IsOffline(s.GlobalConfig.OfflineThreshold()) {
+			return response.BadRequest(fmt.Errorf("Target node is offline"))
```
Comment (tomponline) [inline lxd/instance_post.go:274]: This is a user facing error that mentions "node", but it should say "cluster member".

File: lxd/instances_post.go (hunk 13 above)
Comment (tomponline) [inline lxd/instances_post.go:865]: Is `targetGroup` defined too early now, its only used with `project.CheckTarget` later right?

I'm wondering if it would be clearer for project.CheckTarget to return 2 values, the node info if the target was a specific node, and the group name if the target was a group.

Then you could do:

```
targetMemberInfo, targetGroupName, err := project.CheckTarget(ctx, r, tx, targetProject, queryParam(r, "target"), allMembers)
```

This seems clearer as it keeps all of that logic together. As having ` project.CheckTarget` return `nil,nil` when the target is a group seems a bit unusual.

File: lxd/instances_post.go [hunk 32]
```diff
@@ -1083,6 +1016,18 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 				}
 			}
 
+			allMembers, err := tx.GetNodes(ctx)
```
Comment (tomponline) [inline lxd/instances_post.go:1019]: On the line above that says:

```go
if clustered && !clusterNotification && targetMemberInfo == nil {
```

I'm confused now about the ordering of `targetMemberInfo, err = project.CheckTarget` as it seems that its impossible for `targetMemberInfo` to be non-nil at this point.

File: lxd/instance_post.go (hunk 31 above)
Comment (roosterfish) [reply lxd/instance_post.go]: Missed this one, fixed.

File: lxd/project/permissions.go [hunk 33]
```diff
@@ -1514,3 +1514,113 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+
+	if !targetGroupExists {
+		return api.StatusErrorf(http.StatusBadRequest, "Cluster group %q doesn't exist", groupName)
+	}
+
+	return nil
+}
+
+// CheckTarget checks if the given cluster target (member or group) is allowed.
+// If target is a cluster member, it returns the resolved node information and cluster group.
```
Comment (tomponline) [inline lxd/project/permissions.go:1597]: > ... and empty cluster group name

right?

File: lxd/project/permissions.go [hunk 34]
```diff
@@ -1514,3 +1514,113 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+// If target is a cluster group, it returns nil and the cluster group.
```
Comment (tomponline) [inline lxd/project/permissions.go:1598]: > ... it returns nil and the cluster group name.

Differentiating between names, addresses, objects etc is useful as there have been confusion around that in the past.

File: lxd/project/permissions.go [hunk 35]
```diff
@@ -1514,3 +1514,113 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+// In case of error, neither node information nor cluster group gets returned.
+func CheckTarget(ctx context.Context, r *http.Request, tx *db.ClusterTx, p *api.Project, target string, allMembers []db.NodeInfo) (*db.NodeInfo, string, error) {
+	targetMember, targetGroup := shared.TargetDetect(target)
```
Comment (tomponline) [inline lxd/project/permissions.go:1601]: `targetMemberName, targetGroupName :=`

File: lxd/instances_post.go [hunk 36]
```diff
@@ -1057,7 +988,9 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			logger.Debug("No name provided for new instance, using auto-generated name", logger.Ctx{"project": targetProjectName, "instance": req.Name})
 		}
 
-		if clustered && !clusterNotification && targetMemberInfo == nil {
+		if clustered && !clusterNotification {
+			var targetGroup string
```
Comment (tomponline) [inline lxd/instances_post.go:992]: Lets call this targetGroupName so its easier for readers (when they see the var further down) to see that it doesn't info about the group, just the name. This helps differentiate it from targetMemberInfo which is clear that its not just a name.

File: lxd/db/node.go [hunk 37]
```diff
@@ -1139,6 +1139,10 @@ func (c *ClusterTx) GetNodeWithLeastInstances(ctx context.Context, members []Nod
 		}
 	}
 
+	if member == nil {
```
Comment (tomponline) [inline lxd/db/node.go:1142]: We also need to update callers of `evacuateClusterSelectTarget` which will now get an error when no member was selected, so for example in `evacuateInstances` we have:

```go
		targetMemberInfo, err := evacuateClusterSelectTarget(ctx, opts.s, opts.gateway, inst, candidateMembers)
		if err != nil {
			return err
		}

		// Skip migration if no target available.
		if targetMemberInfo == nil {
			l.Warn("No migration target available for instance")
			continue
		}
```

Previously we would have continued here, but now it will fail with an error so need to change it to:

```go
		targetMemberInfo, err := evacuateClusterSelectTarget(ctx, opts.s, opts.gateway, inst, candidateMembers)
		if err != nil {
	        if api.StatusErrorCheck(err, http.StatusNotFound) {
                // Skip migration if no target available.
				l.Warn("No migration target available for instance")
			    continue
			}

			return err
		}
```

File: lxd/instances_post.go (hunk 36 above)
Comment (tomponline) [reply lxd/instances_post.go:992]: Can this var definition move further down to just before its set so we can limit its scope.

File: lxd/project/permissions.go (hunk 33 above)
Comment (roosterfish) [reply lxd/project/permissions.go:1597]: I have updated the comment in the most recent commit. 
`If target is a cluster member, it returns the resolved node information and cluster group.` should be the right description.

Comment (tomponline) [reply lxd/project/permissions.go]: No I dont think that is quite right.

Perhaps the confusion is coming from:

```go
return member, targetGroup, nil
```

Because targetGroup is empty when target is a specific member name.

So really it would be clearer as:

```go
return member, "", nil
```

The group name is not returned when the target is a cluster member.

File: lxd/project/permissions.go (hunk 34 above)
Comment (roosterfish) [reply lxd/project/permissions.go:1598]: I have added "node information object" in line 1597 to make it more clear.

File: lxd/project/permissions.go [hunk 38]
```diff
@@ -1514,3 +1514,113 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+	} else if targetGroup != "" {
+		err := CheckTargetGroup(ctx, tx, p, targetGroup)
+		if err != nil {
+			return nil, "", err
+		}
+
+		return nil, targetGroup, nil
+	}
+
+	return nil, targetGroup, nil
```
[the remark this answers is not in the document]
Comment (roosterfish) [reply lxd/project/permissions.go]: This might be reached if `CheckTarget` is executed in a non clustered environment. For both the instance and instances endpoint this last return isn't required since `CheckTarget` is only called if `target != "" && clustered`.

Returning the empty `targetGroup` variable isn't very clear so I have changed it to `""`.

File: lxd/project/permissions.go (hunk 35 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Changed.

File: lxd/project/permissions.go (hunk 33 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Aaah yes! Now I feel guilty :D Changed.

File: lxd/db/node.go (hunk 37 above)
Comment (roosterfish) [reply lxd/db/node.go:1142]: I am struggling with if it is an `http.StatusNotFound` or `http.BadRequest`. 

In case of the instance movement, the user would request `lxc move c1 --target foo`. When getting back a 404 from this operation I would think either `c1` or `foo` doesn't exist. @tomponline what do you think?

File: lxd/instances_post.go (hunk 36 above)
Comment (roosterfish) [reply lxd/instances_post.go]: Changed for both instance and instances endpoint.

File: lxd/db/node.go (hunk 37 above)
Comment (tomponline) [reply lxd/db/node.go:1142]: You could push that detection into `evacuateClusterSelectTarget` if you prefer and then continue to return nil here.

Comment (tomponline) [reply lxd/db/node.go:1142]: It should remain http.StatusNotFound in the context of the candidate search though.

Comment (roosterfish) [reply lxd/db/node.go:1142]: the only caller of `evacuateClusterSelectTarget` is `evacuateInstances` and it already has a check it not member could be found:

```go
// Skip migration if no target available.
if targetMemberInfo == nil {
	l.Warn("No migration target available for instance")
	continue
}
```

I would then again return nil from `GetNodeWithLeastInstances` and explicitly return a 404 for both instance and instances endpoint in case there isn't any node available.

Comment (tomponline) [reply lxd/db/node.go:1142]: So `GetNodeWithLeastInstances` needs to remain as it is in this PR, returning a not found error.

This will change the return of `evacuateClusterSelectTarget` as it will now return an error rather than nil in that case.

So I propose adding the not found detection to `evacuateClusterSelectTarget` so that it continues to return nil in that case so that the caller of `evacuateClusterSelectTarget` doesn't need to change.

Comment (roosterfish) [reply lxd/db/node.go:1142]: Seems more reasonable, otherwise the error message in both endpoints needs to be duplicated.

Comment (tomponline) [reply lxd/db/node.go:1142]: Yes, that was what we were trying to avoid originally.

Comment (roosterfish) [reply lxd/db/node.go:1142]: Changes applied.

File: lxd/project/permissions.go [hunk 39]
```diff
@@ -1514,3 +1514,113 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+
+	if len(clusterGroupsAllowed) > 0 && !shared.StringInSlice(groupName, clusterGroupsAllowed) {
+		return fmt.Errorf("Project isn't allowed to use this cluster group: %q", groupName)
+	}
+
+	return nil
+}
+
+// CheckTargetMember checks if the given member is allowed for the project.
+// If nil it also returns the resolved target member node information.
```
Comment (tomponline) [inline lxd/project/permissions.go:1557]: This comment describes the internal implementation and requires the reader to understand it, as it doesn't say what is `nil` in this case (I'm assuming you mean the return value of `AllowClusterMember`).

Ideally the reader of the docblock shouldn't need to see the internal implementation of a function to understand its return values.

I suggest something like this:

> // CheckTargetMember checks if the given targetMemberName is present in allMembers and is allowed for the project.
> // If member is allowed it returns the resolved target member information.

File: lxd/instances_post.go [hunk 40]
```diff
@@ -1057,7 +988,7 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
 			logger.Debug("No name provided for new instance, using auto-generated name", logger.Ctx{"project": targetProjectName, "instance": req.Name})
 		}
 
-		if clustered && !clusterNotification && targetMemberInfo == nil {
+		if clustered && !clusterNotification {
```
Comment (tomponline) [inline lxd/instances_post.go:991]: OK this is good, now that you've moved the targetMemberInfo definition down to where its first used, its forced us to highlight the changes of behaviour that are inadvertently being made.

So previously we were resolving the `targetMemberInfo` info earlier so that if a specific target was specified we then did not need to go an perform the (pretty expensive by the looks of it) call to `instance.SuitableArchitectures`.

So looks like call to `project.CheckTarget` needs to be moved up so we can keep the check against `targetMemberInfo == nil` here.

What do you think?

Comment (roosterfish) [reply lxd/instances_post.go]: This made me thinking. It would report error messages that wouldn't have been shown before since the target checks are performed at a later point in time which would definitely break the expected behavior here. 

To have as little changes as necessary, I have moved back the fetching of all cluster members and the target check to its original place, but still keeping the definition of `targetGroupName` as close to its first usage as possible :)

File: lxd/project/permissions.go (hunk 39 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: Changed as it is much easier to deal with the functions if the text matches the variable name. Also modified the doc strings for the other functions were we added the `{...}Name` suffix.

File: shared/util.go [hunk 41]
```diff
@@ -1371,3 +1371,16 @@ func JoinTokenDecode(input string) (*api.ClusterMemberJoinToken, error) {
 
 	return &j, nil
 }
+
+// TargetDetect returns either target node or group based on the provided prefix:
+// An invocation with `target=h1` returns "h1", "" and
+// `target=@g1` returns "", "g1".
```
Comment (tomponline) [inline shared/util.go:1377]: just a nit, wont block merge, but we dont tend to have strict line length limits, so the comment breaking line here seems a bit odd. Not a problem though.

File: lxd/project/permissions.go [hunk 42]
```diff
@@ -1514,3 +1514,114 @@ func AllowSnapshotCreation(p *api.Project) error {
...
+
+	if !targetGroupExists {
+		return api.StatusErrorf(http.StatusBadRequest, "Cluster group %q doesn't exist", groupName)
+	}
+
+	return nil
+}
+
+// CheckTarget checks if the given cluster target (member or group) is allowed.
+// If target is a cluster member, it returns the resolved node information object and cluster group from allMembers.
```
Comment (tomponline) [inline lxd/project/permissions.go:1598]: This line still doesnt make sense to me.

Looking at the code: 

```go
if targetMemberName != "" {
		member, err := CheckTargetMember(p, targetMemberName, allMembers)
		if err != nil {
			return nil, "", err
		}

		return member, "", nil
```

So if target is a cluster member, it just returns the resolved node information object.
It doesn't return "cluster group from allMembers" right? I don't really know what that is anyway.

Maybe this is just a phrasing issue. 

Did you mean:

> // If target is a cluster member and is found in allMembers it returns the resolved node information object

File: lxd/instances_post.go [hunk 43]
```diff
@@ -880,65 +872,17 @@ func instancesPost(d *Daemon, r *http.Request) response.Response {
...
-					if !found {
-						return api.StatusErrorf(http.StatusForbidden, "Project isn't allowed to use this cluster member")
-					}
-				}
-			} else if targetGroup != "" {
-				// If restricted groups are specified then check the requested group is in the list.
-				if shared.IsTrue(targetProject.Config["restricted"]) && len(clusterGroupsAllowed) > 0 && !shared.StringInSlice(targetGroup, clusterGroupsAllowed) {
-					return api.StatusErrorf(http.StatusForbidden, "Project isn't allowed to use this cluster group")
-				}
+		allMembers, err := tx.GetNodes(ctx)
```
Comment (tomponline) [inline lxd/instances_post.go:875]: I think we've lost some optimisations here, because previously these queries for tx.GetNodes and the ones in project.CheckTarget were done only when `if clustered && !clusterNotification {`.

Now, from my reading of this, it seems we are doing them both on the initial request *and* on the subsequent forwarded request when it arrives at the target member. This seems unnecessary to me. 

Was there a reason you needed to change this?

Comment (roosterfish) [reply lxd/instances_post.go:875]: When comparing with master, looks like the check for `clustered && !clusterNotification` for `GetNodes` got lost in between refactoring and moving the the checks for the target. Below it was covered by the `clustered && !clusterNotification && targetMemberInfo == nil` check we discussed earlier.

To be as close as possible to master, for the fetching of the nodes and target checks I'll add the cluster and notification check.

File: lxd/project/permissions.go (hunk 42 above)
Comment (roosterfish) [reply lxd/project/permissions.go:1598]: I messed this comment up. I was too focused on adding in the variable names into the comments, looks like I wanted to write 

```
// If target is a cluster member, it returns the resolved node information object and cluster group from allMembers.
```

but forgot the delete `and cluster group`. Thanks!

File: shared/util.go (hunk 41 above)
Comment (roosterfish) [reply shared/util.go]: I am used to break it in favor of split screen in the IDE. But I will adapt the repos code style :) Changed.

**Comment by roosterfish** [comment]
@tomponline I was again checking the cluster restrictions and found that [this](https://github.com/lxc/lxd/issues/11875) is currently not working on master but would also affect the changes from this PR.

Should I include the changes right away in this PR? At the end it would just involve moving the function call.

**Comment by tomponline** [comment]
I'm tempted to suggest we split this PR into 2, one for the refactor of instances_post and a separate one for the instance_post change.

**Comment by roosterfish** [comment]
It outgrew the original bug report :) Then I'll leave most of the things in here, but move out the changes to `lxd/instances_post.go` into a new PR to have those two endpoints separated. Once those two are in, I'll put in the changes for https://github.com/lxc/lxd/issues/11875.

**Comment by roosterfish** [comment]
@tomponline the changes affecting the instances endpoint have been moved out of this PR.

**Comment by tomponline** [comment]
@roosterfish ok thanks, I'll wait for the refactor of instances_post pr first and we'll get that merged and then this pr can be rebased so it only contains the changes related to fixing the actual bug. Cheers

**Comment by tomponline** [comment]
@roosterfish on your commit messages, please can you use the following format, so for a change affecting just a file `lxd/api_cluster.go` the commit message would start `lxd/api/cluster: ...`

**Comment by tomponline** [comment]
This can be rebased now please.

**Comment by roosterfish** [comment]
Rebase done. I have also aligned again the doc strings a bit since a node is only called member in case of an active cluster and if a target is provided.

File: lxd/instances_post.go (hunk 40 above)
Comment (roosterfish) [reply lxd/instances_post.go]: I'll resolve this since it is not part of the PR anymore.

File: lxd/instance_post.go [hunk 44]
```diff
@@ -288,7 +324,7 @@ func instancePost(d *Daemon, r *http.Request) response.Response {
 			return operations.OperationResponse(op)
 		}
 
-		if targetNode != "" {
+		if target != "" {
```
Comment (tomponline) [inline lxd/instance_post.go:355]: I think this should be `targetMemberInfo != nil` so that we dont panic if a bug creeps in where `targetMemberInfo` is nil but `target` non-empty.

File: shared/util.go (hunk 41 above)
Comment (roosterfish) [reply shared/util.go]: I'll resolve this since it is not part of the PR anymore.

File: lxd/instances_post.go (hunk 43 above)
Comment (roosterfish) [reply lxd/instances_post.go]: I'll resolve this since it is not part of the PR anymore.

File: lxd/project/permissions.go (hunk 42 above)
Comment (roosterfish) [reply lxd/project/permissions.go]: I'll resolve this since it is not part of the PR anymore.

File: lxd/instance_post.go (hunk 44 above)
Comment (roosterfish) [reply lxd/instance_post.go:355]: I had it in originally but moved it out whilst debugging when I accidentally broke `lxc copy` command since I didn't handle the redirect correctly. Thanks.

**Review by tomponline — APPROVED** [review]
LGTM, I enjoyed the tests you added. Thanks
