### PR TITLE
lxd/lxd: Prevent multiple routed NIC devices from using "auto" gateway mode

### LINKED ISSUE #7943: Prevent multiple routed NIC devices from using "auto" gateway mode
If you attach multiple `routed` NICs to a container then the container will fail to start if using `ipv4.gateway` or `ipv6.gateway` in "auto" mode (which is the default if not specified).

An example error that the user will see currently:

```
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart mytest /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/mytest/lxc.conf:
Try lxc info --show-log mytest for more info

In logfile:

lxc mytest 20200927174100.546 ERROR network - network.c:lxc_network_setup_in_child_namespaces_common:3464 - File exists - Failed to add ipv4 dest “169.254.0.1” for network device “eth1”
lxc mytest 20200927174100.546 ERROR network - network.c:lxc_setup_network_in_child_namespaces:3528 - File exists - Failed to setup netdev
lxc mytest 20200927174100.546 ERROR conf - conf.c:lxc_setup:3218 - Failed to setup network
lxc mytest 20200927174100.546 ERROR start - start.c:do_start:1224 - Failed to setup container “mytest”
lxc mytest 20200927174100.546 ERROR sync - sync.c:__sync_wait:41 - An error occurred in another process (expected sequence number 5)
lxc mytest 20200927174100.546 ERROR lxccontainer - lxccontainer.c:wait_on_daemonized_start:850 - Received container state “ABORTING” instead of “RUNNING”
lxc mytest 20200927174100.547 ERROR start - start.c:__lxc_start:1999 - Failed to spawn container “mytest”
```

We should improve the container start checks to ensure to give a helpful error message explaining the problem.

### PR DESCRIPTION
**Pull request by my5t3ry**
Fixes #7943.

Signed-off-by: Sascha Bast <sash@mischkonsum.org>

### CODE REVIEW

**Comment by tomponline** [comment]
Hi @my5t3ry , thanks for this, but I think it would be better to validate this in the LXD server rather than in the client. That way if someone is using our API they still get the benefit of the validate. Also we don't put device specific validation into the client.

Instead, can you take a look at adding this here https://github.com/lxc/lxd/blob/master/lxd/device/nic_routed.go#L43 using the `d.inst.ExpandedConfig()` function to iterate through the instance's other devices looking for conflicting devices.

**Comment by tomponline** [comment]
@my5t3ry also its useful to link your PR to the issue its fixing by adding `Fixes #<issue number>` in the description.

I presume this is for https://github.com/lxc/lxd/issues/7943

**Comment by tomponline** [comment]
@my5t3ry also as per the https://github.com/lxc/lxd/issues/7943 issue , we don't want to prevent adding multiple `routed` NIC types to an instance, but only to prevent adding multiple routed NICs using the auto gateway mode.

**Comment by my5t3ry** [comment]
thank you for the review. i got it, and will try to complete it at some throughout the weekend :)

**Comment by my5t3ry** [comment]
Hi @tomponline, i have a question regarding the procedure for committing changes to an active pull request. Does it make more sense to commit the changes one by one to get a better overview, and then squash them when the request is technically accepted? Or just squash the changes that need to be reviewed before pushing, like I did for the last review iterartions? thanks : )

**Comment by tomponline** [comment]
@my5t3ry the way we normally do this is to have a commit for each logical change, rather than one single merge commit or lots of little commits showing the iteration of development.

File: lxd/device/nic_routed.go [hunk 1]
```diff
@@ -497,3 +502,36 @@ func (d *nicRouted) ipv6HostAddress() string {
...
+			for _, curNicDevice := range nicDevices {
+				if curNicDevice["name"] != d.name &&
+					curNicDevice["nictype"] == "routed" &&
+					d.hasAutoGatewayConfiguration(curNicDevice) {
+					routedNicDeviceNames = append(routedNicDeviceNames, curNicDevice["name"])
+				}
+			}
+
+			if len(routedNicDeviceNames) > 1 {
+
```
Comment (tomponline) [inline lxd/device/nic_routed.go:522]: and this empty line please

File: lxd/device/nic_routed.go [hunk 2]
```diff
@@ -497,3 +502,36 @@ func (d *nicRouted) ipv6HostAddress() string {
...
+					len(routedNicDeviceNames), strings.Join(routedNicDeviceNames[:], ", "))
+			}
+		}
+	}
+
+	return nil
+}
+
+func (d *nicRouted) hasAutoGatewayConfiguration(config deviceConfig.Device) bool {
+
```
Comment (tomponline) [inline lxd/device/nic_routed.go:534]: and this empty line please

File: lxd/device/nic_routed.go [hunk 3]
```diff
@@ -497,3 +502,36 @@ func (d *nicRouted) ipv6HostAddress() string {
...
+					"instances can't attach more than one routed nic device with gateways in auto mode. ",
+					len(routedNicDeviceNames), strings.Join(routedNicDeviceNames[:], ", "))
+			}
+		}
+	}
+
+	return nil
+}
+
+func (d *nicRouted) hasAutoGatewayConfiguration(config deviceConfig.Device) bool {
```
Comment (tomponline) [inline lxd/device/nic_routed.go:533]: @my5t3ry As you've seen in the implementation of this function, there are two gateway keys, `ipv4.gateway` and `ipv6.gateway`. And because they can be specified separately, potentially on two different NIC devices, it should be allowed that one NIC has `ipv4.gateway=auto`` and another has `ipv6.gateway=auto`, or that a single NIC has both set to `auto`. The only thing we shouldn't allow are two routed NIC devices both specifying the same key as auto.

File: lxd/device/config/devices_test.go [hunk 4]
```diff
@@ -37,3 +41,41 @@ func TestSortableDevices(t *testing.T) {
 		t.Error("devices reverse sorted incorrectly")
 	}
 }
+
+func Test_HasConfigProperties(t *testing.T) {
+
```
Comment (tomponline) [inline lxd/device/config/devices_test.go:46]: please remove empty line

File: lxd/device/nic_routed.go [hunk 5]
```diff
@@ -497,3 +502,36 @@ func (d *nicRouted) ipv6HostAddress() string {
 
 	return nicRoutedIPv6GW
 }
+
+func (d *nicRouted) isUniqueWithGatewayAutoMode(instConf instance.ConfigReader) error {
+
+	if instConf.ExpandedDevices() != nil && d.hasAutoGatewayConfiguration(d.config) {
+		routedNicDeviceNames := []string{d.config["name"]}
+
+		nicDevices := instConf.ExpandedDevices().FilterByConfigProperties(map[string]string{"nictype": "routed"})
```
Comment (tomponline) [inline lxd/device/nic_routed.go:511]: @my5t3ry I think I'd be tempted to handle all the validation in this function and avoid the need for `FilterByConfigProperties` function, and instead keeping all the logic in one function and running the validation for each gateway key in a loop.

e.g.

```go
	instDevs := instConf.ExpandedDevices()
	for k, v := range []string{"ipv4.gateway", "ipv6.gateway"} {
		ourGW := d.config[k]

		if ourGW != "auto" {
			continue // nothing to do as auto not being used.
		}

		// Check other routed NIC devices don't have auto set.
		for nicName, nicConfig := range instDevs {
			if nicName == d.name {
				continue // Skip ourselves.
			}

			if nicConfig[k] == "auto" {
				return fmt.Errorf("Existing NIC %q already uses %q in auto mode", nicName, k)
			}
		}
	}
```

**Review by tomponline — CHANGES_REQUESTED** [review]

**Comment by my5t3ry** [comment]
Well, that ipv4 and ipv6 configuration do not interfere should have been clear to me. Your code is great ; )

**Comment by tomponline** [comment]
jenkins: test this please

File: lxd/instance_test.go [hunk 6]
```diff
@@ -204,6 +204,63 @@ func (suite *containerTestSuite) TestContainer_IsPrivileged_Privileged() {
...
+	err = c.Update(db.InstanceArgs{
+		Type:     instancetype.Container,
+		Profiles: []string{"default"},
+		Devices: deviceConfig.Devices{
+			"eth0": eth0,
+			"eth1": eth1,
+		},
+		Name: "testFoo",
+	}, true)
+	suite.Req.NoError(err, fmt.Errorf("Adding multiple routed with gateway mode ['none'] should succseed. "))
```
Comment (tomponline) [inline lxd/instance_test.go:235]: @my5t3ry typo here for `succseed`

File: lxd/instance_test.go [hunk 7]
```diff
@@ -204,6 +204,63 @@ func (suite *containerTestSuite) TestContainer_IsPrivileged_Privileged() {
...
+		Type:     instancetype.Container,
+		Profiles: []string{"default"},
+		Devices: deviceConfig.Devices{
+			"eth0": eth0,
+			"eth1": eth1,
+		},
+		Name: "testFoo",
+	}, true)
+	suite.Req.Error(err,
+		fmt.Errorf("Adding multiple routed nic devices with any gateway mmode ['auto',''] should threw error. "))
```
Comment (tomponline) [inline lxd/instance_test.go:249]: `throw` rather than `threw`.

File: lxd/instance_test.go [hunk 8]
```diff
@@ -204,6 +204,63 @@ func (suite *containerTestSuite) TestContainer_IsPrivileged_Privileged() {
...
+		Type:     instancetype.Container,
+		Profiles: []string{"default"},
+		Devices: deviceConfig.Devices{
+			"eth0": eth0,
+			"eth2": eth2,
+		},
+		Name: "testFoo",
+	}, true)
+	suite.Req.NoError(err,
+		fmt.Errorf("Adding multiple nic devices with unicque nictype ['routed'] should threw error. "))
```
Comment (tomponline) [inline lxd/instance_test.go:261]: `throw` rather than `threw`.

**Comment by tomponline** [comment]
@my5t3ry thanks, looks good, couple of typos to fix, and am running it through our jenkins CI system now to see if it picks up any issues.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
thanks @my5t3ry !
