### PR TITLE
Fix backup renaming

### LINKED ISSUE #7176: Renaming an instance with a backup breaks backup API
If you do the following on LXD 4.0.0;

 - Create a container
 - Create a backup 
 - Rename container
 - Get `/instances/NEW_CONTAINER_NAME/backups`
    - This works fine shows the backups
 -  Get `/instances/NEW_CONTAINER_NAME/backups/BACKUP_NAME` 
     - Not found 

You have to rename the container back to its original name to access the backup info (just changing instance name in the URL doesn't work)

_Didnt test VM's_

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes #7176.

### CODE REVIEW

File: lxd/instance/drivers/driver_lxc.go [hunk 1]
```diff
@@ -3636,6 +3636,9 @@ func (c *lxc) Rename(newName string) error {
 		}
 	}
 
+	// Set the new name in the struct.
+	c.name = newName
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go:3640]: @monstermunchkin one thing to consider though here is that before this change, c.name was set to the new name at a point where this function cannot fail. However where you have moved it now, its possible to fail and return with an error yet still leave the container struct with the new name set incorrectly.

There's probably a lot more that could be done in this function to allow a clean revert if an error occurs earlier, but at least not introducing any new potential inconsistencies is worth considering.

How about using the `revert` package and adding a revert step here that resets the name back to the original if this functions fails?

Comment (monstermunchkin) [reply lxd/instance/drivers/driver_lxc.go:3640]: That's a good point. I'll add some revert steps.

File: lxd/instance/drivers/driver_lxc.go [hunk 2]
```diff
@@ -3646,13 +3651,16 @@ func (c *lxc) Rename(newName string) error {
...
+		oldName := backup.Name()
+		backupName := strings.Split(oldName, "/")[1]
 		newName := fmt.Sprintf("%s/%s", newName, backupName)
 
 		err = backup.Rename(newName)
 		if err != nil {
 			return err
 		}
+
+		revert.Add(func() { backup.Rename(oldName) })
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go:3663]: @monstermunchkin be careful with this pattern: adding a revert step inside a for loop using the iterator variable.

I've been caught out by that myself.

Try this simple example:

```go
package main

import (
	"fmt"

	"github.com/lxc/lxd/lxd/revert"
)

func main() {
	revert := revert.New()
	defer revert.Fail()

	things := []string{"one", "two", "three"}

	for _, thing := range things {
		revert.Add(func() { fmt.Println(thing) })
	}
}
```

This prints:

```
three
three
three
```

So you'll end up reverting the last snapshot multiple times. This is basically the same issue as using defer in a loop too.

This is because the loop iterator variable is only created once per loop, not once per iteration, and its value is just changed for each loop. Which means when the reverter runs it takes the last value of that variable and passes it into each revert step.

Instead you can either define a local variable inside the loop that copies the iterator value and use that inside the reverter, e.g.

```go
package main

import (
	"fmt"

	"github.com/lxc/lxd/lxd/revert"
)

func main() {
	revert := revert.New()
	defer revert.Fail()

	things := []string{"one", "two", "three"}

	for _, thing := range things {
		name := thing
		revert.Add(func() { fmt.Println(name) })
	}
}
```

Or you can make each iteration its own atomic unit by putting it inside an anonymous function (which is also useful when doing defer to avoid stacking them up until the end of the loop).

```go
package main

import (
	"fmt"

	"github.com/lxc/lxd/lxd/revert"
)

func main() {
	revert := revert.New()
	defer revert.Fail()

	things := []string{"one", "two", "three"}

	for _, thing := range things {
		func(name string) {
			revert.Add(func() { fmt.Println(name) })
		}(thing)
	}
}
```

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:3663]: I've just spotted you are using a local variable, so should be fine. Ignore me :)

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:3663]: Had you done `revert.Add(func() { backup.Rename(backup.Name()) })` that would have been an issue.

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:3663]: @monstermunchkin oh no, it is an issue, because `backup` is always going to reference the last snapshot, so whilst the `oldName` value is correct, you'll be renaming the wrong snapshot.

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:3663]: Here's an updated example:

```go
package main

import (
	"fmt"

	"github.com/lxc/lxd/lxd/revert"
)

type thing struct {
	name string
}

func (t *thing) Name() string {
	return t.name
}

func main() {
	revert := revert.New()
	defer revert.Fail()

	things := []thing{thing{"one"}, thing{"two"}, thing{"three"}}

	for _, thing := range things {
		revert.Add(func() { fmt.Println(thing.Name()) })
	}
}
```

prints:

```
three
three
three
```

Comment (monstermunchkin) [reply lxd/instance/drivers/driver_lxc.go]: This should be fixed now. Thanks for that :)
