### PR TITLE
Fix image refresh when fingerprint is passed

### LINKED ISSUE #3562: lxc image refresh disappearing on no-op
# Required information

 * Distribution: Ubuntu (via snap)
 * Distribution version: 17.04
 * The output of "lxc info" or if that fails:
   * http://paste.ubuntu.com/25112483/
# Issue description

I tried to refresh the Ubuntu 16.04 image, and it got deleted.

> ⟫ lxc image list                   
> +-------+--------------+--------+-----------------------------------------------+--------+----------+-----------------------------+
> | ALIAS | FINGERPRINT  | PUBLIC |                  DESCRIPTION                  |  ARCH  |   SIZE   |         UPLOAD DATE         |
> +-------+--------------+--------+-----------------------------------------------+--------+----------+-----------------------------+                                                                                                                                                       
> |       | 7a7ff654cbd8 | no     | ubuntu 16.04 LTS amd64 (release) (20170619.1) | x86_64 | 153.83MB | Jul 2, 2017 at 3:05pm (UTC) |                                                                                                                                                       
> +-------+--------------+--------+-----------------------------------------------+--------+----------+-----------------------------+                                                                                                                                                       
> |       | 9e0493502f9d | no     | ubuntu 14.04 LTS amd64 (release) (20170424)   | x86_64 | 120.02MB | May 2, 2017 at 2:58pm (UTC) |                                                                                                                                                       
> +-------+--------------+--------+-----------------------------------------------+--------+----------+-----------------------------+                                                                                                                                                       
> ⟫ lxc image refresh 7a7ff654cbd8                                                                                                                                                                                                                       
> Image already up to date.                                                                                                                                                                                                                                                               
> ⟫ lxc image list                                                                   
> +-------+--------------+--------+---------------------------------------------+--------+----------+-----------------------------+
> | ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |         UPLOAD DATE         |
> +-------+--------------+--------+---------------------------------------------+--------+----------+-----------------------------+
> |       | 9e0493502f9d | no     | ubuntu 14.04 LTS amd64 (release) (20170424) | x86_64 | 120.02MB | May 2, 2017 at 2:58pm (UTC) |
> +-------+--------------+--------+---------------------------------------------+--------+----------+-----------------------------+
> 

# Steps to reproduce

 1. Have an up to date image
 2. lxc refresh $IMAGE
 3. lxc image list

### PR DESCRIPTION
**Pull request by albertodonato**
Fixes #3562

### CODE REVIEW

File: lxd/images.go [hunk 1]
```diff
@@ -874,23 +874,24 @@ func autoUpdateImages(d *Daemon) {
 	for _, fingerprint := range images {
 		id, info, err := dbImageGet(d.db, fingerprint, false, true)
 		if err != nil {
-			logger.Error("Error loading image", log.Ctx{"err": err, "fp": fingerprint})
+			logger.Error("Error loading image", log.Ctx{"err": err, "fp": info.Fingerprint})
```
Comment (stgraber) [inline lxd/images.go]: Hmm, this feels like a very bad idea. There's no guarantee that info.Fingerprint will be set on error.

Comment (albertodonato) [inline lxd/images.go]: Submitting a PR to revert this change
