### PR TITLE
Network: Add support for sticky DHCPv4 dynamic allocations for `ovn` NICs

### LINKED ISSUE #11658: Containers using OVN networks get different IPs on reboot
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04 (Jammy)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-71-generic
   * Snap Microcloud version: 0+git.f6e4e40 rev. 407
   * Snap LXD version: 5.13-cea5ee2 rev. 24758
   * Snap Microovn version: 0+git.1177d40 rev. 86
   * Storage backend in use: Snap Microceph version 0+git.fdf6d5e rev. 338 

# Issue description

OVN assigns IPs sequentially. That means if I create two containers then delete one and stop/start the other one, the latter changes IP.

# Steps to reproduce

 1. `lxc launch ubuntu:22.04 test-sticky-ip`
     `lxc launch ubuntu:22.04 test-sticky-ip-2`  
```
| test-sticky-ip   | RUNNING | 10.47.208.3 (eth0)  |      | CONTAINER | 0         | host3 |
+------------------+---------+---------------------+------+-----------+-----------+-----------------+
| test-sticky-ip-2 | RUNNING | 10.47.208.4 (eth0)  |      | CONTAINER | 0         | host2 |
```

 2. `lxc delete  test-sticky-ip --force`
 3. `lxc stop test-sticky-ip-2` 
 4. `lxc start test-sticky-ip-2`
 5. Result `test-sticky-ip-2` get IP previously allocated for `test-sticky-ip`
 ```
 | test-sticky-ip-2 | RUNNING | 10.47.208.3 (eth0)  |      | CONTAINER | 0         | host2 |
 ```

### PR DESCRIPTION
**Pull request by tomponline**
This PR introduces the instance volatile key `volatile.<name>.last_state.ip_addresses` which is used to store a comma-separated list of the DNS IPs associated to an OVN NIC port on last start.

This is then provided to the OVN driver when creating the port so that the OVN driver can choose to allocate this IPv4 address to the port if it is still appropriate to use (DHCPv4 is enabled, no static IPs being used and subnet is unchanged) and is available for use (not statically reserved or in use by another instance).

This fixes an issue where, because OVN allocates IPs from the subnet sequentially (unlike dnsmasq), if an instance with an IP lower than another instance is stopped/deleted and then that other instance is rebooted it will be then allocated that lower IP.

Whilst technically correct, there are some applications (Juju) that expect IPs to remain allocated across a reboot.

This PR also starts storing the OVN logical switch name in the `ovnExtIDLXDSwitch` external_id for logical switch ports.
This was required so LXD can efficiently retrieve all IPs associated to active logical switch ports as part of checking if a previously used IP is still available for reuse.

Fixes #11658

Associated tests https://github.com/lxc/lxc-ci/pull/743

### CODE REVIEW

**Comment by tomponline** [comment]
@peppepetra this should help with the DHCPv4 reboot issue.

File: lxd/network/openvswitch/ovn.go [hunk 1]
```diff
@@ -1085,6 +1085,40 @@ func (o *OVN) LogicalSwitchPorts(switchName OVNSwitch) (map[OVNSwitchPort]OVNSwi
...
+// LogicalSwitchPortIPs returns a list of IPs associated to each port connected to switch.
+func (o *OVN) LogicalSwitchPortIPs(switchName OVNSwitch) (map[OVNSwitchPort][]net.IP, error) {
+	output, err := o.nbctl("--format=csv", "--no-headings", "--data=bare", "--colum=name,addresses,dynamic_addresses", "find", "logical_switch_port",
+		fmt.Sprintf("external_ids:%s=%s", ovnExtIDLXDSwitch, switchName),
+	)
+	if err != nil {
+		return nil, err
+	}
+
+	// Parse lines like:
```
Comment (monstermunchkin) [inline lxd/network/openvswitch/ovn.go:1097]: Missing example?

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

File: lxd/network/openvswitch/ovn.go (hunk 1 above)
Comment (tomponline) [reply lxd/network/openvswitch/ovn.go:1097]: Good spot

Comment (tomponline) [reply lxd/network/openvswitch/ovn.go]: I took it out as the comment lower down suffices.

**Review by monstermunchkin — APPROVED** [review]
