### PR TITLE
Better handle errors in memory reporting

### LINKED ISSUE #3482: Current swap counter overflow (?)
# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-83-generic
  server: lxd
  server_pid: 1466
  server_version: 2.0.10
  storage: dir
  storage_version: ""
```

# Issue description

Sometimes `lxc info <container-name>` command returns the negative value of swap used (and there is no the peak swap usage there at all).

# Steps to reproduce

 1. Run a container with low memory limit (eg 100Mb)
 2. Run any tool/command that consumes memory close to the limit, eg `stress --vm-bytes 90M -m 1`
 3. On the host run `lxc info <container-name>` until you're lucky

# Information to attach

An exact unmodified output of the `lxc info second` I've just got:
```
Name: second
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/06/30 03:37 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 2028
Ips:
  eth0: inet    10.50.200.19    vethVFRKLF
  eth0: inet6   fe80::216:3eff:fe63:c30b        vethVFRKLF
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 18
  Memory usage:
    Memory (current): 97.58MB
    Memory (peak): 100.00MB
    Swap (current): -102318081B
  Network usage:
    eth0:
      Bytes received: 258.49kB
      Bytes sent: 5.09kB
      Packets received: 1238
      Packets sent: 56
    lo:
      Bytes received: 9.08kB
      Bytes sent: 9.08kB
      Packets received: 120
      Packets sent: 120
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #3482

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -4998,39 +4998,36 @@ func (c *containerLXC) memoryState() api.ContainerStateMemory {
...
+		memory.Usage = valueInt
 	}
-	memory.Usage = valueInt
 
 	// Memory peak in bytes
 	value, err = c.CGroupGet("memory.max_usage_in_bytes")
-	valueInt, err = strconv.ParseInt(value, 10, 64)
-	if err != nil {
-		valueInt = -1
+	valueInt, err1 = strconv.ParseInt(value, 10, 64)
```
Comment (brauner) [inline lxd/container_lxc.go]: That's a typical problem in GO programming patterns. :)

Comment (stgraber) [inline lxd/container_lxc.go]: Yeah, kinda weird too, I ran some static analysis tool a while back that'd find those unchecked variables, but it didn't catch those...
