### PR TITLE
Tweak squashfs for low-memory systems

### LINKED ISSUE #2382: squashfs unpack fails on low memory systems
unsquashfs tries to process things in 256MB chunks, which doesn't work so well on low memory systems.

### PR DESCRIPTION
**Pull request by stgraber**
On low-memory systems (below 2GB of RAM), limit unsquashfs to a single
CPU and to 10% of the RAM for its fragment size.

Closes #2382

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/images.go [hunk 1]
```diff
@@ -99,6 +99,13 @@ func unpack(file string, path string) error {
 	} else if strings.HasPrefix(extension, ".squashfs") {
 		command = "unsquashfs"
 		args = append(args, "-f", "-d", path, "-n")
+
+		mem, err := deviceTotalMemory()
+		mem = mem / 1024 / 1024 / 10
```
Comment (sean-jc) [inline lxd/images.go]: This is non-intuitive for me; even with the commit message it took me a bit to work through the logic.  I think it's especially confusing for people used to power-of-two math, the `10` seems so out of place.  Any objection to changing the code to something like this?  This assumes the comparison against 2.5gb instead of 2gb was unintentional.

```go
if err == nil && mem <= (1<<31) {
    mem = mem / 1024 / 1024 / 10
    ...
}
```

Comment (stgraber) [inline lxd/images.go]: The comparison against 2.5GB was absolutely intentional.

Comment (stgraber) [inline lxd/images.go]: The reason is simply that unsquashfs defaults to 256MB chunks, so we only want to set the argument if the resulting computed chunk size is smaller than that and we don't want that chunk to be bigger than 10% of the system's memory.

Comment (stgraber) [inline lxd/images.go]: The "mem" variable is intended as the chunk of memory in MB that we're willing to let unsquashfs use.

Comment (sean-jc) [inline lxd/images.go]: I understand the intent and logic, but for someone coming along later I think the code will be quite confusing, especially since the commit message doesn't match the code.  2gb vs 2.5gb is nitpicking, but my initial reaction when looking at the code was "that's not 2gb".  I can see someone (like me) changing the code to actually compare against 2gb, thinking they're doing the right thing.

**Comment by sergiusens** [comment]
Just want to confirm this works on my low mem env:

```
Creating barkier-maxton
Starting barkier-maxton
error: Error calling 'lxd forkstart barkier-maxton /var/lib/lxd/containers /var/log/lxd/barkier-maxton/lxc.conf': err='exit status 1'
  lxc 20160915190402.013 ERROR lxc_conf - conf.c:lxc_mount_auto_mounts:781 - No such file or directory - error mounting /sys/fs/cgroup
  lxc 20160915190402.013 ERROR lxc_conf - conf.c:lxc_setup:3758 - failed to setup the automatic mounts for 'barkier-maxton'
  lxc 20160915190402.013 ERROR lxc_start - start.c:do_start:834 - failed to setup the container
  lxc 20160915190402.014 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20160915190402.015 ERROR lxc_start - start.c:__lxc_start:1354 - failed to spawn 'barkier-maxton'

Try `lxc info --show-log barkier-maxton` for more info
```
