### PR TITLE
Storage: Fix auto custom volume snapshots

### LINKED ISSUE #8692: Auto custom local volume snapshots in cluster don't get created on correct member
The `autoCreateCustomVolumeSnapshotsTask` function treats all custom volumes as if they were volumes on remote storage pool (and only tries to create the snapshot on a single cluster member). However this is incorrect behaviour for local custom volumes which only exist on a single cluster member. 

Reproducer on a 2 member cluster:

```
lxc storage volume show local vol1
config:
  snapshots.schedule: '* * * * *'
description: ""
name: vol1
type: custom
used_by: []
location: va
content_type: filesystem
```

On VA member (with debug statements added), no snapshot is taken of vol1 (which is incorrect because the vol1 exists on va member):

```
Apr 20 09:17:48 va lxd.daemon[3311]: t=2021-04-20T09:17:48+0000 lvl=eror msg="tomp allvolumes [{ID:1 Name:vol1 Type:0 TypeName: PoolID:0 PoolName:local Snapshot:false Config:map[snapshots.schedule:* * * * *] Description: CreationDate:0001-01-01 00:00:00 +0000 UTC ExpiryDate:0001-01-01 00:00:00 +0000 UTC ProjectID:0 ProjectName:default ContentType:}]"
Apr 20 09:17:48 va lxd.daemon[3311]: t=2021-04-20T09:17:48+0000 lvl=eror msg="tomp schedule vol1 * * * * *"
Apr 20 09:17:48 va lxd.daemon[3311]: t=2021-04-20T09:17:48+0000 lvl=eror msg="tomp scheduled vol1 * * * * *"
Apr 20 09:17:48 va lxd.daemon[3311]: t=2021-04-20T09:17:48+0000 lvl=eror msg="tomp skipping vol1 1 2"
```

And on VB (which doesn't have vol1) the snapshot is attempted and fails:

```
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=eror msg="tomp allvolumes [{ID:1 Name:vol1 Type:0 TypeName: PoolID:0 PoolName:local Snapshot:false Config:map[snapshots.schedule:* * * * *] Description: CreationDate:0001-01-01 00:00:00 +0000 UTC ExpiryDate:0001-01-01 00:00:00 +0000 UTC ProjectID:0 ProjectName:default ContentType:}]"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=eror msg="tomp schedule vol1 * * * * *"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=eror msg="tomp scheduled vol1 * * * * *"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=eror msg="tomp volumes [{ID:1 Name:vol1 Type:0 TypeName: PoolID:0 PoolName:local Snapshot:false Config:map[snapshots.schedule:* * * * *] Description: CreationDate:0001-01-01 00:00:00 +0000 UTC ExpiryDate:0001-01-01 00:00:00 +0000 UTC ProjectID:0 ProjectName:default ContentType:}]"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="New task Operation: 47368abf-6b49-4bd6-981d-d00a4713b38a"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=info msg="Creating scheduled volume snapshots"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="Started task operation: 47368abf-6b49-4bd6-981d-d00a4713b38a"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=info msg="Done creating scheduled volume snapshots"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="CreateCustomVolumeSnapshot started" driver=dir newExpiryDate=0001-01-01T00:00:00+0000 newSnapshotName=snap0 pool=local project=default volName=vol1
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"No such object\"}"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="CreateCustomVolumeSnapshot finished" driver=dir newExpiryDate=0001-01-01T00:00:00+0000 newSnapshotName=snap0 pool=local project=default volName=vol1
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=eror msg="Error creating volume snapshot" err="Parent volume doesn't exist" volume="{ID:1 Name:vol1 Type:0 TypeName: PoolID:0 PoolName:local Snapshot:false Config:map[snapshots.schedule:* * * * *] Description: CreationDate:0001-01-01 00:00:00 +0000 UTC ExpiryDate:0001-01-01 00:00:00 +0000 UTC ProjectID:0 ProjectName:default ContentType:}"
Apr 20 09:22:50 vb lxd.daemon[3434]: t=2021-04-20T09:22:50+0000 lvl=dbug msg="Success for task operation: 47368abf-6b49-4bd6-981d-d00a4713b38a"
```

### PR DESCRIPTION
**Pull request by tomponline**
- Ensure that local custom volumes are always snapshotted on the local member.
- Skip snapshotting remote volumes if no online members to avoid snapshotting on multiple member during a cluster partition.
- Improve logging.

Fixes #8692

Testing:

- [x] Standalone host with local volume
- [x] Standalone host with remote volume
- [x] Single member cluster with remote volume
- [x] Multi member cluster with multiple local volumes
- [x] Multi member cluster with remote volume
- [x] Multi member cluster with remote volume with normal snapshot member offline

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber during the test of this PR, I shutdown one of the cluster members to test the snapshot mechanism moved to the other member (which it did).

I then proceeded to try and remove the cephfs storage pool, which then failed because it couldn't notify the offline member.

When I rebooted the offline member, it could no longer mount the cephfs storage pool and LXD just got into a restart loop, in the syslogs were lots of messages like this, presumably because the actual cephfs had been removed, but had left behind orphaned DB entries:

```
Apr 20 11:28:37 vm02 lxd.daemon[3833]: t=2021-04-20T11:28:37+0000 lvl=dbug msg="Mount started" driver=cephfs pool=cephfs
Apr 20 11:28:37 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:37 vm02 kernel: libceph: client91138514 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:38 vm02 lxd.daemon[3833]: t=2021-04-20T11:28:38+0000 lvl=dbug msg="Found cert" name=0
Apr 20 11:28:38 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:38 vm02 kernel: libceph: client91138520 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:38 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:38 vm02 kernel: libceph: client91138526 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:39 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:39 vm02 kernel: libceph: client91164480 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:39 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:39 vm02 kernel: libceph: client91138532 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:40 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:40 vm02 kernel: libceph: client91164483 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:40 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:40 vm02 kernel: libceph: client91164492 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:41 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:41 vm02 kernel: libceph: client91164495 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:41 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:41 vm02 kernel: libceph: client91164504 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:42 vm02 kernel: libceph: mon2 (1)[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789 session established
Apr 20 11:28:42 vm02 kernel: libceph: client91150861 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:42 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:42 vm02 kernel: libceph: client91164513 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:43 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:43 vm02 kernel: libceph: client91164528 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:43 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:43 vm02 kernel: libceph: client91138571 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:44 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:44 vm02 kernel: libceph: client91164537 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:44 vm02 kernel: libceph: mon2 (1)[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789 session established
Apr 20 11:28:44 vm02 kernel: libceph: client91150882 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:45 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:45 vm02 kernel: libceph: client91138586 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:46 vm02 kernel: libceph: mon1 (1)[2001:470:b0f8:1015:5054:ff:fe0a:750f]:6789 session established
Apr 20 11:28:46 vm02 kernel: libceph: client91164546 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:46 vm02 kernel: libceph: mon2 (1)[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789 session established
Apr 20 11:28:46 vm02 kernel: libceph: client91150903 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:47 vm02 kernel: libceph: mon0 (1)[2001:470:b0f8:1015:5054:ff:fe5e:ea44]:6789 session established
Apr 20 11:28:47 vm02 kernel: libceph: client91138601 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:47 vm02 kernel: libceph: mon2 (1)[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789 session established
Apr 20 11:28:47 vm02 kernel: libceph: client91150906 fsid fdb2bd9e-0ae7-4ff4-bfca-f0e38fb53372
Apr 20 11:28:48 vm02 lxd.daemon[3833]: t=2021-04-20T11:28:48+0000 lvl=dbug msg="Mount finished" driver=cephfs pool=cephfs
Apr 20 11:28:48 vm02 lxd.daemon[3833]: t=2021-04-20T11:28:48+0000 lvl=eror msg="Failed to start the daemon: Failed initializing storage pool \"cephfs\": Failed to mount \"[2001:470:b0f8:1015:5054:ff:fe5e:ea44],[2001:470:b0f8:1015:5054:ff:fe0a:750f],[2001:470:b0f8:1015:5054:ff:fe5e:4c7b]:6789:/persist-vm01\" on \"/var/snap/lxd/common/lxd/storage-pools/cephfs\" using \"ceph\": no such file or directory"
```

I wonder if we need to verify that all members are online before proceeding with remote storage pool operations to avoid this scenario.

File: lxd/storage_volumes_snapshot.go [hunk 1]
```diff
@@ -779,29 +812,29 @@ func autoCreateCustomVolumeSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
...
 }
 
-func autoCreateCustomVolumeSnapshots(ctx context.Context, d *Daemon, volumes []db.StorageVolumeArgs) error {
-	// Make the snapshots
+func autoCreateCustomVolumeSnapshots(ctx context.Context, d *Daemon, volumes []db.StorageVolumeArgs) {
+	// Make the snapshots.
 	for _, v := range volumes {
-		ch := make(chan error)
+		ch := make(chan struct{})
 		go func() {
```
Comment (tomponline) [inline lxd/storage_volumes_snapshot.go:819]: @stgraber @monstermunchkin I wondered when reading this, whether it was a good idea to immediately trigger all scheduled snapshots for a member concurrently. This could potentially cause a lot of I/O (especially for dir storage pools). Perhaps we should limit the concurrency here? Perhaps on a per-pool basis?

Comment (stgraber) [reply lxd/storage_volumes_snapshot.go:819]: That's a very good point and indeed could cause big load spike. Personally, I'd be happy to do them sequentially.

**Comment by stgraber** [comment]
@tomponline for the removal failure, that's odd. I guess we should have such operations check that all nodes are online and if not, fail early as we indeed can't really fully remove a storage or network if some nodes are temporarily offline.

File: lxd/storage_volumes_snapshot.go (hunk 1 above)
Comment (tomponline) [reply lxd/storage_volumes_snapshot.go:819]: @stgraber cool, will change this now to sequential.

Comment (tomponline) [reply lxd/storage_volumes_snapshot.go:820]: @stgraber actually on closer inspection, this is already doing it sequentially, the go routine is just there to allow a select on the ctx cancellation change. I've updated the PR by adding a couple of comments to that function for clarity, but otherwise it remains unchanged.
