### PR TITLE
lxc: Extend image filtering

### LINKED ISSUE #10558: `lxc image list images:` filtering issues
`lxc image list images:`'s architecture filtering uses unexpected values like `amd64`, `arm64` and `armhf` instead of the `x86_64`, `aarch64` and `armv7l` that are shown in unfiltered listing:

```
$ lxc image list -f csv -c lat images:alpine/3.16 | head -n 5
alpine/3.16 (3 more),x86_64,CONTAINER
alpine/3.16 (3 more),x86_64,VIRTUAL-MACHINE
alpine/3.16/arm64 (1 more),aarch64,CONTAINER
alpine/3.16/arm64 (1 more),aarch64,VIRTUAL-MACHINE
alpine/3.16/armhf (1 more),armv7l,CONTAINER
```

```
$ lxc image list -f csv -c lat images:alpine/3.16 architecture=x86_64  # no output
$ lxc image list -f csv -c lat images:alpine/3.16 architecture=amd64
alpine/3.16 (3 more),x86_64,CONTAINER
alpine/3.16 (3 more),x86_64,VIRTUAL-MACHINE
alpine/3.16/cloud (1 more),x86_64,CONTAINER
alpine/3.16/cloud (1 more),x86_64,VIRTUAL-MACHINE
```
Ideally, all arch name variations would work.

Also, using `type=container` (or `type=virtual-machine`) doesn't work with `images:` despite working locally for `lxc list`:

```
$ lxc image list -f csv -c lt images: type=container  # no output
$ lxc list -f csv -c nt type=container
foo,CONTAINER
```

The above was observed with:

```
$ snap list lxd
Name  Version      Rev    Tracking       Publisher   Notes
lxd   5.2-79c3c3b  23155  latest/stable  canonical✓  -
```

### PR DESCRIPTION
**Pull request by monstermunchkin**
This filters images not just by their properties but by any other field.

This fixes #10558 

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

**Comment by monstermunchkin** [comment]
This fixes #10558

**Review by simondeziel — COMMENTED** [review]
This was likely intended for @stgraber to review rather than me.

**Comment by monstermunchkin** [comment]
> This was likely intended for @stgraber to review rather than me.

@simondeziel I added you because you filed the issue ;)

File: lxc/image.go [hunk 1]
```diff
@@ -1208,6 +1211,11 @@ func (c *cmdImageList) imageShouldShow(filters []string, state *api.Image) bool
 					}
 				}
 			}
+
+			val, ok := m[key]
+			if ok && val == value {
```
Comment (tomponline) [inline lxc/image.go:1216]: value is a string, whereras m contains any elements. 
Would it be better to have structToMap unmarshal into map[string]string?

Comment (tomponline) [reply lxc/image.go:1216]: How does string matching against an any that is a bool work later?

Comment (monstermunchkin) [reply lxc/image.go:1216]: I just tested it, and it doesn't work. So, a filter like `cached=true` (as `Cached` is a bool in the struct) won't work at the moment. We'd need some logic for this to work.

Comment (monstermunchkin) [reply lxc/image.go:1216]: I don't believe we need a lot of logic here, as users will probably only filter by `type` or `architecture`, not by something like `cached` (which is always `false` for `images:` anyway) or `size`.

**Review by tomponline — APPROVED** [review]

**Review by tomponline — CHANGES_REQUESTED** [review]
There's intermittent token expiry test failures

**Comment by tomponline** [comment]
More likely related to your earlier pr though. Can you send a separate pr to fix those please?
