### PR TITLE
Fix image expiry, init storage handling when nested and remote storage operations

### LINKED ISSUE #3904: remote_cache_expiry does not work, integration tests are constructed incorrectly
I could not get images.remote_cache_expiry to function correctly. My cached images seem to build up and clog my root filesystem. I tried to debug it myself.

From what I'm seeing, I see last_use_date represented as unix time instead of rfc 3399:
```
sqlite3 /var/lib/lxd/lxd.db 'SELECT fingerprint, creation_date, expiry_date, upload_date, last_use_date FROM images WHERE cached=1'
2a6d95cc689465fbb0fe87c8bf873e096bec1390cb2cadac6dad21d7a0559fd0|0001-01-01 00:00:00+00:00|0001-01-01 00:00:00+00:00|1496996301|2017-06-09 14:49:03.205353548+00:00
16810b9bfa1519ff9a895238d8b8e7dc3b266273e7cba666fc59d0b8d11898b0|0001-01-01 00:00:00+00:00|0001-01-01 00:00:00+00:00|1497539778|2017-06-19 15:52:36.668131347+00:00
```

However, what's worse is that **the integration tests seem to be constructed incorrectly** to verify whether "lxc_remote config set images.remote_cache_expiry 0" expires cached images synchronously:
`  ! lxc_remote image list l2: | grep -q "${fpbrief}"`

Unfortunately, this does not trigger errexit and fail the test when grep -q returns a non-0 exit code, as demonstrated here:
```
# in the next line errexit is not triggered, although the exit code of the statement is non-0!
$ sh -e -c '! echo x | grep -q x; echo exit code: $?'; echo $?
exit code: 1
0
$ sh -e -c 'echo x | grep -q x; echo exit code: $?'; echo $? 
exit code: 0
0
```

This could be a relatively daft-looking workaround:
```
sh -e -c 'echo x | grep -q x && false; echo exit code: $?'; echo $?
1
```
**Unfortunately, this breaks the integration test for image.sh!**

And there are more candidates where this shell construct may be a problem:
```
sander@sander-thuis ~/go/src/github.com/lxc/lxd/test
 % egrep  -r '^\s+\!.*\|' .
./suites/basic.sh:      ! aa-status | grep -q ":${aa_namespace}:"
./suites/basic.sh:      ! aa-status | grep -q "lxd-lxd-apparmor-test_<${LXD_DIR}>"
./suites/basic.sh:  ! lxc image list | grep -q image1
./suites/basic.sh:  ! lxc image list | grep -q image2
./suites/basic.sh:  ! lxc image list | grep -q image3
./suites/basic.sh:  ! lxc list | grep -q foo
./suites/concurrent.sh:  ! lxc list | grep -q concurrent
./suites/config.sh:  ! lxc config show foo | grep -q "raw.lxc"
./suites/config.sh:  ! lxc config show foo | grep -v "volatile.eth0" | grep -q "eth0"
./suites/config.sh:    ! (lxc config template list c | grep -q my.tpl)
./suites/deps.sh:  ! ldd "$(which lxc)" | grep -q liblxc
./suites/idmap.sh:  ! echo "uid $((UID_BASE+1)) 1000" | lxc config set idmap raw.idmap - || false
./suites/idmap.sh:  ! echo "gid $((GID_BASE+1)) 1000" | lxc config set idmap raw.idmap - || false
```
(in the last two lines, the person writing the || false statement, knew this problem!)

### PR DESCRIPTION
**Pull request by stgraber**
Closes #3904

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
That's a potpourri of a branch. :)

File: lxd/db/images.go [hunk 1]
```diff
@@ -76,7 +76,7 @@ func ImagesGetExpired(db *sql.DB, expiry int64) ([]string, error) {
 		results = append(results, r[0].(string))
 	}
 
-	return []string{}, nil
```
Comment (brauner) [inline lxd/db/images.go]: Oh wow...

Comment (freeekanayaka) [reply lxd/db/images.go]: @brauner this went unnoticed despite the review (#3817), unit tests! :)

Comment (sanderbrandenburg) [reply lxd/db/images.go]: I was trying to find this bug in issue #3904, but I found a problem with the unit/integration test instead :)

File: lxd/patches.go [hunk 2]
```diff
@@ -2475,6 +2476,27 @@ func patchStorageApiDirBindMount(name string, d *Daemon) error {
...
+		return err
+	}
+
+	for _, fingerprint := range images {
+		id, image, err := db.ImageGet(d.db, fingerprint, false, true)
+		if err != nil {
+			return err
+		}
+
+		_, err = db.Exec(d.db, "UPDATE images SET upload_date=? WHERE id=?", image.UploadedAt, id)
```
Comment (freeekanayaka) [inline lxd/patches.go]: I'm a concerned about doing database work/fixes/migrations using the patches system, because:

1) It's not transactional, if a single db.XXX api of the one above fails, but the previous ones have succeeded, you are in an undetermined state, in principle. This might not be a practical concern now, but it will be more with clustering.

2) More importantly, these patches are run after all database updates have been applied, so for example the statement "UPDATE images SET upload_date=? WHERE id=?" could fail if at some point (say) we change the schema of the images table or something like that, and the user upgrades from a version that had a schema compatible with the query in the patch to a version with a schema that is incompatible with the query. We could change the statement to match the new schema, but it could be easily missed since we don't cover each and every upgrade path with integration tests.

In this case, I see no reason for not writing a regular database update instead of a patch.

Comment (stgraber) [reply lxd/patches.go]: A DB schema update cannot be backported to 2.0, patches can, that's why this is a patch.

It's true I should probably have used this within a transaction, that being said this particular patch can be re-executed perfectly safely so it doesn't actually matter in the end.

Comment (freeekanayaka) [reply lxd/patches.go]: I see. It's something we'll need to fix then, because in a cluster we'll want patches to be something that is applied locally once per-node, while database changes like this should be applied once cluster-wide by the leader using dqlite.

Comment (stgraber) [reply lxd/patches.go]: @freeekanayaka I think keeping the DB updates for schema changes makes sense, but we may want to expand the patches system to allow for different scopes. So a patch could be marked as either needing to apply to all the nodes individually (when moving stuff on the filesystem or doing other node-local actions) or be run once for the whole cluster (data migration, changing default profiles, ...)
