### PR TITLE
lxd/device: Clean up mdev vGPU on failure

### LINKED ISSUE #9499: mdev GPU devices not cleaned up on mdev errors
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 18.04.6 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-89-generic
   * LXC version: 4.19
   * LXD version: 4.19
   * Storage backend in use: ZFS

# Issue description

When a VM with an mdev GPU fails to start due to an mdev error the created mdev device isn't cleaned up which leads to exhausting them on the host:

# Steps to reproduce
```
anderson@anderson-nzxt:~$ ls -la /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_8/devices/
total 0
drwxr-xr-x 2 root root 0 Nov  8 08:31 .
drwxr-xr-x 3 root root 0 Nov  8 08:26 ..
anderson@anderson-nzxt:~$ lxc config device add impish-desktop i915 gpu gputype=mdev mdev=i915-GVTg_V5_8
Device i915 added to impish-desktop
```
```
anderson@anderson-nzxt:~$ lxc start --console=vga impish-desktop 
Error: Failed to start device "i915": VMs cannot match multiple GPUs per device
Try `lxc info --show-log impish-desktop` for more info
anderson@anderson-nzxt:~$ ls -la /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_8/devices/
total 0
drwxr-xr-x 2 root root 0 Nov  8 08:31 .
drwxr-xr-x 3 root root 0 Nov  8 08:26 ..
lrwxrwxrwx 1 root root 0 Nov  8 08:56 57ced27c-89f3-448e-a288-0bff319cfd76 -> ../../../57ced27c-89f3-448e-a288-0bff319cfd76
```
```
anderson@anderson-nzxt:~$ lxc start --console=vga impish-desktop 
Error: Failed to start device "i915": VMs cannot match multiple GPUs per device
Try `lxc info --show-log impish-desktop` for more info
anderson@anderson-nzxt:~$ ls -la /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_8/devices/
total 0
drwxr-xr-x 2 root root 0 Nov  8 08:31 .
drwxr-xr-x 3 root root 0 Nov  8 08:26 ..
lrwxrwxrwx 1 root root 0 Nov  8 08:56 57ced27c-89f3-448e-a288-0bff319cfd76 -> ../../../57ced27c-89f3-448e-a288-0bff319cfd76
lrwxrwxrwx 1 root root 0 Nov  8 08:56 f9874ac7-e41c-4b4f-b312-151c8d319175 -> ../../../f9874ac7-e41c-4b4f-b312-151c8d319175
```
```
anderson@anderson-nzxt:~$ lxc start --console=vga impish-desktop 
Error: Failed to start device "i915": No available mdev for profile "i915-GVTg_V5_8"
Try `lxc info --show-log impish-desktop` for more info
```

I can manually clean them up, but the error paths should be doing this right?:
```
anderson@anderson-nzxt:~$ echo 1 | sudo tee /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_8/devices/*/remove
1
anderson@anderson-nzxt:~$ ls -la /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_8/devices/
total 0
drwxr-xr-x 2 root root 0 Nov  8 08:31 .
drwxr-xr-x 3 root root 0 Nov  8 08:26 ..
```

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes #9499.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/device/gpu_mdev.go [hunk 1]
```diff
@@ -127,6 +131,17 @@ func (d *gpuMdev) startVM() (*deviceConfig.RunConfig, error) {
...
 				return nil, errors.Wrapf(err, "Failed to create virtual gpu %q", mdevUUID)
 			}
+
+			revert.Add(func() {
+				path := fmt.Sprintf("/sys/bus/mdev/devices/%s", mdevUUID)
+
+				if shared.PathExists(path) {
+					err := ioutil.WriteFile(filepath.Join(path, "remove"), []byte("1\n"), 0200)
+					if err != nil {
+						logger.Debugf("Failed to remove vgpu %q", mdevUUID)
```
Comment (tomponline) [inline lxd/device/gpu_mdev.go:141]: Probably should be an error log rather than debug. Also should use d.logger to get device and instance context

**Review by tomponline — APPROVED** [review]
