### PR TITLE
Storage: Don't attempt multi-sync mode optimized transfers

### LINKED ISSUE #11194: Lxc copy --refresh from/to zfs backed storage pool leaves @migration-xxxx zfs snapshots behind
as  instructed in https://discuss.linuxcontainers.org/t/lxc-copy-refresh-from-to-zfs-backed-storage-pool-leaves-migration-xxxx-zfs-snapshots-behind/15806/17 I'm opening this ticket.

how to reproduce: 

```
~$ lxc launch u20 migtest --target lxd12
Creating migtest
Starting migtest
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                           USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest  10.3M  14.4G      645M  legacy
~$ lxc copy --refresh migtest alexsv:
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                           USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest  10.3M  14.4G      645M  legacy
~$ lxc copy --refresh migtest alexsv:
~$ ssh lxd12 zfs list lxd12/lxd/containers/migtest -r -t all
NAME                                                                          USED  AVAIL     REFER  MOUNTPOINT
lxd12/lxd/containers/migtest                                                 10.6M  14.4G      645M  legacy
lxd12/lxd/containers/migtest@migration-b893e86b-66e6-407f-85d7-d4dab43ce20c   304K      -      645M  -
```

### PR DESCRIPTION
**Pull request by tomponline**
The ZFS and BTRFS storage drivers were already not doing optimised transfers in the final stage of multi-sync mode (just returning nil). Which causes ZFS temporary snapshots to be left behind. So make this invocation type an error, and detect the use of non-optimized transfer mode earlier to avoid using MultiSync=true in the first place.

This then resolves the issue of the temporary snapshots not being cleaned up on the source.

Instead of https://github.com/lxc/lxd/pull/11193

Fixes #11194

### CODE REVIEW

File: lxd/storage/drivers/driver_zfs_volumes.go [hunk 1]
```diff
@@ -2025,8 +2025,18 @@ func (d *zfs) migrateVolumeOptimized(vol Volume, conn io.ReadWriteCloser, volSrc
...
+					if err != nil {
+						d.logger.Warn("Failed deleting final sync temporary snapshot parent", logger.Ctx{"snapshot": finalParent, "err": err})
+					}
+				}()
+				defer func() {
+					_, err := shared.RunCommand("zfs", "destroy", srcSnapshot)
+					if err != nil {
+						d.logger.Warn("Failed deleting final sync temporary snapshot", logger.Ctx{"snapshot": srcSnapshot, "err": err})
+					}
+				}()
```
Comment (monstermunchkin) [inline lxd/storage/drivers/driver_zfs_volumes.go:2039]: This entire branch can actually be removed, as `volSrcArgs.FinalSync` will always be `false.`

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

File: lxd/storage/drivers/driver_zfs_volumes.go (hunk 1 above)
Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go:2039]: Yep doing now infact :)

Comment (tomponline) [reply lxd/storage/drivers/driver_zfs_volumes.go]: @monstermunchkin done.

**Comment by tomponline** [comment]
jenkins: test this please

**Review by monstermunchkin — APPROVED** [review]
