### PR TITLE
Fix a panic in 'remote add'

### LINKED ISSUE #2089: Panic in
# Required information

Ubuntu 16.04, LXD 2.0.2, LXC 2.0.2

# Issue description

The command `lxc remote add tmp tmp` will cause a panic if `tmp` is a valid path in the current working directory.  There are three distinct bugs related to the panic:

- Bad string comparison using unchecked slices (this is the immediate cause of the panic).
- Not checking if the path is a directory when determining scheme.  LXC requires the full path to the UNIX socket when communicating with a server, thus successful communication with a directory is impossible and the path match should be ignored, i.e. https:// scheme should be assumed.
- Handling of relative paths is inconsistent.  If relative paths are allowed, then client.go has a bug where it inadvertently converts relative paths to absolute paths.  If relative paths are not allowed, then the code should be hardened and explicit checks added to addServer and to client.go.

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x8c9080, 0xc82000e100)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
main.(*remoteCmd).addServer(0xc820017900, 0xc8200e0330, 0x7fffed1330b9, 0x3, 0x7fffed1330bd, 0x3, 0x0, 0x0, 0x0, 0x44f100, ...)
	/home/sean/go/src/github.com/lxc/lxd/lxc/remote.go:151 +0x1cc6
main.(*remoteCmd).run(0xc820017900, 0xc8200e0330, 0xc820017ec0, 0x3, 0x4, 0x0, 0x0)
	/home/sean/go/src/github.com/lxc/lxd/lxc/remote.go:312 +0x576
main.run(0x0, 0x0)
	/home/sean/go/src/github.com/lxc/lxd/lxc/main.go:137 +0x1098
main.main()
	/home/sean/go/src/github.com/lxc/lxd/lxc/main.go:21 +0x27
```

# Steps to reproduce
`mkdir tmp`
`lxc remote add tmp tmp`

### PR DESCRIPTION
**Pull request by sean-jc**
Use strings.TrimPrefix to strip 'unix://' from the URL/path in both
remoteCmd.addServer() and connectViaUnix.  This resolves the direct
cause of the panic and makes the handling of relative paths consistent
in both flows.

Add a check for IsDir when determining whether HTTPS or UNIX should
be assumed.  The UNIX scheme requires a full path to the UNIX socket,
i.e. a directory can never be a valid LXD server.

Fixes #2089

Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -255,11 +255,7 @@ func connectViaUnix(c *Client, remote *RemoteConfig) error {
 		//   unix:///path/to/socket
 		//   unix:/path/to/socket
 		//   unix:path/to/socket
-		path := strings.TrimPrefix(remote.Addr, "unix:")
-		if strings.HasPrefix(path, "///") {
-			// translate unix:///path/to, to just "/path/to"
-			path = path[2:]
-		}
+		path := strings.TrimPrefix(strings.TrimPrefix(remote.Addr, "unix:"), "//")
```
Comment (sean-jc) [inline client.go]: This is necessary to allow relative paths for the server, which appear to be allowed given the 'unix:path/to/socket' example above.  If relative paths are not allowed then explicit checks should be added here and in remote.go.  Stripping "unix:" without stripping the "//" prepended by addServer results in relative paths being inadvertently converted to absolute paths.

File: lxc/remote.go [hunk 2]
```diff
@@ -126,7 +126,7 @@ func (c *remoteCmd) addServer(config *lxd.Config, server string, addr string, ac
 	} else if addr[0] == '/' {
 		rScheme = "unix"
 	} else {
-		if !shared.PathExists(addr) {
+		if !shared.PathExists(addr) || shared.IsDir(addr) {
```
Comment (tych0) [inline lxc/remote.go]: It seems to me like what we really want here is an IsUnixSocket test, because if this is e.g. a unix char device, we can't connect to it then either.

**Comment by tych0** [comment]
Just ran the test suite, LGTM other than the unix socket bit.

File: lxc/remote.go (hunk 2 above)
Comment (sean-jc) [inline lxc/remote.go]: Agreed, I'll get that added.

**Comment by sean-jc** [comment]
@tych0, can you confirm that relative paths are allowed for servers?  Allowing relative paths seems a little bizarre as it leads to inconsistent client behavior.

**Comment by tych0** [comment]
I agree that it doesn't make a lot of sense, but IIUC this patch supports them just fine, doesn't it?

**Comment by sean-jc** [comment]
Yeah, they work, just wondering if it made sense to explicitly disallow them.

**Comment by tych0** [comment]
It probably did, but now that we have a release out there that supports them them, it's probably best to leave them there for now since it's not too hard to keep them supported.

**Comment by stgraber** [comment]
jenkins: test this please
