### PR TITLE
Fix BTRFS optimized refresh 

### LINKED ISSUE #10186: Optimized refresh broken
Reported from https://discuss.linuxcontainers.org/t/error-error-transferring-instance-data-failed-getting-instance-storage-pool-name-instance-storage-pool-not-found/13743

This appears to be an issue with optimized refresh, but I am still investigating it.

### PR DESCRIPTION
**Pull request by monstermunchkin**
- lxd/storage/drivers/btrfs: Delete volume after receiving new one
- lxd/storage/drivers/btrfs: Check length of snapshots slice

Fixes #10186

### CODE REVIEW

File: lxd/storage/drivers/driver_btrfs_volumes.go [hunk 1]
```diff
@@ -656,6 +656,12 @@ func (d *btrfs) createVolumeFromMigrationOptimized(vol Volume, conn io.ReadWrite
...
 	}
 
+	// Receive main volume.
+	err = receiveVolume(vol, tmpVolumesMountPoint)
+	if err != nil {
+		return err
+	}
+
 	if volTargetArgs.Refresh {
 		// Delete main volume before receiving it.
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_volumes.go:666]: Comment is out of date.

File: lxd/storage/drivers/driver_btrfs_volumes.go [hunk 2]
```diff
@@ -1341,7 +1341,7 @@ func (d *btrfs) migrateVolumeOptimized(vol Volume, conn io.ReadWriteCloser, volS
 
 			_, snapName, _ := shared.InstanceGetParentAndSnapshotName(snap.name)
 
-			if snapName == volSrcArgs.Snapshots[0] {
+			if len(volSrcArgs.Snapshots) > 0 && snapName == volSrcArgs.Snapshots[0] {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_volumes.go:1344]: @monstermunchkin does this fix the `Error: Failed instance creation: Error transferring instance data: Got error reading migration source: websocket: close 1000 (normal)` error?

Comment (tomponline) [reply lxd/storage/drivers/driver_btrfs_volumes.go:1344]: Was the target LXD crashing?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_volumes.go:1344]: > does this fix the `Error: Failed instance creation: Error transferring instance data: Got error reading migration source: websocket: close 1000 (normal)` error?

Yes.

> Was the target LXD crashing?

No, only the source.

Comment (tomponline) [reply lxd/storage/drivers/driver_btrfs_volumes.go:1344]: Ah I see thanks.

Comment (tomponline) [reply lxd/storage/drivers/driver_btrfs_volumes.go:1344]: Is there a similar issue with the ZFS optimized refresh mode?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_volumes.go:1344]: > Is there a similar issue with the ZFS optimized refresh mode?

No, there isn't. I just checked.

**Review by tomponline — APPROVED** [review]

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you update the tests with the reproducer for this fix.

**Comment by monstermunchkin** [comment]
I also noticed an error I thought to have fixed which is `cannot find parent subvolume`. The error occurs only in certain scenarios but it's caused by us making subvolumes read-write before moving them to their final location (readonly subvolumes cannot be moved). When a received subvolume is set read-write, it loses some important information such as the `Received UUID` and `Receive transid`. Without this information, btrfs is unable to find the parent which leads to the error I mentioned.

There are two possible fixes for this:
1) We receive the subvolumes in their final location without having to move them. I already tried that but ran into problems with nested subvolumes. I might just have to try a bit harder :)
2) We use ioctl to modify the received UUID [0].

This will go into separate PR once I've figured it out.

[0] https://www.spinics.net/lists/linux-btrfs/msg75315.html

File: test/suites/migration.sh [hunk 3]
```diff
@@ -437,6 +437,16 @@ migration() {
   lxc_remote rm -f l1:c1
   lxc_remote rm -f l2:c1
 
+  lxc_remote init testimage l1:c1
```
Comment (tomponline) [inline test/suites/migration.sh:440]: Could you add a comment explaining why we are testing this for future readers. Then this should be good to go assuming the tests pass :)
