### PR TITLE
lxd/resources/memory: Fix memory calculation

### LINKED ISSUE #7362: LXD resources does not report full system memory
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-29-generic
   * LXC version: 4.0.2
   * LXD version: 4.0.1
   * Storage backend in use: dir | lvm

# Issue description

When getting the amount of system memory from LXD resources the full memory amount is not being reported. This causes MAAS to under report the amount of memory the system has. lshw reports the correct amount.

# Steps to reproduce

 1. Create an LXD VM with 2048M of memory
 2. Install LXD in the newly created VM
 3. Memory amount reported by LXD will be 1991M.

Another example can be found on hardware. My laptop has 64G of RAM however LXD is reporting the total memory amount to be 62.47G.

### PR DESCRIPTION
**Pull request by monstermunchkin**
This calculates the total memory from /sys/devices/system/memory, and
replaces the previously retrieved value if successful.

This fixes #7362.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

File: lxd/resources/memory.go [hunk 1]
```diff
@@ -144,6 +199,13 @@ func GetMemory() (*api.ResourcesMemory, error) {
 		return nil, errors.Wrap(err, "Failed to parse /proc/meminfo")
 	}
 
+	// Calculate the total memory from /sys/devices/system/memory.
+	// If successful, replace the previous value, retrieved from /proc/meminfo.
```
Comment (tomponline) [inline lxd/resources/memory.go:203]: @monstermunchkin would it be worth adding a comment here as to why we look up total memory instead of just using the /proc/meminfo value, for future reference.

Comment (tomponline) [reply lxd/resources/memory.go:204]: thanks
