### PR TITLE
lxd/util/net: Assign default port if no port given

### LINKED ISSUE #10181: Trailing colon on https_address freezes cluster
# Issue description

Assigning a `core.https_address` or `cluster.https_address` with a trailing colon will result in no port being assigned to the endpoints, thus causing cluster initialization to never complete.

# Steps to reproduce
```bash
lxd init --auto
lxc config set core.https_address 127.0.0.1: 
# Or `cluster.https_address` above.
lxc cluster enable test1
# This never returns.
```

### PR DESCRIPTION
**Pull request by masnax**
Closes #10181 

Assigns the `defaultPort` (8443) to an address when a colon is specified. A trailing colon makes `net.SplitHostPort` return successfully, but with an empty port.

Signed-off-by: Max Asnaashari <max.asnaashari@canonical.com>

### CODE REVIEW

File: lxd/util/net.go [hunk 1]
```diff
@@ -84,6 +84,9 @@ func CanonicalNetworkAddress(address string, defaultPort int) string {
 			// a port number, so append the default port.
 			address = fmt.Sprintf("%s:%d", address, defaultPort)
 		}
+	} else if port == "" && address[len(address)-1] == ':' {
+		// An address that ends with a trailing colon will be parsed as having an empty port.
+		address = net.JoinHostPort(host, fmt.Sprintf("%d", defaultPort))
```
Comment (stgraber) [inline lxd/util/net.go:89]: Is that going to cause us some issues when passed an IPv6 address like `::` `1234::`?

Comment (stgraber) [reply lxd/util/net.go:89]: Hmm, no, I guess it will be fine, the IPv6 case should parse as a valid address and so hit the above case.
The only time where we should hit this fallback logic is if there's a single trailing colon.

**Comment by tomponline** [comment]
@stgraber @masnax Is there a particular reason we accept `<host>:` as a valid listen address anyway? Seems like we should have just rejected that during validation as an invalid, avoiding the need to handle this scenario?

**Comment by tomponline** [comment]
@masnax please can you add some unit tests for `CanonicalNetworkAddress` so we can document and test its behavior, thanks.
