### PR TITLE
lxd/network/openvswitch: Use %s so that delimiting quotes are not escaped.

### LINKED ISSUE #10605: OVN logical network IP addresss change breaks virtual router
At some point it looks like the tooling around OVN IP changing has altered such that the new IPs are being incorrectly escaped:

New network with automatically generated IPs:

```
lxc network create ovn1 --type=ovn network=lxdbr0

sudo ovn-nbctl list logical_router_port
_uuid               : 1e8fdd0d-f49b-49bd-a8e6-aed2da39fb55
enabled             : []
external_ids        : {}
gateway_chassis     : []
ha_chassis_group    : []
ipv6_prefix         : []
ipv6_ra_configs     : {address_mode=dhcpv6_stateless, dnssl=lxd, max_interval="60", min_interval="30", mtu="1500", rdnss="fd42:bafd:ac21:9f::1", send_periodic="true"}
mac                 : "00:16:3e:15:18:f3"
name                : lxd-net34-lr-lrp-int
networks            : ["10.20.42.1/24", "fd42:fcd6:d173:50b9::1/64"]
options             : {gateway_mtu="1500"}
peer                : []
```

Then alter the network's IP:

```
lxc network set ovn1 ipv4.address=10.21.42.1/24

sudo ovn-nbctl list logical_router_port
_uuid               : 1e8fdd0d-f49b-49bd-a8e6-aed2da39fb55
enabled             : []
external_ids        : {}
gateway_chassis     : []
ha_chassis_group    : []
ipv6_prefix         : []
ipv6_ra_configs     : {address_mode=dhcpv6_stateless, dnssl=lxd, max_interval="60", min_interval="30", mtu="1500", rdnss="fd42:bafd:ac21:9f::1", send_periodic="true"}
mac                 : "00:16:3e:15:18:f3"
name                : lxd-net34-lr-lrp-int
networks            : ["10.21.42.1/24\",\"fd42:fcd6:d173:50b9::1/64"]
options             : {gateway_mtu="1500"}
peer                : []
```

Note the difference between:

```
networks            : ["10.20.42.1/24", "fd42:fcd6:d173:50b9::1/64"]
networks            : ["10.21.42.1/24\",\"fd42:fcd6:d173:50b9::1/64"]
```

Also we see these errors in the OVN log:

```
2022-06-27T08:53:48.620Z|00177|ovn_util|INFO|invalid syntax '10.64.199.2/24","fd42:bafd:ac21:9f:216:3eff:fe15:18f3/64' in networks
```

### PR DESCRIPTION
**Pull request by markylaing**
Closes #10605

### CODE REVIEW

File: lxd/network/openvswitch/ovn.go [hunk 1]
```diff
@@ -433,7 +433,7 @@ func (o *OVN) LogicalRouterPortAdd(routerName OVNRouter, portName OVNRouterPort,
 			}
 
 			_, err := o.nbctl("set", "Logical_Router_Port", string(portName),
-				fmt.Sprintf("networks=%q", strings.Join(ips, `","`)),
+				fmt.Sprintf(`networks="%s"`, strings.Join(ips, `","`)),
 				fmt.Sprintf("mac=%q", mac.String()),
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:437]: Can you also use %s on this line too for consistency.

**Comment by tomponline** [comment]
@stgraber we'll want this in the LXD 5.3 snap otherwise it'll cause issues with the LXD OVN networks when they are next modified.

**Comment by tomponline** [comment]
Thanks!
