### PR TITLE
Make blkio limits more robust

### LINKED ISSUE #1568: Adding a device to an instance failed
Adding a mount failed as follows:

```
mthaddon@mallory:~/repos/mojo/userspace-lxc$ lxc exec mojo-is-xenial-xenial -- ls -lha /home/mthaddon/.local/sharetotal 8.0K
drwxr-xr-x 2 root root 4.0K Feb  4 21:45 .
drwxr-xr-x 3 root root 4.0K Feb  4 21:44 ..
mthaddon@mallory:~/repos/mojo/userspace-lxc$ lxc config device add mojo-is-xenial-xenial mojo disk path=/home/mthaddon/.local/share/mojo source=/home/mthaddon/.local/share/mojo
Device mojo added to mojo-is-xenial-xenial
error: Disk is missing /sys/class/block entry
mthaddon@mallory:~/repos/mojo/userspace-lxc$ lxc exec mojo-is-xenial-xenial -- ls -lha /home/mthaddon/.local/sharetotal 8.0K
drwxr-xr-x 2 root root 4.0K Feb  4 21:45 .
drwxr-xr-x 3 root root 4.0K Feb  4 21:44 ..
```

### PR DESCRIPTION
**Pull request by stgraber**
Lets not completely fail startup/update on things the user cannot do
anything about. It's almost impossible to know what devices we can set
block limits on, so if we can't, just move on.

Closes #1568

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -3508,14 +3522,18 @@ func (c *containerLXC) getDiskLimits() (map[string]deviceBlockLimit, error) {
...
 
+			dev := strings.TrimPrefix(block, "/dev/")
 			if strings.Contains(dev, "/") {
 				continue
 			}
 
 			if !shared.PathExists(fmt.Sprintf("/sys/class/block/%s/dev", dev)) {
-				return nil, fmt.Errorf("Disk %s is missing /sys/class/block entry", dev)
+				shared.Log.Error("Disk is missing /sys/class/block entry", log.Ctx{"device": dev})
+				continue
```
Comment (tych0) [inline lxd/container_lxc.go]: Does this mean that it's possible that a user asked for a quota on a block device and if we couldn't set it they'll only get an error in the log? I agree it shouldn't fail if they haven't asked for a quota (i.e. hasDiskLimits above seems reasonable), but I think we should fail to start a container if we can't apply disk limits and the user has asked for them.

Comment (stgraber) [inline lxd/container_lxc.go]: So in theory we could only keep the hasLimits part of this change and drop all other checks, which would then make things fail if setting a limit on a device which doesn't support it.

I'll try and rework this mess when I'm a bit more awake (just got off a plane).
