### PR TITLE
lxd/patches: Reset ZFS mountpoint/canmount

### LINKED ISSUE #6765: Can not start a container after 3.19 upgrade : no mountpoint set
After 3.19 snap upgrade I get the following error when I try to start a container created before 3.19 release.

```
root@lxd01:~# lxc start bionic

Error: Common start logic: Failed to run: zfs mount vgraid/lxd/containers/bionic: cannot mount vgraid/lxd/containers/bionic: no mountpoint set
Try  lxc info --show-log bionic for more info

```

I found also the following work around:

```
root@lxd01:~# zfs set mountpoint=/var/snap/lxd/common/lxd/storage-pools/default/containers/bionic vgraid/lxd/containers/bionic

root@lxd01:~# zfs umount vgraid/lxd/containers/bionic

root@lxd01:~# lxc start disco

```
Hoping that it will not have side effects in other parts of the system

### PR DESCRIPTION
**Pull request by stgraber**
Closes #6765

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline they're unlikely to have changed but I think we had some old LXD versions that just didn't have it set at all. This resets us to current expected state, so we should be fine going forward.

File: lxd/storage/drivers/driver_zfs_patches.go [hunk 1]
```diff
@@ -19,3 +23,61 @@ func (d *zfs) patchStorageCreateVM() error {
...
+	if err != nil {
+		return err
+	}
+
+	for _, dataset := range datasets {
+		// Skip snapshots.
+		if strings.Contains(dataset, "@") {
+			continue
+		}
+
```
Comment (problame) [inline lxd/storage/drivers/driver_zfs_patches.go]: You should be skipping bookmarks as well.
Otherwise, the `setDatasetProperties` below fails with the error message we discovered in this issue:

https://github.com/zrepl/zrepl/pull/259#issuecomment-578481081

(zrepl uses bookmarks for resumable replication)

@stgraber could you fix this? I have no experience with lxd, just tried to root-cause the user issue in zrepl
