### PR TITLE
Optimise proxy device driver nat rules

### LINKED ISSUE #9073: Proxy device with NAT enabled has a single firewall rule per port
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.8.0-1037-oracle #38~20.04.1-Ubuntu`
   * LXC version: 
   * LXD version: 4.0.7
   * Storage backend in use: zfs

# Issue description

Adding the following proxy device to a container causes one iptables rule in the nat table to be generated per port:

```
  turn:
    connect: udp:240.39.0.109:60000-60100
    listen: udp:10.0.0.39:60000-60100
    nat: "true"
    type: proxy
```

```
$ sudo iptables -S -t nat
...
-A POSTROUTING -s 240.39.0.109/32 -d 240.39.0.109/32 -p udp -m udp --dport 60100 -m comment --comment "generated for LXD container juju-111acc-1 (turn)" -j MASQUERADE
....
-A POSTROUTING -s 240.39.0.109/32 -d 240.39.0.109/32 -p udp -m udp --dport 60000 -m comment --comment "generated for LXD container juju-111acc-1 (turn)" -j MASQUERADE
```

# Steps to reproduce

See above

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by markylaing**
Currently, proxy device drivers add NAT rules for every listen port (e.g. given a listen range of `1000-1999` the driver will add 1000 NAT rules). This change optimises the number of rules added by the drivers by examining whether the given ports are part of a range.

Fixes #9073.

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by markylaing** [comment]
jenkins: test this please

File: lxd/firewall/drivers/drivers_util.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
+package drivers
+
+import (
+	"fmt"
+)
+
+// PortRangesFromSlice checks if adjacent indices in the given slice contain consecutive
+// numbers and returns a slice of port ranges ([startNumber, rangeSize]) accordingly.
+//
+// Note that if the input slice was parsed from multiple ranges (e.g. "80-81,5000") then
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:10]: @markylaing this part of the comment doesn't look right?

File: lxd/firewall/drivers/drivers_util.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+			size = ports[i] - ports[startIdx] + 1
+			portRanges = append(portRanges, [2]uint64{ports[startIdx], size})
+			startIdx = i + 1
+		}
+	}
+
+	return portRanges
+}
+
+func portRangeStr(portRange [2]uint64, delimiter string) string {
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:31]: This function portRangeStr, doesn't appear to be relevant or used in the commit "Adds util to convert port list to port ranges. " so probably should be moved to a different commit.

File: lxd/firewall/drivers/drivers_util_test.go [hunk 3]
```diff
@@ -0,0 +1,62 @@
+package drivers
+
+import (
+	"log"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestPortRangesFromSlice(t *testing.T) {
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util_test.go:10]: I'm enjoying the tests :)

File: lxd/firewall/drivers/drivers_xtables.go [hunk 4]
```diff
@@ -936,6 +936,19 @@ func (d Xtables) InstanceSetupProxyNAT(projectName string, instanceName string,
 
 	comment := d.instanceDeviceIPTablesComment(projectName, instanceName, deviceName)
 
+	targetPortRanges := PortRangesFromSlice(forward.TargetPorts)
+	for _, targetPortRange := range targetPortRanges {
+		targetPortStr := portRangeStr(targetPortRange, ":")
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_xtables.go:941]: Could we call this targetPortRangeStr or targetPortsStr to make it clear it could contain multiples.

File: lxd/firewall/drivers/drivers_nftables.go [hunk 5]
```diff
@@ -481,6 +481,17 @@ func (d Nftables) InstanceSetupProxyNAT(projectName string, instanceName string,
...
 	var snatRules []map[string]interface{}
 
+	targetPortRanges := PortRangesFromSlice(forward.TargetPorts)
+	for _, targetPortRange := range targetPortRanges {
+		targetPort := portRangeStr(targetPortRange, "-")
+		snatRules = append(snatRules, map[string]interface{}{
+			"ipFamily":   ipFamily,
+			"protocol":   forward.Protocol,
+			"targetHost": targetAddressStr,
+			"targetPort": targetPort,
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_nftables.go:491]: Could change this variable and template field name to indicate that it could contain multiple ports now.

File: lxd/firewall/drivers/drivers_util.go [hunk 6]
```diff
@@ -36,3 +36,51 @@ func portRangeStr(portRange [2]uint64, delimiter string) string {
 	}
 	return fmt.Sprintf("%d%s%d", portRange[0], delimiter, portRange[0]+portRange[1]-1)
 }
+
+// getOptimisedDNATRanges returns a map of listen port ranges to target port ranges that can be
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:40]: I think it could be worth expanding the comment here a bit to explain why this is needed and what it returns in different scenarios to help the future reader understand what the function is doing.

File: lxd/firewall/drivers/drivers_util.go [hunk 7]
```diff
@@ -36,3 +36,51 @@ func portRangeStr(portRange [2]uint64, delimiter string) string {
...
+	nProcessedPorts := 0
+	for _, listenPortRange := range listenPortRanges {
+		rangeEndIdx := nProcessedPorts + int(listenPortRange[1])
+
+		if targetPortsLen == 1 {
+			// Only one target port. Each listen range maps directly to that port.
+			snatRules[listenPortRange] = targetPortRanges[0]
+			nProcessedPorts += int(listenPortRange[1])
+
+		} else if targetRangeSize, ok := targetPortRangeMap[forward.TargetPorts[nProcessedPorts]]; ok && forward.TargetPorts[nProcessedPorts] == listenPortRange[0] {
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:65]: We try and avoid using this form of if statement, (i.e initialising a local variable inside the if statement itself).
The reason for this is that it complicates the scope, and in this case, makes for a harder to read longer line that goes out of the github viewport.

File: lxd/firewall/drivers/drivers_util.go [hunk 8]
```diff
@@ -36,3 +36,51 @@ func portRangeStr(portRange [2]uint64, delimiter string) string {
...
+				// Port ranges are identical. One to one mapping.
+				snatRules[listenPortRange] = [2]uint64{forward.TargetPorts[nProcessedPorts], targetRangeSize}
+				nProcessedPorts += int(listenPortRange[1])
+
+			} else {
+				// Port ranges are identical for until the end of the target range.
+				snatRules[[2]uint64{listenPortRange[0], targetRangeSize}] = [2]uint64{forward.TargetPorts[nProcessedPorts], targetRangeSize}
+				nProcessedPorts += int(targetRangeSize)
+			}
+
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:76]: Please can you remove this empty line. Thanks

File: lxd/firewall/drivers/drivers_util.go (hunk 1 above)
Comment (markylaing) [reply lxd/firewall/drivers/drivers_util.go:10]: Shall I just remove the note? If we wanted to keep track of user defined ranges we would need to return it when the address is parsed, so I wasn't sure if it was necessary to include this note or not in any case.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thank @markylaing 

Apart from a few minor issues this is looking really good.

Jenkins seems a bit messed up at the moment, so I'll keep an eye on it and re-run the tests later if they don't start.

File: lxd/firewall/drivers/drivers_util.go (hunk 1 above)
Comment (tomponline) [reply lxd/firewall/drivers/drivers_util.go:10]: I wasn't clear on what the comment actually meant.

Comment (markylaing) [reply lxd/firewall/drivers/drivers_util.go:10]: Ahh I see sorry. How about:

> This function cannot differentiate ranges from adjacent ports e.g. if the given slice is "[80,81,82]" then the returned
> range will be "80-82", regardless of whether the user input was parsed from "80-82" or "80,81,82".

Comment (tomponline) [reply lxd/firewall/drivers/drivers_util.go:10]: Oh I see, thats fine to keep the (clarified) comment in then.

File: lxd/firewall/drivers/drivers_util.go [hunk 9]
```diff
@@ -0,0 +1,86 @@
+package drivers
+
+import (
+	"fmt"
+)
+
+// PortRangesFromSlice checks if adjacent indices in the given slice contain consecutive
```
[the remark this answers is not in the document]
Comment (markylaing) [reply lxd/firewall/drivers/drivers_util.go:7]: Yes sorry I originally had it in the network utils. Will change.

File: lxd/firewall/drivers/drivers_util.go [hunk 10]
```diff
@@ -0,0 +1,108 @@
...
+
+// getOptimisedDNATRanges returns a map of listen port ranges to target port ranges that can be
+// applied in any order.
+//
+// Both Xtables and Nftables are able to apply rules for multiple listen ports at a time when a
+// listen port range exactly matches the corresponding target port range (e.g. "80-85" to "80-85")
+// or when there is a single target port (e.g. "80-85" to "80"). This function checks when these
+// conditions are met and returns a map of listen and target port ranges to be applied by the loaded
+// driver.
+func getOptimisedDNATRanges(forward *AddressForward) map[[2]uint64][2]uint64 {
```
Comment (markylaing) [inline lxd/firewall/drivers/drivers_util.go:47]: @tomponline FYI I've changed the order of the logic in this function a little bit to make it easier to read.

Comment (tomponline) [reply lxd/firewall/drivers/drivers_util.go:47]: OK can you let me know when you've rebased (so that the commits are clean, as right now they show a mixture of changes) and I'll review again. Thanks

Comment (markylaing) [reply lxd/firewall/drivers/drivers_util.go:47]: Apologies, It's fixed now.

**Comment by tomponline** [comment]
@markylaing the tests are failing I'm afraid.

**Comment by stgraber** [comment]
Test results look good, will let @tomponline do one last pass and merge if he's happy :)

File: lxd/firewall/drivers/drivers_util.go [hunk 11]
```diff
@@ -35,3 +35,74 @@ func portRangeStr(portRange [2]uint64, delimiter string) string {
...
+	if targetPortsLen == 1 {
+		targetPort := forward.TargetPorts[0]
+		for _, listenPortRange := range listenPortRanges {
+			snatRules[listenPortRange] = [2]uint64{targetPort, 1}
+		}
+
+		return snatRules
+	}
+
+	// For a given listen range, the corresponding target range may not simply be targetRange[i] (where "i"
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:64]: Much better thanks.

File: lxd/firewall/drivers/drivers_util.go [hunk 12]
```diff
@@ -35,3 +35,74 @@ func portRangeStr(portRange [2]uint64, delimiter string) string {
...
+		// at the same value.
+		if ok && listenPortRange[0] == currentTargetPort {
+			targetPortRange := [2]uint64{currentTargetPort, targetPortRangeSize}
+
+			// Check if the listen and target ranges are the same size.
+			if listenPortRange[1] == targetPortRangeSize {
+				// Port ranges are identical. One to one mapping.
+				snatRules[listenPortRange] = targetPortRange
+				nProcessedPorts += int(listenPortRange[1])
+
```
Comment (tomponline) [inline lxd/firewall/drivers/drivers_util.go:92]: Empty line to be removed here please.

**Review by tomponline — APPROVED** [review]
One empty line to remove, then this is good to merge. Thanks

File: lxd/firewall/drivers/drivers_util.go (hunk 12 above)
Comment (markylaing) [reply lxd/firewall/drivers/drivers_util.go]: Done.
