### PR TITLE
Fix backup import

### LINKED ISSUE #5446: Lxc import - error: not found
https://discuss.linuxcontainers.org/t/lxc-import-error-not-found/3927

What we need is:
* Clear error when the storage pool can’t be found during restore
* Option to lxc import to override the storage pool, so one can do -s blah at import time

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes #5446

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

File: lxd/backup.go [hunk 1]
```diff
@@ -248,7 +256,14 @@ func backupFixStoragePool(c *db.Cluster, b backupInfo) error {
 
 		// Change the pool in the backup.yaml
 		backup.Pool = pool
-		backup.Container.Devices["root"]["pool"] = "default"
+		if backup.Container.Devices != nil {
+			backup.Container.Devices["root"]["pool"] = poolName
```
Comment (stgraber) [inline lxd/backup.go]: You can't assume the device is called `root`

File: lxd/backup.go [hunk 2]
```diff
@@ -248,7 +256,14 @@ func backupFixStoragePool(c *db.Cluster, b backupInfo) error {
...
+
+		}
+
+		if backup.Container.ExpandedDevices != nil {
+			backup.Container.ExpandedDevices["root"]["pool"] = poolName
```
Comment (stgraber) [inline lxd/backup.go]: You can't assume the device is called `root`

File: client/lxd_containers.go [hunk 3]
```diff
@@ -88,13 +89,37 @@ func (r *ProtocolLXD) CreateContainerFromBackup(args ContainerBackupArgs) (Opera
...
+		}
+
+		return op, nil
+	}
+
+	if !r.HasExtension("container_backup_override_pool") {
+		return nil, fmt.Errorf("The server is missing the required \"container_backup_override_pool\" API extension")
+	}
+
+	data, err := ioutil.ReadAll(args.BackupFile)
```
Comment (stgraber) [inline client/lxd_containers.go]: That's a terrible idea, this may end up loading several GB of stuff into memory, possibly several time as part of the http query, we really can't do that (and have an open bug to track down an internal case of this causing LXD to take up to 16GB of RAM while importing a backup).

File: shared/api/container.go [hunk 4]
```diff
@@ -138,4 +138,8 @@ type ContainerSource struct {
 
 	// API extension: container_copy_project
 	Project string `json:"project,omitempty" yaml:"project,omitempty"`
+
+	// API extension: container_backup_override_pool
+	Backup []byte `json:"backup,omitempty" yaml:"backup,omitempty"`
+	Pool   string `json:"pool,omitempty" yaml:"pool,omitempty"`
```
Comment (stgraber) [inline shared/api/container.go]: As pointed out in later commits, this isn't a viable option to fix this problem.

When dealing with raw data, the best option is to do what we've done with both files and images, use HTTP headers to encode additional metadata.

File: test/suites/backup.sh [hunk 5]
```diff
@@ -250,6 +250,51 @@ test_backup_import() {
     lxc start b2
     lxc delete --force b2
   fi
+
+  default_pool="$(lxc profile device get default root pool)"
+  default_path="$(lxc profile device get default root path)"
+
+  # Create new storage pools
+  lxc storage create pool_1 dir
+  lxc storage create pool_2 dir
```
Comment (stgraber) [inline test/suites/backup.sh]: This pool is never cleaned up

Comment (stgraber) [inline test/suites/backup.sh]: This pool is never cleaned up

File: test/suites/backup.sh [hunk 6]
```diff
@@ -250,6 +250,51 @@ test_backup_import() {
...
+  lxc rm -f b3
+  lxc storage delete pool_1
+
+  # This should succeed as it will fall back on the default pool
+  lxc import "${LXD_DIR}/c3.tar.gz"
+
+  lxc rm -f b3
+
+  # Remove possible containers attached to the profile
+  lxc rm -f c1 c2 || true
```
Comment (stgraber) [inline test/suites/backup.sh]: Where do those come from? They should just be deleted as part of whatever test created them.

File: test/suites/backup.sh [hunk 7]
```diff
@@ -250,6 +250,51 @@ test_backup_import() {
     lxc start b2
     lxc delete --force b2
   fi
+
+  default_pool="$(lxc profile device get default root pool)"
+  default_path="$(lxc profile device get default root path)"
```
Comment (stgraber) [inline test/suites/backup.sh]: path will always be / so no need for fancy handling of it

File: test/suites/backup.sh [hunk 8]
```diff
@@ -250,6 +250,51 @@ test_backup_import() {
...
+
+  # Create new storage pools
+  lxc storage create pool_1 dir
+  lxc storage create pool_2 dir
+
+  # Export created container
+  lxc init testimage b3 -s pool_1
+  lxc export b3 "${LXD_DIR}/c3.tar.gz"
```
Comment (stgraber) [inline test/suites/backup.sh]: Can we either call the container `c3` or call the file `b3`? The mix of the two is confusing :)

**Comment by monstermunchkin** [comment]
All done

**Comment by stgraber** [comment]
jenkins: test this please

File: test/suites/storage_volume_attach.sh [hunk 9]
```diff
@@ -56,6 +56,7 @@ test_storage_volume_attach() {
 
   if [ "${UIDs}" -lt 500000 ] || [ "${GIDs}" -lt 500000 ]; then
     echo "==> SKIP: The storage volume attach test requires at least 500000 uids and gids"
+    lxc rm -f c1 c2
```
Comment (stgraber) [inline test/suites/storage_volume_attach.sh]: Can you make this fix a separate commit?

File: lxd/containers_post.go [hunk 10]
```diff
@@ -13,7 +13,7 @@ import (
 	"os"
 	"strings"
 
-	"github.com/dustinkirkland/golang-petname"
+	petname "github.com/dustinkirkland/golang-petname"
```
Comment (stgraber) [inline lxd/containers_post.go]: What's the reason behind that one?

Comment (monstermunchkin) [reply lxd/containers_post.go]: vim-go automatically runs `goimports` when saving a file. It formats the code and cleans up imports. That's what happened here ;)
