### PR TITLE
Check all alias args to support subcommand aliases

### LINKED ISSUE #2095: LXC doesn't correctly handle sub-command aliases
# Required information

Ubuntu 16.04, LXC 2.0.2

# Issue description

LXC will incorrectly match a sub-command alias due to effectively checking only the first arg of the alias, e.g. given the alias `lxc image cp`, any `lxc image` command will match the alias.

# Steps to reproduce

```
printf "aliases:\n  image cp: image copy\n" >> ~/.config/lxc/config.yml
lxc image list
...
error: wrong number of subcommand arguments
```

### PR DESCRIPTION
**Pull request by sean-jc**
Fixes #2095

Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

### CODE REVIEW

**Comment by sean-jc** [comment]
What is the rationale behind adding alias support in LXC itself instead of relying on the shell to handle aliases?  I ask because if built-in alias support is a short-term stop gap then I probably won't prioritize adding tests, but if this is something that will stick around for a while then I'll look into adding an alias.sh test.

**Comment by stgraber** [comment]
The shell doesn't let you alias "lxc shell BLAH" to "lxc exec BLAH -- /bin/bash"

**Comment by stgraber** [comment]
@tych0 can you review this? You have a better idea of how aliases work than I do :)

File: lxc/main.go [hunk 1]
```diff
@@ -189,24 +189,16 @@ func expandAlias(config *lxd.Config, origArgs []string) ([]string, bool) {
 	aliasKey := []string{}
 	aliasValue := []string{}
 
+FindAlias:
```
Comment (tych0) [inline lxc/main.go]: Sorry to be a negative nancy here, but can we use the "matches := false" trick as before, instead of this goto-style syntax? I think basically we just want to switch it to "matches := true" by default and switch it to false if we find one that doesn't match (i.e. logical and instead of logical or).

**Comment by tych0** [comment]
Sure, I just have one minor comment that should be a quick fix.

**Comment by sean-jc** [comment]
Modified the code to remove the goto-continue.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tych0** [comment]
jenkins: test this please

was this a fluke?
