### PR TITLE
lxd: save properties on publish

### LINKED ISSUE #2560: lxc doesn't export metadata properties in metadata.yaml
# Required information

 * Distribution: Ubuntu
 * Distribution version: Xenial 
 * The output of "lxc info" 
  architectures:
  - x86_64
  - i686
  - driver: lxc
  - driverversion: 2.0.5
  - kernel: Linux
  - kernelarchitecture: x86_64
  - kernelversion: 4.4.0-45-generic
  - server: lxd
  - serverpid: 2433
  - serverversion: 2.0.5
  - storage: dir
  - storageversion: ""

# Issue description

lxc doesn't export properties in metadata.yaml . 

# Steps to reproduce

 1. Publish an image with properties 

`lxc publish test --alias=myImage description=test age=32`

 2. Check if age and description properties are define . ( It works)
```
lxc image info myImage
Size: 125.08MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 0001/01/01 00:00 UTC
    Uploaded: 2016/10/25 21:32 UTC
    Expires: 0001/01/01 00:00 UTC
Properties:
    age: 32
    description: test
Aliases:
    - myImage
Auto update: disabled
```

 3. Export image and check the content of metadata 

```
 lxc image export myImage image
tar -zxvf image.tar.gz 
cat metadata.yaml 
{
    "architecture": "x86_64",
    "creation_date": 1477367340,
    "properties": {
        "architecture": "x86_64",
        "description": "ubuntu xenial x86_64 (default) (20161025_03:49)",
        "name": "ubuntu-xenial-x86_64-default-20161025_03:49",
        "os": "ubuntu",
        "release": "xenial",
        "variant": "default"
    },
```

Properties are gone ! 
It seems it use the metadata from the original image I used to make my own image.

### PR DESCRIPTION
**Pull request by brauner**
Closes #2560.

### CODE REVIEW

**Comment by brauner** [comment]
So I didn't really see a nice non-intrusive way of doing this. But I suspect @stgraber will. :)
My current approach is:

    lxc publish c --alias=test description=test age=32

leads to the following calls

    - client.go:ImageFromContainer()
    - lxd/images.go:imagesPost()
    - lxd/images.go:imgPostContInfo()

`imgPostContInfo()` in turn will call `Export()` and `Export()` takes care of actually publishing the image. After `Export()` returns it will have created the img tarfile. If we want to change the properties after that we would have to recreate the tar archive just to update the `metadata.yaml` file which is wildly
inefficient. And I'm not aware of an easy way to replace existing files in a tar archive. My proposal is thus to have a new function `SetExportProperties()` that allows users to specify properties that an image created from a container is supposed to receive. In `lxd/images.go:imgPostContInfo()` we can then do:

	// Set properties the user wants the exported image to have.
	if len(req.Properties) != 0 {
		c.SetExportProperties(req.Properties)
	}

prior to

	if err := c.Export(tarfile); err != nil {
		tarfile.Close()
		return info, err
	}
	tarfile.Close()

which means that the published image will have the requested properties at the time of the publish operation. So when you export the image you will receive an updated `metadata.yaml` file containing the properties requested. As @stgraber pointed out, this will still not affect any properties set post-publish.

**Comment by stgraber** [comment]
@brauner why not just change Export() to add a properties argument?

Export() is only called from one place and that's lxd/images.go, so it seems like the easiest way of dealing with all this would be to just pass the value directly to Export() and let it deal with it directly.

**Comment by brauner** [comment]
@stgraber, I thought that might be an API change and so I didn't do that...

**Comment by stgraber** [comment]
@brauner nah, that's internal API we can change that as needed.

**Comment by brauner** [comment]
Updated. Ha, I always thought that the functions associated with the containers struct are supposed to not be changed. :)

**Comment by stgraber** [comment]
Nope, the only reason why we have that interface in place is so that in theory we could add support for alternative container backend or other OS but that's not been done so far.

**Comment by stgraber** [comment]
So for consistency with other bits in our API (like profiles), I think we want to distinguish between:
 - Properties isn't set (shows up as nil)
 - Properties is set to empty (shows up as an empty map)

The former should have the image keep whatever properties are listed in metadata.yaml.
The latter should get you an empty list of properties in metadata.yaml.

Therefore the client tool shouldn't set the Properties key unless it has been passed some properties.
Passing an empty set of properties will be restricted to people using the API directly for now.

**Comment by brauner** [comment]
The patch actually only sets the properties field when the client didn't pass an empty map. The `len(map) != 0` checks take care of that. So I only need the client changes I guess.

**Comment by stgraber** [comment]
I don't see how len(map) != 0 can see the different between map being nil and the map not being nil but being empty.

**Comment by brauner** [comment]
Yeah, misunderstood this.

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -3228,6 +3231,44 @@ func (c *containerLXC) Export(w io.Writer) error {
...
+		if properties != nil {
+			// Parse the metadata
+			content, err := ioutil.ReadFile(fnam)
+			if err != nil {
+				tw.Close()
+				return err
+			}
+
+			metadata := new(imageMetadata)
+			err = yaml.Unmarshal(content, &metadata)
```
Comment (stgraber) [inline lxd/container_lxc.go]: Ignoring the error?

File: lxc/publish.go [hunk 2]
```diff
@@ -134,6 +134,10 @@ func (c *publishCmd) run(config *lxd.Config, args []string) error {
 
 	var fp string
 
+	if len(properties) == 0 {
+		properties = nil
+	}
```
Comment (stgraber) [inline lxc/publish.go]: Might be worth a comment to explain it

File: lxd/container_lxc.go [hunk 3]
```diff
@@ -3196,6 +3196,9 @@ func (c *containerLXC) Export(w io.Writer) error {
 		meta := imageMetadata{}
 		meta.Architecture = arch
 		meta.CreationDate = time.Now().UTC().Unix()
+		if properties != nil {
+			meta.Properties = properties
+		}
```
Comment (stgraber) [inline lxd/container_lxc.go]: The if statement isn't actually needed right?

File: lxd/container_lxc.go (hunk 1 above)
Comment (stgraber) [inline lxd/container_lxc.go]: Nope, they're meant to be yaml. The images on images.linuxcontainers.org are json just because the script I use to generate them doesn't use external python dependencies and there is no native yaml support.

Since yaml is a superset of json, this works fine.

**Comment by stgraber** [comment]
Looks good to me, waiting for Jenkins to confirm.
