### PR TITLE
Fix cluster image replication logic

### LINKED ISSUE #8641: Fix cluster image replication logic
As mentioned in https://github.com/lxc/lxd/pull/8640 our current cluster image replication logic isn't exactly ideal.
With that code removed, there are still a few issues to sort out to get the level of reliability we need for this feature:

 - autoSyncImagesTask should run hourly instead of daily
 - autoSyncImages should iterate over all images, not just the locally available ones
 - imageSyncBetweenNodes should be updated to use our image handling API, get a client for the first address in `syncNodeAddresses` and use that as the source of `CopyImage` to copy to the target. This way the leader which runs this scheduled task will be able to replicate images that it doesn't itself locally own
 - autoSyncImages should be run from clusterPutJoin and clusterNodeDelete to ensure we replicate things as we grow/shrink
 - autoSyncImages should also be called from doApi10UpdateTriggers so a change in `cluster.images_minimal_replica` also triggers a new run

With that done, joining a 4th node to a 3 nodes cluster with a cached and a locally published image should cause no replication (cached image should be stored on 1 node, published one on all 3). Increasing the setting to 4 should lead to immediate replication. Reducing that to two and remove/re-add node 3 and 4 should have them join without any image replicated. Removing node 2 should cause the published image to be replicated on either node 3 or 4. The cached image should never be replicated.

### PR DESCRIPTION
**Pull request by monstermunchkin**
Closes #8641

### CODE REVIEW

File: lxd/images.go [hunk 1]
```diff
@@ -3566,7 +3566,7 @@ func autoSyncImagesTask(d *Daemon) (task.Func, task.Schedule) {
 		logger.Infof("Done synchronizing images across the cluster")
 	}
 
-	return f, task.Daily()
+	return f, task.Every(time.Hour)
```
Comment (stgraber) [inline lxd/images.go:3569]: As we already have one of those `.Every(time.Hour)` can you add `Hourly()` as an alias in `task/schedule.go` and use it in both locations?

File: lxd/db/images.go [hunk 2]
```diff
@@ -1091,6 +1091,36 @@ func (c *Cluster) UpdateImageUploadDate(id int, uploadedAt time.Time) error {
 	return err
 }
 
+// GetImages returns all images.
+func (c *Cluster) GetImages() (map[string][]string, error) {
+	images := make(map[string][]string) // key is fingerprint, value is list of projects
+	err := c.Transaction(func(tx *ClusterTx) error {
+		stmt := `
+    SELECT images.fingerprint, projects.name FROM images
+      LEFT JOIN images_nodes ON images.id = images_nodes.image_id
```
Comment (stgraber) [inline lxd/db/images.go:1100]: Why the `images_nodes` join?

Comment (monstermunchkin) [reply lxd/db/images.go:1100]: I copied the wrong line. That should be `LEFT JOIN projects ON images.project_id = projects.id`

File: lxd/images.go (hunk 1 above)
Comment (monstermunchkin) [reply lxd/images.go:3569]: Sure

Comment (monstermunchkin) [reply lxd/images.go:3569]: @stgraber https://github.com/lxc/lxd/pull/8646 as this is unrelated to the cluster fixes.

File: lxd/api_cluster.go [hunk 3]
```diff
@@ -1255,6 +1255,16 @@ func clusterNodeDelete(d *Daemon, r *http.Request) response.Response {
 		force = 0
 	}
 
+	err = autoSyncImages(d.ctx, d)
```
Comment (stgraber) [inline lxd/api_cluster.go:1258]: I think this can be moved down to after:
```
	logger.Debugf("Deleting member %s from cluster (force=%d)", name, force)
```

And we should add another run of `autoSyncImages` just before the end of the function to replicate any image that was lost with that node back to full replication.

File: lxd/images.go [hunk 4]
```diff
@@ -3652,36 +3664,22 @@ func imageSyncBetweenNodes(d *Daemon, project string, fingerprint string) error
...
-		if err != nil {
-			return err
-		}
-		defer rootfsFile.Close()
 
-		createArgs.RootfsFile = rootfsFile
-		createArgs.RootfsName = filepath.Base(imageRootfsPath)
+	args := lxd.ImageCopyArgs{
+		AutoUpdate:  image.AutoUpdate,
+		CopyAliases: true,
```
Comment (stgraber) [inline lxd/images.go:3674]: I doubt we need this as we're only copying the raw image, so don't care too much about aliases.

Comment (stgraber) [reply lxd/images.go:3674]: For that matter, none of this struct should be needed to be passed except for `Mode` and `Type`.
The DB entry creation phase will be skipped on the receiver so no need for that extra stuff.

**Comment by monstermunchkin** [comment]
The error is `Error: Image sync between nodes: Image with same fingerprint already exists`. We need the target (of the sync) to know that we're currently syncing in order for it not to create a database entry (which seems to be the actual issue).

**Comment by stgraber** [comment]
@monstermunchkin we should be able to figure that out through the user agent, no? Cluster internal connections use a different user agent that can be detected (isClusterNotification or something along those lines).

**Comment by monstermunchkin** [comment]
I didn't find a good way of doing it with `isClusterNotification`, but I'll take another look at it.

**Comment by tomponline** [comment]
@stgraber @monstermunchkin there's also https://github.com/lxc/lxd/blob/master/lxd/cluster/request/clienttype.go#L24 which can be useful for differentiating between request types.

**Comment by stgraber** [comment]
I think I've fixed the issues and things seem to be behaving here, let's see how tests do.

**Comment by stgraber** [comment]
Hmm, somehow my fix is breaking the shutdown tests now... will have to figure that one out a bit later.

**Comment by stgraber** [comment]
Got that particular test sorted at least, pushing a small extra change to randomize the source node too.

@tomponline if this looks green, please review and merge, then we can tag 4.13.

**Comment by stgraber** [comment]
@monstermunchkin in the off chance that this doesn't pass jenkins, please fix whatever's still broken so I can merge and release when I start my day :)
