### PR TITLE
lxd/lxd: Validate https address for config key core.https_address

### LINKED ISSUE #8916: Setting a bogus core.https_address prevents lxd from starting
If you accidentally set a bogus core.https_address and reload the snap.lxd.daemon service, lxd won't come back preventing you from easily fixing your mistake. Here's how to reproduce:

```
# lxc config set core.https_address '*'
Error: cannot listen on https socket: listen tcp: lookup *: no such host
# lxc config get core.https_address
*
# systemctl reload snap.lxd.daemon
```

A workaround is to mangle the local.db with:

```
sqlite3 /var/snap/lxd/common/lxd/database/local.db "UPDATE config SET value=':8443' WHERE key='core.https_address'"
```

From IRC chat:
>  stgraber: so yeah, that's definitely a bug... it should try to set it, fail and revert it

# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * lxd version: 4.15 latest/stable (snap)

### PR DESCRIPTION
**Pull request by my5t3ry**
Fixes #8916 

Signed-off-by: Sascha Bast <sash@mischkonsum.org>

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm, I don't think this is correct.

`core.https_address` and `core.debug_address` don't quite take the same configuration as `cluster.https_address`.

`cluster.https_address` only support fixed addresses + port, it doesn't support things like `:8443`, `0.0.0.0:8443`, `[::]:8443` or relying on DNS names (like `localhost`, `localhost:8443`, ...). But both `core.https_address` and `core.debug_address` do support all of those and so can't share the same validator.

**Comment by my5t3ry** [comment]
ok i was not aware of this. i added a own validator for core.https_address and core.debug_address now. it validates if the host is a valid IPV4,IPV6 address or a valid DNS name. But i encountert another problem while testing it. If i use a DNS name which can't be resolved lxd and systemd-resolve crashes and does so on restart until i reverted /var/lib/lxd/database/local.db. 
Is this a problem which can/should be addressed?
thanks : )

**Comment by tomponline** [comment]
> ok sorry, i wasn't aware of this.
> 
> i added a own validator for core.https_address and core.debug_address now. it validates if the host is a valid IPV4,IPV6 address, :8443, 0.0.0.0:8443, [::]:8443, or a resolveable Hostname.
> I encountert a problem If i changed core.https_address or core.https_address to an unresolveable Hostname. It resulted in systemd-resolved doing something with 100% cpu utilization for ca 2 minutes and after it normalized lxd responded with.
> `Error: Put "http://unix.socket/1.0": EOF`
> Killing and restarting lxd resulted in the same systemd-resolved behavior and lxd got stuck while initializing. I wasn't able to get lxd initialized until i rolled back the config changes @/var/lib/lxd/database/local.db.
> 
> Calling net.Listner("tcp", address) with a unresolveable Hostname will never finish.
> 
> To prevent this case I added a check if the Hostname can be resolved to the validators.
> 
> : )

That sounds like a bug, can you give an example of a value passed to `net.Listener("tcp", address)` that would cause the crash/unresponsive behaviour?

**Comment by my5t3ry** [comment]
sure,

net.Listener("tcp", "llocalhost:8443")
net.Listener("tcp", "kkernel.org:80")

**Comment by my5t3ry** [comment]
i was wrong with guessing it never finishes it just takes a long time. i guess till some timeout occurs. and because it is repeated 10 times in cluster.go:ClusterUpdateAddress() or endpoints.go:NetworkUpdateAddress() it seemd only that it never finishes.

examples are:
net.Listen("tcp", "llocalhost:8443")
net.Listen("tcp", "kkernel.org:8443")

File: lxd/node/config.go [hunk 1]
```diff
@@ -169,16 +169,56 @@ var ConfigSchema = config.Schema{
...
 
+func validateCoreHTTPSAddress(value string) error {
+	if value == "" {
+		return nil // Deleting entry
+	}
+
+	host, _, err := net.SplitHostPort(value)
+	if err != nil {
+		return errors.Wrap(err, "Address not in form of <HOST>:<PORT>")
+	}
```
Comment (stgraber) [inline lxd/node/config.go:180]: I thought we currently supported just `::` or any other address and it would then default to the usual port number (8443 or 8444 in this case).

File: lxd/node/config.go [hunk 2]
```diff
@@ -169,16 +169,56 @@ var ConfigSchema = config.Schema{
...
+
+	if shared.StringInSlice(host, []string{"::", "0.0.0.0"}) {
+		return nil
+	}
```
Comment (stgraber) [inline lxd/node/config.go:184]: Those should be valid addresses and so pass ParseIP, no?

Comment (my5t3ry) [reply lxd/node/config.go]: yes, you are right. i changed this.

**Comment by tomponline** [comment]
jenkins: test this please

File: lxd/node/config.go [hunk 3]
```diff
@@ -169,16 +168,53 @@ var ConfigSchema = config.Schema{
...
+	if ip != nil {
+		return nil
+	}
+
+	_, err = net.LookupHost(host)
+	if err == nil {
+		return nil
+	}
+
+	return fmt.Errorf("Only IPV4, IPV6 address, :<HOST>:<PORT>, or a valid and resolvable Hostname are valid")
```
Comment (tomponline) [inline lxd/node/config.go:192]: Is that first colon in the error message a mistake, isn't it the same form as in `validateClusterHTTPSAddress`, i.e `<HOST>:<PORT>` not `:<HOST>:<PORT>`?

File: lxd/node/config.go [hunk 4]
```diff
@@ -169,16 +168,53 @@ var ConfigSchema = config.Schema{
...
+	if ip != nil {
+		return nil
+	}
+
+	_, err = net.LookupHost(host)
+	if err == nil {
+		return nil
+	}
+
+	return fmt.Errorf("Only valid IPV4, IPV6 aaddresses or resolvable hostnames are valid")
```
Comment (tomponline) [inline lxd/node/config.go:219]: Why is this error different from the one in validateCoreHTTPSAddress, even though in this function higher up it has an error that says `errors.Wrap(err, "Address not in form of <HOST>:<PORT>")`? Seems inconsistent in messaging. Do we only accept an IP (and no port here)? If so, then the error above needs changing.

File: lxd/node/config.go (hunk 3 above)
Comment (stgraber) [reply lxd/node/config.go:192]: I guess it's either a typo or a mix of things. It's getting hard to cover everything that's supported in the error message though. What's supported is:
 - Wildcard addresses without a port (`0.0.0.0`, `::`, `[::]`)
 - Wildcard addresses with a port (`0.0.0.0:8443`, `[::]:8443`)
 - IPv4/IPv6 address without a port (`1.2.3.4`, `1234:4567`, `[1234::4567]`)
 - IPv4/IPv6 address with a port (`1.2.3.4:8443`, `[1234::4567]:8443`)
 - DNS record without a port (`blah`)
 - DNS record with a port (`blah:8443`)
 - Port only (`:8443`)

Comment (stgraber) [reply lxd/node/config.go:192]: So we probably ought to check the validator against all of those ^ but the error itself should probably just be `Bad or unavailable listen address: %s'

Comment (tomponline) [reply lxd/node/config.go:192]: Yeah makes sense, the inconsistency just stood out as a warning sign to me :)

**Comment by stgraber** [comment]
I've done some tweaks here, moving the logic into a single validator in `shared/validate` and porting the code over to that.
I also validated its behavior against the entire set of values provided above and it looks correct.

**Comment by stgraber** [comment]
jenkins: test this please
