### PR TITLE
lxc/export: Rename backup file based on compression type

### LINKED ISSUE #11543: export --compression none generates TAR but the filename is tar.gz
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: `5.15.0-67-generic #74-Ubuntu`
   * LXD version: 5.12-c63881f
   * Storage backend in use: zfs/ceph

# Issue description

This is a very cosmetic issue. `lxc export test-c-1 --compression none` generates a backup in TAR format but the actual filename is backup.tar.gz.

Of course, the file name can be specified explicitly as `lxc export test-c-1 --compression none backup.tar`

# Steps to reproduce

 1. `lxc launch ubuntu:jammy test-c-1`
 2. `lxc export test-c-1 --compression none`
 3. `file backup.tar.gz` -> `POSIX tar archive`

### PR DESCRIPTION
**Pull request by ChrisSmith2**
Fixes #11543

With this patch, running `lxc export` without an explicit file name will no longer fallback to the hardcoded file name `backup.tar.gz`. Instead, the backup is named based on the instance name combined with appropriate file extension for the detected compression type for the tarball.

### CODE REVIEW

File: lxc/export.go [hunk 1]
```diff
@@ -9,7 +9,7 @@ import (
 
 	"github.com/spf13/cobra"
 
-	"github.com/lxc/lxd/client"
+	lxd "github.com/lxc/lxd/client"
```
Comment (tomponline) [inline lxc/export.go:12]: Please dont change this.

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
LGTM! 

But please can you sign off all of your commits.

**Comment by ChrisSmith2** [comment]
@tomponline Just fixed the sign offs on all my commits.
Thanks!

**Comment by tomponline** [comment]
Thanks!
