### PR TITLE
Prevent concurent snapshot and snapshot expiry for a volume

### LINKED ISSUE #9558: Prevent concurent snapshot and snapshot expiry for a volume
# Required information

 * Distribution: ubuntu
 * Distribution version: ubuntu 20.04 server (fully updated)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-90-generic
   * LXC version: 4.20
   * LXD version: 4.20 (installed via snap)
   * Storage backend in use: btrfs

I am sorry, I cannot run "lxc info" because lxd is currently disabled (because of the problem being reported).
However, I can provide lxc info for another machine on the cluster, which should have the same configuration.

# Issue description

lxc creates new task "Cleaning up expired instance snapshots" every minute idefinitely until a limit of 10000 threads is reached, after which it is killed by the kernel.

Looks like the tasks for deleting snapshots get stuck in the kernel, so no task gets completed.

# Steps to reproduce

I think the problem is triggered by a combination of the following factors:

- enabling btrfs quotas
- creating an lxd container with `security.nesting=true`
- installing docker within the container and using it (creating a few docker containers).
- setting automated daily snapshots for the lxd container (using `snapshot.schedule: 0 3 * * *`)

Whenever docker creates containers, new btrfs subvolume are being created, which are then duplicated by lxd during daily snapshots (even if all docker containers are stopped). This way the number of btrfs subvolumes grows very quickly. On my machine, I ended up with about 46000 subvolumes before the problem took place. 

# Information to attach

 - [X] Any relevant kernel output (`dmesg`)
<details><summary>dmesg</summary>

```
$ dmesg
[    0.000000] microcode: microcode updated early to revision 0x71a, date = 2020-03-24
[    0.000000] Linux version 5.4.0-90-generic (buildd@lgw01-amd64-054) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 (Ubuntu 5.4.0-90.101-generic 5.4.148)
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-5.4.0-90-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro maybe-ubiquity
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai  
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009bfff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000007d2effff] usable
[    0.000000] BIOS-e820: [mem 0x000000007d2f0000-0x000000007d31bfff] reserved
[    0.000000] BIOS-e820: [mem 0x000000007d31c000-0x000000007d35afff] ACPI data
[    0.000000] BIOS-e820: [mem 0x000000007d35b000-0x000000007fffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000e0000000-0x00000000efffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fe000000-0x00000000ffffffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000247fffffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.7 present.
[    0.000000] DMI: Dell Inc. PowerEdge R420/072XWF, BIOS 2.9.0 01/09/2020
[    0.000000] tsc: Fast TSC calibration using PIT
[    0.000000] tsc: Detected 2400.257 MHz processor
[    0.003221] e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
[    0.003223] e820: remove [mem 0x000a0000-0x000fffff] usable
[    0.003226] last_pfn = 0x2480000 max_arch_pfn = 0x400000000
[    0.003232] MTRR default type: uncachable
[    0.003233] MTRR fixed ranges enabled:
[    0.003234]   00000-9FFFF write-back
[    0.003235]   A0000-BFFFF uncachable
[    0.003235]   C0000-CBFFF write-protect
[    0.003236]   CC000-D3FFF write-back
[    0.003237]   D4000-EBFFF uncachable
[    0.003237]   EC000-FFFFF write-protect
[    0.003238] MTRR variable ranges enabled:
[    0.003239]   0 base 000000000000 mask 3FFF80000000 write-back
[    0.003240]   1 base 000100000000 mask 3FFF00000000 write-back
[    0.003241]   2 base 000200000000 mask 3FFE00000000 write-back
[    0.003242]   3 base 000400000000 mask 3FFC00000000 write-back
[    0.003242]   4 base 000800000000 mask 3FF800000000 write-back
[    0.003243]   5 base 001000000000 mask 3FF000000000 write-back
[    0.003244]   6 base 002000000000 mask 3FFC00000000 write-back
[    0.003245]   7 base 002400000000 mask 3FFF80000000 write-back
[    0.003245]   8 disabled
[    0.003246]   9 disabled
[    0.003694] x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT  
[    0.004289] e820: update [mem 0x80000000-0xffffffff] usable ==> reserved
[    0.004295] last_pfn = 0x7d2f0 max_arch_pfn = 0x400000000
[    0.014057] found SMP MP-table at [mem 0x000fe710-0x000fe71f]
[    0.024815] check: Scanning 1 areas for low memory corruption
[    0.024820] Using GB pages for direct mapping
[    0.024959] RAMDISK: [mem 0x2def3000-0x32f70fff]
[    0.024966] ACPI: Early table checksum verification disabled
[    0.024972] ACPI: RSDP 0x00000000000F10D0 000024 (v02 DELL  )
[    0.024976] ACPI: XSDT 0x00000000000F1218 0000A4 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.024984] ACPI: FACP 0x000000007D33534C 0000F4 (v03 DELL   PE_SC3   00000001 DELL 00000001)
[    0.024991] ACPI: DSDT 0x000000007D31C000 0072F1 (v01 DELL   PE_SC3   00000001 INTL 20110211)
[    0.024994] ACPI: FACS 0x000000007D337000 000040
[    0.024997] ACPI: FACS 0x000000007D337000 000040
[    0.025000] ACPI: APIC 0x000000007D334478 0001EA (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025003] ACPI: SPCR 0x000000007D334664 000050 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025006] ACPI: HPET 0x000000007D3346B8 000038 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025009] ACPI: DMAR 0x000000007D3346F4 000110 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025012] ACPI: MCFG 0x000000007D334A10 00003C (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025015] ACPI: WD__ 0x000000007D334A50 000134 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025019] ACPI: SLIC 0x000000007D334B88 000024 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025022] ACPI: ERST 0x000000007D3234B4 000270 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025025] ACPI: HEST 0x000000007D323724 00055C (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025028] ACPI: BERT 0x000000007D3232F4 000030 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025031] ACPI: EINJ 0x000000007D323324 000190 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025035] ACPI: TCPA 0x000000007D3352E4 000064 (v02 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025038] ACPI: PC__ 0x000000007D335274 00006E (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025041] ACPI: SRAT 0x000000007D334DB0 0004C0 (v01 DELL   PE_SC3   00000001 DELL 00000001)
[    0.025044] ACPI: SSDT 0x000000007D338000 006D84 (v01 INTEL  PPM RCM  80000001 INTL 20061109)
[    0.025047] ACPI: Reserving FACP table memory at [mem 0x7d33534c-0x7d33543f]
[    0.025048] ACPI: Reserving DSDT table memory at [mem 0x7d31c000-0x7d3232f0]
[    0.025049] ACPI: Reserving FACS table memory at [mem 0x7d337000-0x7d33703f]
[    0.025050] ACPI: Reserving FACS table memory at [mem 0x7d337000-0x7d33703f]
[    0.025051] ACPI: Reserving APIC table memory at [mem 0x7d334478-0x7d334661]
[    0.025052] ACPI: Reserving SPCR table memory at [mem 0x7d334664-0x7d3346b3]
[    0.025053] ACPI: Reserving HPET table memory at [mem 0x7d3346b8-0x7d3346ef]
[    0.025054] ACPI: Reserving DMAR table memory at [mem 0x7d3346f4-0x7d334803]
[    0.025055] ACPI: Reserving MCFG table memory at [mem 0x7d334a10-0x7d334a4b]
[    0.025056] ACPI: Reserving WD__ table memory at [mem 0x7d334a50-0x7d334b83]
[    0.025057] ACPI: Reserving SLIC table memory at [mem 0x7d334b88-0x7d334bab]
[    0.025058] ACPI: Reserving ERST table memory at [mem 0x7d3234b4-0x7d323723]
[    0.025059] ACPI: Reserving HEST table memory at [mem 0x7d323724-0x7d323c7f]
[    0.025060] ACPI: Reserving BERT table memory at [mem 0x7d3232f4-0x7d323323]
[    0.025061] ACPI: Reserving EINJ table memory at [mem 0x7d323324-0x7d3234b3]
[    0.025062] ACPI: Reserving TCPA table memory at [mem 0x7d3352e4-0x7d335347]
[    0.025063] ACPI: Reserving PC__ table memory at [mem 0x7d335274-0x7d3352e1]
[    0.025064] ACPI: Reserving SRAT table memory at [mem 0x7d334db0-0x7d33526f]
[    0.025065] ACPI: Reserving SSDT table memory at [mem 0x7d338000-0x7d33ed83]
[    0.025077] ACPI: Local APIC address 0xfee00000
[    0.025112] SRAT: PXM 1 -> APIC 0x00 -> Node 0
[    0.025113] SRAT: PXM 2 -> APIC 0x20 -> Node 1
[    0.025114] SRAT: PXM 1 -> APIC 0x02 -> Node 0
[    0.025115] SRAT: PXM 2 -> APIC 0x22 -> Node 1
[    0.025116] SRAT: PXM 1 -> APIC 0x04 -> Node 0
[    0.025117] SRAT: PXM 2 -> APIC 0x24 -> Node 1
[    0.025117] SRAT: PXM 1 -> APIC 0x06 -> Node 0
[    0.025118] SRAT: PXM 2 -> APIC 0x26 -> Node 1
[    0.025119] SRAT: PXM 1 -> APIC 0x08 -> Node 0
[    0.025120] SRAT: PXM 2 -> APIC 0x28 -> Node 1
[    0.025121] SRAT: PXM 1 -> APIC 0x0a -> Node 0
[    0.025121] SRAT: PXM 2 -> APIC 0x2a -> Node 1
[    0.025122] SRAT: PXM 1 -> APIC 0x01 -> Node 0
[    0.025123] SRAT: PXM 2 -> APIC 0x21 -> Node 1
[    0.025124] SRAT: PXM 1 -> APIC 0x03 -> Node 0
[    0.025125] SRAT: PXM 2 -> APIC 0x23 -> Node 1
[    0.025125] SRAT: PXM 1 -> APIC 0x05 -> Node 0
[    0.025126] SRAT: PXM 2 -> APIC 0x25 -> Node 1
[    0.025127] SRAT: PXM 1 -> APIC 0x07 -> Node 0
[    0.025128] SRAT: PXM 2 -> APIC 0x27 -> Node 1
[    0.025129] SRAT: PXM 1 -> APIC 0x09 -> Node 0
[    0.025129] SRAT: PXM 2 -> APIC 0x29 -> Node 1
[    0.025130] SRAT: PXM 1 -> APIC 0x0b -> Node 0
[    0.025131] SRAT: PXM 2 -> APIC 0x2b -> Node 1
[    0.025136] ACPI: SRAT: Node 0 PXM 1 [mem 0x00000000-0x127fffffff]
[    0.025137] ACPI: SRAT: Node 1 PXM 2 [mem 0x1280000000-0x247fffffff]
[    0.025150] NODE_DATA(0) allocated [mem 0x127ffd5000-0x127fffffff]
[    0.025175] NODE_DATA(1) allocated [mem 0x247ffd5000-0x247fffffff]
[    0.025505] Zone ranges:
[    0.025507]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.025508]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
[    0.025509]   Normal   [mem 0x0000000100000000-0x000000247fffffff]
[    0.025511]   Device   empty
[    0.025512] Movable zone start for each node
[    0.025515] Early memory node ranges
[    0.025516]   node   0: [mem 0x0000000000001000-0x000000000009bfff]
[    0.025518]   node   0: [mem 0x0000000000100000-0x000000007d2effff]
[    0.025519]   node   0: [mem 0x0000000100000000-0x000000127fffffff]
[    0.025525]   node   1: [mem 0x0000001280000000-0x000000247fffffff]
[    0.025692] Zeroed struct page in unavailable ranges: 11637 pages
[    0.025693] Initmem setup node 0 [mem 0x0000000000001000-0x000000127fffffff]
[    0.025695] On node 0 totalpages: 18862731
[    0.025696]   DMA zone: 64 pages used for memmap
[    0.025697]   DMA zone: 21 pages reserved
[    0.025698]   DMA zone: 3995 pages, LIFO batch:0
[    0.025783]   DMA32 zone: 7948 pages used for memmap
[    0.025784]   DMA32 zone: 508656 pages, LIFO batch:63
[    0.035879]   Normal zone: 286720 pages used for memmap
[    0.035881]   Normal zone: 18350080 pages, LIFO batch:63
[    0.303458] Initmem setup node 1 [mem 0x0000001280000000-0x000000247fffffff]
[    0.303462] On node 1 totalpages: 18874368
[    0.303464]   Normal zone: 294912 pages used for memmap
[    0.303465]   Normal zone: 18874368 pages, LIFO batch:63
[    0.617168] ACPI: PM-Timer IO Port: 0x808
[    0.617176] ACPI: Local APIC address 0xfee00000
[    0.617189] ACPI: LAPIC_NMI (acpi_id[0xff] high edge lint[0x1])
[    0.617203] IOAPIC[0]: apic_id 0, version 32, address 0xfec00000, GSI 0-23
[    0.617207] IOAPIC[1]: apic_id 1, version 32, address 0xfec3f000, GSI 32-55
[    0.617211] IOAPIC[2]: apic_id 2, version 32, address 0xfec7f000, GSI 64-87
[    0.617214] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.617217] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.617219] ACPI: IRQ0 used by override.
[    0.617220] ACPI: IRQ9 used by override.
[    0.617222] Using ACPI (MADT) for SMP configuration information
[    0.617224] ACPI: HPET id: 0x8086a701 base: 0xfed00000
[    0.617230] ACPI: SPCR: SPCR table version 1
[    0.617230] ACPI: SPCR: Unexpected SPCR Access Width.  Defaulting to byte size
[    0.617232] ACPI: SPCR: console: uart,mmio,0x0
[    0.617235] TSC deadline timer available
[    0.617238] smpboot: Allowing 48 CPUs, 24 hotplug CPUs
[    0.617254] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
[    0.617256] PM: Registered nosave memory: [mem 0x0009c000-0x000fffff]
[    0.617258] PM: Registered nosave memory: [mem 0x7d2f0000-0x7d31bfff]
[    0.617259] PM: Registered nosave memory: [mem 0x7d31c000-0x7d35afff]
[    0.617260] PM: Registered nosave memory: [mem 0x7d35b000-0x7fffffff]
[    0.617261] PM: Registered nosave memory: [mem 0x80000000-0xdfffffff]
[    0.617262] PM: Registered nosave memory: [mem 0xe0000000-0xefffffff]
[    0.617262] PM: Registered nosave memory: [mem 0xf0000000-0xfdffffff]
[    0.617263] PM: Registered nosave memory: [mem 0xfe000000-0xffffffff]
[    0.617266] [mem 0x80000000-0xdfffffff] available for PCI devices
[    0.617268] Booting paravirtualized kernel on bare hardware
[    0.617272] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
[    0.617279] setup_percpu: NR_CPUS:8192 nr_cpumask_bits:48 nr_cpu_ids:48 nr_node_ids:2
[    0.619648] percpu: Embedded 55 pages/cpu s188416 r8192 d28672 u262144
[    0.619657] pcpu-alloc: s188416 r8192 d28672 u262144 alloc=1*2097152
[    0.619658] pcpu-alloc: [0] 00 02 04 06 08 10 12 14 [0] 16 18 20 22 24 26 28 30 
[    0.619663] pcpu-alloc: [0] 32 34 36 38 40 42 44 46 [1] 01 03 05 07 09 11 13 15 
[    0.619666] pcpu-alloc: [1] 17 19 21 23 25 27 29 31 [1] 33 35 37 39 41 43 45 47 
[    0.619706] Built 2 zonelists, mobility grouping on.  Total pages: 37147434
[    0.619707] Policy zone: Normal
[    0.619710] Kernel command line: BOOT_IMAGE=/vmlinuz-5.4.0-90-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro maybe-ubiquity
[    0.619783] printk: log_buf_len individual max cpu contribution: 4096 bytes
[    0.619784] printk: log_buf_len total cpu_extra contributions: 192512 bytes
[    0.619785] printk: log_buf_len min size: 262144 bytes
[    0.619910] printk: log_buf_len: 524288 bytes
[    0.619912] printk: early log buf free: 248880(94%)
[    0.620439] mem auto-init: stack:off, heap alloc:on, heap free:off
[    0.629778] Calgary: detecting Calgary via BIOS EBDA area
[    0.629780] Calgary: Unable to locate Rio Grande table in EBDA - bailing!
[    1.066158] Memory: 148396296K/150948396K available (14339K kernel code, 2400K rwdata, 5020K rodata, 2736K init, 4964K bss, 2552100K reserved, 0K cma-reserved)
[    1.066170] random: get_random_u64 called from kmem_cache_open+0x2d/0x410 with crng_init=0
[    1.066587] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=48, Nodes=2
[    1.066614] Kernel/User page tables isolation: enabled
[    1.066651] ftrace: allocating 44628 entries in 175 pages
[    1.085687] rcu: Hierarchical RCU implementation.
[    1.085689] rcu: 	RCU restricting CPUs from NR_CPUS=8192 to nr_cpu_ids=48.
[    1.085691] 	Tasks RCU enabled.
[    1.085692] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    1.085693] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=48
[    1.088652] NR_IRQS: 524544, nr_irqs: 1896, preallocated irqs: 16
[    1.088985] Console: colour dummy device 80x25
[    1.089213] printk: console [tty0] enabled
[    1.089278] mempolicy: Enabling automatic NUMA balancing. Configure with numa_balancing= or the kernel.numa_balancing sysctl
[    1.089283] ACPI: Core revision 20190816
[    1.089415] clocksource: hpet: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 133484882848 ns
[    1.089429] APIC: Switch to symmetric I/O mode setup
[    1.089433] DMAR: Host address width 46
[    1.089435] DMAR: DRHD base: 0x000000d3000000 flags: 0x0
[    1.089441] DMAR: dmar0: reg_base_addr d3000000 ver 1:0 cap d2078c106f0462 ecap f020fe
[    1.089444] DMAR: DRHD base: 0x000000df100000 flags: 0x1
[    1.089449] DMAR: dmar1: reg_base_addr df100000 ver 1:0 cap d2078c106f0462 ecap f020fe
[    1.089452] DMAR: RMRR base: 0x0000007f458000 end: 0x0000007f46ffff
[    1.089454] DMAR: RMRR base: 0x0000007f450000 end: 0x0000007f450fff
[    1.089456] DMAR: RMRR base: 0x0000007f452000 end: 0x0000007f452fff
[    1.089458] DMAR: ATSR flags: 0x0
[    1.089461] DMAR-IR: IOAPIC id 2 under DRHD base  0xd3000000 IOMMU 0
[    1.089463] DMAR-IR: IOAPIC id 0 under DRHD base  0xdf100000 IOMMU 1
[    1.089465] DMAR-IR: IOAPIC id 1 under DRHD base  0xdf100000 IOMMU 1
[    1.089467] DMAR-IR: HPET id 0 under DRHD base 0xdf100000
[    1.089469] DMAR-IR: x2apic is disabled because BIOS sets x2apic opt out bit.
[    1.089470] DMAR-IR: Use 'intremap=no_x2apic_optout' to override the BIOS setting.
[    1.090013] DMAR-IR: Enabled IRQ remapping in xapic mode
[    1.090016] x2apic: IRQ remapping doesn't support X2APIC mode
[    1.090021] Switched APIC routing to physical flat.
[    1.090642] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    1.109433] clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x22992a4c99e, max_idle_ns: 440795250641 ns
[    1.109439] Calibrating delay loop (skipped), value calculated using timer frequency.. 4800.51 BogoMIPS (lpj=9601028)
[    1.109443] pid_max: default: 49152 minimum: 384
[    1.109538] LSM: Security Framework initializing
[    1.109555] Yama: becoming mindful.
[    1.109760] AppArmor: AppArmor initialized
[    1.130706] Dentry cache hash table entries: 16777216 (order: 15, 134217728 bytes, vmalloc)
[    1.141273] Inode-cache hash table entries: 8388608 (order: 14, 67108864 bytes, vmalloc)
[    1.141681] Mount-cache hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
[    1.142021] Mountpoint-cache hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
[    1.142064] *** VALIDATE tmpfs ***
[    1.142313] *** VALIDATE proc ***
[    1.142450] *** VALIDATE cgroup1 ***
[    1.142453] *** VALIDATE cgroup2 ***
[    1.142546] mce: CPU0: Thermal monitoring enabled (TM1)
[    1.142579] process: using mwait in idle threads
[    1.142583] Last level iTLB entries: 4KB 512, 2MB 8, 4MB 8
[    1.142585] Last level dTLB entries: 4KB 512, 2MB 32, 4MB 32, 1GB 0
[    1.142592] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization
[    1.142595] Spectre V2 : Mitigation: Full generic retpoline
[    1.142597] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[    1.142600] Spectre V2 : Enabling Restricted Speculation for firmware calls
[    1.142603] Spectre V2 : mitigation: Enabling conditional Indirect Branch Prediction Barrier
[    1.142605] Spectre V2 : User space: Mitigation: STIBP via seccomp and prctl
[    1.142608] Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl and seccomp
[    1.142614] MDS: Mitigation: Clear CPU buffers
[    1.142815] Freeing SMP alternatives memory: 40K
[    1.145614] smpboot: CPU0: Intel(R) Xeon(R) CPU E5-2440 0 @ 2.40GHz (family: 0x6, model: 0x2d, stepping: 0x7)
[    1.145808] Performance Events: PEBS fmt1+, SandyBridge events, 16-deep LBR, full-width counters, Intel PMU driver.
[    1.145821] ... version:                3
[    1.145822] ... bit width:              48
[    1.145824] ... generic registers:      4
[    1.145826] ... value mask:             0000ffffffffffff
[    1.145828] ... max period:             00007fffffffffff
[    1.145830] ... fixed-purpose events:   3
[    1.145831] ... event mask:             000000070000000f
[    1.145903] rcu: Hierarchical SRCU implementation.
[    1.149437] NMI watchdog: Enabled. Permanently consumes one hw-PMU counter.
[    1.150122] smp: Bringing up secondary CPUs ...
[    1.150288] x86: Booting SMP configuration:
[    1.150291] .... node  #1, CPUs:        #1
[    0.004550] smpboot: CPU 1 Converting physical 0 to logical die 1
[    1.233598] .... node  #0, CPUs:    #2
[    1.237686] .... node  #1, CPUs:    #3
[    1.241627] .... node  #0, CPUs:    #4
[    1.245683] .... node  #1, CPUs:    #5
[    1.249580] .... node  #0, CPUs:    #6
[    1.253650] .... node  #1, CPUs:    #7
[    1.257611] .... node  #0, CPUs:    #8
[    1.261683] .... node  #1, CPUs:    #9
[    1.265539] .... node  #0, CPUs:   #10
[    1.269604] .... node  #1, CPUs:   #11
[    1.273439] .... node  #0, CPUs:   #12
[    1.276347] MDS CPU bug present and SMT on, data leak possible. See https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html for more details.
[    1.276347] .... node  #1, CPUs:   #13
[    1.277615] .... node  #0, CPUs:   #14
[    1.280360] .... node  #1, CPUs:   #15
[    1.283482] .... node  #0, CPUs:   #16
[    1.285687] .... node  #1, CPUs:   #17
[    1.288355] .... node  #0, CPUs:   #18
[    1.291541] .... node  #1, CPUs:   #19
[    1.293617] .... node  #0, CPUs:   #20
[    1.296346] .... node  #1, CPUs:   #21
[    1.297609] .... node  #0, CPUs:   #22
[    1.300332] .... node  #1, CPUs:   #23
[    1.303491] smp: Brought up 2 nodes, 24 CPUs
[    1.303491] smpboot: Max logical packages: 4
[    1.303491] smpboot: Total of 24 processors activated (115229.62 BogoMIPS)
[    1.312447] devtmpfs: initialized
[    1.312447] x86/mm: Memory block size: 2048MB
[    1.313538] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    1.313699] futex hash table entries: 16384 (order: 8, 1048576 bytes, vmalloc)
[    1.313943] pinctrl core: initialized pinctrl subsystem
[    1.314090] PM: RTC time: 15:03:34, date: 2021-11-18
[    1.314312] NET: Registered protocol family 16
[    1.314423] audit: initializing netlink subsys (disabled)
[    1.314433] audit: type=2000 audit(1637247813.224:1): state=initialized audit_enabled=0 res=1
[    1.314433] EISA bus registered
[    1.314433] cpuidle: using governor ladder
[    1.314433] cpuidle: using governor menu
[    1.314433] ACPI FADT declares the system doesn't support PCIe ASPM, so disable it
[    1.314433] ACPI: bus type PCI registered
[    1.314433] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    1.314433] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xe0000000-0xefffffff] (base 0xe0000000)
[    1.314433] PCI: MMCONFIG at [mem 0xe0000000-0xefffffff] reserved in E820
[    1.314433] PCI: Using configuration type 1 for base access
[    1.314433] PCI: Dell System detected, enabling pci=bfsort.
[    1.314433] core: PMU erratum BJ122, BV98, HSD29 worked around, HT is on
[    1.314471] mtrr: your CPUs had inconsistent variable MTRR settings
[    1.314473] mtrr: probably your BIOS does not setup all CPUs.
[    1.314475] mtrr: corrected configuration.
[    1.317496] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    1.317496] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    1.317565] fbcon: Taking over console
[    1.317638] ACPI: Added _OSI(Module Device)
[    1.317640] ACPI: Added _OSI(Processor Device)
[    1.317642] ACPI: Added _OSI(3.0 _SCP Extensions)
[    1.317644] ACPI: Added _OSI(Processor Aggregator Device)
[    1.317647] ACPI: Added _OSI(Linux-Dell-Video)
[    1.317649] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[    1.317651] ACPI: Added _OSI(Linux-HPI-Hybrid-Graphics)
[    1.320674] ACPI: 2 ACPI AML tables successfully acquired and loaded
[    1.321133] ACPI: [Firmware Bug]: BIOS _OSI(Linux) query ignored
[    1.331027] ACPI: Interpreter enabled
[    1.331046] ACPI: (supports S0 S4 S5)
[    1.331049] ACPI: Using IOAPIC for interrupt routing
[    1.331325] HEST: Table parsing has been initialized.
[    1.331331] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    1.331572] ACPI: Enabled 4 GPEs in block 00 to 3F
[    1.340195] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-3d])
[    1.340205] acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI HPX-Type3]
[    1.340371] acpi PNP0A08:00: PCIe AER handled by firmware
[    1.340697] acpi PNP0A08:00: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME PCIeCapability LTR]
[    1.340701] acpi PNP0A08:00: FADT indicates ASPM is unsupported, using BIOS configuration
[    1.341868] PCI host bridge to bus 0000:00
[    1.341873] pci_bus 0000:00: root bus resource [io  0x0000-0x03af window]
[    1.341876] pci_bus 0000:00: root bus resource [io  0x03e0-0x0cf7 window]
[    1.341878] pci_bus 0000:00: root bus resource [io  0x03b0-0x03df window]
[    1.341881] pci_bus 0000:00: root bus resource [io  0x0d00-0x1fff window]
[    1.341883] pci_bus 0000:00: root bus resource [io  0xe000-0xffff window]
[    1.341886] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff window]
[    1.341889] pci_bus 0000:00: root bus resource [mem 0xd8000000-0xdfffffff window]
[    1.341892] pci_bus 0000:00: root bus resource [mem 0xfed40000-0xfed44fff window]
[    1.341896] pci_bus 0000:00: root bus resource [bus 00-3d]
[    1.341948] pci 0000:00:00.0: [8086:3c00] type 00 class 0x060000
[    1.342030] pci 0000:00:00.0: PME# supported from D0 D3hot D3cold
[    1.342123] pci 0000:00:01.0: [8086:3c02] type 01 class 0x060400
[    1.342216] pci 0000:00:01.0: PME# supported from D0 D3hot D3cold
[    1.342370] pci 0000:00:03.0: [8086:3c08] type 01 class 0x060400
[    1.342416] pci 0000:00:03.0: enabling Extended Tags
[    1.342469] pci 0000:00:03.0: PME# supported from D0 D3hot D3cold
[    1.342632] pci 0000:00:05.0: [8086:3c28] type 00 class 0x088000
[    1.342777] pci 0000:00:05.2: [8086:3c2a] type 00 class 0x088000
[    1.342911] pci 0000:00:11.0: [8086:1d3e] type 01 class 0x060400
[    1.343020] pci 0000:00:11.0: PME# supported from D0 D3hot D3cold
[    1.343114] pci 0000:00:16.0: [8086:1d3a] type 00 class 0x078000
[    1.343136] pci 0000:00:16.0: reg 0x10: [mem 0xdf0fb000-0xdf0fb00f 64bit]
[    1.343199] pci 0000:00:16.0: PME# supported from D0 D3hot D3cold
[    1.343283] pci 0000:00:16.1: [8086:1d3b] type 00 class 0x078000
[    1.343305] pci 0000:00:16.1: reg 0x10: [mem 0xdf0fc000-0xdf0fc00f 64bit]
[    1.343366] pci 0000:00:16.1: PME# supported from D0 D3hot D3cold
[    1.343459] pci 0000:00:1a.0: [8086:1d2d] type 00 class 0x0c0320
[    1.343482] pci 0000:00:1a.0: reg 0x10: [mem 0xdf0fd000-0xdf0fd3ff]
[    1.343564] pci 0000:00:1a.0: PME# supported from D0 D3hot D3cold
[    1.343656] pci 0000:00:1c.0: [8086:1d10] type 01 class 0x060400
[    1.343746] pci 0000:00:1c.0: PME# supported from D0 D3hot D3cold
[    1.343927] pci 0000:00:1c.4: [8086:1d18] type 01 class 0x060400
[    1.344019] pci 0000:00:1c.4: PME# supported from D0 D3hot D3cold
[    1.344124] pci 0000:00:1c.7: [8086:1d1e] type 01 class 0x060400
[    1.344216] pci 0000:00:1c.7: PME# supported from D0 D3hot D3cold
[    1.344324] pci 0000:00:1d.0: [8086:1d26] type 00 class 0x0c0320
[    1.344347] pci 0000:00:1d.0: reg 0x10: [mem 0xdf0fe000-0xdf0fe3ff]
[    1.344430] pci 0000:00:1d.0: PME# supported from D0 D3hot D3cold
[    1.344517] pci 0000:00:1e.0: [8086:244e] type 01 class 0x060401
[    1.344634] pci 0000:00:1f.0: [8086:1d41] type 00 class 0x060100
[    1.344816] pci 0000:00:1f.2: [8086:1d02] type 00 class 0x010601
[    1.344835] pci 0000:00:1f.2: reg 0x10: [io  0xece8-0xecef]
[    1.344843] pci 0000:00:1f.2: reg 0x14: [io  0xecf8-0xecfb]
[    1.344851] pci 0000:00:1f.2: reg 0x18: [io  0xecf0-0xecf7]
[    1.344859] pci 0000:00:1f.2: reg 0x1c: [io  0xecfc-0xecff]
[    1.344867] pci 0000:00:1f.2: reg 0x20: [io  0xecc0-0xecdf]
[    1.344875] pci 0000:00:1f.2: reg 0x24: [mem 0xdf0ff000-0xdf0ff7ff]
[    1.344916] pci 0000:00:1f.2: PME# supported from D3hot
[    1.345025] pci 0000:01:00.0: [1000:005b] type 00 class 0x010400
[    1.345040] pci 0000:01:00.0: reg 0x10: [io  0xfc00-0xfcff]
[    1.345049] pci 0000:01:00.0: reg 0x14: [mem 0xdcffc000-0xdcffffff 64bit]
[    1.345058] pci 0000:01:00.0: reg 0x1c: [mem 0xdcf80000-0xdcfbffff 64bit]
[    1.345069] pci 0000:01:00.0: reg 0x30: [mem 0xdc000000-0xdc01ffff pref]
[    1.345076] pci 0000:01:00.0: enabling Extended Tags
[    1.345118] pci 0000:01:00.0: supports D1 D2
[    1.345172] pci 0000:00:01.0: PCI bridge to [bus 01]
[    1.345177] pci 0000:00:01.0:   bridge window [io  0xf000-0xffff]
[    1.345181] pci 0000:00:01.0:   bridge window [mem 0xdc000000-0xdcffffff]
[    1.345221] pci 0000:00:03.0: PCI bridge to [bus 08]
[    1.345270] pci 0000:00:11.0: PCI bridge to [bus 09]
[    1.345318] pci 0000:00:1c.0: PCI bridge to [bus 0a]
[    1.345406] pci 0000:02:00.0: [14e4:165f] type 00 class 0x020000
[    1.345450] pci 0000:02:00.0: reg 0x10: [mem 0xd90a0000-0xd90affff 64bit pref]
[    1.345472] pci 0000:02:00.0: reg 0x18: [mem 0xd90b0000-0xd90bffff 64bit pref]
[    1.345494] pci 0000:02:00.0: reg 0x20: [mem 0xd90c0000-0xd90cffff 64bit pref]
[    1.345509] pci 0000:02:00.0: reg 0x30: [mem 0xdd000000-0xdd03ffff pref]
[    1.345631] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    1.345670] pci 0000:02:00.0: 4.000 Gb/s available PCIe bandwidth, limited by 5 GT/s x1 link at 0000:00:1c.4 (capable of 8.000 Gb/s with 5 GT/s x2 link)
[    1.345775] pci 0000:02:00.1: [14e4:165f] type 00 class 0x020000
[    1.345819] pci 0000:02:00.1: reg 0x10: [mem 0xd90d0000-0xd90dffff 64bit pref]
[    1.345841] pci 0000:02:00.1: reg 0x18: [mem 0xd90e0000-0xd90effff 64bit pref]
[    1.345863] pci 0000:02:00.1: reg 0x20: [mem 0xd90f0000-0xd90fffff 64bit pref]
[    1.345878] pci 0000:02:00.1: reg 0x30: [mem 0xdd000000-0xdd03ffff pref]
[    1.345999] pci 0000:02:00.1: PME# supported from D0 D3hot D3cold
[    1.346161] pci 0000:00:1c.4: PCI bridge to [bus 02]
[    1.346169] pci 0000:00:1c.4:   bridge window [mem 0xdd000000-0xdd7fffff]
[    1.346175] pci 0000:00:1c.4:   bridge window [mem 0xd9000000-0xd90fffff 64bit pref]
[    1.346522] pci 0000:03:00.0: [1912:0013] type 01 class 0x060400
[    1.353845] pci 0000:03:00.0: PME# supported from D0 D3hot D3cold
[    1.354957] pci 0000:00:1c.7: PCI bridge to [bus 03-07]
[    1.354964] pci 0000:00:1c.7:   bridge window [mem 0xdd800000-0xdeffffff]
[    1.354971] pci 0000:00:1c.7:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.356136] pci 0000:04:00.0: [1912:0013] type 01 class 0x060400
[    1.359594] pci 0000:04:00.0: PME# supported from D0 D3hot D3cold
[    1.360775] pci 0000:04:01.0: [1912:0013] type 01 class 0x060400
[    1.364451] pci 0000:04:01.0: PME# supported from D0 D3hot D3cold
[    1.366986] pci 0000:03:00.0: PCI bridge to [bus 04-07]
[    1.367179] pci 0000:03:00.0:   bridge window [mem 0xdd800000-0xdeffffff]
[    1.367303] pci 0000:03:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.368518] pci 0000:05:00.0: [1912:0012] type 01 class 0x060400
[    1.372993] pci 0000:04:00.0: PCI bridge to [bus 05-06]
[    1.373208] pci 0000:04:00.0:   bridge window [mem 0xdd800000-0xde7fffff]
[    1.373353] pci 0000:04:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.374388] pci_bus 0000:06: extended config space not accessible
[    1.374619] pci 0000:06:00.0: [102b:0534] type 00 class 0x030000
[    1.375103] pci 0000:06:00.0: reg 0x10: [mem 0xd8000000-0xd8ffffff pref]
[    1.375363] pci 0000:06:00.0: reg 0x14: [mem 0xde7fc000-0xde7fffff]
[    1.375624] pci 0000:06:00.0: reg 0x18: [mem 0xdd800000-0xddffffff]
[    1.379812] pci 0000:05:00.0: PCI bridge to [bus 06]
[    1.380035] pci 0000:05:00.0:   bridge window [mem 0xdd800000-0xde7fffff]
[    1.380180] pci 0000:05:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.381419] pci 0000:04:01.0: PCI bridge to [bus 07]
[    1.381618] pci 0000:04:01.0:   bridge window [mem 0xdef00000-0xdeffffff]
[    1.382746] pci_bus 0000:0b: extended config space not accessible
[    1.382796] pci 0000:00:1e.0: PCI bridge to [bus 0b] (subtractive decode)
[    1.382807] pci 0000:00:1e.0:   bridge window [io  0x0000-0x03af window] (subtractive decode)
[    1.382810] pci 0000:00:1e.0:   bridge window [io  0x03e0-0x0cf7 window] (subtractive decode)
[    1.382813] pci 0000:00:1e.0:   bridge window [io  0x03b0-0x03df window] (subtractive decode)
[    1.382817] pci 0000:00:1e.0:   bridge window [io  0x0d00-0x1fff window] (subtractive decode)
[    1.382820] pci 0000:00:1e.0:   bridge window [io  0xe000-0xffff window] (subtractive decode)
[    1.382823] pci 0000:00:1e.0:   bridge window [mem 0x000a0000-0x000bffff window] (subtractive decode)
[    1.382826] pci 0000:00:1e.0:   bridge window [mem 0xd8000000-0xdfffffff window] (subtractive decode)
[    1.382830] pci 0000:00:1e.0:   bridge window [mem 0xfed40000-0xfed44fff window] (subtractive decode)
[    1.382870] pci_bus 0000:00: on NUMA node 0
[    1.384650] ACPI: PCI Root Bridge [PCI1] (domain 0000 [bus 40-7e])
[    1.384657] acpi PNP0A08:01: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI HPX-Type3]
[    1.384822] acpi PNP0A08:01: PCIe AER handled by firmware
[    1.385147] acpi PNP0A08:01: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME PCIeCapability LTR]
[    1.385151] acpi PNP0A08:01: FADT indicates ASPM is unsupported, using BIOS configuration
[    1.386234] PCI host bridge to bus 0000:40
[    1.386238] pci_bus 0000:40: root bus resource [io  0x2000-0x3fff window]
[    1.386241] pci_bus 0000:40: root bus resource [io  0x4000-0x5fff window]
[    1.386243] pci_bus 0000:40: root bus resource [io  0x6000-0x7fff window]
[    1.386246] pci_bus 0000:40: root bus resource [io  0x8000-0x9fff window]
[    1.386249] pci_bus 0000:40: root bus resource [io  0xa000-0xbfff window]
[    1.386251] pci_bus 0000:40: root bus resource [io  0xc000-0xdfff window]
[    1.386254] pci_bus 0000:40: root bus resource [mem 0xd0000000-0xd7ffffff window]
[    1.386257] pci_bus 0000:40: root bus resource [bus 40-7e]
[    1.386310] pci 0000:40:03.0: [8086:3c08] type 01 class 0x060400
[    1.386359] pci 0000:40:03.0: enabling Extended Tags
[    1.386417] pci 0000:40:03.0: PME# supported from D0 D3hot D3cold
[    1.386555] pci 0000:40:05.0: [8086:3c28] type 00 class 0x088000
[    1.386684] pci 0000:40:05.2: [8086:3c2a] type 00 class 0x088000
[    1.386837] pci 0000:40:03.0: PCI bridge to [bus 41]
[    1.386854] pci_bus 0000:40: on NUMA node 1
[    1.386924] ACPI: PCI Root Bridge [P0B1] (domain 0000 [bus 3f])
[    1.386930] acpi PNP0A08:02: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI HPX-Type3]
[    1.387094] acpi PNP0A08:02: PCIe AER handled by firmware
[    1.387419] acpi PNP0A08:02: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME PCIeCapability LTR]
[    1.387422] acpi PNP0A08:02: FADT indicates ASPM is unsupported, using BIOS configuration
[    1.387511] PCI host bridge to bus 0000:3f
[    1.387514] pci_bus 0000:3f: root bus resource [bus 3f]
[    1.387525] pci 0000:3f:08.0: [8086:3c80] type 00 class 0x088000
[    1.387595] pci 0000:3f:09.0: [8086:3c90] type 00 class 0x088000
[    1.387653] pci 0000:3f:0a.0: [8086:3cc0] type 00 class 0x088000
[    1.387703] pci 0000:3f:0a.1: [8086:3cc1] type 00 class 0x088000
[    1.387752] pci 0000:3f:0a.2: [8086:3cc2] type 00 class 0x088000
[    1.387802] pci 0000:3f:0a.3: [8086:3cd0] type 00 class 0x088000
[    1.387852] pci 0000:3f:0b.0: [8086:3ce0] type 00 class 0x088000
[    1.387900] pci 0000:3f:0b.3: [8086:3ce3] type 00 class 0x088000
[    1.387968] pci 0000:3f:0c.0: [8086:3ce8] type 00 class 0x088000
[    1.388023] pci 0000:3f:0c.1: [8086:3ce8] type 00 class 0x088000
[    1.388071] pci 0000:3f:0c.2: [8086:3ce8] type 00 class 0x088000
[    1.388121] pci 0000:3f:0c.6: [8086:3cf4] type 00 class 0x088000
[    1.388169] pci 0000:3f:0c.7: [8086:3cf6] type 00 class 0x088000
[    1.388216] pci 0000:3f:0d.0: [8086:3ce8] type 00 class 0x088000
[    1.388264] pci 0000:3f:0d.1: [8086:3ce8] type 00 class 0x088000
[    1.388314] pci 0000:3f:0d.2: [8086:3ce8] type 00 class 0x088000
[    1.388363] pci 0000:3f:0d.6: [8086:3cf5] type 00 class 0x088000
[    1.388419] pci 0000:3f:0e.0: [8086:3ca0] type 00 class 0x088000
[    1.388471] pci 0000:3f:0e.1: [8086:3c46] type 00 class 0x110100
[    1.388527] pci 0000:3f:0f.0: [8086:3ca8] type 00 class 0x088000
[    1.388596] pci 0000:3f:0f.1: [8086:3c71] type 00 class 0x088000
[    1.388661] pci 0000:3f:0f.2: [8086:3caa] type 00 class 0x088000
[    1.388728] pci 0000:3f:0f.3: [8086:3cab] type 00 class 0x088000
[    1.388795] pci 0000:3f:0f.4: [8086:3cac] type 00 class 0x088000
[    1.388861] pci 0000:3f:0f.5: [8086:3cad] type 00 class 0x088000
[    1.388934] pci 0000:3f:0f.6: [8086:3cae] type 00 class 0x088000
[    1.388990] pci 0000:3f:10.0: [8086:3cb0] type 00 class 0x088000
[    1.389057] pci 0000:3f:10.1: [8086:3cb1] type 00 class 0x088000
[    1.389124] pci 0000:3f:10.2: [8086:3cb2] type 00 class 0x088000
[    1.389190] pci 0000:3f:10.3: [8086:3cb3] type 00 class 0x088000
[    1.389256] pci 0000:3f:10.5: [8086:3cb5] type 00 class 0x088000
[    1.389323] pci 0000:3f:10.6: [8086:3cb6] type 00 class 0x088000
[    1.389388] pci 0000:3f:10.7: [8086:3cb7] type 00 class 0x088000
[    1.389463] pci 0000:3f:11.0: [8086:3cb8] type 00 class 0x088000
[    1.389523] pci 0000:3f:13.0: [8086:3ce4] type 00 class 0x088000
[    1.389572] pci 0000:3f:13.1: [8086:3c43] type 00 class 0x110100
[    1.389622] pci 0000:3f:13.4: [8086:3ce6] type 00 class 0x110100
[    1.389670] pci 0000:3f:13.5: [8086:3c44] type 00 class 0x110100
[    1.389720] pci 0000:3f:13.6: [8086:3c45] type 00 class 0x088000
[    1.389782] pci_bus 0000:3f: on NUMA node 0
[    1.389871] ACPI: PCI Root Bridge [P1B1] (domain 0000 [bus 7f])
[    1.389877] acpi PNP0A08:03: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI HPX-Type3]
[    1.390042] acpi PNP0A08:03: PCIe AER handled by firmware
[    1.390368] acpi PNP0A08:03: _OSC: OS now controls [PCIeHotplug SHPCHotplug PME PCIeCapability LTR]
[    1.390372] acpi PNP0A08:03: FADT indicates ASPM is unsupported, using BIOS configuration
[    1.390424] PCI host bridge to bus 0000:7f
[    1.390428] pci_bus 0000:7f: root bus resource [bus 7f]
[    1.390440] pci 0000:7f:08.0: [8086:3c80] type 00 class 0x088000
[    1.390497] pci 0000:7f:09.0: [8086:3c90] type 00 class 0x088000
[    1.390559] pci 0000:7f:0a.0: [8086:3cc0] type 00 class 0x088000
[    1.390606] pci 0000:7f:0a.1: [8086:3cc1] type 00 class 0x088000
[    1.390653] pci 0000:7f:0a.2: [8086:3cc2] type 00 class 0x088000
[    1.390701] pci 0000:7f:0a.3: [8086:3cd0] type 00 class 0x088000
[    1.390749] pci 0000:7f:0b.0: [8086:3ce0] type 00 class 0x088000
[    1.390794] pci 0000:7f:0b.3: [8086:3ce3] type 00 class 0x088000
[    1.390840] pci 0000:7f:0c.0: [8086:3ce8] type 00 class 0x088000
[    1.390889] pci 0000:7f:0c.1: [8086:3ce8] type 00 class 0x088000
[    1.390941] pci 0000:7f:0c.2: [8086:3ce8] type 00 class 0x088000
[    1.390987] pci 0000:7f:0c.6: [8086:3cf4] type 00 class 0x088000
[    1.391032] pci 0000:7f:0c.7: [8086:3cf6] type 00 class 0x088000
[    1.391079] pci 0000:7f:0d.0: [8086:3ce8] type 00 class 0x088000
[    1.391124] pci 0000:7f:0d.1: [8086:3ce8] type 00 class 0x088000
[    1.391169] pci 0000:7f:0d.2: [8086:3ce8] type 00 class 0x088000
[    1.391215] pci 0000:7f:0d.6: [8086:3cf5] type 00 class 0x088000
[    1.391261] pci 0000:7f:0e.0: [8086:3ca0] type 00 class 0x088000
[    1.391318] pci 0000:7f:0e.1: [8086:3c46] type 00 class 0x110100
[    1.391372] pci 0000:7f:0f.0: [8086:3ca8] type 00 class 0x088000
[    1.391437] pci 0000:7f:0f.1: [8086:3c71] type 00 class 0x088000
[    1.391503] pci 0000:7f:0f.2: [8086:3caa] type 00 class 0x088000
[    1.391571] pci 0000:7f:0f.3: [8086:3cab] type 00 class 0x088000
[    1.391636] pci 0000:7f:0f.4: [8086:3cac] type 00 class 0x088000
[    1.391701] pci 0000:7f:0f.5: [8086:3cad] type 00 class 0x088000
[    1.391765] pci 0000:7f:0f.6: [8086:3cae] type 00 class 0x088000
[    1.391824] pci 0000:7f:10.0: [8086:3cb0] type 00 class 0x088000
[    1.391891] pci 0000:7f:10.1: [8086:3cb1] type 00 class 0x088000
[    1.391956] pci 0000:7f:10.2: [8086:3cb2] type 00 class 0x088000
[    1.392023] pci 0000:7f:10.3: [8086:3cb3] type 00 class 0x088000
[    1.392090] pci 0000:7f:10.5: [8086:3cb5] type 00 class 0x088000
[    1.392156] pci 0000:7f:10.6: [8086:3cb6] type 00 class 0x088000
[    1.392222] pci 0000:7f:10.7: [8086:3cb7] type 00 class 0x088000
[    1.392285] pci 0000:7f:11.0: [8086:3cb8] type 00 class 0x088000
[    1.392347] pci 0000:7f:13.0: [8086:3ce4] type 00 class 0x088000
[    1.392393] pci 0000:7f:13.1: [8086:3c43] type 00 class 0x110100
[    1.392442] pci 0000:7f:13.4: [8086:3ce6] type 00 class 0x110100
[    1.392488] pci 0000:7f:13.5: [8086:3c44] type 00 class 0x110100
[    1.392533] pci 0000:7f:13.6: [8086:3c45] type 00 class 0x088000
[    1.392586] pci_bus 0000:7f: on NUMA node 1
[    1.392809] ACPI: PCI Interrupt Link [LK00] (IRQs 3 4 5 6 7 11 14 *15)
[    1.392915] ACPI: PCI Interrupt Link [LK01] (IRQs 3 4 5 6 7 11 *14 15)
[    1.393021] ACPI: PCI Interrupt Link [LK02] (IRQs 3 4 5 6 7 11 14 15) *0, disabled.
[    1.393124] ACPI: PCI Interrupt Link [LK03] (IRQs 3 4 5 6 7 *11 14 15)
[    1.393227] ACPI: PCI Interrupt Link [LK04] (IRQs 3 4 *5 6 7 11 14 15)
[    1.393331] ACPI: PCI Interrupt Link [LK05] (IRQs 3 4 5 6 7 11 14 15) *0, disabled.
[    1.393434] ACPI: PCI Interrupt Link [LK06] (IRQs 3 4 5 *6 7 11 14 15)
[    1.393544] ACPI: PCI Interrupt Link [LK07] (IRQs 3 4 5 6 7 11 *14 15)
[    1.393702] iommu: Default domain type: Translated 
[    1.393719] SCSI subsystem initialized
[    1.393741] libata version 3.00 loaded.
[    1.393741] pci 0000:06:00.0: vgaarb: setting as boot VGA device
[    1.393741] pci 0000:06:00.0: vgaarb: VGA device added: decodes=io+mem,owns=io+mem,locks=none
[    1.393741] pci 0000:06:00.0: vgaarb: bridge control possible
[    1.393741] vgaarb: loaded
[    1.393741] ACPI: bus type USB registered
[    1.393741] usbcore: registered new interface driver usbfs
[    1.393741] usbcore: registered new interface driver hub
[    1.393741] usbcore: registered new device driver usb
[    1.393741] pps_core: LinuxPPS API ver. 1 registered
[    1.393741] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    1.393746] PTP clock support registered
[    1.393777] EDAC MC: Ver: 3.0.0
[    1.394152] PCI: Using ACPI for IRQ routing
[    1.396756] PCI: pci_cache_line_size set to 64 bytes
[    1.397226] e820: reserve RAM buffer [mem 0x0009c000-0x0009ffff]
[    1.397229] e820: reserve RAM buffer [mem 0x7d2f0000-0x7fffffff]
[    1.397486] NetLabel: Initializing
[    1.397489] NetLabel:  domain hash size = 128
[    1.397491] NetLabel:  protocols = UNLABELED CIPSOv4 CALIPSO
[    1.397511] NetLabel:  unlabeled traffic allowed by default
[    1.402389] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0, 0, 0, 0, 0, 0
[    1.402398] hpet0: 8 comparators, 64-bit 14.318180 MHz counter
[    1.404473] clocksource: Switched to clocksource tsc-early
[    1.416610] *** VALIDATE bpf ***
[    1.416775] VFS: Disk quotas dquot_6.6.0
[    1.416823] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    1.416859] *** VALIDATE ramfs ***
[    1.416874] *** VALIDATE hugetlbfs ***
[    1.417010] AppArmor: AppArmor Filesystem Enabled
[    1.417051] pnp: PnP ACPI init
[    1.417294] system 00:00: Plug and Play ACPI device, IDs PNP0c01 (active)
[    1.417347] pnp 00:01: Plug and Play ACPI device, IDs PNP0b00 (active)
[    1.417642] pnp 00:02: Plug and Play ACPI device, IDs PNP0501 (active)
[    1.417907] pnp 00:03: Plug and Play ACPI device, IDs PNP0501 (active)
[    1.418357] system 00:04: [io  0x0800-0x087f] has been reserved
[    1.418361] system 00:04: [io  0x0880-0x08ff] has been reserved
[    1.418364] system 00:04: [io  0x0900-0x091f] has been reserved
[    1.418366] system 00:04: [io  0x0920-0x0923] has been reserved
[    1.418369] system 00:04: [io  0x0924] has been reserved
[    1.418372] system 00:04: [io  0x0370-0x0377] has been reserved
[    1.418375] system 00:04: [io  0x0ca0-0x0ca7] has been reserved
[    1.418377] system 00:04: [io  0x0ca9-0x0cab] has been reserved
[    1.418380] system 00:04: [io  0x0cad-0x0caf] has been reserved
[    1.418383] system 00:04: [io  0x0cb0-0x0cbf] has been reserved
[    1.418388] system 00:04: Plug and Play ACPI device, IDs PNP0c01 (active)
[    1.418491] system 00:05: [io  0x0ca8] has been reserved
[    1.418495] system 00:05: [io  0x0cac] has been reserved
[    1.418501] system 00:05: Plug and Play ACPI device, IDs IPI0001 PNP0c01 (active)
[    1.418981] system 00:06: [mem 0xe0000000-0xe3efffff] has been reserved
[    1.418988] system 00:06: Plug and Play ACPI device, IDs PNP0c02 (active)
[    1.419214] system 00:07: [mem 0xe4000000-0xe7ffffff] has been reserved
[    1.419221] system 00:07: Plug and Play ACPI device, IDs PNP0c02 (active)
[    1.419316] system 00:08: [mem 0xe3f00000-0xe3ffffff] has been reserved
[    1.419322] system 00:08: Plug and Play ACPI device, IDs PNP0c02 (active)
[    1.419432] system 00:09: [mem 0xdf100000-0xdf101fff] could not be reserved
[    1.419439] system 00:09: Plug and Play ACPI device, IDs PNP0c02 (active)
[    1.419577] system 00:0a: [mem 0xd3000000-0xd3001fff] could not be reserved
[    1.419584] system 00:0a: Plug and Play ACPI device, IDs PNP0c02 (active)
[    1.419843] pnp: PnP ACPI: found 11 devices
[    1.421287] thermal_sys: Registered thermal governor 'fair_share'
[    1.421288] thermal_sys: Registered thermal governor 'bang_bang'
[    1.421291] thermal_sys: Registered thermal governor 'step_wise'
[    1.421293] thermal_sys: Registered thermal governor 'user_space'
[    1.421296] thermal_sys: Registered thermal governor 'power_allocator'
[    1.425788] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    1.425830] pci 0000:02:00.1: can't claim BAR 6 [mem 0xdd000000-0xdd03ffff pref]: address conflict with 0000:02:00.0 [mem 0xdd000000-0xdd03ffff pref]
[    1.425847] pci 0000:00:01.0: PCI bridge to [bus 01]
[    1.425851] pci 0000:00:01.0:   bridge window [io  0xf000-0xffff]
[    1.425857] pci 0000:00:01.0:   bridge window [mem 0xdc000000-0xdcffffff]
[    1.425865] pci 0000:00:03.0: PCI bridge to [bus 08]
[    1.425874] pci 0000:00:11.0: PCI bridge to [bus 09]
[    1.425887] pci 0000:00:1c.0: PCI bridge to [bus 0a]
[    1.425902] pci 0000:02:00.1: BAR 6: assigned [mem 0xdd040000-0xdd07ffff pref]
[    1.425906] pci 0000:00:1c.4: PCI bridge to [bus 02]
[    1.425911] pci 0000:00:1c.4:   bridge window [mem 0xdd000000-0xdd7fffff]
[    1.425916] pci 0000:00:1c.4:   bridge window [mem 0xd9000000-0xd90fffff 64bit pref]
[    1.425924] pci 0000:05:00.0: PCI bridge to [bus 06]
[    1.426066] pci 0000:05:00.0:   bridge window [mem 0xdd800000-0xde7fffff]
[    1.426160] pci 0000:05:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.426355] pci 0000:04:00.0: PCI bridge to [bus 05-06]
[    1.426498] pci 0000:04:00.0:   bridge window [mem 0xdd800000-0xde7fffff]
[    1.426592] pci 0000:04:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.426786] pci 0000:04:01.0: PCI bridge to [bus 07]
[    1.426930] pci 0000:04:01.0:   bridge window [mem 0xdef00000-0xdeffffff]
[    1.427280] pci 0000:03:00.0: PCI bridge to [bus 04-07]
[    1.427410] pci 0000:03:00.0:   bridge window [mem 0xdd800000-0xdeffffff]
[    1.427495] pci 0000:03:00.0:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427734] pci 0000:00:1c.7: PCI bridge to [bus 03-07]
[    1.427739] pci 0000:00:1c.7:   bridge window [mem 0xdd800000-0xdeffffff]
[    1.427744] pci 0000:00:1c.7:   bridge window [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427751] pci 0000:00:1e.0: PCI bridge to [bus 0b]
[    1.427762] pci_bus 0000:00: resource 4 [io  0x0000-0x03af window]
[    1.427764] pci_bus 0000:00: resource 5 [io  0x03e0-0x0cf7 window]
[    1.427767] pci_bus 0000:00: resource 6 [io  0x03b0-0x03df window]
[    1.427769] pci_bus 0000:00: resource 7 [io  0x0d00-0x1fff window]
[    1.427772] pci_bus 0000:00: resource 8 [io  0xe000-0xffff window]
[    1.427775] pci_bus 0000:00: resource 9 [mem 0x000a0000-0x000bffff window]
[    1.427778] pci_bus 0000:00: resource 10 [mem 0xd8000000-0xdfffffff window]
[    1.427780] pci_bus 0000:00: resource 11 [mem 0xfed40000-0xfed44fff window]
[    1.427783] pci_bus 0000:01: resource 0 [io  0xf000-0xffff]
[    1.427785] pci_bus 0000:01: resource 1 [mem 0xdc000000-0xdcffffff]
[    1.427788] pci_bus 0000:02: resource 1 [mem 0xdd000000-0xdd7fffff]
[    1.427791] pci_bus 0000:02: resource 2 [mem 0xd9000000-0xd90fffff 64bit pref]
[    1.427794] pci_bus 0000:03: resource 1 [mem 0xdd800000-0xdeffffff]
[    1.427796] pci_bus 0000:03: resource 2 [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427799] pci_bus 0000:04: resource 1 [mem 0xdd800000-0xdeffffff]
[    1.427802] pci_bus 0000:04: resource 2 [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427805] pci_bus 0000:05: resource 1 [mem 0xdd800000-0xde7fffff]
[    1.427807] pci_bus 0000:05: resource 2 [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427811] pci_bus 0000:06: resource 1 [mem 0xdd800000-0xde7fffff]
[    1.427813] pci_bus 0000:06: resource 2 [mem 0xd8000000-0xd8ffffff 64bit pref]
[    1.427816] pci_bus 0000:07: resource 1 [mem 0xdef00000-0xdeffffff]
[    1.427819] pci_bus 0000:0b: resource 4 [io  0x0000-0x03af window]
[    1.427822] pci_bus 0000:0b: resource 5 [io  0x03e0-0x0cf7 window]
[    1.427824] pci_bus 0000:0b: resource 6 [io  0x03b0-0x03df window]
[    1.427827] pci_bus 0000:0b: resource 7 [io  0x0d00-0x1fff window]
[    1.427829] pci_bus 0000:0b: resource 8 [io  0xe000-0xffff window]
[    1.427832] pci_bus 0000:0b: resource 9 [mem 0x000a0000-0x000bffff window]
[    1.427834] pci_bus 0000:0b: resource 10 [mem 0xd8000000-0xdfffffff window]
[    1.427837] pci_bus 0000:0b: resource 11 [mem 0xfed40000-0xfed44fff window]
[    1.427868] pci 0000:40:03.0: PCI bridge to [bus 41]
[    1.427879] pci_bus 0000:40: resource 4 [io  0x2000-0x3fff window]
[    1.427882] pci_bus 0000:40: resource 5 [io  0x4000-0x5fff window]
[    1.427884] pci_bus 0000:40: resource 6 [io  0x6000-0x7fff window]
[    1.427887] pci_bus 0000:40: resource 7 [io  0x8000-0x9fff window]
[    1.427889] pci_bus 0000:40: resource 8 [io  0xa000-0xbfff window]
[    1.427892] pci_bus 0000:40: resource 9 [io  0xc000-0xdfff window]
[    1.427894] pci_bus 0000:40: resource 10 [mem 0xd0000000-0xd7ffffff window]
[    1.427979] NET: Registered protocol family 2
[    1.428488] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, vmalloc)
[    1.431180] tcp_listen_portaddr_hash hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
[    1.432286] TCP established hash table entries: 524288 (order: 10, 4194304 bytes, vmalloc)
[    1.433174] TCP bind hash table entries: 65536 (order: 8, 1048576 bytes, vmalloc)
[    1.433276] TCP: Hash tables configured (established 524288 bind 65536)
[    1.433857] UDP hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    1.434595] UDP-Lite hash table entries: 65536 (order: 9, 2097152 bytes, vmalloc)
[    1.435013] NET: Registered protocol family 1
[    1.435021] NET: Registered protocol family 44
[    1.435040] pci 0000:00:05.0: disabled boot interrupts on device [8086:3c28]
[    1.453679] pci 0000:00:1a.0: quirk_usb_early_handoff+0x0/0x670 took 18180 usecs
[    1.454142] pci 0000:01:00.0: [Firmware Bug]: disabling VPD access (can't determine size of non-standard VPD format)
[    1.454508] pci 0000:06:00.0: Video device with shadowed ROM at [mem 0x000c0000-0x000dffff]
[    1.454608] pci 0000:40:05.0: disabled boot interrupts on device [8086:3c28]
[    1.454673] PCI: CLS 64 bytes, default 64
[    1.454748] Trying to unpack rootfs image as initramfs...
[    1.704504] Freeing initrd memory: 82424K
[    1.729462] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    1.729466] software IO TLB: mapped [mem 0x792f0000-0x7d2f0000] (64MB)
[    1.730726] check: Scanning for low memory corruption every 60 seconds
[    1.731742] Initialise system trusted keyrings
[    1.731756] Key type blacklist registered
[    1.731821] workingset: timestamp_bits=36 max_order=26 bucket_order=0
[    1.733202] zbud: loaded
[    1.733715] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    1.733902] fuse: init (API version 7.31)
[    1.733924] *** VALIDATE fuse ***
[    1.733927] *** VALIDATE fuse ***
[    1.734075] Platform Keyring initialized
[    1.737893] Key type asymmetric registered
[    1.737897] Asymmetric key parser 'x509' registered
[    1.737908] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 244)
[    1.737955] io scheduler mq-deadline registered
[    1.738745] pcieport 0000:00:01.0: PME: Signaling with IRQ 25
[    1.739164] pcieport 0000:00:03.0: PME: Signaling with IRQ 26
[    1.739529] pcieport 0000:00:11.0: PME: Signaling with IRQ 27
[    1.739658] pcieport 0000:00:1c.0: PME: Signaling with IRQ 28
[    1.739979] pcieport 0000:00:1c.4: PME: Signaling with IRQ 29
[    1.740309] pcieport 0000:00:1c.7: PME: Signaling with IRQ 30
[    1.744716] pcieport 0000:40:03.0: PME: Signaling with IRQ 32
[    1.745047] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[    1.745139] vesafb: mode is 640x480x32, linelength=2560, pages=0
[    1.745142] vesafb: scrolling: redraw
[    1.745144] vesafb: Truecolor: size=8:8:8:8, shift=24:16:8:0
[    1.745158] vesafb: framebuffer at 0xd8000000, mapped to 0x(____ptrval____), using 1216k, total 1216k
[    1.745257] Console: switching to colour frame buffer device 80x30
[    1.809848] fb0: VESA VGA frame buffer device
[    1.811167] intel_idle: MWAIT substates: 0x21120
[    1.811168] intel_idle: v0.4.1 model 0x2D
[    1.812258] intel_idle: lapic_timer_reliable_states 0xffffffff
[    1.812383] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.814702] ACPI: Power Button [PWRF]
[    1.816777] ERST: Error Record Serialization Table (ERST) support is initialized.
[    1.885716] pstore: Registered erst as persistent store backend
[    1.920932] GHES: APEI firmware first mode is enabled by APEI bit and WHEA _OSC.
[    1.993295] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    2.052198] 00:02: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[    2.150514] 00:03: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    2.230606] Linux agpgart interface v0.103
[    2.413519] loop: module loaded
[    2.452126] libphy: Fixed MDIO Bus: probed
[    2.491356] tun: Universal TUN/TAP device driver, 1.6
[    2.531948] PPP generic driver version 2.4.2
[    2.573405] VFIO - User Level meta-driver version: 0.3
[    2.616401] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.660707] ehci-pci: EHCI PCI platform driver
[    2.705928] ehci-pci 0000:00:1a.0: EHCI Host Controller
[    2.749477] tsc: Refined TSC clocksource calibration: 2399.992 MHz
[    2.750451] ehci-pci 0000:00:1a.0: new USB bus registered, assigned bus number 1
[    2.795225] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x22982fdf183, max_idle_ns: 440795240423 ns
[    2.884981] ehci-pci 0000:00:1a.0: debug port 2
[    3.023296] clocksource: Switched to clocksource tsc
[    3.027260] ehci-pci 0000:00:1a.0: cache line size of 64 is not supported
[    3.114623] ehci-pci 0000:00:1a.0: irq 23, io mem 0xdf0fd000
[    3.173486] ehci-pci 0000:00:1a.0: USB 2.0 started, EHCI 1.00
[    3.218277] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    3.307386] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.396971] usb usb1: Product: EHCI Host Controller
[    3.441631] usb usb1: Manufacturer: Linux 5.4.0-90-generic ehci_hcd
[    3.486370] usb usb1: SerialNumber: 0000:00:1a.0
[    3.529842] hub 1-0:1.0: USB hub found
[    3.572551] hub 1-0:1.0: 2 ports detected
[    3.614612] ehci-pci 0000:00:1d.0: EHCI Host Controller
[    3.656194] ehci-pci 0000:00:1d.0: new USB bus registered, assigned bus number 2
[    3.738563] ehci-pci 0000:00:1d.0: debug port 2
[    3.784734] ehci-pci 0000:00:1d.0: cache line size of 64 is not supported
[    3.827941] ehci-pci 0000:00:1d.0: irq 22, io mem 0xdf0fe000
[    3.885491] usb 1-1: new high-speed USB device number 2 using ehci-pci
[    3.901462] ehci-pci 0000:00:1d.0: USB 2.0 started, EHCI 1.00
[    3.971787] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    4.058892] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    4.082283] usb 1-1: New USB device found, idVendor=8087, idProduct=0024, bcdDevice= 0.00
[    4.146443] usb usb2: Product: EHCI Host Controller
[    4.146445] usb usb2: Manufacturer: Linux 5.4.0-90-generic ehci_hcd
[    4.235232] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.235743] hub 1-1:1.0: USB hub found
[    4.278338] usb usb2: SerialNumber: 0000:00:1d.0
[    4.324468] hub 1-1:1.0: 6 ports detected
[    4.366739] hub 2-0:1.0: USB hub found
[    4.540376] hub 2-0:1.0: 2 ports detected
[    4.581776] ehci-platform: EHCI generic platform driver
[    4.622344] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.663229] ohci-pci: OHCI PCI platform driver
[    4.697454] usb 1-1.6: new high-speed USB device number 3 using ehci-pci
[    4.703258] ohci-platform: OHCI generic platform driver
[    4.785585] uhci_hcd: USB Universal Host Controller Interface driver
[    4.827333] i8042: PNP: No PS/2 controller found.
[    4.851344] usb 1-1.6: New USB device found, idVendor=413c, idProduct=a001, bcdDevice= 0.00
[    4.869466] usb 2-1: new high-speed USB device number 2 using ehci-pci
[    4.869929] mousedev: PS/2 mouse device common for all mice
[    4.956226] usb 1-1.6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.956228] usb 1-1.6: Product: Gadget USB HUB
[    5.000696] rtc_cmos 00:01: RTC can wake from S4
[    5.033974] usb 2-1: New USB device found, idVendor=8087, idProduct=0024, bcdDevice= 0.00
[    5.033976] usb 2-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    5.034365] hub 2-1:1.0: USB hub found
[    5.034569] hub 2-1:1.0: 8 ports detected
[    5.045142] usb 1-1.6: Manufacturer: no manufacturer
[    5.045143] usb 1-1.6: SerialNumber: 0123456789
[    5.045631] hub 1-1.6:1.0: USB hub found
[    5.135231] rtc_cmos 00:01: registered as rtc0
[    5.180094] hub 1-1.6:1.0: 6 ports detected
[    5.224769] rtc_cmos 00:01: alarms up to one day, y3k, 242 bytes nvram, hpet irqs
[    5.730180] i2c /dev entries driver
[    5.770982] device-mapper: uevent: version 1.0.3
[    5.793454] usb 1-1.6.1: new high-speed USB device number 4 using ehci-pci
[    5.812657] device-mapper: ioctl: 4.41.0-ioctl (2019-09-16) initialised: dm-devel@redhat.com
[    5.941349] platform eisa.0: Probing EISA bus 0
[    5.984797] platform eisa.0: EISA: Cannot allocate resource for mainboard
[    5.987474] usb 1-1.6.1: New USB device found, idVendor=0624, idProduct=0249, bcdDevice= 0.00
[    6.027859] platform eisa.0: Cannot allocate resource for EISA slot 1
[    6.027861] platform eisa.0: Cannot allocate resource for EISA slot 2
[    6.114906] usb 1-1.6.1: New USB device strings: Mfr=4, Product=5, SerialNumber=6
[    6.114907] usb 1-1.6.1: Product: Keyboard/Mouse Function
[    6.114920] usb 1-1.6.1: Manufacturer: Avocent
[    6.159284] platform eisa.0: Cannot allocate resource for EISA slot 3
[    6.159296] platform eisa.0: Cannot allocate resource for EISA slot 4
[    6.159298] platform eisa.0: Cannot allocate resource for EISA slot 5
[    6.201830] usb 1-1.6.1: SerialNumber: 20121018
[    6.527486] platform eisa.0: Cannot allocate resource for EISA slot 6
[    6.565975] platform eisa.0: Cannot allocate resource for EISA slot 7
[    6.603173] platform eisa.0: Cannot allocate resource for EISA slot 8
[    6.640080] platform eisa.0: EISA: Detected 0 cards
[    6.676551] intel_pstate: Intel P-state driver initializing
[    6.717108] ledtrig-cpu: registered to indicate activity on CPUs
[    6.755251] drop_monitor: Initializing network drop monitor service
[    6.794150] NET: Registered protocol family 10
[    6.840849] Segment Routing with IPv6
[    6.878539] NET: Registered protocol family 17
[    6.915919] Key type dns_resolver registered
[    6.956534] RAS: Correctable Errors collector initialized.
[    6.994837] microcode: sig=0x206d7, pf=0x8, revision=0x71a
[    7.033667] microcode: Microcode Update Driver: v2.2.
[    7.033672] IPI shorthand broadcast: enabled
[    7.106283] sched_clock: Marking stable (7105721654, 550039)->(7142914227, -36642534)
[    7.179561] registered taskstats version 1
[    7.215745] Loading compiled-in X.509 certificates
[    7.252584] Loaded X.509 cert 'Build time autogenerated kernel key: 85cd93e325e502cfcb4258a2209a1e273ffd77af'
[    7.326768] Loaded X.509 cert 'Canonical Ltd. Live Patch Signing: 14df34d1a87cf37625abec039ef2bf521249b969'
[    7.402968] Loaded X.509 cert 'Canonical Ltd. Kernel Module Signing: 88f752e560a1e0737e31163a466ad7b70a850c19'
[    7.480979] zswap: loaded using pool lzo/zbud
[    7.520586] Key type ._fscrypt registered
[    7.560346] Key type .fscrypt registered
[    7.600899] pstore: Using crash dump compression: deflate
[    7.648429] Key type big_key registered
[    7.691416] Key type encrypted registered
[    7.731679] AppArmor: AppArmor sha1 policy hashing enabled
[    7.773413] ima: No TPM chip found, activating TPM-bypass!
[    7.815079] ima: Allocated hash algorithm: sha1
[    7.856766] ima: No architecture policies found
[    7.897759] evm: Initialising EVM extended attributes:
[    7.938611] evm: security.selinux
[    7.978680] evm: security.SMACK64
[    8.017740] evm: security.SMACK64EXEC
[    8.056246] evm: security.SMACK64TRANSMUTE
[    8.094416] evm: security.SMACK64MMAP
[    8.131139] evm: security.apparmor
[    8.167167] evm: security.ima
[    8.202313] evm: security.capability
[    8.237074] evm: HMAC attrs: 0x1
[    8.271684] PM:   Magic number: 13:487:83
[    8.304477] event_source uncore_cbox_1: hash matches
[    8.337620] rtc_cmos 00:01: setting system clock to 2021-11-18T15:03:41 UTC (1637247821)
[    8.406187] Freeing unused decrypted memory: 2040K
[    8.440250] Freeing unused kernel image memory: 2736K
[    8.477576] Write protecting the kernel read-only data: 22528k
[    8.510591] Freeing unused kernel image memory: 2008K
[    8.542182] Freeing unused kernel image memory: 1124K
[    8.581857] x86/mm: Checked W+X mappings: passed, no W+X pages found.
[    8.611793] x86/mm: Checking user space page tables
[    8.651189] x86/mm: Checked W+X mappings: passed, no W+X pages found.
[    8.681902] Run /init as init process
[    8.873653] megasas: 07.713.01.00-rc1
[    8.907279] hidraw: raw HID events driver (C) Jiri Kosina
[    8.909546] megaraid_sas 0000:01:00.0: BAR:0x1  BAR's base_addr(phys):0x00000000dcffc000  mapped virt_addr:0x(____ptrval____)
[    8.937577] megaraid_sas 0000:01:00.0: FW now in Ready state
[    8.967943] megaraid_sas 0000:01:00.0: 63 bit DMA mask and 32 bit consistent mask
[    9.028266] cryptd: max_cpu_qlen set to 1000
[    9.028498] megaraid_sas 0000:01:00.0: firmware supports msix	: (16)
[    9.091640] megaraid_sas 0000:01:00.0: requested/available msix 16/16
[    9.124633] megaraid_sas 0000:01:00.0: current msix/online cpus	: (16/24)
[    9.158440] megaraid_sas 0000:01:00.0: RDPQ mode	: (disabled)
[    9.192332] megaraid_sas 0000:01:00.0: Current firmware supports maximum commands: 1008	 LDIO threshold: 0
[    9.263086] megaraid_sas 0000:01:00.0: Configured max firmware commands: 1007
[    9.305983] megaraid_sas 0000:01:00.0: Performance mode :Latency
[    9.344107] megaraid_sas 0000:01:00.0: FW supports sync cache	: No
[    9.382351] megaraid_sas 0000:01:00.0: megasas_disable_intr_fusion is called outbound_intr_mask:0x40000009
[    9.481934] tg3.c:v3.137 (May 11, 2014)
[    9.519799] ahci 0000:00:1f.2: version 3.0
[    9.527548] usbcore: registered new interface driver usbhid
[    9.530783] ahci 0000:00:1f.2: AHCI 0001.0300 32 slots 6 ports 3 Gbps 0x1f impl SATA mode
[    9.564563] usbhid: USB HID core driver
[    9.639955] ahci 0000:00:1f.2: flags: 64bit ncq sntf pm led clo pio slum part ems apst 
[    9.650378] tg3 0000:02:00.0 eth0: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 90:b1:1c:24:a1:f1
[    9.756359] AVX version of gcm_enc/dec engaged.
[    9.838303] tg3 0000:02:00.0 eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[    9.838307] tg3 0000:02:00.0 eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[    9.879579] AES CTR mode by8 optimization enabled
[    9.964509] tg3 0000:02:00.0 eth0: dma_rwctrl[00000001] dma_mask[64-bit]
[   10.143326] megaraid_sas 0000:01:00.0: FW provided supportMaxExtLDs: 0	max_lds: 64
[   10.233799] megaraid_sas 0000:01:00.0: controller type	: MR(512MB)
[   10.280302] megaraid_sas 0000:01:00.0: Online Controller Reset(OCR)	: Enabled
[   10.327500] megaraid_sas 0000:01:00.0: Secure JBOD support	: No
[   10.374549] megaraid_sas 0000:01:00.0: NVMe passthru support	: No
[   10.421415] megaraid_sas 0000:01:00.0: FW provided TM TaskAbort/Reset timeout	: 0 secs/0 secs
[   10.514064] megaraid_sas 0000:01:00.0: JBOD sequence map support	: No
[   10.560892] megaraid_sas 0000:01:00.0: PCI Lane Margining support	: No
[   10.634434] megaraid_sas 0000:01:00.0: megasas_enable_intr_fusion is called outbound_intr_mask:0x40000000
[   10.728469] megaraid_sas 0000:01:00.0: INIT adapter done
[   10.775617] megaraid_sas 0000:01:00.0: JBOD sequence map is disabled megasas_setup_jbod_map 5734
[   10.869602] scsi host1: ahci
[   10.916097] input: Avocent Keyboard/Mouse Function as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6.1/1-1.6.1:1.0/0003:0624:0249.0001/input/input1
[   10.916296] megaraid_sas 0000:01:00.0: pci id		: (0x1000)/(0x005b)/(0x1028)/(0x1f38)
[   11.069815] hid-generic 0003:0624:0249.0001: input,hidraw0: USB HID v1.00 Keyboard [Avocent Keyboard/Mouse Function] on usb-0000:00:1a.0-1.6.1/input0
[   11.107159] megaraid_sas 0000:01:00.0: unevenspan support	: no
[   11.205518] input: Avocent Keyboard/Mouse Function as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6.1/1-1.6.1:1.1/0003:0624:0249.0002/input/input2
[   11.254569] megaraid_sas 0000:01:00.0: firmware crash dump	: no
[   11.354762] hid-generic 0003:0624:0249.0002: input,hidraw1: USB HID v1.00 Mouse [Avocent Keyboard/Mouse Function] on usb-0000:00:1a.0-1.6.1/input1
[   11.403961] megaraid_sas 0000:01:00.0: JBOD sequence map	: disabled
[   11.503377] input: Avocent Keyboard/Mouse Function as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.6/1-1.6.1/1-1.6.1:1.2/0003:0624:0249.0003/input/input3
[   11.553358] scsi host2: ahci
[   11.654024] hid-generic 0003:0624:0249.0003: input,hidraw2: USB HID v1.00 Mouse [Avocent Keyboard/Mouse Function] on usb-0000:00:1a.0-1.6.1/input2
[   11.704215] scsi host3: ahci
[   11.859518] scsi host0: Avago SAS based MegaRAID driver
[   11.913863] scsi host4: ahci
[   11.937003] scsi 0:2:0:0: Direct-Access     DELL     PERC H710        3.13 PQ: 0 ANSI: 5
[   11.965340] scsi host5: ahci
[   12.086159] random: fast init done
[   12.117150] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[   12.117377] scsi host6: ahci
[   12.117738] ata1: SATA max UDMA/133 abar m2048@0xdf0ff000 port 0xdf0ff100 irq 50
[   12.117752] ata2: SATA max UDMA/133 abar m2048@0xdf0ff000 port 0xdf0ff180 irq 50
[   12.117757] ata3: SATA max UDMA/133 abar m2048@0xdf0ff000 port 0xdf0ff200 irq 50
[   12.117761] ata4: SATA max UDMA/133 abar m2048@0xdf0ff000 port 0xdf0ff280 irq 50
[   12.117766] ata5: SATA max UDMA/133 abar m2048@0xdf0ff000 port 0xdf0ff300 irq 50
[   12.117767] ata6: DUMMY
[   12.123773] tg3 0000:02:00.1 eth1: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 90:b1:1c:24:a1:f2
[   12.123776] tg3 0000:02:00.1 eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
[   12.123777] tg3 0000:02:00.1 eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
[   12.123779] tg3 0000:02:00.1 eth1: dma_rwctrl[00000001] dma_mask[64-bit]
[   12.176755] scsi 0:2:0:0: Attached scsi generic sg0 type 0
[   12.176979] sd 0:2:0:0: [sda] 11717836800 512-byte logical blocks: (6.00 TB/5.46 TiB)
[   12.177041] sd 0:2:0:0: [sda] Write Protect is off
[   12.177043] sd 0:2:0:0: [sda] Mode Sense: 1f 00 00 08
[   12.177101] sd 0:2:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   12.216152] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[   12.432089] ata1: SATA link down (SStatus 0 SControl 300)
[   12.467869] random: systemd-udevd: uninitialized urandom read (16 bytes read)
[   12.568083] ata2: SATA link down (SStatus 0 SControl 300)
[   12.671298] tg3 0000:02:00.0 eno1: renamed from eth0
[   12.767945] ata4: SATA link down (SStatus 0 SControl 300)
[   13.761295] ata3: SATA link down (SStatus 0 SControl 300)
[   13.811864] ata5: SATA link down (SStatus 0 SControl 300)
[   13.816403]  sda: sda1 sda2 sda3
[   13.862601] tg3 0000:02:00.1 eno2: renamed from eth1
[   13.958905] mgag200 0000:06:00.0: remove_conflicting_pci_framebuffers: bar 0: 0xd8000000 -> 0xd8ffffff
[   14.052447] mgag200 0000:06:00.0: remove_conflicting_pci_framebuffers: bar 1: 0xde7fc000 -> 0xde7fffff
[   14.146758] mgag200 0000:06:00.0: remove_conflicting_pci_framebuffers: bar 2: 0xdd800000 -> 0xddffffff
[   14.243010] checking generic (d8000000 130000) vs hw (d8000000 1000000)
[   14.243010] fb0: switching to mgag200drmfb from VESA VGA
[   14.291831] Console: switching to colour dummy device 80x25
[   14.291851] mgag200 0000:06:00.0: vgaarb: deactivate vga console
[   14.293784] sd 0:2:0:0: [sda] Attached SCSI disk
[   14.303645] [TTM] Zone  kernel: Available graphics memory: 74243334 KiB
[   14.303649] [TTM] Zone   dma32: Available graphics memory: 2097152 KiB
[   14.303651] [TTM] Initializing pool allocator
[   14.303668] [TTM] Initializing DMA pool allocator
[   14.335652] fbcon: mgag200drmfb (fb0) is primary device
[   14.405505] Console: switching to colour frame buffer device 128x48
[   14.407065] mgag200 0000:06:00.0: fb0: mgag200drmfb frame buffer device
[   14.437510] [drm] Initialized mgag200 1.0.0 20110418 for 0000:06:00.0 on minor 0
[   14.893447] raid6: sse2x4   gen() 11647 MB/s
[   14.941449] raid6: sse2x4   xor()  7890 MB/s
[   14.989447] raid6: sse2x2   gen() 10010 MB/s
[   15.037447] raid6: sse2x2   xor()  6762 MB/s
[   15.085451] raid6: sse2x1   gen()  8193 MB/s
[   15.133450] raid6: sse2x1   xor()  6079 MB/s
[   15.133465] raid6: using algorithm sse2x4 gen() 11647 MB/s
[   15.133483] raid6: .... xor() 7890 MB/s, rmw enabled
[   15.133519] raid6: using ssse3x2 recovery algorithm
[   15.135764] xor: automatically using best checksumming function   avx       
[   15.137513] async_tx: api initialized (async)
[   15.250209] Btrfs loaded, crc32c=crc32c-intel
[   15.267637] BTRFS: device label local devid 1 transid 1266667 /dev/mapper/ubuntu--vg-lxd--lv
[   15.351481] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[   16.633216] systemd[1]: Inserted module 'autofs4'
[   16.692823] ERST: NVRAM ERST Log Address Range not implemented yet.
[   16.734121] systemd[1]: systemd 245.4-4ubuntu3.13 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
[   16.753570] systemd[1]: Detected architecture x86-64.
[   16.827818] systemd[1]: Set hostname to <frodo>.
[   18.285557] random: crng init done
[   18.286403] random: 7 urandom warning(s) missed due to ratelimiting
[   18.438878] systemd[1]: Created slice system-modprobe.slice.
[   18.443205] systemd[1]: Created slice User and Session Slice.
[   18.444921] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[   18.446840] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[   18.448592] systemd[1]: Reached target User and Group Name Lookups.
[   18.450296] systemd[1]: Reached target Slices.
[   18.452057] systemd[1]: Listening on Device-mapper event daemon FIFOs.
[   18.453921] systemd[1]: Listening on LVM2 poll daemon socket.
[   18.455749] systemd[1]: Listening on multipathd control socket.
[   18.461654] systemd[1]: Listening on RPCbind Server Activation Socket.
[   18.463630] systemd[1]: Listening on Syslog Socket.
[   18.465584] systemd[1]: Listening on initctl Compatibility Named Pipe.
[   18.467616] systemd[1]: Listening on Journal Audit Socket.
[   18.469526] systemd[1]: Listening on Journal Socket (/dev/log).
[   18.471422] systemd[1]: Listening on Journal Socket.
[   18.473295] systemd[1]: Listening on Network Service Netlink Socket.
[   18.475139] systemd[1]: Listening on udev Control Socket.
[   18.476898] systemd[1]: Listening on udev Kernel Socket.
[   18.479932] systemd[1]: Mounting Huge Pages File System...
[   18.482830] systemd[1]: Mounting POSIX Message Queue File System...
[   18.485643] systemd[1]: Mounting RPC Pipe File System...
[   18.488513] systemd[1]: Mounting Kernel Debug File System...
[   18.491594] systemd[1]: Mounting Kernel Trace File System...
[   18.495750] systemd[1]: Starting Journal Service...
[   18.499275] systemd[1]: Starting Set the console keyboard layout...
[   18.502323] systemd[1]: Starting Create list of static device nodes for the current kernel...
[   18.505336] systemd[1]: Starting Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
[   18.507280] systemd[1]: Condition check resulted in Load Kernel Module drm being skipped.
[   18.508226] systemd[1]: Condition check resulted in OpenVSwitch configuration for cleanup being skipped.
[   18.523841] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[   18.529874] systemd[1]: Starting Load Kernel Modules...
[   18.532873] systemd[1]: Starting Remount Root and Kernel File Systems...
[   18.535845] systemd[1]: Starting udev Coldplug all Devices...
[   18.538807] systemd[1]: Starting Uncomplicated firewall...
[   18.543360] systemd[1]: Mounted Huge Pages File System.
[   18.545324] systemd[1]: Mounted POSIX Message Queue File System.
[   18.547627] systemd[1]: Mounted Kernel Debug File System.
[   18.550028] systemd[1]: Mounted Kernel Trace File System.
[   18.552487] systemd[1]: Finished Create list of static device nodes for the current kernel.
[   18.553200] EXT4-fs (dm-0): re-mounted. Opts: (null)
[   18.557342] systemd[1]: Finished Remount Root and Kernel File Systems.
[   18.561369] systemd[1]: Activating swap /swap.img...
[   18.571681] systemd[1]: Condition check resulted in Rebuild Hardware Database being skipped.
[   18.573581] systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.
[   18.577342] systemd[1]: Starting Load/Save Random Seed...
[   18.582678] systemd[1]: Starting Create System Users...
[   18.587364] systemd[1]: Finished Uncomplicated firewall.
[   18.620242] systemd[1]: Finished Load Kernel Modules.
[   18.623879] systemd[1]: Mounting FUSE Control File System...
[   18.627233] systemd[1]: Mounting Kernel Configuration File System...
[   18.628314] RPC: Registered named UNIX socket transport module.
[   18.628315] RPC: Registered udp transport module.
[   18.628316] RPC: Registered tcp transport module.
[   18.628317] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   18.637319] systemd[1]: Starting Apply Kernel Variables...
[   18.640185] systemd[1]: Mounted RPC Pipe File System.
[   18.642658] systemd[1]: Finished Load/Save Random Seed.
[   18.644676] systemd[1]: Mounted FUSE Control File System.
[   18.646613] systemd[1]: Mounted Kernel Configuration File System.
[   18.651044] systemd[1]: Finished Set the console keyboard layout.
[   18.654381] systemd[1]: Started Journal Service.
[   18.691347] systemd-journald[612]: Received client request to flush runtime journal.
[   18.769513] Adding 4603900k swap on /swap.img.  Priority:-2 extents:7 across:5169148k FS
[   19.331561] ACPI Error: No handler for Region [SYSI] (000000004f7ece08) [IPMI] (20190816/evregion-129)
[   19.332505] ACPI Error: Region IPMI (ID=7) has no handler (20190816/exfldio-261)
[   19.333951] No Local Variables are initialized for Method [_GHL]
[   19.333952] No Arguments are initialized for method [_GHL]
[   19.333957] ACPI Error: Aborting method \_SB.PMI0._GHL due to previous error (AE_NOT_EXIST) (20190816/psparse-529)
[   19.333991] IPMI message handler: version 39.2
[   19.335402] ACPI Error: Aborting method \_SB.PMI0._PMC due to previous error (AE_NOT_EXIST) (20190816/psparse-529)
[   19.336781] ACPI Error: AE_NOT_EXIST, Evaluating _PMC (20190816/power_meter-743)
[   19.349587] ipmi device interface
[   19.367018] ipmi_si: IPMI System Interface driver
[   19.367047] ipmi_si dmi-ipmi-si.0: ipmi_platform: probing via SMBIOS
[   19.367051] ipmi_platform: ipmi_si: SMBIOS: io 0xca8 regsize 1 spacing 4 irq 10
[   19.367052] ipmi_si: Adding SMBIOS-specified kcs state machine
[   19.368342] ipmi_si: Trying SMBIOS-specified kcs state machine at i/o address 0xca8, slave address 0x20, irq 10
[   19.398621] mei_me 0000:00:16.0: Device doesn't have valid ME Interface
[   19.431776] RAPL PMU: API unit is 2^-32 Joules, 3 fixed counters, 163840 ms ovfl timer
[   19.431779] RAPL PMU: hw unit of domain pp0-core 2^-16 Joules
[   19.431780] RAPL PMU: hw unit of domain package 2^-16 Joules
[   19.431781] RAPL PMU: hw unit of domain dram 2^-16 Joules
[   19.482600] dcdbas dcdbas: Dell Systems Management Base Driver (version 5.6.0-3.3)
[   19.748128] EDAC sbridge: Seeking for: PCI ID 8086:3ca0
[   19.748149] EDAC sbridge: Seeking for: PCI ID 8086:3ca0
[   19.748163] EDAC sbridge: Seeking for: PCI ID 8086:3ca0
[   19.748170] EDAC sbridge: Seeking for: PCI ID 8086:3ca8
[   19.748176] EDAC sbridge: Seeking for: PCI ID 8086:3ca8
[   19.748181] EDAC sbridge: Seeking for: PCI ID 8086:3ca8
[   19.748183] EDAC sbridge: Seeking for: PCI ID 8086:3c71
[   19.748189] EDAC sbridge: Seeking for: PCI ID 8086:3c71
[   19.748194] EDAC sbridge: Seeking for: PCI ID 8086:3c71
[   19.748196] EDAC sbridge: Seeking for: PCI ID 8086:3caa
[   19.748201] EDAC sbridge: Seeking for: PCI ID 8086:3caa
[   19.748207] EDAC sbridge: Seeking for: PCI ID 8086:3caa
[   19.748209] EDAC sbridge: Seeking for: PCI ID 8086:3cab
[   19.748214] EDAC sbridge: Seeking for: PCI ID 8086:3cab
[   19.748220] EDAC sbridge: Seeking for: PCI ID 8086:3cab
[   19.748221] EDAC sbridge: Seeking for: PCI ID 8086:3cac
[   19.748227] EDAC sbridge: Seeking for: PCI ID 8086:3cac
[   19.748232] EDAC sbridge: Seeking for: PCI ID 8086:3cac
[   19.748234] EDAC sbridge: Seeking for: PCI ID 8086:3cad
[   19.748240] EDAC sbridge: Seeking for: PCI ID 8086:3cad
[   19.748245] EDAC sbridge: Seeking for: PCI ID 8086:3cad
[   19.748247] EDAC sbridge: Seeking for: PCI ID 8086:3cb8
[   19.748253] EDAC sbridge: Seeking for: PCI ID 8086:3cb8
[   19.748258] EDAC sbridge: Seeking for: PCI ID 8086:3cb8
[   19.748259] EDAC sbridge: Seeking for: PCI ID 8086:3cf4
[   19.748264] EDAC sbridge: Seeking for: PCI ID 8086:3cf4
[   19.748269] EDAC sbridge: Seeking for: PCI ID 8086:3cf4
[   19.748272] EDAC sbridge: Seeking for: PCI ID 8086:3cf6
[   19.748277] EDAC sbridge: Seeking for: PCI ID 8086:3cf6
[   19.748282] EDAC sbridge: Seeking for: PCI ID 8086:3cf6
[   19.748284] EDAC sbridge: Seeking for: PCI ID 8086:3cf5
[   19.748289] EDAC sbridge: Seeking for: PCI ID 8086:3cf5
[   19.748294] EDAC sbridge: Seeking for: PCI ID 8086:3cf5
[   19.748407] EDAC MC0: Giving out device to module sb_edac controller Sandy Bridge SrcID#0_Ha#0: DEV 0000:3f:0e.0 (INTERRUPT)
[   19.748497] EDAC MC1: Giving out device to module sb_edac controller Sandy Bridge SrcID#1_Ha#0: DEV 0000:7f:0e.0 (INTERRUPT)
[   19.748497] EDAC sbridge:  Ver: 1.1.2 
[   19.757510] ipmi_si dmi-ipmi-si.0: The BMC does not support setting the recv irq bit, compensating, but the BMC needs to be fixed.
[   19.803516] intel_rapl_common: Found RAPL domain package
[   19.803518] intel_rapl_common: Found RAPL domain core
[   19.803521] intel_rapl_common: Found RAPL domain dram
[   19.803633] intel_rapl_common: Found RAPL domain package
[   19.803635] intel_rapl_common: Found RAPL domain core
[   19.803637] intel_rapl_common: Found RAPL domain dram
[   19.837561] ipmi_si dmi-ipmi-si.0: Using irq 10
[   19.860458] ipmi_si dmi-ipmi-si.0: IPMI message handler: Found new BMC (man_id: 0x0002a2, prod_id: 0x0100, dev_id: 0x20)
[   19.910002] ipmi_si dmi-ipmi-si.0: IPMI kcs interface initialized
[   19.922626] ipmi_ssif: IPMI SSIF Interface driver
[   20.359278] alua: device handler registered
[   20.360909] emc: device handler registered
[   20.362987] rdac: device handler registered
[   20.524599] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
[   21.180166] audit: type=1400 audit(1637247834.336:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=953 comm="apparmor_parser"
[   21.180170] audit: type=1400 audit(1637247834.336:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=953 comm="apparmor_parser"
[   21.180298] audit: type=1400 audit(1637247834.336:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lsb_release" pid=951 comm="apparmor_parser"
[   21.189089] audit: type=1400 audit(1637247834.344:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=952 comm="apparmor_parser"
[   21.189093] audit: type=1400 audit(1637247834.344:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=952 comm="apparmor_parser"
[   21.189095] audit: type=1400 audit(1637247834.344:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=952 comm="apparmor_parser"
[   21.192822] audit: type=1400 audit(1637247834.348:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine" pid=949 comm="apparmor_parser"
[   21.192828] audit: type=1400 audit(1637247834.348:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=949 comm="apparmor_parser"
[   21.235393] audit: type=1400 audit(1637247834.392:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/tcpdump" pid=950 comm="apparmor_parser"
[   27.856231] tg3 0000:02:00.0 eno1: Link is up at 1000 Mbps, full duplex
[   27.856239] tg3 0000:02:00.0 eno1: Flow control is off for TX and off for RX
[   27.856240] tg3 0000:02:00.0 eno1: EEE is disabled
[   27.856259] IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
[   30.444477] FS-Cache: Loaded
[   30.592601] FS-Cache: Netfs 'nfs' registered for caching
[   30.763228] NFS: Registering the id_resolver key type
[   30.763238] Key type id_resolver registered
[   30.763239] Key type id_legacy registered
[   30.765615] FS-Cache: Duplicate cookie detected
[   30.766187] FS-Cache: O-cookie c=0000000032c1ef50 [p=00000000c8a4cb66 fl=222 nc=0 na=1]
[   30.766764] FS-Cache: O-cookie d=000000002d2526ad n=000000003ee77e52
[   30.767301] FS-Cache: O-key=[16] '040000000100000002000801863c4414'
[   30.767843] FS-Cache: N-cookie c=000000006d4b93e2 [p=00000000c8a4cb66 fl=2 nc=0 na=1]
[   30.768444] FS-Cache: N-cookie d=000000002d2526ad n=0000000031b32c72
[   30.769014] FS-Cache: N-key=[16] '040000000100000002000801863c4414'
[   35.065351] new mount options do not match the existing superblock, will be ignored
[   36.342196] NET: Registered protocol family 40
[   38.594964] bpfilter: Loaded bpfilter_umh pid 1529
[   38.595568] Started bpfilter
[   39.083823] spl: loading out-of-tree module taints kernel.
[   39.108934] znvpair: module license 'CDDL' taints kernel.
[   39.108936] Disabling lock debugging due to kernel taint
[   40.964519] ZFS: Loaded module v0.8.3-1ubuntu12.12, ZFS pool version 5000, ZFS filesystem version 5
[   41.164518] BTRFS info (device dm-1): flagging fs with big metadata feature
[   41.164526] BTRFS info (device dm-1): use lzo compression, level 0
[   41.164530] BTRFS info (device dm-1): disk space caching is enabled
[   41.164533] BTRFS info (device dm-1): has skinny extents
[   61.287680] BTRFS info (device dm-1): start tree-log replay
[   61.634926] BTRFS warning (device dm-1): block group 1881226084352 has wrong amount of free space
[   61.634930] BTRFS warning (device dm-1): failed to load free space cache for block group 1881226084352, rebuilding it now
[   72.885426] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   72.912950] lxdfan0: port 1(lxdfan0-mtu) entered blocking state
[   72.912958] lxdfan0: port 1(lxdfan0-mtu) entered disabled state
[   72.913162] device lxdfan0-mtu entered promiscuous mode
[   72.938525] lxdfan0: port 1(lxdfan0-mtu) entered blocking state
[   72.938530] lxdfan0: port 1(lxdfan0-mtu) entered forwarding state
[   73.065033] lxdfan0: port 2(lxdfan0-fan) entered blocking state
[   73.065038] lxdfan0: port 2(lxdfan0-fan) entered disabled state
[   73.065193] device lxdfan0-fan entered promiscuous mode
[   73.072605] lxdfan0: port 2(lxdfan0-fan) entered blocking state
[   73.072611] lxdfan0: port 2(lxdfan0-fan) entered forwarding state
[   73.205125] kauditd_printk_skb: 21 callbacks suppressed
[   73.205127] audit: type=1400 audit(1637247886.089:32): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_dnsmasq-lxdfan0_</var/snap/lxd/common/lxd>" pid=1682 comm="apparmor_parser"
[   73.228862] audit: type=1400 audit(1637247886.113:33): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd_forkdns-lxdfan0_</var/snap/lxd/common/lxd>" pid=1684 comm="apparmor_parser"
[   73.942151] IPv6: ADDRCONF(NETDEV_CHANGE): lxdfan0: link becomes ready
[   75.604368] lxdfan0: port 3(vethf31ab1b1) entered blocking state
[   75.604372] lxdfan0: port 3(vethf31ab1b1) entered disabled state
[   75.604489] device vethf31ab1b1 entered promiscuous mode
[   75.846345] audit: type=1400 audit(1637247888.709:34): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-nocs2021-old_</var/snap/lxd/common/lxd>" pid=1790 comm="apparmor_parser"
[   75.889917] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
[   75.964851] phys6G92fK: renamed from veth5a4359cf
[   76.005619] eth0: renamed from phys6G92fK
[   76.034329] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   76.034432] lxdfan0: port 3(vethf31ab1b1) entered blocking state
[   76.034435] lxdfan0: port 3(vethf31ab1b1) entered forwarding state
[   86.694285] audit: type=1400 audit(1637247899.521:35): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="nvidia_modprobe" pid=2050 comm="apparmor_parser"
[   86.694301] audit: type=1400 audit(1637247899.521:36): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="nvidia_modprobe//kmod" pid=2050 comm="apparmor_parser"
[   86.694880] audit: type=1400 audit(1637247899.521:37): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="/usr/bin/man" pid=2052 comm="apparmor_parser"
[   86.694890] audit: type=1400 audit(1637247899.521:38): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="man_filter" pid=2052 comm="apparmor_parser"
[   86.694909] audit: type=1400 audit(1637247899.521:39): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="man_groff" pid=2052 comm="apparmor_parser"
[   86.702345] audit: type=1400 audit(1637247899.529:40): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/snapd/snap-confine" pid=2055 comm="apparmor_parser"
[   86.702359] audit: type=1400 audit(1637247899.529:41): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=2055 comm="apparmor_parser"
[   86.702433] audit: type=1400 audit(1637247899.529:42): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="lsb_release" pid=2049 comm="apparmor_parser"
[   86.719776] audit: type=1400 audit(1637247899.549:43): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=2051 comm="apparmor_parser"
[   86.719788] audit: type=1400 audit(1637247899.549:44): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=2051 comm="apparmor_parser"
[  112.498685] overlayfs: unrecognized mount option "userxattr" or missing value
[  114.163891] kauditd_printk_skb: 20 callbacks suppressed
[  114.163895] audit: type=1400 audit(1637247926.985:65): apparmor="STATUS" operation="profile_load" label="lxd-nocs2021-old_</var/snap/lxd/common/lxd>//&:lxd-nocs2021-old_<var-snap-lxd-common-lxd>:unconfined" name="docker-default" pid=2419 comm="apparmor_parser"
[  244.073428] INFO: task btrfs-transacti:1625 blocked for more than 120 seconds.
[  244.073542]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  244.073622] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  244.073723] btrfs-transacti D    0  1625      2 0x80004000
[  244.073731] Call Trace:
[  244.073756]  __schedule+0x2e3/0x740
[  244.073763]  schedule+0x42/0xb0
[  244.073831]  wait_for_commit+0x5e/0x90 [btrfs]
[  244.073840]  ? wait_woken+0x80/0x80
[  244.073872]  btrfs_commit_transaction+0x7f3/0x970 [btrfs]
[  244.073949]  ? start_transaction+0xb7/0x510 [btrfs]
[  244.073957]  ? __next_timer_interrupt+0x60/0xe0
[  244.073987]  transaction_kthread+0x15b/0x180 [btrfs]
[  244.073994]  kthread+0x104/0x140
[  244.074022]  ? btrfs_cleanup_transaction+0x530/0x530 [btrfs]
[  244.074026]  ? kthread_park+0x90/0x90
[  244.074031]  ret_from_fork+0x35/0x40
[  244.074054] INFO: task snapd:2369 blocked for more than 120 seconds.
[  244.074115]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  244.074176] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  244.074236] snapd           D    0  2369   1791 0x00004320
[  244.074248] Call Trace:
[  244.074254]  __schedule+0x2e3/0x740
[  244.074258]  schedule+0x42/0xb0
[  244.074291]  wait_for_commit+0x5e/0x90 [btrfs]
[  244.074295]  ? wait_woken+0x80/0x80
[  244.074324]  btrfs_commit_transaction+0x7f3/0x970 [btrfs]
[  244.074329]  ? rwsem_wake.isra.0+0x75/0xa0
[  244.074363]  btrfs_sync_file+0x3b9/0x400 [btrfs]
[  244.074371]  vfs_fsync_range+0x49/0x80
[  244.074376]  ? __fget_light+0x57/0x70
[  244.074380]  do_fsync+0x3d/0x70
[  244.074384]  __x64_sys_fsync+0x14/0x20
[  244.074395]  do_syscall_64+0x57/0x190
[  244.074398]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  244.074402] RIP: 0033:0x5636448ff1d0
[  244.074412] Code: Bad RIP value.
[  244.074413] RSP: 002b:000000c42050d7b0 EFLAGS: 00000202 ORIG_RAX: 000000000000004a
[  244.074417] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00005636448ff1d0
[  244.074418] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000008
[  244.074420] RBP: 000000c42050d7f8 R08: 0000000000000000 R09: 0000000000000000
[  244.074422] R10: 0000000000000000 R11: 0000000000000202 R12: ffffffffffffffff
[  244.074423] R13: 0000000000000015 R14: 0000000000000014 R15: 0000000000000100
[  244.074432] INFO: task containerd:2382 blocked for more than 120 seconds.
[  244.074495]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  244.074548] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  244.074615] containerd      D    0  2382   1791 0x00004320
[  244.074618] Call Trace:
[  244.074624]  __schedule+0x2e3/0x740
[  244.074628]  schedule+0x42/0xb0
[  244.074661]  wait_for_commit+0x5e/0x90 [btrfs]
[  244.074665]  ? wait_woken+0x80/0x80
[  244.074694]  btrfs_commit_transaction+0x7f3/0x970 [btrfs]
[  244.074697]  ? dput+0xcd/0x2f0
[  244.074736]  ? btrfs_log_dentry_safe+0x61/0x80 [btrfs]
[  244.074769]  btrfs_sync_file+0x3b9/0x400 [btrfs]
[  244.074775]  vfs_fsync_range+0x49/0x80
[  244.074779]  ? __fget_light+0x57/0x70
[  244.074783]  do_fsync+0x3d/0x70
[  244.074787]  __x64_sys_fdatasync+0x17/0x20
[  244.074791]  do_syscall_64+0x57/0x190
[  244.074794]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  244.074796] RIP: 0033:0x5649e9f3af30
[  244.074801] Code: Bad RIP value.
[  244.074802] RSP: 002b:000000c0001a9550 EFLAGS: 00000206 ORIG_RAX: 000000000000004b
[  244.074805] RAX: ffffffffffffffda RBX: 000000c000053400 RCX: 00005649e9f3af30
[  244.074807] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000003
[  244.074808] RBP: 000000c0001a9590 R08: 0000000000000000 R09: 0000000000000000
[  244.074810] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000018
[  244.074811] R13: 0000000000000000 R14: 00005649eb247f9c R15: 0000000000000000
[  244.074822] INFO: task dockerd:2413 blocked for more than 120 seconds.
[  244.074874]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  244.074927] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  244.074993] dockerd         D    0  2413   1791 0x00004320
[  244.074996] Call Trace:
[  244.075002]  __schedule+0x2e3/0x740
[  244.075006]  schedule+0x42/0xb0
[  244.075039]  wait_current_trans+0xbd/0x100 [btrfs]
[  244.075050]  ? wait_woken+0x80/0x80
[  244.075079]  start_transaction+0x476/0x510 [btrfs]
[  244.075108]  btrfs_start_transaction+0x1e/0x20 [btrfs]
[  244.075139]  btrfs_sync_file+0x274/0x400 [btrfs]
[  244.075145]  vfs_fsync_range+0x49/0x80
[  244.075149]  ? __fget_light+0x57/0x70
[  244.075152]  do_fsync+0x3d/0x70
[  244.075156]  __x64_sys_fdatasync+0x17/0x20
[  244.075160]  do_syscall_64+0x57/0x190
[  244.075163]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  244.075165] RIP: 0033:0x560931ffbed0
[  244.075170] Code: Bad RIP value.
[  244.075171] RSP: 002b:000000c000f46bc8 EFLAGS: 00000216 ORIG_RAX: 000000000000004b
[  244.075173] RAX: ffffffffffffffda RBX: 000000c00005c000 RCX: 0000560931ffbed0
[  244.075175] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 000000000000000a
[  244.075176] RBP: 000000c000f46c08 R08: 0000000000000000 R09: 0000000000000000
[  244.075178] R10: 0000000000000000 R11: 0000000000000216 R12: 0000000000000018
[  244.075179] R13: 0000000000000000 R14: 0000560933fd2406 R15: 0000000000000000
[  364.904223] INFO: task lxd:1482 blocked for more than 120 seconds.
[  364.904290]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.904344] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.904406] lxd             D    0  1482   1277 0x00000000
[  364.904411] Call Trace:
[  364.904431]  __schedule+0x2e3/0x740
[  364.904436]  schedule+0x42/0xb0
[  364.904444]  d_alloc_parallel+0x3bb/0x4b0
[  364.904451]  ? wake_up_q+0x70/0x70
[  364.904456]  __lookup_slow+0x69/0x160
[  364.904460]  lookup_slow+0x3b/0x60
[  364.904463]  walk_component+0x1da/0x360
[  364.904466]  ? link_path_walk.part.0+0x6d/0x550
[  364.904470]  path_lookupat.isra.0+0x80/0x230
[  364.904475]  filename_lookup+0xae/0x170
[  364.904483]  ? __check_object_size+0x13f/0x150
[  364.904487]  ? strncpy_from_user+0x4c/0x150
[  364.904492]  user_path_at_empty+0x3a/0x50
[  364.904497]  vfs_statx+0x7d/0xe0
[  364.904502]  __do_sys_newfstatat+0x36/0x70
[  364.904507]  __x64_sys_newfstatat+0x1e/0x20
[  364.904514]  do_syscall_64+0x57/0x190
[  364.904520]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  364.904525] RIP: 0033:0x48ddca
[  364.904534] Code: Bad RIP value.
[  364.904536] RSP: 002b:000000c000a68ab8 EFLAGS: 00000212 ORIG_RAX: 0000000000000106
[  364.904539] RAX: ffffffffffffffda RBX: 000000c000057000 RCX: 000000000048ddca
[  364.904541] RDX: 000000c000d92448 RSI: 000000c000d8e7e0 RDI: ffffffffffffff9c
[  364.904543] RBP: 000000c000a68b48 R08: 0000000000000000 R09: 0000000000000000
[  364.904545] R10: 0000000000000100 R11: 0000000000000212 R12: 000000c000d8e7e0
[  364.904547] R13: 0000000000000001 R14: 000000c000ba5a00 R15: ffffffffffffffff
[  364.904553] INFO: task lxd:1517 blocked for more than 120 seconds.
[  364.904604]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.904656] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.904715] lxd             D    0  1517   1277 0x00000000
[  364.904718] Call Trace:
[  364.904724]  __schedule+0x2e3/0x740
[  364.904729]  schedule+0x42/0xb0
[  364.904788]  btrfs_tree_read_lock+0x89/0x1c0 [btrfs]
[  364.904794]  ? wait_woken+0x80/0x80
[  364.904822]  btrfs_search_slot+0x6aa/0x980 [btrfs]
[  364.904848]  ? generic_bin_search.constprop.0+0xde/0x180 [btrfs]
[  364.904878]  btrfs_lookup_inode+0x3e/0xc0 [btrfs]
[  364.904910]  btrfs_read_locked_inode+0x52e/0x5f0 [btrfs]
[  364.904914]  ? inode_insert5+0x12a/0x1b0
[  364.904919]  ? iget5_locked+0x78/0x90
[  364.904950]  btrfs_iget_path+0x97/0xf0 [btrfs]
[  364.904981]  btrfs_lookup_dentry+0x477/0x5a0 [btrfs]
[  364.905011]  btrfs_lookup+0x13/0x30 [btrfs]
[  364.905015]  __lookup_slow+0x92/0x160
[  364.905018]  lookup_slow+0x3b/0x60
[  364.905022]  walk_component+0x1da/0x360
[  364.905025]  ? link_path_walk.part.0+0x6d/0x550
[  364.905028]  path_lookupat.isra.0+0x80/0x230
[  364.905032]  filename_lookup+0xae/0x170
[  364.905037]  ? __check_object_size+0x13f/0x150
[  364.905039]  ? strncpy_from_user+0x4c/0x150
[  364.905044]  user_path_at_empty+0x3a/0x50
[  364.905047]  vfs_statx+0x7d/0xe0
[  364.905052]  __do_sys_newfstatat+0x36/0x70
[  364.905057]  __x64_sys_newfstatat+0x1e/0x20
[  364.905061]  do_syscall_64+0x57/0x190
[  364.905064]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  364.905066] RIP: 0033:0x48ddca
[  364.905071] Code: Bad RIP value.
[  364.905072] RSP: 002b:000000c000f98ab8 EFLAGS: 00000212 ORIG_RAX: 0000000000000106
[  364.905075] RAX: ffffffffffffffda RBX: 000000c000054800 RCX: 000000000048ddca
[  364.905077] RDX: 000000c000d6c448 RSI: 000000c000d5eb60 RDI: ffffffffffffff9c
[  364.905078] RBP: 000000c000f98b48 R08: 0000000000000000 R09: 0000000000000000
[  364.905080] R10: 0000000000000100 R11: 0000000000000212 R12: 000000c000d5eb60
[  364.905081] R13: 0000000000000001 R14: 000000c001698340 R15: ffffffffffffffff
[  364.905096] INFO: task btrfs-transacti:1625 blocked for more than 241 seconds.
[  364.905153]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.905205] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.905264] btrfs-transacti D    0  1625      2 0x80004000
[  364.905267] Call Trace:
[  364.905272]  __schedule+0x2e3/0x740
[  364.905277]  schedule+0x42/0xb0
[  364.905311]  wait_for_commit+0x5e/0x90 [btrfs]
[  364.905315]  ? wait_woken+0x80/0x80
[  364.905345]  btrfs_commit_transaction+0x7f3/0x970 [btrfs]
[  364.905374]  ? start_transaction+0xb7/0x510 [btrfs]
[  364.905379]  ? __next_timer_interrupt+0x60/0xe0
[  364.905407]  transaction_kthread+0x15b/0x180 [btrfs]
[  364.905412]  kthread+0x104/0x140
[  364.905439]  ? btrfs_cleanup_transaction+0x530/0x530 [btrfs]
[  364.905443]  ? kthread_park+0x90/0x90
[  364.905446]  ret_from_fork+0x35/0x40
[  364.905453] INFO: task systemd:2457 blocked for more than 120 seconds.
[  364.905506]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.905558] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.905618] systemd         D    0  2457   1770 0x00000320
[  364.905620] Call Trace:
[  364.905625]  __schedule+0x2e3/0x740
[  364.905630]  schedule+0x42/0xb0
[  364.905661]  wait_current_trans+0xbd/0x100 [btrfs]
[  364.905665]  ? wait_woken+0x80/0x80
[  364.905694]  start_transaction+0x476/0x510 [btrfs]
[  364.905723]  btrfs_start_transaction_fallback_global_rsv+0x1b/0x20 [btrfs]
[  364.905752]  btrfs_rmdir+0x64/0x190 [btrfs]
[  364.905756]  vfs_rmdir+0x86/0x1a0
[  364.905760]  do_rmdir+0x18c/0x1c0
[  364.905765]  ? syscall_trace_enter+0x134/0x2b0
[  364.905769]  __x64_sys_unlinkat+0x45/0x60
[  364.905773]  do_syscall_64+0x57/0x190
[  364.905776]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  364.905778] RIP: 0033:0x7f844a25ce6b
[  364.905782] Code: Bad RIP value.
[  364.905784] RSP: 002b:00007f8448bc6a78 EFLAGS: 00000246 ORIG_RAX: 0000000000000107
[  364.905786] RAX: ffffffffffffffda RBX: 00007f8448bc7680 RCX: 00007f844a25ce6b
[  364.905788] RDX: 0000000000000200 RSI: 00007f8444000bd3 RDI: 0000000000000015
[  364.905790] RBP: 0000000000000015 R08: 0000000000000000 R09: 000000000000007c
[  364.905791] R10: 00007f8448bc68a4 R11: 0000000000000246 R12: 00007f8444000b60
[  364.905793] R13: 0000000000000000 R14: 0000000000000000 R15: 00007f8444000bd3
[  364.905797] INFO: task systemd:2458 blocked for more than 120 seconds.
[  364.905849]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.905901] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.905960] systemd         D    0  2458   1770 0x00000320
[  364.905963] Call Trace:
[  364.905969]  __schedule+0x2e3/0x740
[  364.905973]  schedule+0x42/0xb0
[  364.906005]  wait_current_trans+0xbd/0x100 [btrfs]
[  364.906009]  ? wait_woken+0x80/0x80
[  364.906037]  start_transaction+0x476/0x510 [btrfs]
[  364.906066]  btrfs_start_transaction_fallback_global_rsv+0x1b/0x20 [btrfs]
[  364.906095]  btrfs_rmdir+0x64/0x190 [btrfs]
[  364.906099]  vfs_rmdir+0x86/0x1a0
[  364.906103]  do_rmdir+0x18c/0x1c0
[  364.906107]  ? syscall_trace_enter+0x134/0x2b0
[  364.906111]  __x64_sys_unlinkat+0x45/0x60
[  364.906114]  do_syscall_64+0x57/0x190
[  364.906117]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  364.906119] RIP: 0033:0x7f844a25ce6b
[  364.906124] Code: Bad RIP value.
[  364.906125] RSP: 002b:00007f84493c7a78 EFLAGS: 00000246 ORIG_RAX: 0000000000000107
[  364.906127] RAX: ffffffffffffffda RBX: 00007f84493c8680 RCX: 00007f844a25ce6b
[  364.906129] RDX: 0000000000000200 RSI: 00007f843c000bd3 RDI: 0000000000000017
[  364.906130] RBP: 0000000000000017 R08: 0000000000000000 R09: 000000000000007c
[  364.906132] R10: 00007f84493c78a4 R11: 0000000000000246 R12: 00007f843c000b60
[  364.906134] R13: 0000000000000000 R14: 0000000000000000 R15: 00007f843c000bd3
[  364.906139] INFO: task systemd-journal:1874 blocked for more than 120 seconds.
[  364.906195]       Tainted: P           O      5.4.0-90-generic #101-Ubuntu
[  364.906248] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  364.906309] systemd-journal D    0  1874   1791 0x00000320
[  364.906311] Call Trace:
[  364.906317]  __schedule+0x2e3/0x740
[  364.906321]  schedule+0x42/0xb0
[  364.906353]  wait_current_trans+0xbd/0x100 [btrfs]
[  364.906357]  ? wait_woken+0x80/0x80
[  364.906385]  start_transaction+0x476/0x510 [btrfs]
[  364.906413]  btrfs_start_transaction+0x1e/0x20 [btrfs]
[  364.906442]  btrfs_setsize.isra.0+0x19f/0x4c0 [btrfs]
[  364.906447]  ? setattr_prepare+0x75/0x1f0
[  364.906476]  btrfs_setattr+0x66/0xf0 [btrfs]
[  364.906480]  notify_change+0x357/0x4e0
[  364.906485]  do_truncate+0x78/0xd0
[  364.906489]  do_sys_ftruncate+0x14a/0x1c0
[  364.906493]  __x64_sys_ftruncate+0x1b/0x20
[  364.906497]  do_syscall_64+0x57/0x190
[  364.906500]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  364.906502] RIP: 0033:0x7f120c373e5b
[  364.906506] Code: Bad RIP value.
[  364.906507] RSP: 002b:00007ffc48dbaf08 EFLAGS: 00000202 ORIG_RAX: 000000000000004d
[  364.906509] RAX: ffffffffffffffda RBX: 00007ffc48dbaf40 RCX: 00007f120c373e5b
[  364.906511] RDX: 000055855cfec350 RSI: 0000000000800000 RDI: 0000000000000015
[  364.906513] RBP: 000055855cfec5a0 R08: 0000000000000001 R09: 000055855cfec624
[  364.906514] R10: 0000000000000000 R11: 0000000000000202 R12: 00007ffc48dbaf38
[  364.906515] R13: 0000000000000003 R14: 0000000000000000 R15: 0000000000000000
[ 2010.690672] perf: interrupt took too long (2522 > 2500), lowering kernel.perf_event_max_sample_rate to 79250
[ 2649.558344] perf: interrupt took too long (3166 > 3152), lowering kernel.perf_event_max_sample_rate to 63000
[ 4190.842884] perf: interrupt took too long (3967 > 3957), lowering kernel.perf_event_max_sample_rate to 50250
```
</details>

 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

 - `ps auxH | grep lxd`
<details>

```
$ ps auxH | grep lxd
root        1277  0.0  0.0   2616   128 ?        Ss   15:04   0:00 /bin/sh /snap/lxd/21902/commands/daemon.start
root        1434  0.0  0.0 298880   964 ?        Sl   15:04   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root        1434  0.0  0.0 298880   964 ?        Sl   15:04   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root        1434  0.0  0.0 298880   964 ?        Sl   15:04   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root        1434  0.0  0.0 298880   964 ?        Sl   15:05   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root        1434  0.0  0.0 298880   964 ?        Sl   15:05   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.3  0.1 11126560 186104 ?     Sl   15:04   1:24 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   15:04   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:40 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:04   0:49 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:04   0:35 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.9  0.1 11126560 186104 ?     Dl   15:04   0:58 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:04   0:53 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:37 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.1  0.1 11126560 186104 ?     Dl   15:04   0:11 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:04   0:44 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:04   0:20 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:40 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:04   0:33 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:41 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Sl   15:04   0:50 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:04   0:32 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:04   0:35 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:42 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   15:04   0:12 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   15:04   0:25 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:40 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:04   0:20 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   15:04   1:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:04   0:51 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:04   0:44 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   15:04   0:26 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Sl   15:04   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:04   0:46 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:04   0:47 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:04   0:39 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:06   0:53 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:08   0:52 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:09   0:44 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:09   0:43 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:10   0:50 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.2  0.1 11126560 186104 ?     Sl   15:12   1:13 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:12   0:32 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   15:14   0:22 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:14   0:45 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:16   0:34 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:16   0:45 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:17   0:19 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:17   0:47 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   15:20   0:55 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:21   0:29 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   15:21   0:24 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.1  0.1 11126560 186104 ?     Dl   15:22   0:06 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:24   0:34 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   15:25   0:49 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:26   0:24 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.4  0.1 11126560 186104 ?     Dl   15:26   1:08 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:28   0:34 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Sl   15:29   0:41 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:29   0:32 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.1  0.1 11126560 186104 ?     Dl   15:30   0:06 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.1  0.1 11126560 186104 ?     Dl   15:32   0:07 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Sl   15:32   0:39 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   15:34   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:34   0:26 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:34   0:34 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:36   0:16 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:37   0:29 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   15:38   0:10 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   15:39   0:41 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:41   0:12 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   15:41   0:29 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Sl   15:43   0:28 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Sl   15:44   0:24 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:45   0:24 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.9  0.1 11126560 186104 ?     Dl   15:46   0:33 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:46   0:22 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   15:47   0:08 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   15:48   0:11 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.1  0.1 11126560 186104 ?     Sl   15:50   0:38 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   15:50   0:28 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.5  0.1 11126560 186104 ?     Dl   15:51   0:18 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Sl   15:52   0:35 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   15:54   0:21 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Sl   15:55   0:14 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   15:56   0:13 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Sl   15:56   0:19 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   15:57   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   15:58   0:01 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   16:00   0:28 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.2  0.1 11126560 186104 ?     Dl   16:00   0:35 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:01   0:10 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:02   0:10 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.3  0.1 11126560 186104 ?     Dl   16:03   0:35 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   16:05   0:08 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.5  0.1 11126560 186104 ?     Sl   16:05   0:37 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   16:06   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.1  0.1 11126560 186104 ?     Dl   16:08   0:03 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   16:08   0:20 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   16:09   0:15 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   16:10   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Sl   16:11   0:15 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:12   0:08 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.9  0.1 11126560 186104 ?     Dl   16:14   0:18 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  2.6  0.1 11126560 186104 ?     Sl   16:14   0:51 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   16:16   0:19 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.4  0.1 11126560 186104 ?     Sl   16:16   0:26 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.8  0.1 11126560 186104 ?     Dl   16:18   0:15 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:18   0:07 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Sl   16:19   0:17 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Dl   16:20   0:16 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.3  0.1 11126560 186104 ?     Sl   16:22   0:19 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   16:22   0:01 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Dl   16:23   0:10 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   16:25   0:04 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   16:25   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.9  0.1 11126560 186104 ?     Dl   16:26   0:10 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:27   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   16:29   0:03 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.2  0.1 11126560 186104 ?     Dl   16:30   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.2  0.1 11126560 186104 ?     Dl   16:30   0:12 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.6  0.1 11126560 186104 ?     Dl   16:32   0:06 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Dl   16:33   0:03 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.5  0.1 11126560 186104 ?     Dl   16:33   0:13 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Sl   16:33   0:06 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Sl   16:34   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.5  0.1 11126560 186104 ?     Sl   16:35   0:11 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.2  0.1 11126560 186104 ?     Sl   16:36   0:08 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  2.1  0.1 11126560 186104 ?     Sl   16:37   0:11 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.3  0.1 11126560 186104 ?     Dl   16:37   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.7  0.1 11126560 186104 ?     Rl   16:39   0:03 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.1  0.1 11126560 186104 ?     Sl   16:39   0:05 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.0  0.1 11126560 186104 ?     Dl   16:39   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Sl   16:42   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  1.0  0.1 11126560 186104 ?     Sl   16:43   0:02 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  2.2  0.1 11126560 186104 ?     Sl   16:43   0:04 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root        1467  0.4  0.1 11126560 186104 ?     Sl   16:46   0:00 lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
lxd         1686  0.0  0.0   7204  1340 ?        Ss   15:04   0:00 dnsmasq --keep-in-foreground --strict-order --bind-interfaces --except-interface=lo --pid-file= --no-ping --interface=lxdfan0 --dhcp-rapid-commit --quiet-dhcp --quiet-dhcp6 --quiet-ra --listen-address=240.196.0.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/snap/lxd/common/lxd/networks/lxdfan0/dnsmasq.leases --dhcp-hostsfile=/var/snap/lxd/common/lxd/networks/lxdfan0/dnsmasq.hosts --dhcp-range 240.196.0.2,240.196.0.254,1h -s lxd --interface-name _gateway.lxd,lxdfan0 -S /lxd/240.196.0.1#1053 --rev-server=240.0.0.0/8,240.196.0.1#1053 --conf-file=/var/snap/lxd/common/lxd/networks/lxdfan0/dnsmasq.raw -u lxd -g lxd
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:04   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:06   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:06   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:06   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:06   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:06   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:08   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:08   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:10   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:10   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:10   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:10   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:12   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:12   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:14   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:14   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:24   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
lxd         1687  0.0  0.0 2753316 13824 ?       Ssl  15:36   0:00 /snap/lxd/current/bin/lxd forkdns 240.196.0.1:1053 lxd lxdfan0
root        1770  0.0  0.0 1792688 14012 ?       Ss   15:04   0:00 [lxc monitor] /var/snap/lxd/common/lxd/containers nocs2021-old
1000000     2027  0.0  0.0   3508   192 ?        Ss   15:04   0:00 snapfuse /var/lib/snapd/snaps/lxd_21545.snap /snap/lxd/21545 -o ro,nodev,allow_other,suid
1000000     2029  0.0  0.0   3900  2060 ?        Ss   15:04   0:01 snapfuse /var/lib/snapd/snaps/lxd_21803.snap /snap/lxd/21803 -o ro,nodev,allow_other,suid
1000000     2668  0.0  0.0 1268216 17036 ?       D    15:09   0:00 lxd activateifneeded
```
</details>
 
 - `lxc operation list`

```
lxc operation list
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
|                  ID                  | TYPE |              DESCRIPTION               | STATUS  | CANCELABLE |       CREATED        | LOCATION |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 0c7d4bea-1cb2-4453-ace7-4392ce3103e1 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 19:41 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 0c14dedb-e34c-4745-9a7d-8cbb8f63b993 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 18:54 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 0db0cc9b-9488-4d4d-a1b6-df67527c795d | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 17:24 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 0e1e77c1-2d8a-40e8-bca7-7459d7977c73 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 16:59 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 0fa0967d-4a09-4036-ab8c-f74ef11b9883 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 14:53 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1aff389c-2b84-4d05-abf0-7290716848f5 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 14:24 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1b4c45eb-f2a8-424c-b0bb-378110a1c97a | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 20:11 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1b150ab9-a137-492d-abf3-9f9a4c54fdd7 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 16:44 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1bda3d26-50c5-48ce-b878-a922f939d65c | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 14:11 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1d587f49-c7bb-4412-b342-5fece5154698 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 16:57 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
| 1d814005-6177-46bf-906f-fd4a387f1cd3 | TASK | Cleaning up expired instance snapshots | RUNNING | NO         | 2021/11/17 15:41 UTC | server1  |
+--------------------------------------+------+----------------------------------------+---------+------------+----------------------+----------+
```

(truncated)

- `top`:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                           
   1624 root      20   0       0      0      0 R  99.7   0.0  33:53.35 btrfs-cleaner                                                                     
   1467 root      20   0 6428344 166676  35512 S  70.4   0.1  21:53.07 lxd                                                                               
   2944 root      20   0       0      0      0 I   3.3   0.0   0:10.65 kworker/u98:0-btrfs-endio-meta                                                    
   2938 root      20   0       0      0      0 I   2.7   0.0   0:03.20 kworker/u97:3-btrfs-endio-meta                                                    
   2868 root      20   0       0      0      0 I   2.0   0.0   0:18.01 kworker/u98:4-btrfs-endio-meta                                                    
    230 root      20   0       0      0      0 I   0.7   0.0   0:09.18 kworker/u97:1-events_power_efficient                                              
    220 root      20   0       0      0      0 I   0.3   0.0   0:01.01 kworker/0:3-events_freezable                                                      
    426 root       0 -20       0      0      0 I   0.3   0.0   0:00.87 kworker/2:1H-kblockd                                                              
    516 root       0 -20       0      0      0 I   0.3   0.0   0:00.79 kworker/20:1H-kblockd                                                             
    521 root       0 -20       0      0      0 I   0.3   0.0   0:00.74 kworker/14:1H-kblockd                                                             
    554 root       0 -20       0      0      0 I   0.3   0.0   0:00.50 kworker/8:1H-kblockd                                                              
    586 root       0 -20       0      0      0 I   0.3   0.0   0:02.41 kworker/23:1H-kblockd                                                             
    616 root       0 -20       0      0      0 I   0.3   0.0   0:02.74 kworker/1:1H-kblockd       
```

 - Snapshots of the container with docker inside:

<details><description>`lxc info container`</description>

```
...
+-------------------------+-----------------------+----------------------+----------+
|          NAME           |       TAKEN AT        |      EXPIRES AT      | STATEFUL |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-24-0     | 2020/11/24 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-25-0     | 2020/11/25 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-26-0     | 2020/11/26 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-27-0     | 2020/11/27 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-28-0     | 2020/11/28 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-29-0     | 2020/11/29 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-11-30-0     | 2020/11/30 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-01-0     | 2020/12/01 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-02-0     | 2020/12/02 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-03-0     | 2020/12/03 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-04-0     | 2020/12/04 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-05-0     | 2020/12/05 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-06-0     | 2020/12/06 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-07-0     | 2020/12/07 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-08-0     | 2020/12/08 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-09-0     | 2020/12/09 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-10-0     | 2020/12/10 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-11-0     | 2020/12/11 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-12-0     | 2020/12/12 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-13-0     | 2020/12/13 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-14-0     | 2020/12/14 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-15-0     | 2020/12/15 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-16-0     | 2020/12/16 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-17-0     | 2020/12/17 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-18-0     | 2020/12/18 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-19-0     | 2020/12/19 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-20-0     | 2020/12/20 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-21-0     | 2020/12/21 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-22-0     | 2020/12/22 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2020-12-23-0     | 2020/12/23 04:00 CET  |                      | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-07-0     | 2021/10/07 05:00 CEST | 2021/11/07 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-08-0     | 2021/10/08 05:00 CEST | 2021/11/08 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-09-0     | 2021/10/09 05:00 CEST | 2021/11/09 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-10-0     | 2021/10/10 05:00 CEST | 2021/11/10 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-11-0     | 2021/10/11 05:00 CEST | 2021/11/11 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-12-0     | 2021/10/12 05:00 CEST | 2021/11/12 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-13-0     | 2021/10/13 05:00 CEST | 2021/11/13 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-14-0     | 2021/10/14 05:00 CEST | 2021/11/14 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-15-0     | 2021/10/15 05:00 CEST | 2021/11/15 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-16-0     | 2021/10/16 05:00 CEST | 2021/11/16 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-17-0     | 2021/10/17 05:00 CEST | 2021/11/17 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-18-0     | 2021/10/18 05:00 CEST | 2021/11/18 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-19-0     | 2021/10/19 05:00 CEST | 2021/11/19 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-20-0     | 2021/10/20 05:00 CEST | 2021/11/20 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-22-0     | 2021/10/22 05:00 CEST | 2021/11/22 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-23-0     | 2021/10/23 05:00 CEST | 2021/11/23 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-24-0     | 2021/10/24 05:00 CEST | 2021/11/24 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-25-0     | 2021/10/25 05:00 CEST | 2021/11/25 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-26-0     | 2021/10/26 05:00 CEST | 2021/11/26 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-27-0     | 2021/10/27 05:00 CEST | 2021/11/27 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-28-0     | 2021/10/28 05:00 CEST | 2021/11/28 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-29-0     | 2021/10/29 05:00 CEST | 2021/11/29 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-30-0     | 2021/10/30 05:00 CEST | 2021/11/30 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-10-31-0     | 2021/10/31 04:00 CET  | 2021/12/01 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-01-0     | 2021/11/01 04:00 CET  | 2021/12/01 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-02-0     | 2021/11/02 04:00 CET  | 2021/12/02 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-03-0     | 2021/11/03 04:00 CET  | 2021/12/03 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-04-0     | 2021/11/04 04:00 CET  | 2021/12/04 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-05-0     | 2021/11/05 04:00 CET  | 2021/12/05 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-06-0     | 2021/11/06 04:00 CET  | 2021/12/06 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-08-0     | 2021/11/08 04:00 CET  | 2021/12/08 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-09-0     | 2021/11/09 04:00 CET  | 2021/12/09 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-10-0     | 2021/11/10 04:00 CET  | 2021/12/10 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-11-0     | 2021/11/11 04:00 CET  | 2021/12/11 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-12-0     | 2021/11/12 04:00 CET  | 2021/12/12 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-13-0     | 2021/11/13 04:00 CET  | 2021/12/13 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-14-0     | 2021/11/14 04:00 CET  | 2021/12/14 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-15-0     | 2021/11/15 04:00 CET  | 2021/12/15 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
| backup-2021-11-16-0     | 2021/11/16 04:00 CET  | 2021/12/16 04:00 CET | NO       |
+-------------------------+-----------------------+----------------------+----------+
```
</details>

- `lxc storage info local --target server1`

```
lxc storage info local --target server1
info:
  description: ""
  driver: btrfs
  name: local
  space used: 2.45TB
  total space: 5.98TB
```

# Further notes

It is well known that btrfs performs poorly with quota and subvolumes. Since this issue has been discovered, I have disabled quota, but btrfs still hangs in the kernell (even after multiple reboots). Currently `btrfs check` is running, which takes about a day. Next I will try to delete the docker subvolumes manually from the snapshots.

The issue was originally reported on the [lxd discussion forum](https://discuss.linuxcontainers.org/t/operations-cleaning-up-expired-instance-snapshots-are-piling-up/12667)

### PR DESCRIPTION
**Pull request by presztak**
Closes #9558

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
Thanks for this PR. I've re-read the original issue https://github.com/lxc/lxd/issues/9558 and from what I understand the original problem is that the prune expired snapshots tasks was creating more and more operations resulting in LXD attempting to remove the same snapshots over and over again (which was then being slow or blocked by the OS itself).

So I think part of the problem here is that when the operation created (and run) from inside `pruneExpiredContainerSnapshotsTask` is started, the task `f` returned does not wait for the operation to actually finish. This means if it takes over 1 minute to complete the task, then a new task is started again and again and again (causing the multiple operations we see  in the issue report).

The PR as it currently stands does not fix this.

I think if we add `op.WaitFinal(-1)` after `op.Run()` on line 598, then this will prevent another prune operation from starting until the last one has finished.

What do you think about this @stgraber ?

File: lxd/storage/backend_lxd.go [hunk 1]
```diff
@@ -3980,6 +3998,17 @@ func (b *lxdBackend) DeleteCustomVolumeSnapshot(projectName, volName string, op
 	// There's no need to pass config as it's not needed when deleting a volume snapshot.
 	vol := b.GetVolume(drivers.VolumeTypeCustom, contentType, volStorageName, nil)
 
+	// Get parent volume name.
+	parentVolName := strings.Split(volName, shared.SnapshotDelimiter)[0]
+
+	// Delete volume snapshot only if there is no lock acquired on parent.
+	lockName := drivers.OperationLockName("DeleteInstanceSnapshot", b.name, vol.Type(), contentType, parentVolName)
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go:4005]: This lock name should be `DeleteCustomVolumeSnapshot`

File: lxd/locking/lock.go [hunk 2]
```diff
@@ -16,47 +16,67 @@ var locksMutex sync.Mutex
...
+			return unlock
+		}
 		<-waitCh
 	}
 }
+
+// TryLock creates the lock for storage volume.
+// It's not blocking function. On success, it returns an unlock function which needs to be called to unlock the lock.
+// On failure, it returns nil.
+func TryLock(lockName string) UnlockFunc {
```
Comment (tomponline) [inline lxd/locking/lock.go:78]: We probably dont need these changes, see my other comments below.

**Review by tomponline — CHANGES_REQUESTED** [review]
See comments above.

**Comment by presztak** [comment]
@tomponline Yeah, I misunderstood this. Thanks for clarification.

So I've made PoC with removing snapshots in `pruneExpiredContainerSnapshotsTask` based on additional map with snapshots being removed and moved this PR to draft. If this approach is fine maybe we should do something similar for:

`pruneExpireCustomVolumeSnapshotsTask`
`autoCreateContainerSnapshotsTask`
`autoCreateCustomVolumeSnapshotsTask`

What do you think about it?

File: lxd/locking/lock.go (hunk 2 above)
Comment (presztak) [reply lxd/locking/lock.go]: I've removed this part.

File: lxd/storage/backend_lxd.go [hunk 3]
```diff
@@ -3980,6 +3998,17 @@ func (b *lxdBackend) DeleteCustomVolumeSnapshot(projectName, volName string, op
...
+	unlock := locking.TryLock(lockName)
```
[the remark this answers is not in the document]
Comment (presztak) [reply lxd/storage/backend_lxd.go]: I've implemented solution based on a map with snapshots which are in the process of being removed.

File: lxd/storage/backend_lxd.go [hunk 4]
```diff
@@ -2338,6 +2338,11 @@ func (b *lxdBackend) CreateInstanceSnapshot(inst instance.Instance, src instance
 	// There's no need to pass config as it's not needed when creating volume snapshots.
 	vol := b.GetVolume(volType, contentType, volStorageName, nil)
 
+	// Lock this operation to ensure that the only one snapshot is made at the time.
+	// Other operations will wait for this one to finish.
+	unlock := locking.Lock(drivers.OperationLockName("CreateInstanceSnapshot", b.name, volType, contentType, src.Name()))
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go:2343]: Please use `vol.Type()` here for consistency with the equivalent line for custom volumes.

File: lxd/instance.go [hunk 5]
```diff
@@ -577,6 +593,13 @@ func pruneExpiredContainerSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
...
 
 		opRun := func(op *operations.Operation) error {
+			defer func() {
+				snapshotsMutex.Lock()
+				for _, snapshot := range expiredSnapshots {
+					delete(snapshotsInProgress, snapshot.ID())
+				}
+				snapshotsMutex.Unlock()
+			}()
 			return pruneExpiredContainerSnapshots(ctx, d, expiredSnapshots)
```
Comment (tomponline) [inline lxd/instance.go:603]: I think it would be cleaner to add/remove/check entries in snapshotsInProgress from inside `pruneExpiredContainerSnapshots` rather than `pruneExpiredContainerSnapshotsTask`, as that is where the actual `snapshot.Delete()` function that we want to skip is called.

File: lxd/instance.go [hunk 6]
```diff
@@ -540,6 +541,9 @@ func autoCreateContainerSnapshots(ctx context.Context, d *Daemon, instances []in
 	return nil
 }
 
+var snapshotsInProgress = map[int]struct{}{}
```
Comment (tomponline) [inline lxd/instance.go:544]: Bit of a misleading name, as the snapshots are being removed, not created.
How about `snapshotPruneRunning`, and then the associated mutex can be called `snapshotPruneRunningMu` to show its association to `snapshotPruneRunning`

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks, this is going in the right direction. There's a couple of small changes, and then it'll be good to merge. Thanks

**Comment by tomponline** [comment]
> @tomponline Great, thanks!
> 
> What do you think about implementing same solution (with map) also for this tasks:
> 
> `pruneExpireCustomVolumeSnapshotsTask` `autoCreateContainerSnapshotsTask` `autoCreateCustomVolumeSnapshotsTask`
> 
> as this ones are also responsible for creating/pruning snapshots. Then we could remove solution with `locking` from `CreateInstanceSnapshot` and have one consistent solution in all places.

Its an attractive idea for sure. However based on @stgraber comment:

> for taking snapshots, I don't think we should skip, but for the expiry we definitely can skip as they'll be handled later on.

https://github.com/lxc/lxd/issues/9558#issuecomment-975889261

We wouldn't want to skip if the lock was present on creation.
Also it is possible for snapshots to be taken manually so if the lock was only in the scheduled code path it wouldn't protect manual snapshot creation requests.

Instead if we add the locking to the storage backend, then the scheduler will attempt to create/remove the first time, and if the create is blocked, the next time the scheduler runs it too will be blocked until the snapshot is created. But for the pruning code path, if there is already a prune in progress it will just skip.

**Comment by presztak** [comment]
@tomponline oh, that's right. Forgot about this @stgraber comment.

but what about `pruneExpireCustomVolumeSnapshotsTask`?

**Comment by tomponline** [comment]
> @tomponline oh, that's right. Forgot about this @stgraber comment.
> 
> but what about `pruneExpireCustomVolumeSnapshotsTask`?

Yes that should have skip locking the same as the other prune task.

File: lxd/storage/backend_lxd.go (hunk 4 above)
Comment (presztak) [reply lxd/storage/backend_lxd.go]: Fixed

**Comment by presztak** [comment]
@tomponline

I've modified last solution a little bit. First of all I've added new `PruneLock` struct to reduce code duplication because we need to have this kind of lock in two places right now. Also I've added some logic to remove items from `PruneLock` map when something goes wrong.

File: lxd/instance.go (hunk 5 above)
Comment (presztak) [reply lxd/instance.go:591]: This part of code was removed. Look at the comment below.

File: lxd/instance.go (hunk 6 above)
Comment (presztak) [reply lxd/instance.go]: I've added new `PruneLock` struct and I've changed this part of code a little bit. Look at the comment below.

File: lxd/locking/prune_lock.go [hunk 7]
```diff
@@ -0,0 +1,45 @@
+package locking
+
+import "sync"
+
+// PruneLock tracks a pruning items
+type PruneLock struct {
```
Comment (tomponline) [inline lxd/locking/prune_lock.go:6]: This type is very specific to snapshot pruning and yet this package `locking` is a general package, so not really well suited here. If it was renamed to `MapLock` or similar and the key type changed to `interface{}` then it would be more suitable. But it would then basically offer the same thing as https://pkg.go.dev/sync#Map in which case we should probably just use that.

File: lxd/instance.go [hunk 8]
```diff
@@ -540,6 +542,8 @@ func autoCreateContainerSnapshots(ctx context.Context, d *Daemon, instances []in
 	return nil
 }
 
+var cSnapshotsPruneRunning = locking.NewPruneLock()
+
 func pruneExpiredContainerSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
```
Comment (tomponline) [inline lxd/instance.go:547]: Lets rename this function to `pruneExpiredInstanceSnapshotsTask`.

File: lxd/instance.go [hunk 9]
```diff
@@ -612,12 +629,20 @@ func pruneExpiredContainerSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
 }
 
 func pruneExpiredContainerSnapshots(ctx context.Context, d *Daemon, snapshots []instance.Instance) error {
```
Comment (tomponline) [inline lxd/instance.go:631]: Lets rename to `pruneExpiredInstanceSnapshots`

File: lxd/instance.go [hunk 10]
```diff
@@ -566,8 +570,15 @@ func pruneExpiredContainerSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
 					continue
 				}
 
+				snapshotID := snapshot.ID()
+				if cSnapshotsPruneRunning.Contains(strconv.Itoa(snapshotID)) {
+					continue
```
Comment (tomponline) [inline lxd/instance.go:575]: I think the skipping should be handled in `pruneExpiredContainerSnapshots` not in `pruneExpiredContainerSnapshotsTask`. Basically all locking stuff should be in `pruneExpiredContainerSnapshots` where the actual call to `snapshot.Delete` is made.

File: lxd/instance.go (hunk 8 above)
Comment (presztak) [reply lxd/instance.go]: Fixed.

File: lxd/instance.go (hunk 9 above)
Comment (presztak) [reply lxd/instance.go]: Fixed.

File: lxd/locking/prune_lock.go (hunk 7 above)
Comment (presztak) [reply lxd/locking/prune_lock.go]: I've removed `PruneLock` struct and used `sync.Map`.

File: lxd/instance.go (hunk 10 above)
Comment (presztak) [reply lxd/instance.go]: Everything related to locking  is in `pruneExpiredContainerSnapshots` right now.

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by tomponline** [comment]
jenkins: please test this

**Comment by tomponline** [comment]
jenkins: test this please
