### PR TITLE
Return an error if an image already exists on import

### LINKED ISSUE #3244: Importing the same image twice (lxc image import) results in an SQL error
```
stgraber@castiana:~/data/code/lxc/lxd/a (stgraber/new-client)$ lxc image export 401
Image exported successfully!           

stgraber@castiana:~/data/code/lxc/lxd/a (stgraber/new-client)$ lxc image import meta-401.tar.xz 401.tar.xz 
error: UNIQUE constraint failed: images.fingerprint
```

### PR DESCRIPTION
**Pull request by albertodonato**
Return a more meaningful error when trying to import an already existing image.

Closes #3244

### CODE REVIEW

File: lxd/db_images.go [hunk 1]
```diff
@@ -105,8 +105,17 @@ func dbImageSourceGet(db *sql.DB, imageId int) (int, api.ImageSource, error) {
 
 }
 
-// dbImageGet gets an ImageBaseInfo object from the database.
-// The argument fingerprint will be queried with a LIKE query, means you can
+// Whether an image with the given fingerprint exists.
+func dbImageExists(db *sql.DB, fingerprint string) (exists bool, err error) {
```
Comment (brauner) [inline lxd/db_images.go]: Could we please stay away from named return parameters. I find them really confusing and easy to miss.

Comment (brauner) [inline lxd/db_images.go]: Why do we need this custom function anyway? Isn't

```
	_, _, err = dbImageGet(d.db, info.Fingerprint, false, true)
	if err == nil {
		return nil, fmt.Errorf("The image already exists: %s", info.Fingerprint)
	}
```
doing an equally fine job or am I missing something?

Comment (albertodonato) [inline lxd/db_images.go]: Well, not really, that method can error out for many reasons, like a database error or whatever.
also, dbImageGet needs the public attribute specified, and we want to match both public and private images

Comment (albertodonato) [inline lxd/db_images.go]: FWIW I find named return parameters one of the (few) nice things of go :)

Comment (brauner) [inline lxd/db_images.go]: I get the public vs private argument but your function is subject to db errors just like `dbImageGet()`. Can't we just have something along the lines of:

```
func dbImageExists(db *sql.DB, fingerprint string) (bool, error) {
	query := "SELECT COUNT(*) > 0 FROM images WHERE fingerprint=?"
	inargs := []interface{}{fingerprint}
	outargs := []interface{}{&exists}

	err = dbQueryRowScan(db, query, inargs, outargs)
	if err != nil {
		if err != sql.ErrNoRows {
			return false, err
		}
		return false, nil
	}
	return true, nil
}
```

Comment (albertodonato) [inline lxd/db_images.go]: Indeed, that's why the new function also returns err beside the boolean value.
Also, in your code, if you SELECT COUNT() you always get exactly one row, so the ErrNoRows is never triggered.

Comment (brauner) [inline lxd/db_images.go]: That code wasn't supposed to be copy-and-pasteable. :)

Comment (albertodonato) [inline lxd/db_images.go]: Then I'm not sure what's the difference between your code and mine, beside the named values :)
My code also returns the boolean (which is set via outargs by dbQueryRowScan() and the err, returned by the same function.
It's effectively the same as:

```
query := "SELECT COUNT(*) > 0 FROM images WHERE fingerprint=?"
inargs := []interface{}{fingerprint}
outargs := []interface{}{&exists}
err = dbQueryRowScan(db, query, inargs, outargs)
return exists, err
```

Comment (brauner) [inline lxd/db_images.go]: If your function can't erroneously report `true` although `dbQueryRowScan()` failed when called as:

    exists, _, := dbImageExists()

and you remove the named parameters I'm satisfied. :)

Comment (stgraber) [inline lxd/db_images.go]: I was about to add a comment about the named parameters and then saw this, so +1 on not using them :)

**Comment by albertodonato** [comment]
@brauner @stgraber done

**Comment by brauner** [comment]
jenkins: test this please
