### PR TITLE
NIC: Check static IPs are not defined on other NIC on same network and cluster member

### LINKED ISSUE #8921: assigned IP changed after creation copy of container
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
  driver: qemu | lxc
  driver_version: 5.2.0 | 4.0.9
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-73-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: server1
  server_pid: 1398
  server_version: 4.0.6
  storage: btrfs
  storage_version: 4.15.1

# Issue description

After creating new container2 as copy from running container1 snapshot the running container IP is changed, not immediately but after 1hour.
New created container2 is created as STOPPED , both have configured same IP but it shouldnt change IP of running container.

I try fix it by edit config IP new and original container but it is not work well as original contaner is not able get/set old IP. 
Maybe restart of dnsmaq or LXD will help i dont try it.

# Steps to reproduce

 1. lxc config device add contaner1 eth0 nic name=etho nictype=bridged parent=lxdbr0 ipv4.address=10.1.1.20
 2. lxc snapshot contaner1 forcopy
 3. lxc copy contaner1/forcopy container2

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tomponline**
Fixes #8921 and #8799

Tested with:

- Single server and project.
- Single server with instances in different projects connected to same bridge.
- Multi-server cluster with instances on different members connect to the same network (albeit it with different DHCP servers).

### CODE REVIEW

File: lxd/device/nic_bridged.go [hunk 1]
```diff
@@ -197,6 +197,63 @@ func (d *nicBridged) validateConfig(instConf instance.ConfigReader) error {
 		}
 	}
 
+	// Check there isn't another NIC with the any of the same addresses specified on the same cluster member.
```
Comment (stgraber) [inline lxd/device/nic_bridged.go:200]: `with any of the same addresses`

File: lxd/device/nic_bridged.go [hunk 2]
```diff
@@ -197,6 +197,63 @@ func (d *nicBridged) validateConfig(instConf instance.ConfigReader) error {
...
+	// Can only validate this when the instance is supplied (and not doing profile validation).
+	if d.inst != nil && (d.config["ipv4.address"] != "" || d.config["ipv6.address"] != "") {
+		err := d.state.Cluster.InstanceList(nil, func(inst db.Instance, p api.Project, profiles []api.Profile) error {
```
Comment (stgraber) [inline lxd/device/nic_bridged.go:203]: Don't we have a version of this which filters at the SQL level for instances that are local to the node?

If we're on a cluster with tens of thousand of instances, having to pull all the data for every device is going to get quite expensive. If we could do the node and project filter at the SQL level, that'd improve speed quite a lot.

Comment (stgraber) [reply lxd/device/nic_bridged.go:203]: Actually, possibly a stupid question there, but wouldn't it be a LOT faster to parse the dnsmasq hosts file for that network?

Comment (stgraber) [reply lxd/device/nic_bridged.go:203]: Anyway, merging the current branch as the fix is correct and it will resolve those two issues, just thinking about ways to get the same result faster and with less DB data transfer.

Comment (tomponline) [reply lxd/device/nic_bridged.go:203]: @stgraber Yes, in fact the `InstanceList` fucntion takes a filter argument that is passed to `GetInstances` and is applied at the SQL level. We use that in `SRIOVGetHostDevicesInUse` already, so I'll update this to use the same approach.

As for parsing the dnsmasq hosts file, I wanted to avoid that for 2 reason:

1. I try and avoid depending on external config files, especially as we are potentially looking at replacing some of dnsmasqs usage in the future.
2. This wouldn't be available when checking unmanaged networks or networks with DHCP disabled.

But by using the filtered `InstanceList` function I think we can get some significant improvements in the scenario you mentioned above.

Comment (tomponline) [reply lxd/device/nic_bridged.go:203]: @stgraber I do think we could improve/extend the `InstanceList` function (or a new function) in the future that allows pre-filtering of certain device types (perhaps `DeviceList` function that returns instances that have certain devices), as that is a common use of the `InstanceList` function.

Comment (tomponline) [reply lxd/device/nic_bridged.go:203]: https://github.com/lxc/lxd/pull/8982
