### PR TITLE
instance: stop API races while creating/deleting snapshots

### LINKED ISSUE #11538: Snapshot delete with the API race
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.2
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-38-generic
   * LXC version: 5.12
   * LXD version: 5.12
   * Storage backend in use: zfs

# Issue description

I hit the single-snapshot-delete API endpoint with 50 parallel requests `1.0/instances/foo/snapshots/bar` `DELETE` and fetch the operations for each of them `1.0/operations/my-id/wait?timeout=10`.
For many of the operations, I get an error back:
"Instance snapshot record count doesn't match instance snapshot volume record count"
This seems like a race condition due to the many parallel requests.
Eventually, after some time, all 50 snapshots are removed successfully.
I'd expect no error in that case.

# Steps to reproduce

 1. Create a lot of snapshots for an instance
 2. Trigger 50 parallel delete snapshot requests on that instance via the HTTP API
 3. Fetch the operation for all 50 delete requests via the HTTP API
 4. See some operations return the error "Instance snapshot record count doesn't match instance snapshot volume record count"

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #11538 

Here is an test script : 

```go
package main

import (
	"fmt"
	"sync"
	"time"

	lxd "github.com/lxc/lxd/client"
	"github.com/lxc/lxd/shared/api"
)

const LxdSock = "/var/snap/lxd/common/lxd/unix.socket"

func main() {
	fmt.Println("Trying to connect to LXD...")
	if srv, err := lxd.ConnectLXDUnix(LxdSock, nil); err == nil {
		fmt.Println("LXD server connection acquired")
		imageServer, err := lxd.ConnectSimpleStreams("https://images.linuxcontainers.org/", nil)
		if err != nil {
			panic(err)
		}

		fmt.Println("Connected to image server")

		alias, _, err := imageServer.GetImageAlias("alpine/3.17/cloud/amd64")
		if err != nil {
			panic(err)
		}

		fmt.Println("Got image alias")

		image, _, err := imageServer.GetImage(alias.Target)
		if err != nil {
			panic(err)
		}

		fmt.Println("Got image")

		req := api.InstancesPost{
			Name: "snap-del-api-race",
			Type: api.InstanceType("container"),
			Source: api.InstanceSource{
				Type:        "image",
				Fingerprint: image.Fingerprint,
				Project:     "default",
			},
		}

		op, err := srv.CreateInstanceFromImage(imageServer, *image, req)
		if err != nil {
			panic(err)
		}
		op.Wait()

		fmt.Println("Instance created")

		start := api.InstanceStatePut{
			Action:  "start",
			Timeout: 5,
			Force:   true,
		}

		upd, err := srv.UpdateInstanceState("snap-del-api-race", start, "")
		if err != nil {
			panic(err)
		}
		upd.Wait()

		fmt.Println("Instance started")

		// Create a lot of snapshots for an instance
		var wg sync.WaitGroup
		for i := 0; i < 100; i++ {
			go func(i int) {
				wg.Add(1)
				fmt.Println(fmt.Sprintf("Creating snapshot snap-%d", i))
				snap := api.InstanceSnapshotsPost{
					Name: fmt.Sprintf("snap-%d", i),
				}

				opCreate, err := srv.CreateInstanceSnapshot("snap-del-api-race", snap)
				if err != nil {
					panic(err)
				}

				err = opCreate.Wait()
				if err != nil {
					panic(err)
				}

				wg.Done()
				fmt.Println(fmt.Sprintf("snap-%d created", i))
			}(i)
		}

		wg.Wait()
		fmt.Println("All snapshots created")

		// Trigger 50 parallel delete snapshot requests on that instance via the HTTP API
		tasks := make([]lxd.Operation, 0)
		tasksMu := sync.Mutex{}
		for i := 0; i < 50; i++ {
			go func(i int) {
				opDel, err := srv.DeleteInstanceSnapshot("snap-del-api-race", fmt.Sprintf("snap-%d", i))
				if err != nil {
					panic(err)
				}

				fmt.Println(fmt.Sprintf("Deleting snapshot snap-%d", i))
				tasksMu.Lock()
				tasks = append(tasks, opDel)
				tasksMu.Unlock()
			}(i)
		}

		// created a ticker of 100ms
		// every 100ms, we check if the instance is running
		ticker := time.NewTicker(100 * time.Millisecond)
		longTicker := time.NewTicker(20 * time.Second)
		wait := make(chan struct{})
		// ...And fetch the operations for all 50 delete requests via the HTTP API at the same time
		// and check that we don't have "Instance snapshot record count doesn't match instance snapshot volume record count"
		go func() {
			for {
				select {
				case <-ticker.C:
					tasksMu.Lock()
					for i, task := range tasks {
						status := task.Get()
						fmt.Println(fmt.Sprintf("Snapshot snap-%d status: %s", i, status.Status))
					}

					tasksMu.Unlock()
				case <-longTicker.C:
					fmt.Println("Timeout")
					ticker.Stop()
					longTicker.Stop()
					wait <- struct{}{}
					return
				}
			}
		}()

		<-wait
		fmt.Println("Done")
	} else {
		fmt.Println(err)
	}
}

```

### CODE REVIEW

**Comment by gabrielmougard** [comment]
@tomponline this scenario also causes problems that I think are an extension of the PR https://github.com/lxc/lxd/pull/11586#:~:text=err%20%3D%20opCreate.Wait()%0A%09%09%09%09if%20err%20!%3D%20nil%20%7B%0A%09%09%09%09%09panic(err)%0A%09%09%09%09%7D

File: lxd/instance/drivers/driver_lxc.go [hunk 1]
```diff
@@ -3637,6 +3637,12 @@ func (d *lxc) Delete(force bool) error {
 
 // Delete deletes the instance without creating an operation lock.
 func (d *lxc) delete(force bool) error {
+	if !force {
```
Comment (gabrielmougard) [inline lxd/instance/drivers/driver_lxc.go:3640]: I experienced some locking issue here in case of broken concurrent snapshot creation so I think that if `force = true`, maybe we shoul not lock

**Comment by gabrielmougard** [comment]
@tomponline the following script gives no error on my side. Does it reproduce the needed scenario on your side ?

**Review by tomponline — CHANGES_REQUESTED** [review]
The use of different `locking.Lock()` prefixes isn't going to fully cure the problem I think.
As this will allow multiple concurrent different operations (that can update the backup file) to proceed.

Instead I think we should create an unexported function on the `common` instance driver like this:

```go
// updateBackupFileLock acquires the update backup file lock that protects concurrent access to actions that will call UpdateBackupFile() as part of their operation. 
func (d *common) updateBackupFileLock(ctx context.Context) locking.UnlockFunc {
    parentName, _, _ := api.GetParentAndSnapshotName(d.Name())
    return locking.Lock(context.TODO(), fmt.Sprintf("instance_updatebackupfile_%s_%s", d.Project().Name, parentName))
}
```

Then look for places where `.UpdateBackupFile(` is called in the code base and assess whether we should call `d.updateBackupFileLock()` and defer the unlock function it returns for each of them.

For example the calls in the `instanceCreate*` functions shouldn't be necessary to protect because they are not going to allow other operations to proceed until creation has finished.

But the ones in `driver_*.go` are good candidates for using the lock.

Keep in mind also that the place where `.UpdateBackupFile(` is called is not necessarily the function where we want to take the lock. 

For example `startCommon()` calls `.UpdateBackupFile(` but we wouldn't want to take the lock there, but instead take it in the callers of `startCommon()` so that the lock isn't take half way through an action.

Another example of this would be the `delete()` function.

Finally, I think we should avoid calling the lock in the `onStop(` functions as we don't want to delay those if a snapshot is being taken.

**Comment by gabrielmougard** [comment]
@tomponline yep, tested this solution and it seems to work too ;) thanks

**Comment by tomponline** [comment]
@gabrielmougard tests are failing pretty badly though :(

**Comment by gabrielmougard** [comment]
yeah looking at it

**Comment by tomponline** [comment]
@gabrielmougard its probably a deadlock with the startup snapshot functionality. As Start will have taken a lock and then it probably calls Snapshot to take a start up time snapshot and blocks.

**Comment by tomponline** [comment]
@gabrielmougard look at where `startupSnapshot` is called.

**Comment by tomponline** [comment]
@gabrielmougard suggest creating an unexported `func (d *lxc) snapshot(name string, expiry time.Time, stateful bool) error {` function that doesn't lock and then calling that instead of `inst.Snapshot()` from `startupSnapshot` then update `Snapshot()` to lock and then call `snapshot()`.

**Comment by gabrielmougard** [comment]
@tomponline tests should be ok now

File: lxd/instance/drivers/driver_common.go [hunk 2]
```diff
@@ -711,29 +712,28 @@ func (d *common) isStartableStatusCode(statusCode api.StatusCode) error {
 	return nil
 }
 
-// startupSnapshot triggers a snapshot if configured.
-func (d *common) startupSnapshot(inst instance.Instance) error {
+func (d *common) getSnapNameAndExpiry(inst instance.Instance) (string, time.Time, error) {
```
Comment (tomponline) [inline lxd/instance/drivers/driver_common.go:715]: Lets call this `getStartupSnapNameAndExpiry()` so its clear its to do with startup snapshots. Also please retain and update the comment.

File: lxd/instance/drivers/driver_qemu.go [hunk 3]
```diff
@@ -4392,8 +4403,7 @@ func (d *qemu) IsPrivileged() bool {
 	return false
 }
 
-// Snapshot takes a new snapshot.
-func (d *qemu) Snapshot(name string, expiry time.Time, stateful bool) error {
+func (d *qemu) takeSnapshot(name string, expiry time.Time, stateful bool) error {
```
[the remark this answers is not in the document]
Comment (gabrielmougard) [reply lxd/instance/drivers/driver_qemu.go:4406]: @tomp this will collision with the `snapshot` boolean field in `common`

File: lxd/instance/drivers/driver_common.go (hunk 2 above)
Comment (tomponline) [reply lxd/instance/drivers/driver_common.go:715]: Lets also return a *time.Time so we can return nil for that var on error.

File: lxd/instance/drivers/driver_lxc.go [hunk 4]
```diff
@@ -2247,11 +2247,18 @@ func (d *lxc) startCommon() (string, []func() error, error) {
 	_ = unix.Unmount(d.RootfsPath(), unix.MNT_DETACH)
 
 	// Snapshot if needed.
-	err = d.startupSnapshot(d)
+	snapName, expiry, err := d.getSnapNameAndExpiry(d)
 	if err != nil {
 		return "", nil, err
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go:2252]: I know not strictly part of this issue, but lets wrap the error returned here (in both drivers) so its like:

```go
fmt.Errorf("Failed getting startup snapshot info: %w", err)
```

File: lxd/instance/drivers/driver_lxc.go [hunk 5]
```diff
@@ -2247,11 +2247,18 @@ func (d *lxc) startCommon() (string, []func() error, error) {
...
 	}
 
+	if snapName != "" {
+		err := d.takeSnapshot(snapName, expiry, false)
+		if err != nil {
+			return "", nil, err
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go:2258]: Lets wrap the error here so its:

```go
fmt.Errorf("Failed taking startup snapshot: %w", err)
```

File: lxd/instance/drivers/driver_qemu.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:4406]: Ah OK, can we change the snapshot bool to `isSnapshot` it would actually read more clearly in my view (as "snapshot" can be an action as well as a description).

**Review by tomponline — APPROVED** [review]
LGTM!

**Review by monstermunchkin — APPROVED** [review]
