### PR TITLE
Checks that the host node is clustered before editing.

### LINKED ISSUE #9688: Running lxd cluster edit on a standalone server gives save error: At least one member must be a "voter"
Running lxd cluster edit on a standalone server and then exiting without making any changes gives save error: 

```
Config validation error: At least one member must be a "voter"
Press enter to open the editor again or ctrl+c to abort change
```

Perhaps this should detect if server is clustered and either error when command is run or allow no changes to be applied.

### PR DESCRIPTION
**Pull request by markylaing**
The daemon is not running when this command is executed. To check
whether the host is clustered, we load it's config and check if it has a
cluster address.

Fixes #9688

### CODE REVIEW

File: lxd/main_cluster.go [hunk 1]
```diff
@@ -136,7 +137,16 @@ func (c *cmdClusterEdit) Run(cmd *cobra.Command, args []string) error {
...
 	err = database.Transaction(func(tx *db.NodeTx) error {
-		var err error
+		config, err := node.ConfigLoad(tx)
+		if err != nil {
+			return err
+		}
+
+		clusterAddress := config.ClusterAddress()
+		if clusterAddress == "" {
+			return fmt.Errorf("LXD is not clustered - set up clustering first with 'lxc cluster enable <host>'")
```
Comment (tomponline) [inline lxd/main_cluster.go:147]: Maybe:

`LXD is not clustered (missing "cluster.https_address") - set up clustering first with "lxc cluster enable <host>"`

So its clear what we are checking?

**Review by tomponline — APPROVED** [review]

File: lxd/main_cluster.go (hunk 1 above)
Comment (markylaing) [reply lxd/main_cluster.go]: Done :+1:

File: lxd/main_cluster.go [hunk 2]
```diff
@@ -136,7 +137,16 @@ func (c *cmdClusterEdit) Run(cmd *cobra.Command, args []string) error {
...
 	err = database.Transaction(func(tx *db.NodeTx) error {
-		var err error
+		config, err := node.ConfigLoad(tx)
+		if err != nil {
+			return err
+		}
+
+		clusterAddress := config.ClusterAddress()
+		if clusterAddress == "" {
+			return fmt.Errorf(`LXD is not clustered (missing "cluster.https_address") - set up clustering first with "lxc cluster enable <host>"`)
```
Comment (stgraber) [inline lxd/main_cluster.go:147]: We usually don't like recommending specific `lxc` commands on server-side errors. Also this may have the side effect of random users enabling clustering just so they can run the edit command.

I think I'd prefer the error be something along the lines of `fmt.Errorf("Can't edit cluster configuration as server isn't clustered")`

**Review by stgraber — CHANGES_REQUESTED** [review]
Just needs a tweak to the error.

File: lxd/main_cluster.go (hunk 2 above)
Comment (tomponline) [reply lxd/main_cluster.go:147]: Ah yes I'd not remembered that. I suggested adding the bit about the  cluster.https_address because this tool is used when things go wrong and thought it'd be good to be transparent about why we think its not clustered, in case that setting was removed too.

Comment (stgraber) [reply lxd/main_cluster.go:147]: Yeah, the `missing cluster.https_address` is probably fine to keep, it's the `lxc cluster enable` bit that's problematic.

Comment (tomponline) [reply lxd/main_cluster.go:147]: Yep agreed. Thanks

Comment (markylaing) [reply lxd/main_cluster.go]: I've changed it to `Can't edit cluster configuration as server isn't clustered (missing "cluster.https_address" config)`

**Review by tomponline — APPROVED** [review]
