### PR TITLE
[GH-9248] Restrict protocol version

### LINKED ISSUE #9248: Setting `core.https_address` to `0.0.0.0` listens on IPv6 too
# Required information

```
# snap info lxd | grep installed
installed:          4.18                   (21468) 75MB -
```

# Steps to reproduce

1. Tell LXD to listen on all IPv4 addresses
```
# lxc config set core.https_address 0.0.0.0
```
 2. Check which IP/port is bounded
```
# ss -nltp | grep lxd
LISTEN    0         0                        *:8443                   *:*        users:(("lxd",pid=2533,fd=19))
```
 3. Confirm IPv6 connectivity
```
# nc -zv ::1 8443
Connection to ::1 8443 port [tcp/*] succeeded!
```

Connecting to IPv6 should *not* work.

### PR DESCRIPTION
**Pull request by masnax**
Closes #9248

Works off of https://github.com/lxc/lxd/pull/9259 by @dizlv

Seems everything was already in place, just incorrect formatting on the error message. I just changed the assertion to check for any error, since the error that was being checked isn't from us.

### CODE REVIEW

File: lxd/endpoints/network_test.go [hunk 1]
```diff
@@ -88,3 +90,22 @@ func newTCPListener(t *testing.T) *net.TCPListener {
...
+	defer cleanup()
+
+	config.NetworkAddress = "0.0.0.0:0"
+	require.NoError(t, endpoints.Up(config))
+
+	address, certificate := endpoints.NetworkAddressAndCert()
+	parts := strings.Split(address, ":")
+	ipv6Address := fmt.Sprintf("[::1]:%s", parts[1])
+
+	assert.NoError(t, httpGetOverTLSSocket(address, certificate))
```
Comment (tomponline) [inline lxd/endpoints/network_test.go:107]: Can this use 127.0.0.1 rather than address from listener to show sane behavior as ipv6 request?

**Review by tomponline — CHANGES_REQUESTED** [review]

File: lxd/endpoints/network_test.go (hunk 1 above)
Comment (tomponline) [reply lxd/endpoints/network_test.go:107]: So I mean use a var called ipv4Address like the ipv6 approach.

**Review by tomponline — APPROVED** [review]
