### PR TITLE
lxd: Rework listening logic

### LINKED ISSUE #4256: Trying to change core.https_address when set returns an error
# Required information

 * Distribution: ubuntu
 * Distribution version: 17.10
 * The output of "lxc info":
```

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <REDACTED>
  certificate_fingerprint: <REDACTED>
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-32-generic
  server: lxd
  server_pid: 30643
  server_version: "2.21"
  storage: btrfs
  storage_version: "4.12"
```
# Issue description

Trying to change the `core.https_address` when already set returns 'address already in use'

# Steps to reproduce

```
$ lxc config set core.https_address '127.0.0.1:8443'
$ lxc config set core.https_address '[::]:8443'
error: cannot listen on https socket: listen tcp 0.0.0.0:8443: bind: address already in use
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #4256

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/endpoints/network.go [hunk 1]
```diff
@@ -43,36 +43,60 @@ func (e *Endpoints) NetworkUpdateAddress(address string) error {
...
 	}
 
 	logger.Infof("Update network address")
 
-	// First try to see if we can listen to this new port at all, so we
-	// don't close the old one (if any) in case of errors.
-	var listener net.Listener
-	if address != "" {
+	e.mu.Lock()
+	defer e.mu.Unlock()
```
Comment (brauner) [inline lxd/endpoints/network.go]: Holding a lock for a whole second. :)
