### PR TITLE
instance: No collisions between `proxy` device and network fwd listenAddr

### LINKED ISSUE #11332: LXD does not cross-check if network forwards conflict with proxy port forwarding
For context, see https://discuss.linuxcontainers.org/t/how-to-investigate-why-ipv4-proxy-stops-for-one-container/16014/.

# Required information

```
  driver: lxc
  driver_version: 5.0.2
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.0-58-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "22.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: mackerel
  server_pid: 1110326
  server_version: "5.10"
  storage: zfs
  storage_version: 2.1.4-0ubuntu0.1
```

# Issue description

If both `lxc network forward port add lxdbr0` and profile proxy configurations are used to set up port forwarding, a `snap refresh` or `systemctl reload` of lxd will potentially break the firewall rules used to enact the forwarding.

My specific environment is nftables, with `type: proxy`, `nat: "true"` devices set up in profiles.

# Steps to reproduce

1. Boot a new container, using DHCP addressing. (Do not, at this point, enable static/long term memory of addresses in lxd)
2. Add a network forward for a TCP port from the public IP of the host to the internal IP of the container (tcp 25 as an example).
3. Verify the forwarding works (set up something to listen on the port)
4. Add a new profile from default, and add a devices section that sets up a NAT proxy for a port.

For instance, 
```
  proxy_25:
    connect: tcp:10.68.0.103:25   # container ip
    listen: tcp:1.2.3.4:25   # public ip
    nat: "true"
    type: proxy
```

5. Stop and delete the container
6. Create the container again, from the profile that has the proxy device; it should get a different IP. If it doesn't, make it.
7. Verify that the port forwarding works. If it doesn't, reboot the host and see if it does. If it doesn't, I'm not sure what's different from my scenario.
8. `systemctl reload snap.lxd.daemon`
9. Verify that the port forwarding works. It **should not**.

Review `nft list ruleset` for the port. It should appear in several chains with both the current container IP, and the one used in the `network forward port` command.

The network forward should have put the forward in something like `chain fwdprert.lxdbr0`. It'll be a `dnat` rule, with the receiving IP being the old container IP.

The proxy forward should have put the forward in `chain prert.[container].[proxy_name]`. It'll be the same `dnat` rule, but the receiving IP will be the current container IP.

This feels like something that lxd should be able to detect, as it has full context on both network forwards and proxy devices being set up with the same public IP and port.

### PR DESCRIPTION
**Pull request by gabrielmougard**
Closes #11332

### CODE REVIEW

File: lxd/instance/instance_utils.go [hunk 1]
```diff
@@ -18,7 +18,7 @@ import (
 	liblxc "github.com/lxc/go-lxc"
 	"github.com/pborman/uuid"
 
-	"github.com/lxc/lxd/client"
+	lxd "github.com/lxc/lxd/client"
```
Comment (monstermunchkin) [inline lxd/instance/instance_utils.go:21]: This needs to be removed. The import organizer tool does this, but we don't want it.

Comment (gabrielmougard) [reply lxd/instance/instance_utils.go:21]: ah yes.. this is sth I thought I removed before

Comment (tomponline) [reply lxd/instance/instance_utils.go:21]: Yeah, this happened on the other PR you put up yesterday. Probably need to disabling something in vscode.

File: lxd/instance/instance_utils.go [hunk 2]
```diff
@@ -866,6 +895,10 @@ func CreateInternal(s *state.State, args db.InstanceArgs, clearLogDir bool) (Ins
 		if err != nil {
 			return err
 		}
+		// The `proxy` devices might collide with existing forward networks
```
Comment (tomponline) [inline lxd/instance/instance_utils.go:898]: We use empty new line after each stanza.

File: lxd/instance/instance_utils.go (hunk 1 above)
Comment (monstermunchkin) [reply lxd/instance/instance_utils.go:21]: > Yeah, this happened on the other PR you put up yesterday. Probably need to disabling something in vscode.

I haven't found a way of doing this without disabling the autoimport feature which is quite handy.

File: lxd/instance/instance_utils.go [hunk 3]
```diff
@@ -866,6 +895,10 @@ func CreateInternal(s *state.State, args db.InstanceArgs, clearLogDir bool) (Ins
...
+		if err = validateProxyDevCollisions(ctx, proj, s.DB.Cluster, tx, devices); err != nil {
```
Comment (tomponline) [inline lxd/instance/instance_utils.go:899]: This would only get called at instance creation time, but we need it to occur at instance NIC start type.
This should be part of NIC `checkAddressConflict` I think.

File: lxd/instance/instance_utils.go (hunk 1 above)
Comment (tomponline) [reply lxd/instance/instance_utils.go:21]: Yep I disabled that I think.

File: lxd/instance/instance_utils.go (hunk 3 above)
Comment (tomponline) [reply lxd/instance/instance_utils.go:899]: Oh wait we are talking about network forwards and proxy devices, not NICs. Sorry multi-tasking...badly.
But we do need something similar in the proxy device to check for address conflicts from network forwards, and then something for checking network forwards don't conflict.

File: lxd/network/driver_bridge.go [hunk 4]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+									netFwdAddr,
+								),
+						)
+					}
+				}
+			}
+		}
+		return nil
+	})
+
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2571]: err result not checked

File: lxd/network/driver_bridge.go [hunk 5]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+							) +
+								fmt.Sprintf(
+									"with the network forward IP address ('%s') you are creating",
+									netFwdAddr,
+								),
+						)
+					}
+				}
+			}
+		}
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2568]: newline after each stanza

File: lxd/network/driver_bridge.go [hunk 6]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+	err = n.state.DB.Cluster.InstanceList(context.TODO(), func(inst db.InstanceArgs, p api.Project) error {
+		devices := db.ExpandInstanceDevices(inst.Devices, inst.Profiles)
+		for devName, devConfig := range devices {
+			if devConfig["type"] == "proxy" {
+				proxyListenAddr := strings.Split(devConfig["listen"], ":")[1]
+
+				for netFwdAddr, _ := range projectNetworksForwardsOnUplink {
+					if proxyListenAddr == netFwdAddr {
+						return fmt.Errorf(
+							fmt.Sprintf(
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2556]: keep these on the same line to aid with grepping

File: lxd/network/driver_bridge.go [hunk 7]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+								"A proxy device ('%s') has an overlapping listen IP address ",
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2557]: Use %q for quoting strings to avoid the need for manual quotes

File: lxd/network/driver_bridge.go [hunk 8]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
 	externalSubnets = append(externalSubnets, bridgeNetworkExternalSubnets...)
 	externalSubnets = append(externalSubnets, bridgedNICExternalRoutes...)
 
+	// Detect if there are any conflicting proxy devices on all instances with the to be created network forward
+	err = n.state.DB.Cluster.InstanceList(context.TODO(), func(inst db.InstanceArgs, p api.Project) error {
+		devices := db.ExpandInstanceDevices(inst.Devices, inst.Profiles)
+		for devName, devConfig := range devices {
+			if devConfig["type"] == "proxy" {
+				proxyListenAddr := strings.Split(devConfig["listen"], ":")[1]
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2551]: Stuff like this makes me uncomfortable that if there was ever a listen setting with no `:` in it then this would cause LXD to panic. Better to check the length of the slice first before using it.

File: lxd/network/driver_bridge.go [hunk 9]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
 	externalSubnets = append(externalSubnets, bridgeNetworkExternalSubnets...)
 	externalSubnets = append(externalSubnets, bridgedNICExternalRoutes...)
 
+	// Detect if there are any conflicting proxy devices on all instances with the to be created network forward
+	err = n.state.DB.Cluster.InstanceList(context.TODO(), func(inst db.InstanceArgs, p api.Project) error {
+		devices := db.ExpandInstanceDevices(inst.Devices, inst.Profiles)
+		for devName, devConfig := range devices {
+			if devConfig["type"] == "proxy" {
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2550]: We generally prefer using the "happy path" coding style. I.e. rather than nesting for every if condition you want, instead add checks at the top that `continue` if the item you're looking at isn't what you want. Effectively only continue if you are "happy" this is what you want.

So instead to:

```go
	for devName, devConfig := range devices {
			if devConfig["type"] != "proxy" {
                continue
           }
```

See also https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88

File: lxd/network/driver_bridge.go [hunk 10]
```diff
@@ -2543,6 +2543,32 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+				proxyListenAddr := strings.Split(devConfig["listen"], ":")[1]
+
+				for netFwdAddr, _ := range projectNetworksForwardsOnUplink {
+					if proxyListenAddr == netFwdAddr {
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2554]: Need to parse all IPs to their canonical form using net.ParseIP before comparing them.
Otherwise you'll run into trouble if whats in the DB for a network forward is in a different format to that being used for the proxy device.

E.g. these are the same IPs:

```
fd42:b967:ba02:1032::1
fd42:b967:ba02:1032:0000:0000:0000:0001
```

File: lxd/device/proxy.go [hunk 11]
```diff
@@ -181,13 +182,51 @@ func (d *proxy) validateEnvironment() error {
 	return nil
 }
 
+// validateNetworkForwardConflicts checks that the proxy device about to be created does not
+// overlap on existing network forward (both entities can't have the same listening address with
+// the same port number)
+func (d *proxy) validateNetworkForwardConflicts() error {
```
Comment (tomponline) [inline lxd/device/proxy.go:188]: I would call this something more generic like `validateListenAddressConflicts()` and then we can expand it later to cover other things.

File: lxd/device/proxy.go [hunk 12]
```diff
@@ -181,13 +182,51 @@ func (d *proxy) validateEnvironment() error {
...
+	}
+
+	return d.state.DB.Cluster.Transaction(context.TODO(), func(ctx context.Context, tx *db.ClusterTx) error {
+		projectNetworksForwardsOnUplink, err := tx.GetProjectNetworkForwardListenAddressesOnMember(ctx)
+		if err != nil {
+			return fmt.Errorf("Failed loading network forward listen addresses: %w", err)
+		}
+
+		for netFwdAddr, _ := range projectNetworksForwardsOnUplink {
+			if proxyListenAddr.Address == netFwdAddr {
```
Comment (tomponline) [inline lxd/device/proxy.go:201]: Use net.ParseIP when comparing IPs.

File: lxd/device/proxy.go [hunk 13]
```diff
@@ -181,13 +182,51 @@ func (d *proxy) validateEnvironment() error {
...
+				return fmt.Errorf(
+					fmt.Sprintf(
+						"The proxy device ('%s') has an overlapping listen IP address ",
```
Comment (tomponline) [inline lxd/device/proxy.go:204]: %q for quotes

Comment (tomponline) [reply lxd/device/proxy.go:204]: And single line please

File: lxd/network/driver_bridge.go (hunk 8 above)
Comment (tomponline) [reply lxd/network/driver_bridge.go:2551]: Suggest moving the `ProxyParseAddr` function into network/network_utils.go and then you can use it from here and in proxy device.

File: lxd/device/proxy.go [hunk 14]
```diff
@@ -181,13 +182,51 @@ func (d *proxy) validateEnvironment() error {
...
+}
+
 // Start is run when the device is added to the instance.
 func (d *proxy) Start() (*deviceConfig.RunConfig, error) {
 	err := d.validateEnvironment()
 	if err != nil {
 		return nil, err
 	}
 
+	err = d.validateNetworkForwardConflicts()
```
Comment (tomponline) [inline lxd/device/proxy.go:225]: Lets call this from `validateConfig` so it occurs at device creation/edit time as well as start time.

Also to avoid needing to parse the listen address multiple times with `ProxyParseAddr` can you update the `validateNetworkForwardConflicts` to accept a `net.IP` type that you can extract from `ProxyParseAddr` already called in `validateConfig` and then parse using `net.ParseIP`.

File: lxd/network/driver_bridge.go [hunk 15]
```diff
@@ -2543,6 +2543,29 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+			}
+
+			proxyListenAddr, err := ProxyParseAddr(devConfig["listen"])
+			if err != nil {
+				return err
+			}
+
+			for netFwdAddr := range projectNetworksForwardsOnUplink {
+				if net.ParseIP(proxyListenAddr.Address).Equal(net.ParseIP(netFwdAddr)) {
+					return fmt.Errorf("A proxy device (%q) has an overlapping listen IP address with the network forward IP address (%q) you are creating", devName, netFwdAddr)
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2562]: We cant always be sure that this function is called in a creation context (it is at the moment, but could be changed in the future), so lets lose that part.

Also the proxy dev name is somewhat meaningless without the project and instance name too.

How about something like:

"Listen address %q conflicts with proxy device %q(devName) on %(instanceName) in project %q(projectName)"

File: lxd/network/driver_bridge.go (hunk 4 above)
Comment (tomponline) [reply lxd/network/driver_bridge.go:2568]: Error still unhandled.

**Review by tomponline — CHANGES_REQUESTED** [review]
Looking much better. A couple of small nits.

We should also add some tests to the proxy device test to check this works as expected.

Thanks!

File: lxd/network/driver_bridge.go (hunk 4 above)
Comment (tomponline) [reply lxd/network/driver_bridge.go:2568]: line 2547 assigns an err value that you dont check here.

**Comment by tomponline** [comment]
Static analysis failing.

File: lxd/network/driver_bridge.go [hunk 16]
```diff
@@ -2543,6 +2543,33 @@ func (n *bridge) getExternalSubnetInUse() ([]externalSubnetUsage, error) {
...
+			}
+
+			proxyListenAddr, err := ProxyParseAddr(devConfig["listen"])
+			if err != nil {
+				return err
+			}
+
+			for netFwdAddr := range projectNetworksForwardsOnUplink {
+				if net.ParseIP(proxyListenAddr.Address).Equal(net.ParseIP(netFwdAddr)) {
+					return fmt.Errorf("Listen address %q conflicts with proxy device %q on %q in project %q", netFwdAddr, devName, inst.Name, p.Name)
```
Comment (tomponline) [inline lxd/network/driver_bridge.go:2562]: I don't think we should return an error here, as this function is just for returning "external subnets in use", not for casting a judgement on whether they conflict or not (we dont know that the caller of the function even wants to check for that).

Instead we should add the parsed proxy listen addresses to the `externalSubnets` slice with new `subnetUsageType` type (https://github.com/lxc/lxd/blob/7b3f46e08688043134b05888bfce9860e7274bcf/lxd/network/driver_common.go#L56-L65) called `subnetUsageProxy`.
See

Comment (tomponline) [reply lxd/network/driver_bridge.go:2562]: Like we do here https://github.com/lxc/lxd/blob/7b3f46e08688043134b05888bfce9860e7274bcf/lxd/network/driver_common.go#L1105-L1119 but filling the instance fields on that struct instead.

**Comment by gabrielmougard** [comment]
sorry, wrong branch :)

**Review by tomponline — CHANGES_REQUESTED** [review]
That revert commit needs removing from this branch.

File: test/suites/container_devices_proxy.sh [hunk 17]
```diff
@@ -692,3 +693,70 @@ container_devices_proxy_tcp_udp() {
...
+  # First, launch container with a static IP
+  lxc launch testimage proxyTester
+  lxc config device add proxyTester eth0 nic \
+    nictype=bridged \
+    name=eth0 \
+    parent=${netName} \
+    ipv4.address=${proxyTesterStaticIP}
+
+  # Then, we set up network forward
+  firewallDriver=$(lxc info | awk -F ":" '/firewall:/{gsub(/ /, "", $0); print $2}')
```
Comment (tomponline) [inline test/suites/container_devices_proxy.sh:721]: We dont need this bit as we are not testing the network forward functionality, only whether its listen address is overlapping with proxy devices.

File: test/suites/container_devices_proxy.sh [hunk 18]
```diff
@@ -692,3 +693,70 @@ container_devices_proxy_tcp_udp() {
...
+    ! iptables -w -t nat -S | grep -c "generated for LXD network-forward ${netName}" || false
+  else
+    ! nft -nn list chain inet lxd "fwdprert.${netName}" || false
+    ! nft -nn list chain inet lxd "fwdout.${netName}" || false
+    ! nft -nn list chain inet lxd "fwdpstrt.${netName}" || false
+  fi
+
+  # Test overlapping issue (network forward exists --> proxy creation should fail)
+  if lxc config device add proxyTester proxyDev proxy "listen=tcp:${overlappingAddr}:$HOST_TCP_PORT" "connect=tcp:${proxyTesterStaticIP}:4321" nat=true; then
+    echo "Address should overlap with network forward while creating proxy device"
```
Comment (tomponline) [inline test/suites/container_devices_proxy.sh:735]: This is quite a confusing message IMHO.

Comment (tomponline) [reply test/suites/container_devices_proxy.sh:735]: You can just do this I think:

```
! lxc config device add proxyTester proxyDev proxy "listen=tcp:${overlappingAddr}:$HOST_TCP_PORT" "connect=tcp:${proxyTesterStaticIP}:4321" nat=true || false
```

File: test/suites/container_devices_proxy.sh [hunk 19]
```diff
@@ -692,3 +693,70 @@ container_devices_proxy_tcp_udp() {
...
+  lxc config device add proxyTester eth0 nic \
+    nictype=bridged \
+    name=eth0 \
+    parent=${netName} \
+    ipv4.address=${proxyTesterStaticIP}
+
+  lxc config device add proxyTester proxyDev proxy "listen=tcp:${overlappingAddr}:$HOST_TCP_PORT" "connect=tcp:${proxyTesterStaticIP}:4321" nat=true
+
+  # Test overlapping issue (proxy exists --> network forward creation should fail)
+  if lxc network forward create "${netName}" "${overlappingAddr}"; then
```
Comment (tomponline) [inline test/suites/container_devices_proxy.sh:754]: Can just be:

```
! lxc network forward create "${netName}" "${overlappingAddr}" || false
```

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks looks good.

Just a couple of things:

- Please can you re-order the commits so that earlier commits don't use functions that don't exist yet.
- Update the tests to not test for firewall rules (not relevant here) and simplify the error checking.

**Comment by tomponline** [comment]
@gabrielmougard looks like the latest changes broke the tests.

File: test/suites/container_devices_proxy.sh [hunk 20]
```diff
@@ -692,3 +693,54 @@ container_devices_proxy_tcp_udp() {
...
+  lxc config device add proxyTester eth0 nic \
+    nictype=bridged \
+    name=eth0 \
+    parent=${netName} \
+    ipv4.address=${proxyTesterStaticIP}
+
+  lxc config device add proxyTester proxyDev proxy "listen=tcp:${overlappingAddr}:$HOST_TCP_PORT" "connect=tcp:${proxyTesterStaticIP}:4321" nat=true
+
+  # Test overlapping issue (proxy exists --> network forward creation should fail)
+  lxc network forward create "${netName}" "${overlappingAddr}" || false
```
Comment (tomponline) [inline test/suites/container_devices_proxy.sh:741]: missing `!` at start

File: test/suites/container_devices_proxy.sh [hunk 21]
```diff
@@ -692,3 +693,54 @@ container_devices_proxy_tcp_udp() {
...
+    nictype=bridged \
+    name=eth0 \
+    parent=${netName} \
+    ipv4.address=${proxyTesterStaticIP}
+
+  # Check creating empty forward doesn't create any firewall rules.
+  lxc network forward create "${netName}" "${overlappingAddr}"
+
+  # Test overlapping issue (network forward exists --> proxy creation should fail)
+  lxc config device add proxyTester proxyDev proxy "listen=tcp:${overlappingAddr}:$HOST_TCP_PORT" "connect=tcp:${proxyTesterStaticIP}:4321" nat=true || false
```
Comment (tomponline) [inline test/suites/container_devices_proxy.sh:724]: missing `!` at start

**Comment by tomponline** [comment]
Thanks!

**Comment by cricalix** [comment]
Thank you for fixing this; it was certainly brain-bending to work out what had gone wrong :)
