### PR TITLE
lxd-generate join config

### LINKED ISSUE #10844: lxd-generate join config tag not working as expected
I'm working on a follow up to https://github.com/canonical/lxd-cloud/pull/151. Many (if not all) methods that use the resources table would be greatly simplified by changing the `Resource` database type from 
```go
type Resource struct {
	ID        int
	Name      string       `db:"primary=true"`
	Type      ResourceType `db:"primary=true"`
	Cluster   string       `db:"join=clusters.name"`
	ProjectID int          `db:"primary=true"`
}
```
to
```go
type Resource struct {
	ID      int
	Name    string       `db:"primary=true"`
	Type    ResourceType `db:"primary=true"`
	Cluster string       `db:"join=clusters.name"`
	ProjectUUID string       `db:"primary=true&join=projects.uuid"`
}
```

i.e. changing `ProjectID` to `ProjectUUID` and using joins.

However I'm having problems generating the statements and methods.

Firstly, there is an incorrect table name in the `ORDER BY` clause of all `objects` statements. E.g:
```sql
SELECT resources.id, resources.name, resources.type, clusters.name AS cluster, projects.uuid AS project_uuid
  FROM resources JOIN clusters ON resources.cluster_id = clusters.id JOIN projects ON resources.project_id = projects.id
  ORDER BY resources.name, resources.type, project_uuids.id
```
where `project_uuids.id` is incorrect.

Secondly, the `delete`, `rename`, and `update` statements perform subselects on both the wrong table, and the wrong column. E.g.
```sql
DELETE FROM resources WHERE name = ? AND type = ? AND project_uuid_id = (SELECT projects_uuids.id FROM projects_uuids WHERE projects_uuids.name = ?)
```
where `project_uuids` is the wrong table, and `name` is the wrong column.

I've tried changing `ProjectUUID` to `Project` and this solves the first issue, but not the second (i.e. the subselect still uses the `name` column). This is also not ideal as the field name becomes more ambiguous.

Ideally the table name and column for performing joins and selects should come directly from the config.

@masnax is this feasible?

### PR DESCRIPTION
**Pull request by markylaing**
Uses the join configuration in the `db` struct tag to set correct table and column names in the where, join, and order by clauses or generated statements.

`make update-schema` does not change generated statements for LXD.

@masnax I've made the changes necessary to fix the issues in #10844 but I'm not sure if there are any other parts of the generator that might need similar changes. Also in the `whereClause` function, I'm not sure if it's ok to use the singular form of the join table name in the `via` map. Let me know what you think.

Closes #10844.

### CODE REVIEW

**Comment by tomponline** [comment]
@markylaing in order to review this please can I have some context as to why this is needed?

**Comment by markylaing** [comment]
> @markylaing in order to review this please can I have some context as to why this is needed? Are you basically needing to filter on the joined table?

@tomponline I've created #10844 which describes the problem and yes I need to filter on the joined table because it is also one of the tagged "primary keys".

**Comment by tomponline** [comment]
> 

Sorry I saw that, but I updated my post with further questions.
I'm trying to understand what is new/changed that means you need this whereas we didn't need this before with LXD?
Why are you needing to filter on a joined field whereas presumably we didn't need that before.

**Comment by tomponline** [comment]
Also @markylaing is this related to https://github.com/lxc/lxd/pull/10841

**Comment by markylaing** [comment]
This is related to, but not the same as #10841. In fact, #10841 addresses specifically the assumptions that I made (and commented on) in this pull request.

**Comment by tomponline** [comment]
> In fact, #10841 addresses specifically the assumptions that I made (and commented on) in this pull request.

Can you clarify so I've got the whole picture, which assumptions does it address? Thanks

**Comment by markylaing** [comment]
> > In fact, #10841 addresses specifically the assumptions that I made (and commented on) in this pull request.
> 
> Can you clarify so I've got the whole picture, which assumptions does it address? Thanks

Sorry, in this pull request I've made the assumption that a column which is a foreign key for table `thing` is named `thing_id`. (So it takes the singular and appends `_id`). #10841 looks like it allows specifying this column name.

File: lxd/db/generate/db/stmt.go [hunk 1]
```diff
@@ -268,7 +273,14 @@ func (s *Stmt) create(buf *file.Buffer, replace bool) error {
...
 	for i, field := range fields {
 		if field.IsScalar() {
-			ref := lex.Snake(field.Name)
+			joinTable, _, err := field.ScalarTableColumn()
+			if err != nil {
+				return err
+			}
+
+			// Assumes that the reference column for table "things" is of the form "thing_id"
+			ref := lex.Singular(joinTable)
```
Comment (tomponline) [inline lxd/db/generate/db/stmt.go:282]: Do we still need this if its handled by https://github.com/lxc/lxd/pull/10841

Comment (markylaing) [reply lxd/db/generate/db/stmt.go:282]: I'm honestly not sure. It depends if we want to be prescriptive about how the joins are made (i.e. every db tag containing `join`/`leftjoin` must have an accompanying `joinon`). Otherwise we can use `joinon` if it exists and fallback to making this assumption.

Comment (tomponline) [reply lxd/db/generate/db/stmt.go:282]: My vote would be for being prescriptive and removing the magic :)

Comment (markylaing) [reply lxd/db/generate/db/stmt.go:282]: Sure, I can update this once #10841 is merged. FYI that will require adding `joinon` to many LXD structs e.g. profiles will become:
```go
type Profile struct {
	ID          int
	ProjectID   int    `db:"omit=create,update"`
	Project     string `db:"primary=yes&join=projects.name&joinon=project_id"`
	Name        string `db:"primary=yes"`
	Description string `db:"coalesce=''"`
}
```

Comment (tomponline) [reply lxd/db/generate/db/stmt.go:282]: That sounds good thanks

Comment (masnax) [reply lxd/db/generate/db/stmt.go:282]: Note removing this logic that this would currently break snapshots, and it would need its own manual query I believe.

File: lxd/db/generate/db/stmt.go [hunk 2]
```diff
@@ -384,10 +384,14 @@ func (s *Stmt) update(buf *file.Buffer) error {
...
-			ref := lex.Snake(field.Name)
-			updates[i] = fmt.Sprintf("%s_id = ", ref)
-			updates[i] += fmt.Sprintf("(SELECT id FROM %s WHERE name = ?)", lex.Plural(ref))
+			table, column, err := field.ScalarTableColumn()
+			if err != nil {
+				return err
+			}
+
+			// Assumes that the reference column for table "things" is of the form "thing_id"
+			updates[i] = fmt.Sprintf("%s_id = ", lex.Singular(table))
```
Comment (masnax) [inline lxd/db/generate/db/stmt.go:396]: This could also be updated once the `joinon` change is merged:
```go
columnName := field.Config.Get("joinon")
if columnName == "" {
  columnName = fmt.Sprintf("%s_id", lex.Singular(table))
}

updates[i] = fmt.Sprintf("%s = ", columnName)
```

Comment (tomponline) [reply lxd/db/generate/db/stmt.go:396]: Sounds good

Comment (tomponline) [reply lxd/db/generate/db/stmt.go:396]: Thats merged now

**Review by masnax — APPROVED** [review]
LGTM!

File: lxd/db/generate/db/mapping.go [hunk 3]
```diff
@@ -273,6 +273,25 @@ func (f *Field) Column() string {
...
 
+// ScalarTableColumn gets the table and column from the join configuration.
+func (f Field) ScalarTableColumn() (string, string, error) {
+	join := f.Config.Get("join")
+	if join == "" {
+		join = f.Config.Get("leftjoin")
+	}
+
+	if join == "" {
+		return "", "", fmt.Errorf("Missing join config")
```
Comment (tomponline) [inline lxd/db/generate/db/mapping.go:284]: Will this error get wrapped with the field's name or should we add it here, so that if this failure occurs we know which field its for.

File: lxd/db/generate/db/mapping.go [hunk 4]
```diff
@@ -273,6 +273,25 @@ func (f *Field) Column() string {
 	return column
 }
 
+// ScalarTableColumn gets the table and column from the join configuration.
+func (f Field) ScalarTableColumn() (string, string, error) {
+	join := f.Config.Get("join")
```
Comment (tomponline) [inline lxd/db/generate/db/mapping.go:278]: I've seen this pattern quite a bit, shall we add a function that centralizes this rather than duplicating the logic in multiple places?

**Review by tomponline — APPROVED** [review]
Apart from small nits that can go in a separate PR this LGTM.

File: lxd/db/generate/db/mapping.go (hunk 3 above)
Comment (markylaing) [reply lxd/db/generate/db/mapping.go:284]: It's not wrapped so I'll add it here.

File: lxd/db/generate/db/mapping.go [hunk 5]
```diff
@@ -273,6 +273,25 @@ func (f *Field) Column() string {
...
+		join = f.Config.Get("leftjoin")
+	}
+
+	if join == "" {
+		return "", "", fmt.Errorf("Missing join config")
+	}
+
+	joinFields := strings.Split(join, ".")
+	if len(joinFields) != 2 {
+		return "", "", fmt.Errorf("Join config must be of the format <table>.<column>")
```
Comment (tomponline) [inline lxd/db/generate/db/mapping.go:289]: See above, but same point about field name.

File: lxd/db/generate/db/stmt.go [hunk 6]
```diff
@@ -470,13 +502,17 @@ func whereClause(fields []*Field) string {
 
 	for i, field := range directFields {
 		if field.IsScalar() {
-			ref := lex.Snake(field.Name)
-			refTable := entityTable(ref, "")
-			subSelect := fmt.Sprintf("SELECT %s.id FROM %s", refTable, refTable)
+			joinTable, joinColumn, err := field.ScalarTableColumn()
+			if err != nil {
+				return "", err
```
Comment (tomponline) [inline lxd/db/generate/db/stmt.go:507]: Maybe wrap the error with field name here?

File: lxd/db/generate/db/stmt.go [hunk 7]
```diff
@@ -181,7 +181,12 @@ func (s *Stmt) objects(buf *file.Buffer) error {
 		orderBy = make([]string, len(nk))
 		for i, field := range nk {
 			if field.IsScalar() {
-				orderBy[i] = lex.Plural(lex.Snake(field.Name)) + ".id"
+				table, _, err := field.ScalarTableColumn()
+				if err != nil {
+					return err
```
Comment (tomponline) [inline lxd/db/generate/db/stmt.go:186]: Maybe wrap the error with field name here?

File: lxd/db/generate/db/stmt.go (hunk 6 above)
Comment (masnax) [reply lxd/db/generate/db/stmt.go:507]: I think we can wrap the struct name here (and below) with `mapping.Name`, and include the field name in the function's own errors.

Comment (markylaing) [reply lxd/db/generate/db/stmt.go:507]: Can do but the field name is in the `Field` struct already so may as well include it in the error string.

Comment (tomponline) [reply lxd/db/generate/db/stmt.go:507]: OK.

**Comment by markylaing** [comment]
@tomponline @masnax should be good to go

File: lxd/db/generate/db/stmt.go [hunk 8]
```diff
@@ -289,8 +289,18 @@ func (s *Stmt) create(buf *file.Buffer, replace bool) error {
...
+			}
+
+			ref := lex.Singular(joinTable)
+			referenceColumn := field.Config.Get("joinon")
+			if referenceColumn == "" {
+				referenceColumn = ref + "_id"
+			}
+
+			columns[i] = referenceColumn
 			table := entityTable(ref, "")
```
Comment (masnax) [inline lxd/db/generate/db/stmt.go:304]: Can you please remove this `table := entityTable(ref, "")` and just use `joinTable` above? Since we're specifying the table name anyway, we shouldn't try to generate it.

Comment (stgraber) [reply lxd/db/generate/db/stmt.go:304]: I'll push a commit to @markylaing that does that so we don't have to wait until tomorrow

**Comment by stgraber** [comment]
Made the change, rebased on master and pushed.
If jenkins is happy, we should be good to go on this one.

**Review by tomponline — APPROVED** [review]
