### PR TITLE
lxd: Check if warning exists before acknowledging it

### LINKED ISSUE #11785: `lxc warning ack` always returns 0 even for nonexistent warnings
# Issue description

Ack'ing an nonexistent warning should error out.

# Steps to reproduce

```
$ lxc warning show foo; echo $?
Error: Warning not found
1

$ lxc warning ack foo; echo $?
0
```

# Information to attach

```
$ snap list lxd; uname -a
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.14-7072c7b  24918  latest/stable  canonical✓  -
Linux sdeziel-lemur 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #11785

Now:
```
$ lxc warning ack foo
Error: Warning not found
```

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Review by tomponline — CHANGES_REQUESTED** [review]
Hrm, should `remoteServer.UpdateWarning` fail if the warning doesn't exist?

Seems like the current fix is covering over the underlying problem.

File: lxd/warnings.go [hunk 1]
```diff
@@ -362,7 +362,12 @@ func warningPut(d *Daemon, r *http.Request) response.Response {
 	}
 
 	err = s.DB.Cluster.Transaction(context.TODO(), func(ctx context.Context, tx *db.ClusterTx) error {
-		err := tx.UpdateWarningStatus(id, status)
+		_, err := cluster.GetWarning(ctx, tx.Tx(), id)
+		if err != nil {
+			return err
+		}
+
+		err = tx.UpdateWarningStatus(id, status)
```
Comment (tomponline) [inline lxd/warnings.go:370]: @gabrielmougard please can you look into why this function call does not return a not found error when the `id` doesn't exist. We shouldn't need to use `GetWarning` first.

File: lxd/db/warnings.go [hunk 2]
```diff
@@ -120,11 +120,20 @@ func (c *Cluster) UpsertWarning(nodeName string, projectName string, entityTypeC
...
 		return fmt.Errorf("Failed to update warning status for warning %q: %w", UUID, err)
 	}
 
+	rowsAffected, err := res.RowsAffected()
+	if err != nil {
+		return fmt.Errorf("Failed to get affected rows to update warning status %q: %w", UUID, err)
+	}
+
+	if rowsAffected == 0 {
+		return fmt.Errorf("Warning %q not found", UUID)
```
Comment (tomponline) [inline lxd/db/warnings.go:134]: Please use:

```
return api.StatusErrorf(http.StatusNotFound, "Warning not found")
```
