### PR TITLE
Instance: Add KVM module check for VMs

### LINKED ISSUE #8899: QEMU dependency check for creating VMs
I was trying to check to see if a host supports virtual machines or not using the HOST API call, on the host in a parallels VM it still reports QEMU and virtual-machine despite it not going to work. Can we added some validation here and some way to identify properly if this is supported.

```
jsharief@ubuntu-zfs:~$ lxc launch images:ubuntu/focal test --vm
Creating test
Starting test                                 
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/20330/bin/qemu-system-aarch64 -S -name test -uuid 73537b0e-e93d-4a37-9988-3e3d022da6c4 -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/test/qemu.conf -spice unix=on,disable-ticketing=on,addr=/var/snap/lxd/common/lxd/logs/test/qemu.spice -pidfile /var/snap/lxd/common/lxd/logs/test/qemu.pid -D /var/snap/lxd/common/lxd/logs/test/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/test -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: char device redirected to /dev/pts/8 (label console)
: Process exited with a non-zero value
Try `lxc info --show-log local:test` for more info
jsharief@ubuntu-zfs:~$ lxc info --show-log local:test
Name: test
Location: none
Remote: unix://
Architecture: aarch64
Created: 2021/06/16 14:46 UTC
Status: Stopped
Type: virtual-machine
Profiles: default

Log:

Could not access KVM kernel module: No such file or directory
qemu-system-aarch64: failed to initialize kvm: No such file or directory
````

### PR DESCRIPTION
**Pull request by tomponline**
- Only indicate instance drivers that are operational in `lxc info` (`/1.0` API endpoint) output.
- Add detection for present of `/dev/kvm` and `vhost_vsock` module for `qemu` instance driver support.
- Prevents creation of instances where there is no operational supported driver for that instance type.

This ensures that you cannot copy a VM to a server that doesn't support it:

```
lxc copy va v2:
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported
```

Fixes #8899

### CODE REVIEW

**Comment by jamielsharief** [comment]
Should I put a feature request for the LXC copy command to check remote host if it supports it?

**Comment by tomponline** [comment]
@jamielsharief this is still in draft I've not finished it yet.

File: lxd/instance/drivers/driver_qemu.go [hunk 1]
```diff
@@ -5543,31 +5543,38 @@ func (d *qemu) writeInstanceData() error {
...
 	out, err := exec.Command(qemuPath, "--version").Output()
 	if err != nil {
+		data.Error = fmt.Errorf("Failed getting QEMU version")
 		return data
 	}
 
 	qemuOutput := strings.Fields(string(out))
 	if len(qemuOutput) < 4 {
-		data.Version = "unknown"
+		data.Version = "unknown" // Not necessarily an error that should prevent us using driver.
```
Comment (stgraber) [inline lxd/instance/drivers/driver_qemu.go:5582]: But it will still be treated as such since you initialize `Error` with `Unknown error` at the beginning.
So if an unknown version should be accepted, this needs to do `data.Error = nil`

File: lxd/instance/drivers/driver_qemu.go [hunk 2]
```diff
@@ -5547,6 +5547,11 @@ func (d *qemu) Info() instance.Info {
 		Error: fmt.Errorf("Unknown error"),
 	}
 
+	if !shared.PathExists("/dev/kvm") {
+		data.Error = fmt.Errorf("kvm kernel module not loaded")
```
Comment (stgraber) [inline lxd/instance/drivers/driver_qemu.go:5552]: Maybe `KVM support is missing`? As the module could be loaded with the platform not supporting it.

File: lxd/instance/instance_utils.go [hunk 3]
```diff
@@ -920,6 +920,11 @@ func ValidName(instanceName string, isSnapshot bool) error {
 // Accepts a reverter that revert steps this function does will be added to. It is up to the caller to call the
 // revert's Fail() or Success() function as needed.
 func CreateInternal(s *state.State, args db.InstanceArgs, revert *revert.Reverter) (Instance, error) {
+	// Check instance type requested is supported by this machine.
+	if _, supported := s.InstanceTypes[args.Type]; !supported {
+		return nil, fmt.Errorf("Instance type %q is not supported", args.Type)
```
Comment (stgraber) [inline lxd/instance/instance_utils.go:925]: `is not supported on this server`? So it doesn't look too confusing in a cluster.

**Comment by stgraber** [comment]
@tomponline just a few minor nits/tweaks

File: lxd/instance/drivers/driver_qemu.go (hunk 1 above)
Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:5582]: Oh yes good spot!

File: lxd/instance/instance_utils.go (hunk 3 above)
Comment (tomponline) [reply lxd/instance/instance_utils.go:925]: good idea

**Comment by tomponline** [comment]
Thanks, those are fixed now.

**Comment by jamielsharief** [comment]
I have had a look at the code, if my understanding is correct, the API result from GET /1.0  which now only show  `lxc | qemu` if the host supports virtual machine, is this correct?

**Comment by jamielsharief** [comment]
Also, this will be in latest 4.16 and stable 4.0.7?

**Comment by tomponline** [comment]
Yes that is correct.

**Comment by jamielsharief** [comment]
People using the other channels like latest etc, is it likely any of them using an older release with similar version number e.g. 4.0.8? I am just trying to figure out using `server_version` wether or not this patch has been applied?

**Comment by tomponline** [comment]
@stgraber shall we do an api extension for this?

**Comment by stgraber** [comment]
We can do an API extension for it if that's useful. We definitely don't want folks to make assumptions based on LXD version.

**Comment by tomponline** [comment]
OK will add one.

**Comment by jamielsharief** [comment]
Thank you. I believe it is useful because in all versions it reports QEMU regardless if to works.  This could be dangerous, for example, if user tries to move the VM to a host that does not support VMs, when it gets to the other end and it does not work, it will be a problem. With this new API endpoint the `LXC move` could warn the user if the endpoint is not available, and ask for confirmation to continue, to prevent intentionally corrupting the VM.

**Comment by tomponline** [comment]
This PR already prevents moving/copying a VM to an instance that doesn't support QEMU, see above:

"Prevents creation of instances where there is no operational supported driver for that instance type."

**Comment by jamielsharief** [comment]
> This PR already prevents moving/copying a VM to an instance that doesn't support QEMU, see above:
> 
> "Prevents creation of instances where there is no operational supported driver for that instance type."
> 
> It will check before starting the copy/move and return an error.

How can I check from the API?  That is why i was checking the version number.

**Comment by tomponline** [comment]
@jamielsharief that is what I'm going to add, which was todays discussion.

**Comment by jamielsharief** [comment]
Sorry I am confused, the PR says it is closed and complete. How is the LXC move command protected if this feature does not exist?

**Comment by jamielsharief** [comment]
Ahh, I think i understand, you added separate code to the move command which does not rely upon the API?

**Comment by tomponline** [comment]
It exists internally, just not exposed via API (which is what we are discussing adding now so you can interrogate the API to check, potentially avoiding the need to even attempt the operation. However if you do, on a server that doesn't support QEMU it will return a remote error and terminate the transfer).

**Comment by jamielsharief** [comment]
Just to confirm, so from this new version, if I copy a VM via the API, and the remote host does not support QEMU, it will fail, similar to copying a container with a different architecture?

**Comment by tomponline** [comment]
Yes, see example in https://github.com/lxc/lxd/pull/8919#issue-673408967
