### PR TITLE
zfs: improve dummy dataset creation

### LINKED ISSUE #3399: zfs: incorrect mountpoint on dummy datasets when using existing zfs pool with mountpoint set
Trying to get LxD running on Debian Stretch with zfs-dkms

fresh install of Debian Testing (Stretch) today (12th of June 2017).
Updated kernal to 4.9.0-3 - because after installation system is running with 4.9.0-2 and with that zfs-installation doesn't work

```
root@alarich ~ # uname -a
Linux alarich 4.9.0-3-amd64 #1 SMP Debian 4.9.30-1 (2017-06-04) x86_64 GNU/Linux
```
then installed zfs:
```apt-get install zfs-dkms```

-> is running well

added pool and datasets:
```
root@alarich ~ # zpool create -f -m /var/zpool1 zpool1 raidz /dev/sda4 .... (4 devices)
root@alarich ~ # zpool list
NAME     SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT                                                                                                            
zpool1  1.64T   374K  1.64T         -     0%     0%  1.00x  ONLINE  -     
```

Added datasets:
```
root@alarich ~ # zfs create zpool1/vmail -o mountpoint=/var/vmail
root@alarich ~ # zfs create zpool1/www -o mountpoint=/var/www
root@alarich ~ # zfs create zpool1/lxd -o mountpoint=/var/lxd
```
install lxd from snap
aptitude install snapd
snap install core lxd

and then initialize lxd with existing zfs-pool

```
root@alarich ~ # lxd init
root@alarich ~ # lxd init                                                                                                                                                              
Do you want to configure a new storage pool (yes/no) [default=yes]?                                                                                                                    
Name of the new storage pool [default=default]: store                                                                                                                                 
Name of the storage backend to use (dir, btrfs, zfs) [default=zfs]:                                                                                                                    
Create a new ZFS pool (yes/no) [default=yes]? no                                                                                                                                       
Name of the existing ZFS pool or dataset: zpool1/lxd                                                                                                                                   
Would you like LXD to be available over the network (yes/no) [default=no]? yes                                                                                                         
Address to bind LXD to (not including port) [default=all]:                                                                                                                             
Port to bind LXD to [default=8443]:                                                                                                                                                    
Trust password for new clients:                                                                                                                                                        
Again:                                                                                                                                                                                 
Would you like stale cached images to be updated automatically (yes/no) [default=yes]?                                                                                                 
Would you like to create a new network bridge (yes/no) [default=yes]?                                                                                                                  
What should the new bridge be called [default=lxdbr0]?                                                                                                                                 
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?                                                                                              
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?                                                                                              
error: Failed to create ZFS filesystem: cannot mount '/var/lxd/containers': failed to create mountpoint                                                                                
filesystem successfully created, but not mounted
```

creating the zfs datasets doesn't work in this case...
I already set up a system with Ubuntu 17.04, installed zfs from default packages and also lxd -> there it worked.

regards

```
root@alarich ~ # lxc info
config:                                                                                                                                                                                
  core.trust_password: true                                                                                                                                                            
api_extensions:                                                                                                                                                                        
- storage_zfs_remove_snapshots                                                                                                                                                         
- container_host_shutdown_timeout                                                                                                                                                      
- container_syscall_filtering                                                                                                                                                          
- auth_pki                                                                                                                                                                             
- container_last_used_at                                                                                                                                                               
- etag                                                                                                                                                                                 
- patch                                                                                                                                                                                
- usb_devices                                                                                                                                                                          
- https_allowed_credentials                                                                                                                                                            
- image_compression_algorithm                                                                                                                                                          
- directory_manipulation                                                                                                                                                               
- container_cpu_time                                                                                                                                                                   
- storage_zfs_use_refquota                                                                                                                                                             
- storage_lvm_mount_options                                                                                                                                                            
- network                                                                                                                                                                              
- profile_usedby                                                                                                                                                                       
- container_push                                                                                                                                                                       
- container_exec_recording                                                                                                                                                             
- certificate_update                                                                                                                                                                   
- container_exec_signal_handling                                                                                                                                                       
- gpu_devices                                                                                                                                                                          
- container_image_properties                                                                                                                                                           
- migration_progress                                                                                                                                                                   
- id_map                                                                                                                                                                               
- network_firewall_filtering                                                                                                                                                           
- network_routes                                                                                                                                                                       
- storage                                                                                                                                                                              
- file_delete                                                                                                                                                                          
- file_append                                                                                                                                                                          
- network_dhcp_expiry                                                                                                                                                                  
- storage_lvm_vg_rename                                                                                                                                                                
- storage_lvm_thinpool_rename                                                                                                                                                          
- network_vlan                                                                                                                                                                         
- image_create_aliases                                                                                                                                                                 
- container_stateless_copy                                                                                                                                                             
- container_only_migration                                                                                                                                                             
- storage_zfs_clone_copy                                                                                                                                                               
- unix_device_rename                                                                                                                                                                   
- storage_lvm_use_thinpool                                                                                                                                                             
- storage_rsync_bwlimit                                                                                                                                                                
- network_vxlan_interface                                                                                                                                                              
- storage_btrfs_mount_options                                                                                                                                                          
- entity_description                                                                                                                                                                   
- image_force_refresh                                                                                                                                                                  
- storage_lvm_lv_resizing                                                                                                                                                              
api_status: stable                                                                                                                                                                     
api_version: "1.0"                                                                                                                                                                     
auth: trusted                                                                                                                                                                          
public: false                                                                                                                                                                          
environment:                                                                                                                                                                           
  addresses: []                                                                                                                                                                        
  architectures:                                                                                                                                                                       
  - x86_64                                                                                                                                                                             
  - i686                                                                                                                                                                               
  certificate: |                                                                                                                                                                       
    -----BEGIN CERTIFICATE-----                                                                                                                                                        
    MIIFVjCCAz6gAwIBAgIRAPNRjsOYoqNuKFfjLsltoqEwDQYJKoZIhvcNAQELBQAw                                                                                                                   
    NTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBh                                                                                                                   
    bGFyaWNoMB4XDTE3MDYxMjE0MzgyNFoXDTI3MDYxMDE0MzgyNFowNTEcMBoGA1UE                                                                                                                   
    ChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBhbGFyaWNoMIIC                                                                                                                   
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsUhhcaPPLBv11sijv+CRkpkD                                                                                                                   
    OqyDGoQFpkiWqZVVJfh0pUWMTbLNCpBrjb0F3CtLYI5+p5uhU4+PcJ4IhE77XMA5                                                                                                                   
    tqD/PSHlmvzqPqpcmUjCNFIzl2hwXwNLGjPORXscjGjwSNv9KIAaqDZ11po8c8rc                                                                                                                   
    bQRMVNhuHYvZzeWZ1YBjBeoh8aSwTAiDmnjo7yTwA8akDig+/nL19XPB4YZ7gnoo                                                                                                                   
    Ho8aEQxClK546gBsfISGhDy/2+t38P21Dwu2dWiNGLfdj7w9u2D4ZNR9IVvJkF4N                                                                                                                   
    BpV2BKhwu4RNp0AMx5z4B6p+HbI/Ejr5sAs55ym7wfYn82sfDxNJauP1a9dbB8Qm                                                                                                                   
    lwD/5lej+34e3lmrltWEzV29tkQuPTyNndm+QgE/3GJZGvvU+j0XQjMC37csa9BX                                                                                                                   
    nZ+z/THFZ/56IyFfeaeZBo87klZ7g8JLrmNJlK8WhkKOE9sQ/AgYzx5IjdggsmW5                                                                                                                   
    bQgBEREJzbBf86DBir2zB5/tQmtbu7Hvl70mm/n8vr1IzJbuXclp9TfW3WV26frY                                                                                                                   
    JisHoTSr435fqcx+yHZqTtNoBQh9zCreoUjoBUU37SpdCHCUyeIzA47qrkcHqzdc                                                                                                                   
    8Om5kAVExWG1FqjrU1EOHmcd1K0G3feHz5opk3DCdMsXjnYr+KIgfgHNvsbLDd5R                                                                                                                   
    b/jHDqqhjLODbZ0YxYcCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQM                                                                                                                   
    MAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwKgYDVR0RBCMwIYIHYWxhcmljaIcE                                                                                                                   
    XoIIFIcQKgEE+AELDFgAAAAAAAAAAjANBgkqhkiG9w0BAQsFAAOCAgEAEEI4P053                                                                                                                   
    4GPf7ktWtkHwtZNdJ86KA+6hZkc4mZxpz6TN7jqJhfgeQetuy/KWLRAPiCY820TE                                                                                                                   
    2MzC8WC48Pzj02dczdZJACNdS2G8I4Ng/Y6wbXqAEIJ5MiwQf1W7vKd4xtTZQerq                                                                                                                   
    IIGdypYXQJcnvpvk6hNpi7qyCczxAQ8Emo77WUcKL1AJPikzUa34E6nbuXIq+l7R                                                                                                                   
    abY8KamCDWcGaOtW82xYn4DGhMJA0IK4PK2SvZPCN8h/Nn+8VaZEdZHA0TKXQbOU                                                                                                                   
    ug540GxZEgCmNVlD8ez67hK9VYiv/XJaO+511ube9tg3YqMGBNcNTlIuMRItFW8y                                                                                                                   
    UVfoMsBM2A54rx2Hk/TAbSrIWQWOqiAUvpkabFysNQqkb7OB4psUQhq5Rfz40pvy                                                                                                                   
    12RtHAwdGhbi6Wa2q6GUIpsCA3GjndYNybCkPWnf0F1Ef1IgRjA6PrRnNVGEspl7                                                                                                                   
    VZCaOm/Rn8W9r/TuMoBqzwJBM/sPudW6NafuYMe7BL15bPtQrC7duewaPbuSbZRK                                                                                                                   
    JBomqsgUsKDZ814J8babDcoXLJ+5WudWlRaX+oN096Qvc9wnw9rCkfCUZLqvyPPB                                                                                                                   
    nuNTmayWkajUnz4Oryjtnm/5op8mOxj33inRoVuUvli55KcgCC7sjNgvDGTuZEo4                                                                                                                   
    xnUvi0N6SNhxxMFxrsc4luQJVtWYoZ2N2DQ=                                                                                                                                               
    -----END CERTIFICATE-----                                                                                                                                                          
  certificate_fingerprint: 337b675bc5ceffdbf3838b394bf1191d00fe2b9f9d70b30cd63cd632cea1ee48                                                                                            
  driver: lxc                                                                                                                                                                          
  driver_version: 2.0.8                                                                                                                                                                
  kernel: Linux                                                                                                                                                                        
  kernel_architecture: x86_64                                                                                                                                                          
  kernel_version: 4.9.0-3-amd64                                                                                                                                                        
  server: lxd                                                                                                                                                                          
  server_pid: 6168                                                                                                                                                                     
  server_version: "2.14"                                                                                                                                                               
  storage: ""                                                                                                                                                                          
  storage_version: ""
```

### PR DESCRIPTION
**Pull request by brauner**
Instead of creating the dataset and then setting its mountpoint let's create
the dataset with the mountpoint right away.

Closes #3399.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, good to go.

File: test/main.sh [hunk 1]
```diff
@@ -591,7 +591,7 @@ if [ "$#" -gt 0 ]; then
 fi
 
 run_test test_check_deps "checking dependencies"
-run_test test_static_analysis "static analysis"
+# run_test test_static_analysis "static analysis"
```
Comment (stgraber) [inline test/main.sh]: Hmm, what? :)

Comment (brauner) [inline test/main.sh]: oh f*ck, I had to disable the static check locally because of a broken xgettext. Will update in a sec second :)

Comment (brauner) [inline test/main.sh]: done

File: lxd/storage_zfs.go [hunk 2]
```diff
@@ -1842,75 +1842,73 @@ func (s *storageZfs) zfsPoolCreate() error {
...
-	err := s.zfsPoolVolumeCreate("containers")
-	if err != nil {
-		return err
-	}
-
-	err = s.zfsPoolVolumeSet("containers", "mountpoint", "none")
+	poolName := s.getOnDiskPoolName()
+	dataset := fmt.Sprintf("%s/containers", poolName)
+	fixperms := shared.VarPath("storage-pools", s.pool.Name, "containers")
+	msg, err := zfsPoolVolumeCreate(dataset, fmt.Sprintf("mountpoint=%s", fixperms))
```
Comment (stgraber) [inline lxd/storage_zfs.go]: So why do we set this one? I thought every container filesystem we create has a mountpoint= directly set on it, making it unnecessary for us to set a mountpoint on the parent.

Comment (brauner) [inline lxd/storage_zfs.go]: This is for the case where the user has set mountpoints on already existing dataset that would be inherited by the suddatasets. I do however, now that I see this, think that all of those subdatasets should have `mountpoint=none` including the pool when reusing an existing one.

Comment (stgraber) [inline lxd/storage_zfs.go]: Yeah, my question wasn't about setting mountpoint or not, it was about why not setting this one to =none too. Sorry I wasn't clear.

Comment (brauner) [inline lxd/storage_zfs.go]: NP, totally fair point. I just pointlessly replicated the same mistake I made when writing the original code in a more concise manner. :) I'll send an updated branch and also make sure that mountpoints of existing pools and datasets will be cleared as well.

**Comment by stgraber** [comment]
Jenkins looks unhappy

**Comment by brauner** [comment]
Looks finally good to go.
