### PR TITLE
Don't change permissions of existing containers directory

### LINKED ISSUE #5797: Btrfs mount permission denied due to incorrect permissions on .../containers
# Required information

 * Distribution: Arch linux
 * The output of "lxc info":
```
config:
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICPzCCAcWgAwIBAgIRAP61HvbiUzW9cXFrKujLw+QwCgYIKoZIzj0EAwMwNTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBMdXh1
    cmlhMB4XDTE5MDUyNjIyMjcwNFoXDTI5MDUyMzIyMjcwNFowNTEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBMdXh1cmlhMHYwEAYH
    KoZIzj0CAQYFK4EEACIDYgAESa7S7Em2M1CLImTNqbER+u85ny8UpU9jtAwtr29H
    2ciAXLjjWP5jQE+/xePlEwFemgnO7+vE0Atm/Qs8TbVPVfL271hjhm/UKcysahbV
    B+vULrfCXKEsk2HbP5YOj1w1o4GYMIGVMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMGAGA1UdEQRZMFeCB0x1eHVyaWGH
    BMCoAQqHEP1L6KvTkgAAAAAAAAAADVyHEP1NhFm/xAAAaNY0//7CmCGHECoAECiW
    yv52aNY0//7CmCGHEP1L6KvTkgAAaNY0//7CmCEwCgYIKoZIzj0EAwMDaAAwZQIx
    ANX2O73o8rVwoet0LaDlvCWm7W4Wkix9nMdQCkRL3Baosle54voon+A1ntuNG33R
    LwIwKpOKAC6Khx/wvy5R7aaDmc2mVZl/i+gy0B/zgS1oAu8RgKlntqnxG76SGelp
    rMRY
    -----END CERTIFICATE-----
  certificate_fingerprint: e6c1c67b091b1fc718f9248de24e0ee1eee27b34c3915a5c0de93c7d2795a8fa
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.1.4-arch1-1-ARCH
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_clustered: false
  server_name: Luxuria
  server_pid: 905
  server_version: "3.13"
  storage: btrfs
  storage_version: "4.4"
```

# Issue description

I have migrated containers from AUR/lxd installation of LXD into a snap version of LXD on another machine.
I could then start the containers just fine. After rebooting however, some of the containers fail.
**EDIT: Looks like I can't create and start new containers either with the same error.**

# Steps to reproduce

 1. 'lxc mv' a container from AUR/lxd instance
 2. Try to lxc start a problematic migrated container
 3. Error:
```
[0] % sudo lxc info --show-log pxe
Name: pxe
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/05/26 23:12 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc pxe 20190526235338.286 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc pxe 20190526235338.286 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc pxe 20190526235338.287 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc pxe 20190526235338.287 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc pxe 20190526235338.330 ERROR    dir - storage/dir.c:dir_mount:198 - Permission denied - Failed to mount "/var/snap/lxd/common/lxd/containers/pxe/rootfs" on "/var/snap/lxd/common/lxc/"
lxc pxe 20190526235338.331 ERROR    conf - conf.c:lxc_mount_rootfs:1351 - Failed to mount rootfs "/var/snap/lxd/common/lxd/containers/pxe/rootfs" onto "/var/snap/lxd/common/lxc/" with options "(null)"
lxc pxe 20190526235338.331 ERROR    conf - conf.c:lxc_setup_rootfs_prepare_root:3498 - Failed to setup rootfs for
lxc pxe 20190526235338.331 ERROR    conf - conf.c:lxc_setup:3551 - Failed to setup rootfs
lxc pxe 20190526235338.331 ERROR    start - start.c:do_start:1282 - Failed to setup container "pxe"
lxc pxe 20190526235338.331 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc pxe 20190526235338.372 ERROR    start - start.c:__lxc_start:1975 - Failed to spawn container "pxe"
lxc pxe 20190526235338.372 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:864 - Received container state "ABORTING" instead of "RUNNING"
lxc pxe 20190526235338.373 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc pxe 20190526235338.373 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc 20190526235338.377 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"
```

# Information to attach

 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
```
2019/05/27 02:00:53.335177 cmd_run.go:889: WARNING: cannot copy user Xauthority file: Xauthority file isn't owned by the current user 0
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Archlinux current amd64 (20190213_04:19)
  image.os: Archlinux
  image.release: current
  image.serial: "20190213_04:19"
  volatile.base_image: dd44789451bb561a84228a3f148eec3b144c51ca8607d91bc9ec4d282cc5f628
  volatile.eth0.hwaddr: 00:16:3e:d4:5e:18
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: sysdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
t=2019-05-27T01:51:19+0200 lvl=info msg="LXD 3.13 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2019-05-27T01:51:19+0200 lvl=info msg="Kernel uid/gid map:" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - u 0 0 4294967295" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - g 0 0 4294967295" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Configured LXD uid/gid map:" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - u 0 1000000 1000000000" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - g 0 1000000 1000000000" 
t=2019-05-27T01:51:19+0200 lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Kernel features:" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - uevent injection: yes" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - seccomp listener: yes" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - shiftfs support: no" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Initializing local database" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Starting /dev/lxd handler:" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-05-27T01:51:19+0200 lvl=info msg="REST API daemon:" 
t=2019-05-27T01:51:19+0200 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-05-27T01:51:19+0200 lvl=info msg="Initializing global database" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Initializing storage pools" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Initializing networks" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Pruning leftover image files" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done pruning leftover image files" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Loading daemon configuration" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Started seccomp handler" path=/var/snap/lxd/common/lxd/seccomp.socket
t=2019-05-27T01:51:19+0200 lvl=info msg="Pruning expired images" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done pruning expired images" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Pruning expired container backups" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done pruning expired container backups" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Updating instance types" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Updating images" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done updating instance types" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done updating images" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Expiring log files" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Done expiring log files" 
t=2019-05-27T01:51:19+0200 lvl=info msg="Starting container" action=start created=2019-05-27T00:46:09+0200 ephemeral=false name=ansible project=default stateful=false used=2019-05-27T01:02:21+0200
t=2019-05-27T01:51:19+0200 lvl=info msg="Started container" action=start created=2019-05-27T00:46:09+0200 ephemeral=false name=ansible project=default stateful=false used=2019-05-27T01:02:21+0200
t=2019-05-27T01:51:19+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:14:55+0200
t=2019-05-27T01:51:19+0200 lvl=eror msg="Failed starting container" action=start created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:14:55+0200
t=2019-05-27T01:51:19+0200 lvl=eror msg="Failed to start container 'chris': Failed to run: /snap/lxd/current/bin/lxd forkstart chris /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/chris/lxc.conf: " 
t=2019-05-27T01:51:19+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:40:08+0200 ephemeral=false name=cloud project=default stateful=false used=2019-05-27T01:46:27+0200
t=2019-05-27T01:51:19+0200 lvl=info msg="Started container" action=start created=2019-05-27T01:40:08+0200 ephemeral=false name=cloud project=default stateful=false used=2019-05-27T01:46:27+0200
t=2019-05-27T01:51:19+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:32:42+0200 ephemeral=false name=proxy project=default stateful=false used=2019-05-27T01:35:54+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Started container" action=start created=2019-05-27T01:32:42+0200 ephemeral=false name=proxy project=default stateful=false used=2019-05-27T01:35:54+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:13:28+0200
t=2019-05-27T01:51:20+0200 lvl=eror msg="Failed starting container" action=start created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:13:28+0200
t=2019-05-27T01:51:20+0200 lvl=eror msg="Failed to start container 'pxe': Failed to run: /snap/lxd/current/bin/lxd forkstart pxe /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/pxe/lxc.conf: " 
t=2019-05-27T01:51:20+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:27:21+0200 ephemeral=false name=tt-rss project=default stateful=false used=2019-05-27T01:31:27+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Started container" action=start created=2019-05-27T01:27:21+0200 ephemeral=false name=tt-rss project=default stateful=false used=2019-05-27T01:31:27+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Container initiated stop" action=stop created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:51:19+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:15:12+0200 ephemeral=false name=wekan project=default stateful=false used=2019-05-27T01:20:46+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Started container" action=start created=2019-05-27T01:15:12+0200 ephemeral=false name=wekan project=default stateful=false used=2019-05-27T01:20:46+0200
t=2019-05-27T01:51:20+0200 lvl=info msg="Container initiated stop" action=stop created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:51:20+0200
t=2019-05-27T01:53:08+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:51:19+0200
t=2019-05-27T01:53:08+0200 lvl=eror msg="Failed starting container" action=start created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:51:19+0200
t=2019-05-27T01:53:09+0200 lvl=info msg="Container initiated stop" action=stop created=2019-05-27T01:13:40+0200 ephemeral=false name=chris project=default stateful=false used=2019-05-27T01:53:08+0200
t=2019-05-27T01:53:38+0200 lvl=info msg="Starting container" action=start created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:51:20+0200
t=2019-05-27T01:53:38+0200 lvl=eror msg="Failed starting container" action=start created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:51:20+0200
t=2019-05-27T01:53:38+0200 lvl=info msg="Container initiated stop" action=stop created=2019-05-27T01:12:58+0200 ephemeral=false name=pxe project=default stateful=false used=2019-05-27T01:53:38+0200
```
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by freeekanayaka**
This fixes #5797.

Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>

### CODE REVIEW

File: lxd/storage_btrfs.go [hunk 1]
```diff
@@ -2802,7 +2802,7 @@ func (s *storageBtrfs) MigrationSink(conn *websocket.Conn, op *operation, args M
 	}
 
 	containersMntPoint := getContainerMountPoint(args.Container.Project(), s.pool.Name, "")
-	err := createContainerMountpoint(containersMntPoint, args.Container.Path(), args.Container.IsPrivileged())
+	err := createMountpoint(containersMntPoint, args.Container.Path(), args.Container.IsPrivileged(), true)
```
Comment (stgraber) [inline lxd/storage_btrfs.go]: Any idea what this is trying to achieve?

From what I understand, this is creating a symlink from the container's path to the storage-pool's containers path, which seems very odd.

Comment (freeekanayaka) [reply lxd/storage_btrfs.go]: I have no idea, it's very odd indeed, but for the purpose of fixing this bug I wanted to keep the change at minimum and not change existing behavior that I was not sure about.

This PR keeps the semantics of ```createContainerMountpoint``` totally unchanged. So all call sites that "legitimately" use it won't get any surprise.

However the one use of ```createContainerMountpoint``` in this particular spot does not indeed seem to be legitimate: for this case I minimized the change by only running os.Chmod if the directory is created from scratch.

Now, in practice I think that the os.Chmod code path will never be taken, because at least in case of btrfs the ```containers``` directory is created upfront so it should always be there. I also think that if the code path was actually taken (because the directory doesn't exist), that os.Chmod would probably be wrong, but it would match existing behavior.

If you feel confident that we can get rid of this mess altogether by simply dropping this call site (because we can safely assume the containers directory is there and it has the correct permission), I can change the PR accordingly.

Comment (stgraber) [reply lxd/storage_btrfs.go]: Yeah, this call looks completely bogus to me, if it's there for a reason, we have a much deeper issue that we should fix. I'd say, get rid of that weird createContainerMountpoint call, which likely means the rest of this PR can go away. Then lets see if Jenkins is happy with it. We have reasonably good migration testing in place so if it's actually needed for some reason, it should be pretty obvious.

Comment (freeekanayaka) [reply lxd/storage_btrfs.go]: Done. Let's see what jenkins says.

Comment (freeekanayaka) [reply lxd/storage_btrfs.go]: It seems that the call is actually needed, for some reason:

```
Error: Failed container creation: Error transferring container data: stat /lxc-ci/build/tmp.uXGg6Ztljd/go/src/github.com/lxc/lxd/test/tmp.q6Z/ztT/storage-pools/lxdtest-ztT/containers/proj_: no such file or directory
```

see the full [job output](https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/6020/arch=amd64,backend=btrfs,compiler=golang-1.12,restrict=lxd-priv/console#console-section-3).

Comment (stgraber) [reply lxd/storage_btrfs.go]: That's one odd path to be checking, also means that if this is indeed used and two containers are being migrated at the same time, `bad things` will happen.

**Comment by stgraber** [comment]
@freeekanayaka pushed what should be a fix for this to your branch, lets see what Jenkins thinks

**Comment by stgraber** [comment]
Jenkins looks happy with this change and that removes the bit of code that was messing up the permisisons, so I think we can call this good.
