### PR TITLE
Report ovn network state

### LINKED ISSUE #9232: Report OVN network state in /1.0/networks/NAME/state
Currently trying to fetch the network state for an OVN network returns:
```
stgraber@dakara:~$ lxc query s-dcmtl-cluster:/1.0/networks/default/state?project=core
Error: Network interface "default" not found
```

Compare to what we get for a traditional bridge:
```
stgraber@dakara:~$ lxc query /1.0/networks/lxdbr0/state
{
	"addresses": [
		{
			"address": "172.17.250.1",
			"family": "inet",
			"netmask": "24",
			"scope": "global"
		},
		{
			"address": "2602:fc62:b:250::1",
			"family": "inet6",
			"netmask": "64",
			"scope": "global"
		},
		{
			"address": "fe80::216:3eff:fe36:1f28",
			"family": "inet6",
			"netmask": "64",
			"scope": "link"
		}
	],
	"bond": null,
	"bridge": {
		"forward_delay": 1500,
		"id": "8000.00163e361f28",
		"stp": false,
		"upper_devices": [
			"tapf59a5d19",
			"tapfb01853f",
			"veth2cd1b8fd",
			"veth5ef8d6a3",
			"veth6063b243"
		],
		"vlan_default": 1,
		"vlan_filtering": true
	},
	"counters": {
		"bytes_received": 12396298233,
		"bytes_sent": 114815830037,
		"packets_received": 28723462,
		"packets_sent": 43057416
	},
	"hwaddr": "00:16:3e:36:1f:28",
	"mtu": 1500,
	"state": "up",
	"type": "broadcast",
	"vlan": null
}
```

OVN networks are a bit special but we should still be able to:
 - Compute the addresses section from the known virtual router addresses
 - Maybe fill in the counters? (@tomponline is there such a thing on an OVN router?)
 - Fill in the hwaddr, mtu, state and type
 - Add a new `ovn` section which should then expose what server is currently handling the router traffic for the network (@tomponline do you have details on how to fetch that?)

### PR DESCRIPTION
**Pull request by markylaing**
Implements `network.State` for the `OVN` network driver. 

Fixes #9232 when paired with #9817.

### CODE REVIEW

**Comment by markylaing** [comment]
@stgraber @tomponline would you mind doing a quick sanity check on this? I'll fix up the commits if I am on the right track.

One thing I was particularly confused about was finding the addresses. I can see them listed under `state.network` when I run `lxc query /1.0/instances/c1?recursion=1` but I couldn't figure out where that info came from. I ended up getting the addresses from `Address_Set` in the southbound database instead.

**Comment by tomponline** [comment]
Can you always link to the issue being worked on in the pr description so we can use it as a refresher for the reviewer to remember what this is about and his we agrees to solve it. Thanks

File: lxd/network/openvswitch/ovn.go [hunk 1]
```diff
@@ -2047,3 +2082,192 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
 
 	return nil
 }
+
+// GetHardwareAddress gets the mac address of the ovn managed network.
+func (o *OVN) GetHardwareAddress(networkID int64) (string, error) {
+	nameFilter := fmt.Sprintf("name=lxd-net%d-lr-lrp-ext", networkID)
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2088]: O could be wrong but I think the ovn client library doesn't previously have the concept of network Id as is supposed to not be tightly coupled to lxds network concepts.

File: lxd/networks.go [hunk 2]
```diff
@@ -1488,11 +1488,26 @@ func networkStateGet(d *Daemon, r *http.Request) response.Response {
...
-	if err != nil {
-		return response.SmartError(err)
+	projectName := queryParam(r, "project")
+	if projectName == "" {
+		projectName = project.Default
+	}
+
+	var state *api.NetworkState
+	var err error
+	n, networkLoadError := network.LoadByName(d.State(), projectName, networkName)
```
Comment (tomponline) [inline lxd/networks.go:1500]: I would put this and the associated interface changes up as a separate PR to separate them from the ovn specific changes. Makes reviewing easier.

File: lxd/network/openvswitch/ovs.go [hunk 3]
```diff
@@ -352,3 +352,18 @@ func (o *OVS) HardwareOffloadingEnabled() bool {
 
 	return offload == "true"
 }
+
+// OVNRemoteAddress gets the address of the southbound ovn database.
+func (o *OVS) OVNRemoteAddress() (string, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovs.go:357]: Can you call this OVNSouthboundDBRemoteAddress

File: lxd/network/openvswitch/ovn.go [hunk 4]
```diff
@@ -2047,3 +2082,192 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+		if row["_uuid"] == chassisID {
+			return row["name"], nil
+		}
+	}
+
+	return "", fmt.Errorf("couldn't get chassis")
+}
+
+// GetAddresses gets the addresses present in the ovn network.
+func (o *OVN) GetAddresses(networkID int64) ([]api.NetworkStateAddress, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2177]: Can u get these from the network config in lxd db. What way is it different to this?

File: lxd/network/openvswitch/ovn.go [hunk 5]
```diff
@@ -2047,3 +2082,192 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+
+// GetChassis gets the name of the ovn chassis (host+gateway)
+func (o *OVN) GetChassis(networkID int64) (string, error) {
+	filter := fmt.Sprintf("logical_port=cr-lxd-net%d-lr-lrp-ext", networkID)
+	data, err := o.sbctl("--data=bare", "--format=csv", "find", "Port_Binding", filter)
+	if err != nil {
+		return "", err
+	}
+
+	rows, err := readCSV(data)
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2142]: There could be a lot of ports so we don't really want to be reading the output into memory, can we stream it and process line by line?

File: lxd/network/openvswitch/ovn.go [hunk 6]
```diff
@@ -2047,3 +2082,192 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+	if err != nil {
+		return "", err
+	}
+
+	if len(rows) != 1 || rows[0]["chassis"] == "" {
+		return "", fmt.Errorf("couldn't get chassis")
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2148]: Upper case first char of error

Comment (tomponline) [reply lxd/network/openvswitch/ovn.go:2148]: I tend to used Failed getting or Error getting rather than "couldn't" to aid in language conversion.

File: lxd/network/openvswitch/ovn.go (hunk 4 above)
Comment (markylaing) [reply lxd/network/openvswitch/ovn.go:2177]: Ah I can see where I've gone wrong here. I've extracted the addresses of instances within the subnet instead of just getting the bridge itself.

File: lxd/network/openvswitch/ovn.go (hunk 1 above)
Comment (markylaing) [reply lxd/network/openvswitch/ovn.go:2088]: So it looks like the network id does make it into the OVN name via the following route:

`n.Create` calls `n.setup` which calls `client.ChassisGroupAdd` with `n.getChassisGroupName()` as the OVNChassisgroup argument. `n.getChassisGroupName` then calls `n.getNetworkPrefix` and finally `acl.OVNNetworkPrefix(n.id)`, which returns `lxd-net<id>`.

So I guess with the current version of ovn we can expect to find names that include the chassis group name. Of course this might change, but I'm not sure how to filter the results without it.

What I will do at lease in the meantime is pass in the chassis group name as an argument and use that to create the filter instead.

File: lxd/networks.go (hunk 2 above)
Comment (markylaing) [reply lxd/networks.go]: Done (#9817) and updated the PR description to include it.

File: lxd/network/openvswitch/ovn.go [hunk 7]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+
+		if record.values["_uuid"] == chassisID {
+			return record.values["name"], nil
+		}
+	}
+
+	return "", fmt.Errorf("Error getting chassis id")
+}
+
+func readCSV(data string) chan struct {
```
Comment (markylaing) [inline lxd/network/openvswitch/ovn.go:2183]: I wonder if this might be better placed under `shared/csv` or similar, since it is completely general. What do you think?

File: lxd/network/openvswitch/ovn.go [hunk 8]
```diff
@@ -178,34 +181,66 @@ func NewOVN(s *state.State) (*OVN, error) {
...
-	return o.dbAddr
+	return o.nbDBAddr
+}
+
+// SetSouthboundDBAddress sets the address that runs the OVN northbound databases.
+func (o *OVN) SetSouthboundDBAddress(addr string) {
+	o.sbDBAddr = addr
+}
+
+// getNorthboundDB returns connection string to use for northbound database.
```
Comment (stgraber) [inline lxd/network/openvswitch/ovn.go:218]: Comment doesn't line up with function name

**Comment by stgraber** [comment]
Looks good to me, just one tiny issue with a comment and we need to relocate the CSV bit over to `lxd/util` then this should be good to go.

File: lxd/network/openvswitch/ovn.go [hunk 9]
```diff
@@ -178,34 +181,66 @@ func NewOVN(s *state.State) (*OVN, error) {
...
+func (o *OVN) sbctl(args ...string) (string, error) {
+	return o.xbctl(true, args...)
 }
 
-// nbctl executes ovn-nbctl with arguments to connect to wrapper's northbound database.
 func (o *OVN) nbctl(args ...string) (string, error) {
+	return o.xbctl(false, args...)
+}
+
+// nbctl executes ovn-nbctl with arguments to connect to wrapper's northbound database.
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:235]: This comment also doesn't line up with the function.

File: lxd/network/openvswitch/ovn.go [hunk 10]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
 
 	return nil
 }
+
+// GetHardwareAddress gets the mac address of the ovn managed network.
+func (o *OVN) GetHardwareAddress(chassisGroup OVNChassisGroup) (string, error) {
+	nameFilter := fmt.Sprintf("name=%s-lr-lrp-ext", chassisGroup)
+	data, err := o.nbctl("--data=bare", "--format=csv", "find", "Logical_Router_Port", nameFilter)
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2089]: As you're only extracting a single value, there's no need to use a csv parser here, you can just ask ovn-nbctl for the specific field using `--column=` arg and use `--data=bare` with `--no-headings`. See https://github.com/lxc/lxd/blob/master/lxd/network/openvswitch/ovn.go#L1312 for an example.

File: lxd/network/openvswitch/ovn.go [hunk 11]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+
+		chassisID = record.values["chassis"]
+		i++
+	}
+
+	if i != 1 || chassisID == "" {
+		return "", fmt.Errorf("Error getting chassis id")
+	}
+
+	data, err = o.sbctl("--data=bare", "--format=csv", "find", "Chassis")
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2164]: As you're only extracting a single value, there's no need to use a csv parser here, you can just ask ovn-sbctl for the specific field using --column= arg and use --data=bare with --no-headings. See https://github.com/lxc/lxd/blob/master/lxd/network/openvswitch/ovn.go#L1312 for an example.

File: lxd/network/openvswitch/ovn.go [hunk 12]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+
+	if i != 1 || mac == "" {
+		return "", fmt.Errorf("Error getting hardware address")
+	}
+
+	return mac, nil
+}
+
+// GetMTU gets the mtu of the ovn managed network.
+func (o *OVN) GetMTU(chassisGroup OVNChassisGroup) (int, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2110]: I don't think we need this function as the MTU DHCP/RA options are derived in LXD and save into the bridge.mtu setting here https://github.com/lxc/lxd/blob/master/lxd/network/driver_ovn.go#L1709

File: lxd/network/openvswitch/ovn.go (hunk 7 above)
Comment (tomponline) [reply lxd/network/openvswitch/ovn.go:2183]: I dont think we need this function at all as the functions that use it can be simplified or removed to avoid needing it.

File: lxd/network/openvswitch/ovn.go (hunk 1 above)
Comment (tomponline) [reply lxd/network/openvswitch/ovn.go]: @markylaing yes that was my point, that networkID (as a standalone concept) is not used in the `openvswitch` package directly, but rather OVS/OVN object names are used (which LXD then might choose to embed its networkID into).

My thinking with the `openvswitch` package was to make it a fairly low-level package that deals with configuring/accessing OVN/OVS, rather than implementing LXD's concepts on top. 

So yes, the approach you're using now of passing in the OVN object names to these functions is preferred. Thanks

File: lxd/network/openvswitch/ovn.go (hunk 7 above)
Comment (stgraber) [reply lxd/network/openvswitch/ovn.go:2183]: Even better!

File: lxd/network/openvswitch/ovn.go [hunk 13]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
 
 	return nil
 }
+
+// GetHardwareAddress gets the mac address of the ovn managed network.
+func (o *OVN) GetHardwareAddress(chassisGroup OVNChassisGroup) (string, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2087]: This function should take an `OVNRouterPort` as an argument rather than a `OVNChassisGroup`, it may be used to access the MAC address of any logical router port, not one specific to a chassis group. Lets not pass LXD concepts into this package if we can help it.

Comment (tomponline) [reply lxd/network/openvswitch/ovn.go:2087]: The `ovn` driver in LXD has a `getRouterIntPortName` function that will return the logical router port for the internal network, that can be passed in to this function.

File: lxd/network/openvswitch/ovn.go [hunk 14]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
 
 	return nil
 }
+
+// GetHardwareAddress gets the mac address of the ovn managed network.
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2086]: Please update this comment too. Thanks

File: lxd/network/openvswitch/ovn.go [hunk 15]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+		if record.err != nil {
+			return "", err
+		}
+
+		if record.values["_uuid"] == chassisID {
+			return record.values["name"], nil
+		}
+	}
+
+	return "", fmt.Errorf("Error getting chassis id")
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2180]: Always upper case "id" in errors or user facing messages/documentation. Thanks

File: lxd/network/openvswitch/ovn.go [hunk 16]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+
+	kvPairs := strings.Fields(ipv6RAConfigs)
+	for _, kvPair := range kvPairs {
+		kv := strings.Split(kvPair, "=")
+		if len(kv) == 2 && kv[0] == "mtu" {
+			return strconv.Atoi(kv[1])
+		}
+	}
+
+	return 0, fmt.Errorf("Error getting mtu")
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2137]: We don't need this function, but just for future reference, MTU is an acronym, so just like gofmt, we should upper case it in user facing errors/messages/documentation.

File: lxd/network/openvswitch/ovn.go [hunk 17]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+}
+
+// GetChassis gets the name of the ovn chassis (host+gateway)
+func (o *OVN) GetChassis(chassisGroup OVNChassisGroup) (string, error) {
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2141]: This function should take a `OVNRouterPort` as an argument rather than `OVNChassisGroup` and let the `ovn` network driver generate the port name. You can then use the `ovn` network driver's `getRouterExtPortName` function to generate the port name.

There should be a comment added to the bit where `cr-` is prepended to the logical router port name, explaining why it is doing that (this is because it is looking for the associated "chassis redirect" port for the logical router port).

File: lxd/network/openvswitch/ovn.go [hunk 18]
```diff
@@ -2047,3 +2082,154 @@ func (o *OVN) LogicalRouterPeeringDelete(opts OVNRouterPeering) error {
...
+	}
+
+	records = readCSV(data)
+	for record := range records {
+		if record.err != nil {
+			return "", err
+		}
+
+		if record.values["_uuid"] == chassisID {
+			return record.values["name"], nil
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2176]: We should be extracting the `hostname` field not the `name` field as per https://github.com/lxc/lxd/issues/9232#issuecomment-992696069

File: lxd/network/openvswitch/ovn.go (hunk 17 above)
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:2141]: I think this function should be renamed to GetLogicalRouterPortActiveChassisHostname

File: lxd/network/openvswitch/ovn.go (hunk 12 above)
Comment (markylaing) [reply lxd/network/openvswitch/ovn.go:2110]: In that case shall I error if the config key isn't set? (so it is caught if the preceding logic changes)

Comment (markylaing) [reply lxd/network/openvswitch/ovn.go]: For now I've just returned the result of `n.getBridgeMTU()` which will be zero if the config key is not set.

Comment (stgraber) [reply lxd/network/openvswitch/ovn.go]: If not set, we should return 1500 which is the default value for a MTU.

**Comment by stgraber** [comment]
So I think we just need to check if `getBridgeMTU` is 0 and if it is, return 1500 and we'll be good here.

**Comment by stgraber** [comment]
@markylaing 
```
/lxc-ci/build/tmp.sToSbFAGts/go/src/github.com/lxc/lxd/lxd/network/openvswitch/ovn.go:181:16: ineffectual assignment to err
```

**Comment by markylaing** [comment]
> @markylaing
> 
> ```
> /lxc-ci/build/tmp.sToSbFAGts/go/src/github.com/lxc/lxd/lxd/network/openvswitch/ovn.go:181:16: ineffectual assignment to err
> ```

I'm pretty confused about this because locally it is passing (I also put `make static-analysis` into my pre-push hook). Anyway it ought to be fixed now.

**Comment by stgraber** [comment]
@markylaing 
Hmm, still getting the exact same failure.

File: lxd/network/openvswitch/ovn.go [hunk 19]
```diff
@@ -178,34 +178,68 @@ func NewOVN(s *state.State) (*OVN, error) {
 		return nil, errors.Wrapf(err, "Failed to get OVN northbound connection string")
 	}
 
+	sbConnection, err := NewOVS().OVNSouthboundDBRemoteAddress()
```
Comment (stgraber) [inline lxd/network/openvswitch/ovn.go:181]: You indeed never check `err` here.

Comment (stgraber) [reply lxd/network/openvswitch/ovn.go:181]: Prior to this branch, the function would return `return client, err` which was taking care of the check that way.

I actually much prefer the `return client, nil` but we do need to add a:
```
	if err != nil {
		return nil, errors.Wrapf(err, "Failed to get OVN southbound connection string")
	}
```

So that we properly handled errors.

File: lxd/network/openvswitch/ovn.go [hunk 20]
```diff
@@ -178,34 +178,71 @@ func NewOVN(s *state.State) (*OVN, error) {
...
+	if err != nil {
+		return nil, err
```
Comment (stgraber) [inline lxd/network/openvswitch/ovn.go:183]: This should be wrapped the same we do for the NorthBound one.

File: lxd/network/openvswitch/ovn.go (hunk 19 above)
Comment (markylaing) [reply lxd/network/openvswitch/ovn.go:181]: Ok sorted now.

File: lxd/network/openvswitch/ovn.go [hunk 21]
```diff
@@ -178,34 +178,71 @@ func NewOVN(s *state.State) (*OVN, error) {
 		return nil, errors.Wrapf(err, "Failed to get OVN northbound connection string")
 	}
 
+	sbConnection, err := NewOVS().OVNSouthboundDBRemoteAddress()
+	if err != nil {
+		return nil, errors.Wrapf(err, "Failed to get OVN southbound connection string")
```
Comment (tomponline) [inline lxd/network/openvswitch/ovn.go:183]: We don't use Wrapf error anymore though 😀

Comment (stgraber) [reply lxd/network/openvswitch/ovn.go:183]: I'll give that one a pass though, but yeah, we should put that file on the list of ones to convert :)
