### PR TITLE
zfs: Set canmount=noauto on all mountable datasets

### LINKED ISSUE #3437: Issue with ZFS unmounts when LXD is inside a mount namespace (snap)
After several tests with the debian strech testing in the last weeks i have now switched over to newest debian stable (complete reinstall). Installed zfs-dkms and lxd (snap).
Difference to my older tests: instead of lxdbr0 I'm using br0 now (set up directly in the host, to reach all vms directly from network) -> that all works fine!! after my last issue (zfs-mountpoint of dataset had to be set to none) also lxc-container setup works well.

Another difference: when I run lxd init, i selected a different name for the storage pool - I didn't select default, I selected a own name. 

And now I get errors when I restart/reboot a container or stop and start it via lxc command. I can init a new container, set it up, start it, work with it, but after stopping it, it doesn't come up again - gives me the following errors. I didn't get this errors on my testing system where I used the name "default" for the storage pool and the lxdbr0...

```
# lxc start c000331975
error: Failed to run: /snap/lxd/2518/bin/lxd forkstart c000331975 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/c000331975/lxc.conf:
Try `lxc info --show-log c000331975` for more info
```

```
# lxc info --show-log c000331975
Name: c000331975
Remote: unix:/var/snap/lxd/common/lxd/unix.socket
Architecture: x86_64
Created: 2017/06/23 09:19 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:mount_rootfs:798 - No such file or directory - Failed to get real path for "/var/snap/lxd/common/lxd/containers/c000331975/rootfs".
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:setup_rootfs:1220 - Failed to mount rootfs "/var/snap/lxd/common/lxd/containers/c000331975/rootfs" onto "/var/snap/lxd/common/lxc/" with options "(null)".
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:do_rootfs_setup:3899 - failed to setup rootfs for 'c000331975'
            lxc 20170623094709.412 ERROR    lxc_conf - conf.c:lxc_setup:3981 - Error setting up rootfs mount after spawn
            lxc 20170623094709.413 ERROR    lxc_start - start.c:do_start:811 - Failed to setup container "c000331975".
            lxc 20170623094709.413 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20170623094709.140 ERROR    lxc_start - start.c:__lxc_start:1358 - Failed to spawn container "c000331975".
            lxc 20170623094709.703 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.
            lxc 20170623094709.703 ERROR    lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "c000331975".
            lxc 20170623094709.703 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.
            lxc 20170623094709.703 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.

```

but If I search for the directory I get the following:

```
# ls -l /var/snap/lxd/common/lxd/containers/c000331975
lrwxrwxrwx 1 root root 67 Jun 23 11:20 /var/snap/lxd/common/lxd/containers/c000331975 -> /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/c000331975
# ls -l /var/snap/lxd/common/lxd/containers/c000331975/
total 8
-r--------  1 root    root    2094 Jun 23 11:42 backup.yaml
-rw-r--r--  1 root    root     691 Jan  1  1970 metadata.yaml
drwxr-xr-x 22 1000000 1000000   22 May  4 05:25 rootfs
drwxr-xr-x  2 root    root       4 Jun 22 14:49 templates
```
so it should be there, shouldn't it?

after that i also cannot delete this conatiner:
```
 # lxc delete c000331975
error: Failed to destroy ZFS filesystem: cannot destroy 'zpool1/lxd/containers/c000331975': dataset is busy
```
But If I do the following:
```
# zfs unmount zpool1/lxd/containers/c000331975
```
then everything works again -> after that i can start the container again.

Maybe lxd doesn't unmount correctly, if the storagepool-name was changed?

 * Distribution: Debian Strech, fresh install
 * The output of "lxc info" or if that fails:
root@alarich ~ # lxc info
config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 94.130.8.20:8443
  - '[2a01:4f8:10b:c58::2]:8443'
  - 94.130.8.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIQIioZM/371/VPfLX2P2QCODANBgkqhkiG9w0BAQsFADA/
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR8wHQYDVQQDDBZyb290QGFs
    YXJpY2gucHdob3N0LmRlMB4XDTE3MDYyMjExMzE1OVoXDTI3MDYyMDExMzE1OVow
    PzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEfMB0GA1UEAwwWcm9vdEBh
    bGFyaWNoLnB3aG9zdC5kZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AMNd4aHhrntfa4Af0FeUlfVt2oeshvu3our8EnUcPX4qcGsV7mIPZUtfdixHUCrt
    MDYxwH9qIUtI5Hx9ii6rim3xTSvSvJ/s9QmbDMKfKGc9robBdHcpKemQS/atjBV4
    BCywIh8q0xrzjstzXCixmyqq06RhGrJ9ot3O5OMFVT0JsOQmqA9TVcwMxi2lK3XE
    Ekxwyt3N6oWsEgRKlMZJtfL7My+wDmUcOeMSjNcfGx/0pSwF8Ul4BNyx6rVxiqm8
    IgkxRLy1ZVyPa1s3dP81e75EFYCqkwPUWvZJGca6g3DqZ57VfuqkBbQMpH1LD1v+
    KrvIGWXWkVK9Vy0vkn1c5htP4fCeE2dq7H2X4oxcZneDdxEhdBVWej2C/P6RJdg9
    MIzTw/xQ6cQZl1CZ6IhtnEJCirHEXqyMugQxwFPyvtH5COzHwCPNtTFDMbUtMgyY
    KD5TekHq0B2li+0Rm4cdlPZzJdi7gys47IBDGBsTzDLjqFWs3Kh8PrtK5dz20EKG
    U3rsgHKxGiRA0ZhO4l/1ta0eDNaFz45xuJ8VJNz5F+XhEzTu/79GYj/qw9o6zefD
    Yad2lIIX4D5v2vZp7fQnU+2Zpm5x9Y27uwKaQvhrZ1bNP2ok4QupYe0brsbNmQbF
    w9I0OKj092JI/RwyEpvYGnPIOQ4MZtHfR6d/re9EBiWXAgMBAAGjgYQwgYEwDgYD
    VR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAw
    TAYDVR0RBEUwQ4IRYWxhcmljaC5wd2hvc3QuZGWHBF6CCBSHBF6CB5CHBF6CB5GH
    BF6CB5KHBF6CB5OHECoBBPgBCwxYAAAAAAAAAAIwDQYJKoZIhvcNAQELBQADggIB
    AAduN9y8YklpLLMuAF1E2/GErNGYmIwTTnAqTjkSnHpx5idrC1EZOrBjFKvRHd5W
    i3u/8Z8Z95fdzjSzqASmAy14WD4FJzXIyM1a2sbzegRSDn/x/68i/xRqIfSA5dJC
    Y49dJsiurCOrGO+gqBY7MT+TQw2acnADGQ0uaRtt4riFQQPWlPwNBbZzLHbwx1Xf
    47pI6T7yPmZ3ZBLkL6FPHN9ODh23m4rs6AhZ26vG6fyo+FRTNLDqc0FRgjbLzHaz
    5fjoEAp9dqwvp7mpMdaZAoQHkNmlNqxdMsHmIOCosvR5QloihE8mi23z+5p+N9bv
    SZhIVWPuykQ1h3gz+qE9/6yBTr3teqa64Zzwe1pPDn9k05jRoMqLPKr/g/4oGF5e
    PegAUdZUHIA2QBuv4bvKR8jliRGUpu91DxwKuueff2yCPF62Ee5GCVitrNXAxIOL
    kA3mMQJHzKYxuuWOw9da7WWq2uMedDe1Kf4FJdn6yfQpgDDbyz3cImpiTeXP+O3S
    N1RmL9UbcCTS2kcTYvcyQK4KuQWJc/47Arpw5wiDFpl+j3/0LwLlD1N7ReZpiUXW
    XW3hIqaBsS2221CrC2DmIeHZXmh++tDfimAu5I4TjJjEAvrHhWRzA4Jr8UdYHSSt
    o85kw5XyzmQY1oaaSbCUgkB8+dAK8DsiurGy8RcPU52g
    -----END CERTIFICATE-----
  certificate_fingerprint: f495c2c18106300c031b0f6bceb5d694cb23d0b8b410be017020e11aa3ad71af
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_pid: 2716
  server_version: "2.14"
  storage: zfs
  storage_version: 0.6.5.9-5

### PR DESCRIPTION
**Pull request by stgraber**
We don't want the container host to randomly mount stuff behind our back.

Closes #3437

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Marking as RFC as I'm pretty sure there are other codepaths in the zfs backend that need updating to deal with this. Looks like I covered all the cases where we were missing a mount call, but looking at the log it looks like we have a few cases where we're expecting the filesystem to be mounted, attempt an unmount which now wastes time as it's not going to be mounted anymore.

File: lxd/patches.go [hunk 1]
```diff
@@ -2247,6 +2248,63 @@ func patchStorageApiInsertZfsDriver(name string, d *Daemon) error {
...
+			continue
+		}
+
+		zpool := pool.Config["zfs.pool_name"]
+		if zpool == "" {
+			continue
+		}
+		path := fmt.Sprintf("%s/containers", zpool)
+
+		output, err := shared.RunCommand(
```
Comment (brauner) [inline lxd/patches.go]: Hm, why are you listing this manually and not go through the db by requesting all defined storage volumes of type container?

Comment (stgraber) [inline lxd/patches.go]: I first tried that approach but it ended up looking more complicated than just poking zfs for everything under containers/. That's mostly because with this approach I don't have to care about parsing container names to skip snapshots.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

File: lxd/patches.go [hunk 2]
```diff
@@ -2247,6 +2248,60 @@ func patchStorageApiInsertZfsDriver(name string, d *Daemon) error {
...
+
+		if pool.Driver != "zfs" {
+			continue
+		}
+
+		zpool := pool.Config["zfs.pool_name"]
+		if zpool == "" {
+			continue
+		}
+		paths := []string{fmt.Sprintf("%s/containers", zpool), fmt.Sprintf("%s/custom", zpool)}
```
Comment (brauner) [inline lxd/patches.go]: Listing this will fail when `<pool>/containers` or `<pool>/custom` does not exist.

Comment (brauner) [inline lxd/patches.go]: A temporary workaround is to stop the current upgrade and:

```
systemctl stop lxd.service lxd.socket
zfs create -p -o mountpoint=none rpool/virtual/lxd/custom
```
and try to upgrade again. This could take a little while.
