### PR TITLE
{ceph,lvm}: generate new xfs uuid

### LINKED ISSUE #3752: rbd snapshots need uuid to be re-generated on clone
Hello there!

I've noticed that when creating more than 1 container with the same image per LXD host, the rbd clone function does not change the UUID of the snapshot.

```
for i in {1..5}; do lxc launch ubuntu:16.04; done
Creating the container
Container name is: noble-mite
Starting noble-mite
Creating the container
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: invalid argument
Creating the container
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: invalid argument
Creating the container
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: invalid argument
Creating the container
error: Failed container creation:
 - https://cloud-images.ubuntu.com/releases: invalid argument
```
```
/dev/rbd0: UUID="58cca13a-9c82-46d6-bb09-56545a77c393" TYPE="xfs"
/dev/rbd1: UUID="58cca13a-9c82-46d6-bb09-56545a77c393" TYPE="xfs"
/dev/rbd2: UUID="58cca13a-9c82-46d6-bb09-56545a77c393" TYPE="xfs"
/dev/rbd3: UUID="58cca13a-9c82-46d6-bb09-56545a77c393" TYPE="xfs"
/dev/rbd4: UUID="58cca13a-9c82-46d6-bb09-56545a77c393" TYPE="xfs"
```

This causes Linux to throw an error

```
[153161.925026] XFS (rbd1): Filesystem has duplicate UUID 0e6dc26c-9032-4884-92c1-fbdf267d5c97 - can't mount
```

I was able to solve the problem by running 

```
xfs_admin -U generate /dev/rdb1
xfs_admin -U generate /dev/rdb2
xfs_admin -U generate /dev/rdb3
xfs_admin -U generate /dev/rdb4
```

on the containers that would not start.

### PR DESCRIPTION
**Pull request by brauner**
Closes #3752.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

File: lxd/storage_utils.go [hunk 1]
```diff
@@ -181,13 +181,25 @@ func lxdUsesPool(dbObj *sql.DB, onDiskPoolName string, driver string, onDiskProp
...
+func xfsGenerateNewUUID(path string) error {
+	_, err := shared.RunCommand("xfs_admin", "-U", "generate", path)
+	if err != nil {
+		return err
+	}
+
+	return nil
+}
+
 func makeFSType(path string, fsType string) (string, error) {
```
Comment (stgraber) [inline lxd/storage_utils.go]: This function is never called from within the LVM codebase, so I'm unsure how you expect LVM to have its UUID re-generated when needed.

File: lxd/storage_utils.go [hunk 2]
```diff
@@ -181,13 +181,25 @@ func lxdUsesPool(dbObj *sql.DB, onDiskPoolName string, driver string, onDiskProp
...
 	var err error
 	var msg string
 
 	switch fsType {
 	case "xfs":
 		msg, err = shared.TryRunCommand("mkfs.xfs", path)
+		if err == nil {
+			err = xfsGenerateNewUUID(path)
+		}
```
Comment (stgraber) [inline lxd/storage_utils.go]: My understanding is that this is the one time where this isn't actually needed.

XFS requires all mounted filesystems to have differing UUIDs. So the time where you really need to generate a new UUID is after cloning an existing filesystem. Creating a new one through mkfs.xfs should get you a clean UUID and so not require this step.

File: lxd/storage_utils.go (hunk 1 above)
Comment (brauner) [reply lxd/storage_utils.go]: Uhm, it must be otherwise no volume would have a file system and Jenkins would look very very very sad. I'm sure it's called in the appropriate helpers in one of the storage_lvm_$ files.

File: lxd/storage_utils.go (hunk 2 above)
Comment (brauner) [reply lxd/storage_utils.go]: That point makes sense. I should not send patches at 6 in the morning.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please
