### PR TITLE
Device: Fallback to using disk mount device path for major/minor number extraction for BTRFS

### LINKED ISSUE #8564: BTRFS with LVM storage error when launch container
# Required information

 * Distribution: ubuntu
 * Distribution version: 20.04 (latest upgraded)
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-67-generic
   * LXC version: 4.12
   * LXD version: 4.12
   * Storage backend in use: lvm

# Issue description

```
# lxc launch ubuntu:20.04 test -p network -p nano.docker
Creating test
Starting test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log local:test` for more info
```

After starting container I have got an error `Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test`

It's failed [here](https://github.com/lxc/lxd/tree/6125eca0fc3dc24da20575338f4d416aa55ce2ef/lxd/device/disk.go#L1737) because the condition didn't contain LVM checks, or check making before filesystem mounted.

Used profiles:

```yaml
# lxc profile show network
config:
  boot.autostart: "true"
description: Network profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
name: network
used_by:
- /1.0/instances/template
- /1.0/instances/test
```

```yaml
# lxc profile show nano.docker
config:
  boot.autostart.priority: "0"
  limits.cpu: "1"
  limits.cpu.allowance: 25ms/50ms
  limits.cpu.priority: "1"
  limits.memory: 512MB
  limits.memory.swap: "false"
  limits.network.priority: "0"
  limits.processes: "1000"
  raw.lxc: |
    lxc.cgroup.blkio.bfq.weight = 50
  security.nesting: "true"
description: Nano docker instance limits profile
devices:
  root:
    limits.read: 6MB
    limits.write: 6MB
    path: /
    pool: ssd.btrfs
    size: 8GB
    type: disk
name: nano.docker
used_by:
- /1.0/instances/test
```

Storage pool configuration

```yaml
# lxc storage show ssd.btrfs
config:
  lvm.use_thinpool: "false"
  lvm.vg.force_reuse: "true"
  lvm.vg_name: ssd
  source: ssd
  volatile.initial_source: ssd
  volume.block.filesystem: btrfs
  volume.block.mount_options: compress=zstd,discard,autodefrag,commit=60,datacow,datasum,flushoncommit,inode_cache,ssd,thread_pool=4,user_subvol_rm_allowed
  volume.size: 8GB
description: SSD backed storage pool with BtrFS filesystem
name: ssd.btrfs
driver: lvm
used_by:
- /1.0/instances/template
- /1.0/instances/test
- /1.0/profiles/huge.docker
- /1.0/profiles/large.docker
- /1.0/profiles/medium.docker
- /1.0/profiles/micro.docker
- /1.0/profiles/nano.docker
status: Created
locations:
- none
```

Expected behaviour:

```
# lxc launch ubuntu:20.04 test -p network -p nano.docker
Creating test
Starting test
```

# Steps to reproduce

 1. Create similar storage as described
 2. Create similar profiles as described
 3. Try to create container `lxc launch ubuntu:20.04 test -p network -p nano.docker`

# Information to attach

```
# btrfs filesystem show /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
# btrfs filesystem show /
Label: none  uuid: 54ade60b-c777-42f2-b214-9fd3661d9f03
	Total devices 1 FS bytes used 4.38GiB
	devid    1 size 16.00GiB used 5.52GiB path /dev/mapper/ssd-root
```

Container doesn't restart but after retry start command write the error and boot normally

```
# lxc restart test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log test` for more info

# lxc ls
+----------+---------+------+------+-----------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+------+------+-----------+-----------+
| test     | STOPPED |      |      | CONTAINER | 0         |
+----------+---------+------+------+-----------+-----------+

# lxc start test
Error: Failed to query btrfs filesystem information for "/dev/mapper/ssd-containers_test": Failed to run: btrfs filesystem show /dev/mapper/ssd-containers_test: ERROR: not a valid btrfs filesystem: /var/snap/lxd/common/lxd/storage-pools/ssd.btrfs/containers/test
Try `lxc info --show-log test` for more info

# lxc ls
+----------+---------+------+------+-----------+-----------+
|   NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+------+------+-----------+-----------+
| test     | RUNNING |      |      | CONTAINER | 0         |
+----------+---------+------+------+-----------+-----------+

# sleep 10
# lxc ls
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
|   NAME   |  STATE  |          IPV4          |                   IPV6                   |   TYPE    | SNAPSHOTS |
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
| test     | RUNNING | 192.168.128.113 (eth0) | 2a01:5a9:4af:61a9:f:338:d935:9a5a (eth0) | CONTAINER | 0         |
+----------+---------+------------------------+------------------------------------------+-----------+-----------+
```

### PR DESCRIPTION
**Pull request by tomponline**
If `btrfs filesystem show` doesn't work then fallback to extracting major/minor number directly from the parent block device in the mount info for cgroup limits generation.

Fixes #8564

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

File: lxd/device/disk.go [hunk 1]
```diff
@@ -1734,7 +1734,13 @@ func (d *disk) getParentBlocks(path string) ([]string, error) {
 		// Accessible btrfs filesystems
 		output, err := shared.RunCommand("btrfs", "filesystem", "show", dev[1])
```
Comment (tomponline) [inline lxd/device/disk.go:1735]: @stgraber I would like to add a comment here explaining why we attempt to use `btrfs filesystem show` in the first place, but I do not know why this is, could you enlighten me and I'll update the comment. Thanks :)
