### PR TITLE
network: do not update limits unconditionally

### LINKED ISSUE #3920: error when ipv4.address is set
* Distribution: ubuntu 
 * Distribution version:16.04.3 LTS
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-96-generic
  server: lxd
  server_pid: 22809
  server_version: "2.18"
  storage: dir
  storage_version: "1"

   * Kernel version: 4.4.0-96-generic
   * LXC version: 2.1.0
   * LXD version: 2.18
   * Storage backend in use: dir

# Issue description

since passing in lxd 2.18 I can no longer assign ip to my containers

# Steps to reproduce

lxc network attach lxdbr0 test eth0
lxc config device set test eth0 ipv4.address 10.215.181.249
error: LXC doesn't know about this device and the host_name property isn't set, can't find host side veth name

# Information to attach

 - [ ] Container log (`lxc info NAME --show-log`)
Name: test
Remote: unix://
Architecture: x86_64
Created: 2017/10/03 13:36 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 132946
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 59
  CPU usage:
    CPU usage (in seconds): 8
  Memory usage:
    Memory (current): 474.80MB
    Memory (peak): 476.00MB
  Network usage:
    eth1:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

            lxc 20171009091416.522 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.522 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.767 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.767 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.

 - [ ] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  environment.http_proxy: ""
  image.description: test  (stop) (20171003_15:26)
  limits.cpu: "4"
  limits.memory: 4GB
  user.network_mode: ""
  volatile.base_image: ff532373af026e57b4da0ac6ee385ca2e77a6678331c480a0e05fd4521e99fc0
  volatile.eth0.hwaddr: 00:16:3e:2e:75:37
  volatile.eth0.name: eth1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

### PR DESCRIPTION
**Pull request by brauner**
In order to determine whether a given device needs to be updated LXD will diff
the keys and values for the old and the new device settings. If LXD determines
a difference it will append the key and the corresponding value to the device.
If it determines they don't differ the key and value won't be in the updated
devices list that is passed to the the container's update method. So we can
simply rely on checking whether the given key exists in the device that is to
be updated if it isn't we don't need to run the actual update.

Closes #3920.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -6796,9 +6808,10 @@ func (c *containerLXC) setNetworkLimits(name string, m types.Device) error {
 
 	// Look for the host side interface name
 	veth := c.getHostInterface(m["name"])
-
 	if veth == "" {
-		return fmt.Errorf("LXC doesn't know about this device and the host_name property isn't set, can't find host side veth name")
+		return fmt.Errorf(`LXC doesn't know about this device and the ` +
+			`host_name property isn't set, can't find host side ` +
+			`veth name`)
```
Comment (stgraber) [inline lxd/container_lxc.go]: I'm not convinced by this type of wrapping, it makes grepping for errors much harder than it should be...

File: lxd/container_lxc.go [hunk 2]
```diff
@@ -6777,6 +6777,18 @@ func (c *containerLXC) setNetworkLimits(name string, m types.Device) error {
...
+	for _, v := range containerNetworkLimitKeys {
+		_, needsUpdate = m[v]
+		if needsUpdate {
+			break
+		}
+	}
+
+	if !needsUpdate {
+		return nil
+	}
```
Comment (stgraber) [inline lxd/container_lxc.go]: I think this will prevent us from unsetting limits. If I have limits in place and I unset all limits.* keys, this will cause the function to return without ever removing the existing limits.

Comment (brauner) [reply lxd/container_lxc.go]: If you have limits in place and you clear them that means you set all those limits to `""`. The keys themselves however will still be present and so the existence check for the key itself will yield true and so an update will be performed.

Comment (stgraber) [reply lxd/container_lxc.go]: It does?

If I "lxc config edit" and remove the key, then it won't be in the dict anymore. The value would be "" but the exists value would be False.

Comment (brauner) [reply lxd/container_lxc.go]: That's not how I read the `Update()` method in `lxd/types/devices.go` that spews out the devices to update.

**Comment by stgraber** [comment]
guess I'll have to test it to convince myself that it's fine :)

**Comment by brauner** [comment]
@stgraber, I would do it myself. I'm just currently at another branch that's why I couldn't switch. :)

**Comment by brauner** [comment]
Yeah, it doesn't correctly unset the value.

**Comment by brauner** [comment]
One options is to record whether the ingress keys have changed or have been removed (that's what I originally wanted to avoid) and then remove all values.

**Comment by brauner** [comment]
@stgraber, updated with a new approach. I thought that the `lxd/types/devices.go:Update()` ranges over the keys of a single device and not over the keys for the devices themselves. :)
