### PR TITLE
initial implementation of the "usb" device type

### LINKED ISSUE #2241: Add support for raw USB devices access (/dev/usb)
We have some folks who'd like to be able to interact with usb devices through libusb.
Unfortunately the device paths aren't fixed so we can't just use unix-char/unix-block.

Instead we'd want it to be tied to vendorid/productid.

I think we should do:
 - Add a new "usb" device type
 - Support the following properties
   - vendorid (optional)
   - productid (required)
   - uid (optional)
   - gid (optional)
   - mode (optional)
 - At startup time, check through /sys if the device already exists, if it does, inject it in the container similarly to unix-char. If the device doesn't exist, just move on (don't fail).
 - In the uevent listener, monitor usb device hotplug events, if the device is plugged, add it to the container, if unplugged, remove it from the container.

This needs an update to the documentation for the new device type and an API extension entry so we can detect support for this.

### PR DESCRIPTION
**Pull request by tych0**
I've tested all the cases I can think of (hotplug the actual device,
hotplug the container config, and cold container start/stop), but I'm not
really sure how to add any automated tests for this, since there's no real
way to ensure USB devices will be available.

Closes #2241

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

File: lxd/container_lxc.go [hunk 1]
```diff
@@ -1099,6 +1101,45 @@ func (c *containerLXC) startCommon() (string, error) {
...
+				}
+
+				m["major"] = fmt.Sprintf("%d", usb.major)
+				m["minor"] = fmt.Sprintf("%d", usb.minor)
+				m["path"] = usb.path
+
+				/* it's ok to fail, the device might be hot plugged later */
+				_, err := c.createUnixDevice(m)
+				if err != nil {
+					shared.Log.Warn("failed to create usb device", log.Ctx{"err": err, "device": k})
```
Comment (stgraber) [inline lxd/container_lxc.go]: Should be downgraded to Debug since having the device hot-plugged later is supported.

File: lxd/devices.go [hunk 2]
```diff
@@ -358,8 +457,63 @@ func deviceNetworkPriority(d *Daemon, netif string) {
 	return
 }
 
+func deviceUSBEvent(d *Daemon, usb usbDevice) {
+	containers, err := dbContainersList(d.db, cTypeRegular)
+	if err != nil {
+		shared.Log.Error("problem loading containers list", log.Ctx{"err": err})
+		return
+	}
```
Comment (stgraber) [inline lxd/devices.go]: Readability nit, add a blank line after this.

File: lxd/devices.go [hunk 3]
```diff
@@ -358,8 +457,63 @@ func deviceNetworkPriority(d *Daemon, netif string) {
...
+	for _, name := range containers {
+		containerIf, err := containerLoadByName(d, name)
+		if err != nil {
+			continue
+		}
+
+		c, ok := containerIf.(*containerLXC)
```
Comment (stgraber) [inline lxd/devices.go]: Not fond of this I must say but don't have a good alternative to suggest right now. If we have to do more of that in the future, we'll have to think about how we can better handle such cases within the Container interface.

File: lxd/devices.go [hunk 4]
```diff
@@ -823,3 +979,71 @@ func deviceParseDiskLimit(readSpeed string, writeSpeed string) (int64, int64, in
...
+	return values, nil
+}
+
+func deviceLoadUsb() ([]usbDevice, error) {
+	result := []usbDevice{}
+
+	ents, err := ioutil.ReadDir(USB_PATH)
+	if err != nil {
+		return nil, err
+	}
```
Comment (stgraber) [inline lxd/devices.go]: What happens on a system without USB? Does that only cause a failure when a usb device is added to the container or does that also affect containers without usb devices?

**Comment by stgraber** [comment]
Just a couple of nits and questions in-line.

Looking at the other device types, I was wondering if we should have something like the "optional" flag we have on disk type entries. "optional" doesn't make so much sense for something that's hot-plug, but maybe its reverse "required" would make sense, so that folks can indicate that they only want the container to work if the device is available.

It would also give us a place to mention that USB is hot-plug by default in doc/configuration.md (as part of the description of the required property).

What do you think?

File: lxd/devices.go (hunk 4 above)
Comment (tych0) [inline lxd/devices.go]: On Wed, Aug 03, 2016 at 11:19:27AM -0700, Stéphane Graber wrote:
> > +			return nil, err
> > +		}
> > +
> > +		values[k] = strings.TrimSpace(string(v))
> > +	}
> > +
> > +	return values, nil
> > +}
> > +
> > +func deviceLoadUsb() ([]usbDevice, error) {
> > +	result := []usbDevice{}
> > +
> > +	ents, err := ioutil.ReadDir(USB_PATH)
> > +	if err != nil {
> > +		return nil, err
> > +	}
> 
> What happens on a system without USB? Does that only cause a failure when a usb device is added to the container or does that also affect containers without usb devices?

I *think* I've done it so that it would only fail on systems where
there usb devices configured on containers. that said, it's not hard
to add a little check in there for ENOENT and return an empty list, so
i'll do that.

**Comment by tych0** [comment]
On Wed, Aug 03, 2016 at 11:27:35AM -0700, Stéphane Graber wrote:
> Just a couple of nits and questions in-line.
> 
> Looking at the other device types, I was wondering if we should have something like the "optional" flag we have on disk type entries. "optional" doesn't make so much sense for something that's hot-plug, but maybe its reverse "required" would make sense, so that folks can indicate that they only want the container to work if the device is available.
> 
> It would also give us a place to mention that USB is hot-plug by default in doc/configuration.md (as part of the description of the required property).
> 
> What do you think?

Sure, it shouldn't be too hard to add.

**Comment by stgraber** [comment]
Cool, looks good to me. Waiting on Jenkins.
