### PR TITLE
Handle custom volume refresh properly

### LINKED ISSUE #10186: Optimized refresh broken
Reported from https://discuss.linuxcontainers.org/t/error-error-transferring-instance-data-failed-getting-instance-storage-pool-name-instance-storage-pool-not-found/13743

This appears to be an issue with optimized refresh, but I am still investigating it.

### PR DESCRIPTION
**Pull request by monstermunchkin**
- lxd/migrate_storage_volumes: Make sender aware of refresh
- lxd/migration: Add Refresh to InfoResponse
- lxd/storage: Return InfoResponse from migrationIndexHeaderSend
- lxd/storage: Use Refresh from InfoResponse
- lxd/storage/backend: Add refresh arg to migrationIndexHeaderReceive

Closes  #10186

### CODE REVIEW

File: lxd/storage/backend_lxd.go [hunk 1]
```diff
@@ -3439,50 +3439,51 @@ func (b *lxdBackend) CreateCustomVolumeFromCopy(projectName string, srcProjectNa
 }
 
 // migrationIndexHeaderSend sends the migration index header to target and waits for confirmation of receipt.
-func (b *lxdBackend) migrationIndexHeaderSend(l logger.Logger, indexHeaderVersion uint32, conn io.ReadWriteCloser, info *migration.Info) error {
+func (b *lxdBackend) migrationIndexHeaderSend(l logger.Logger, indexHeaderVersion uint32, conn io.ReadWriteCloser, info *migration.Info) (migration.InfoResponse, error) {
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go:3442]: Please can you return a pointer to resp and return nill on error.

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you enable the test this pr fixes in this pr?

**Review by tomponline — APPROVED** [review]
Thanks lgtm

**Comment by tomponline** [comment]
jenkins: test this please

**Review by tomponline — CHANGES_REQUESTED** [review]
Btrfs tests failing

**Comment by monstermunchkin** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@monstermunchkin type of "negociate" in last commit.

**Comment by monstermunchkin** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@monstermunchkin btrfs is busted

**Comment by monstermunchkin** [comment]
jenkins: test this please

**Comment by monstermunchkin** [comment]
I've added a `VolumeOnly` field to `VolumeSourceArgs` and `VolumeTargetArgs`. Previously, an empty `Snapshots` list would indicate a volume-only copy. Now that btrfs and zfs support optimized copy/refresh, and the drivers negotiate the snapshots, using the `VolumeOnly` field makes it a lot easier to handle volume-only copies.

File: lxd/storage/drivers/driver_btrfs_volumes.go [hunk 2]
```diff
@@ -1219,7 +1219,12 @@ func (d *btrfs) MigrateVolume(vol Volume, conn io.ReadWriteCloser, volSrcArgs *m
 	}
 
 	// Generate restoration header, containing info on the subvolumes and how they should be restored.
-	migrationHeader, err := d.restorationHeader(vol, volSrcArgs.Snapshots)
+	snapshots, err := d.volumeSnapshotsSorted(vol, op)
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_volumes.go]: @monstermunchkin please can you elaborate (and importantly add a comment for future readers) the commit message:

"The passed snapshots dont't always include all which need to be
transferred."

Why don't they always?

File: lxd/storage/drivers/driver_btrfs_volumes.go [hunk 3]
```diff
@@ -1218,10 +1218,15 @@ func (d *btrfs) MigrateVolume(vol Volume, conn io.ReadWriteCloser, volSrcArgs *m
...
 	}
 
-	// Generate restoration header, containing info on the subvolumes and how they should be restored.
-	snapshots, err := d.volumeSnapshotsSorted(vol, op)
-	if err != nil {
-		return err
+	var snapshots []string
+	var err error
+
+	if !volSrcArgs.VolumeOnly {
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs_volumes.go:1224]: @monstermunchkin should there not also be equivalent logic in the ZFS driver?

**Review by tomponline — CHANGES_REQUESTED** [review]
This needs a rebase as the "// FIXME this should have been the top-level info!" comment no longer exists in main.

File: lxd/storage/drivers/driver_btrfs_volumes.go (hunk 2 above)
Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_volumes.go]: Consider the following example:

```
lxc storage volume create l1:btrfs vol1
lxc storage volume snapshot l1:btrfs vol1
lxc storage volume snapshot l1:btrfs vol1
lxc storage volume snapshot l1:btrfs vol1 snapremove

lxc storage volume copy l1:btrfs/vol1 l2:btrfs/vol2 --refresh

lxc storage volume create l1:btrfs vol3
lxc storage volume snapshot l1:btrfs vol3
lxc storage volume snapshot l1:btrfs vol3
lxc storage volume snapshot l1:btrfs vol3
lxc storage volume copy l1:btrfs/vol3 l2:btrfs/vol2 --refresh
```

The last command will fail with

    Error: Failed storage volume creation: Error transferring storage volume: Failed to run: btrfs receive -e /home/thomas/work/lxd/server/storage-pools/btrfs/custom/migration.1597063747/snap2: ERROR: cannot find parent subvolume

On the source we have
```
$ lxc storage volume list l1:btrfs 
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
|       TYPE        |                               NAME                               | DESCRIPTION | CONTENT-TYPE | USED BY |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom            | vol1                                                             |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol1/snap0                                                       |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol1/snap1                                                       |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol1/snapremove                                                  |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom            | vol3                                                             |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol3/snap0                                                       |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol3/snap1                                                       |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
| custom (snapshot) | vol3/snap2                                                       |             | filesystem   | 0       |
+-------------------+------------------------------------------------------------------+-------------+--------------+---------+
```

... and on the target we have
```
$ lxc storage volume list l2:btrfs 
+-------------------+------------+-------------+--------------+---------+
|       TYPE        |    NAME    | DESCRIPTION | CONTENT-TYPE | USED BY |
+-------------------+------------+-------------+--------------+---------+
| custom            | vol2       |             | filesystem   | 0       |
+-------------------+------------+-------------+--------------+---------+
| custom (snapshot) | vol2/snap0 |             | filesystem   | 0       |
+-------------------+------------+-------------+--------------+---------+
| custom (snapshot) | vol2/snap1 |             | filesystem   | 0       |
+-------------------+------------+-------------+--------------+---------+
```

The LXD backend will see that the target is missing the `snap2` snapshot, and will therefore only include `snap2` in `volSrcArgs.Snapshots`. In reality though, `vol2/snap0` and `vol2/snap1` are copies from `vol1/snap0` and `vol1/snap1` respectively, not those of `vol3`. Therefore, they need to be copied as well. The btrfs driver can and will detect this using the migration headers  and do the correct thing which is to copy the entire volume (including all snapshots).

@tomponline does that make sense?

Comment (monstermunchkin) [reply lxd/storage/drivers/driver_btrfs_volumes.go]: > Hrm yeah I see what you're saying. This sounds like its a driver-specific solution to this problem https://github.com/lxc/lxd/issues/10436 right?

I believe so.

> Eventually we will need to fix it for all storage drivers by using a volatile uuid in the config to detect syncing different volumes independent of the actual storage layer.

That would make sense.

> Do we not also need similar for ZFS?

zfs handles this already.

Comment (tomponline) [reply lxd/storage/drivers/driver_btrfs_volumes.go]: > zfs handles this already.

Ah right, in the same way? Please could you link to it for me? Thanks

**Comment by monstermunchkin** [comment]
jenkins: test this please

File: lxd/storage/backend_lxd.go [hunk 4]
```diff
@@ -3555,11 +3560,13 @@ func (b *lxdBackend) MigrateCustomVolume(projectName string, conn io.ReadWriteCl
 	}
 
 	// Send migration index header frame with volume info and wait for receipt.
-	err = b.migrationIndexHeaderSend(l, args.IndexHeaderVersion, conn, args.Info)
+	resp, err := b.migrationIndexHeaderSend(l, args.IndexHeaderVersion, conn, args.Info)
 	if err != nil {
 		return err
 	}
 
+	args.Refresh = resp.Refresh
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go:3568]: @monstermunchkin looking at this more closely this morning, I think I see an issue here.

If the negotiated IndexHeaderVersion is 0 (i.e the target doesn't support index header) then `migrationIndexHeaderSend` will always return `resp.Refresh == false`, which will then effectively break refresh to older LXDs.

Further more even if the target server does support IndexHeaderVersion 1 then LXD 5.2 will not return a response with the `Refresh` field, meaning it will default to false, and again refresh will be broken.

One way to resolve this is to make the `Refresh` field take 3 values, by making it a pointer to a bool, then its default value `nil` means unspecified, and we can stick with the refresh mode requested.

Comment (monstermunchkin) [reply lxd/storage/backend_lxd.go:3568]: OK. I'll make the `Refresh` field in `InfoResponse` a pointer to a bool.

Comment (tomponline) [reply lxd/storage/backend_lxd.go]: Thanks, please could you also expand the comments here to explain what the Refresh field is and why its needed? thanks

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@monstermunchkin please can you keep re-requesting jenkins test this until its clear or all storage driver cluster and standalone tests, then I'm happy to merge. But jenkins being jenkins (or rather the infra its running on) it will take time for us to get that run (I've seen one earlier though so I know it can happen for this PR).

**Comment by tomponline** [comment]
@monstermunchkin once this is merged, I'll rebase https://github.com/lxc/lxd/pull/10526 onto it (already done actually) and then do the jenkins dance again, and then that will be ready too.

**Comment by tomponline** [comment]
Jenkins looks good enough now.
