### PR TITLE
lxd/fsmonitor/drivers: Ignore stale file handle errors.

### LINKED ISSUE #9885: fanotify stale NFS file handle error on instance stop
I'm seeing these errors sometimes when I stop instances locally:

```
EROR[02-08|02:05:33] Failed to open file                      driver=fanotify err="stale NFS file handle"
```

Also seeing them on test suite in jenkins:

https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5929/arch=amd64,backend=lvm,compiler=golang-1.17,section=standalone/console#console-section-4

Another example:

https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5935/arch=amd64,backend=random,compiler=golang-1.17,section=standalone/console#console-section-5

```
+ /lxc-ci/build/tmp.Nvsi3sqg8c/go/bin/lxc storage create lxdtest-VztaeFmhq-btrfs btrfs size=100GB --verbose
[31mEROR[0m[02-08|15:29:06] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:09] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:09] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:12] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:12] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:12] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:12] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:13] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:13] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:13] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:13] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:14] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:14] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:14] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:14] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:15] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
[31mEROR[0m[02-08|15:29:15] Failed to open file                      [31mdriver[0m=fanotify [31merr[0m="stale NFS file handle"
Error: Failed to mount "/dev/loop19" on "/lxc-ci/build/tmp.Nvsi3sqg8c/go/src/github.com/lxc/lxd/test/tmp.ilp/VztaeFmhq/storage-pools/lxdtest-VztaeFmhq-btrfs" using "btrfs": invalid argument
```

### PR DESCRIPTION
**Pull request by markylaing**
Checks the error number of the syscall and logs the error only if it's code is not `ESTALE`.

Closes #9885.

### CODE REVIEW

File: lxd/fsmonitor/drivers/driver_fanotify.go [hunk 1]
```diff
@@ -9,6 +9,7 @@ import (
 	"os"
 	"path/filepath"
 	"strings"
+	"syscall"
```
Comment (monstermunchkin) [inline lxd/fsmonitor/drivers/driver_fanotify.go:12]: The `syscall` package is deprecated. We should use `unix` instead.

**Review by monstermunchkin — CHANGES_REQUESTED** [review]

**Review by tomponline — APPROVED** [review]

**Review by monstermunchkin — APPROVED** [review]
