### PR TITLE
Document image export target behavior and fix bugs

### LINKED ISSUE #2205: Add an option to specify a name for the tarball when exporting an image.
# Required information
 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info".
~~~
apicompat: 0
auth: trusted
environment:
  addresses:
  - 172.31.31.35:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificatefingerprint:
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-41-generic
  server: lxd
  serverpid: 1191
  serverversion: 2.0.3
  storage: btrfs
  storageversion: "4.4"
config:
  core.https_address: 172.31.31.35
public: false
~~~

# Issue description
Currently when we export an image, the tarball is named with the fingerprint of the image. It would be really helpful if we could specify a name for the tarball like:
~~~
lxc image export [remote:]<image> [--name=NAME]
or
lxc image export [remote:]<image> [--alias=ALIAS]
~~~

### PR DESCRIPTION
**Pull request by sean-jc**
Add help documentation for the target of `image export`.

If the target is a file, append the appropriate file extension to the
user-provided filename.  Properly parse the Content-Disposition header
to retrieve the image's filename instead of assuming `filename` is the
only parameter in the header.

Fix a bug where specifying a filename (as opposed to a directory) would
create the file with incorrect permissions (664 instead of 600).

Fixes #2205

Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -845,56 +845,44 @@ func (c *Client) ExportImage(image string, target string) (string, error) {
...
+			return "", err
+		}
+		filename, ok := cdParams["filename"]
+		if !ok {
+			return "", fmt.Errorf("No filename in Content-Disposition header.")
+		}
 
-			if err != nil {
-				return "", err
+		if fi, err := os.Stat(target); err == nil && fi.Mode().IsDir() {
```
Comment (tych0) [inline client.go]: Can we use `shared.IsDir` here?

**Comment by tych0** [comment]
jenkins: test this please

LGTM, one minor comment

**Comment by tych0** [comment]
jenkins: test this please

**Comment by tych0** [comment]
I think these are all unrelated, due to some jenkins weirdness (they all passed before).
