### PR TITLE
check for cap_mac_admin

### LINKED ISSUE #1180: Check for the MAC_ADMIN capability at startup time, turn AppArmor support off if cap was droped
If LXD is started inside a privileged container with apparmor disabled, it will currently fail to spawn any container. That is because it will attempt to load a new apparmor profile which will be denied due to the container not having the mac_admin capability.

Fixing this should "just" be a matter of checking whether we have the MAC_ADMIN capability in our effective set and if not, set aaEnable to false.

### PR DESCRIPTION
**Pull request by hallyn**
and set aaEnabled = false if we don't have it

Closes #1180

Signed-off-by: Serge Hallyn <serge.hallyn@ubuntu.com>

### CODE REVIEW

File: lxd/daemon.go [hunk 1]
```diff
@@ -528,6 +540,10 @@ func (d *Daemon) Init() error {
 	/* Detect user namespaces */
 	runningInUserns = shared.RunningInUserNS()
 
+	if !haveMacAdmin() {
+		shared.Log.Warn("Per-container AppArmor profiles are disabled because mac_admin capability is missing.")
+		aaEnabled = false
+	}
```
Comment (stgraber) [inline lxd/daemon.go]: Should probably move after the /sys/kernel/security test.

I've been trying to order things from the least resource heavy to the most resource heavy to optimize things a bit (probably not noticeable on a typical lxd host though).
