### PR TITLE
cgroups: pre-mount on pure-cgroup2 systems with cgroup namespaces

### LINKED ISSUE #6587: /sbin/init fails in a container on a host booted with systemd.unified_cgroup_hierarchy
Host: Ubuntu Eoan booted with `systemd.unified_cgroup_hierarchy`
LXD version: github master branch retrieved and compiled today
LXC version:

```shell-session
$ dpkg-query -W | grep lxc
liblxc-common	3.2.1+master~20191210-1504-0ubuntu1~eoan
liblxc-dev	3.2.1+master~20191210-1504-0ubuntu1~eoan
liblxc1	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxc	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxc-utils	3.2.1+master~20191210-1504-0ubuntu1~eoan
lxcfs	3.0.4-2
```

Container's Guest: Ubuntu Eoan made by `lxc launch ubuntu:19.10`

When host Linux is booted with `systemd.unified_cgroup_hierarchy`, and the guest Linux is relatively new, e.g. Ubuntu 18.04 or 19.10, we need `lxc.mount.auto = cgroup:rw:force` as told at https://github.com/lxc/lxc/issues/3183#issuecomment-560163709

On the other hand, LXD hard-codes `lxc.mount.auto` as
https://github.com/lxc/lxd/blob/9522abd2e090d4f3b4c7a2a0f1fd4e4564eba4fb/lxd/container_lxc.go#L784-L788

The above hard-coded `lxc.mount.auto` prevents Ubuntu 19.10 from starting as an LXD guest. When Ubuntu 18.04 is started as a guest, only `/sbin/init` (=systemd) is running and there is no other process in the container, which is very abnormal.

After I applied the following changes and rebuilt LXD, everything works fine on my host Ubuntu 19.10 booted with systemd.unified_cgroup_hierarchy:

```diff
--- lxc/lxd/lxd/container_lxc.go-org	2019-12-11 19:57:42.487136537 +0900
+++ lxc/lxd/lxd/container_lxc.go	2019-12-11 20:11:00.732855626 +0900
@@ -783,6 +783,8 @@
 
 	if !shared.PathExists("/proc/self/ns/cgroup") {
 		mounts = append(mounts, "cgroup:mixed")
+	} else {
+		mounts = append(mounts, "cgroup:rw:force")
 	}
 
 	err = lxcSetConfigItem(cc, "lxc.mount.auto", strings.Join(mounts, " "))
```

### PR DESCRIPTION
**Pull request by brauner**
We only do force-premounting if we are on a cgroup2-only system.
While it's paranoid to check for both since cgroup2-only should imply cgroupns
but let's not rely on that.

Closes #6587.
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
```
lxd/cgroup/init.go:21:27: invalid operation: st.Type == cgCgroup2SuperMagic (mismatched types int32 and int64)
```

**Comment by brauner** [comment]
> ```
> lxd/cgroup/init.go:21:27: invalid operation: st.Type == cgCgroup2SuperMagic (mismatched types int32 and int64)
> ```

So they seriously change to a 32bit int on i386...

**Comment by brauner** [comment]
In any case. Fixed.

File: lxd/cgroup/init.go [hunk 1]
```diff
@@ -72,3 +87,11 @@ func init() {
...
 	}
 }
+
+func WantsMountCgroupsForce() bool {
+	return cgFullCgroup2 && cgCgroupNamespace
+}
+
+func WantsMountCgroupsMixed() bool {
+	return cgCgroupNamespace
+}
```
Comment (stgraber) [inline lxd/cgroup/init.go]: This is too lxc specific.

What we could introduce is something like:
```go
// Info contains system cgroup information
type Info struct {
    // Mode is one of "disabled", "cgroup1", "cgroup2" or "hybrid"
    Mode string

    // Namespacing indicates support for the cgroup namespace
    Namespacing bool
}

func GetInfo() Info {
    info := Info{}
    info.Namespacing = cgNamespace
    info.Mode = ...

    return info
}
```

This can then later be extended to also give us details on all the controllers and be used to show the status on LXD startup.

**Comment by stgraber** [comment]
Technically fine, but as `cgroup` is a shiny new clean package, we should put some more thought on how to do this cleanly, the suggestion above should give us a good starting point for further improvements.

**Comment by stgraber** [comment]
Oh and make sure that `golint lxd/cgroup` is clean. It should be added to `test/suites/static_analysis.sh` too, that would have reported two errors with your change.

**Comment by brauner** [comment]
Reading through the cgroup detection logic you sent yesterday. That seems broken. The code doesn't seem to be able to detect a pure cgroup2 layout.

File: lxd/cgroup/init.go (hunk 1 above)
Comment (brauner) [reply lxd/cgroup/init.go]: > Reading through the cgroup detection logic you sent yesterday. That seems broken. The code doesn't seem to be able to detect a pure cgroup2 layout.

Hm, I see it's a fallback option...

**Comment by shreyassood** [comment]
> Oh and make sure that `golint lxd/cgroup` is clean. It should be added to `test/suites/static_analysis.sh` too, that would have reported two errors with your change.

We ended up adding this since this is useful for us too: https://github.com/lxc/lxd/pull/6602

**Comment by brauner** [comment]
> > Oh and make sure that `golint lxd/cgroup` is clean. It should be added to `test/suites/static_analysis.sh` too, that would have reported two errors with your change.
> 
> We ended up adding this since this is useful for us too: #6602

Thank you! I missed this. :)
