### PR TITLE
Clarify why a profile device cannot be modified on an instance

### LINKED ISSUE #9054: Make clear why a profile device cannot be modified on an instance
We see this question/problem fairly often:

https://discuss.linuxcontainers.org/t/setting-disk-read-write-limits/11717

> I am trying to set the read/write limit on the container. So, the container does not affect other containers
lxc config device set container root limits.read 30MB
Error: The device doesn’t exist

The problem is that the `root` disk device exists in the profile(s) not in the instance's own config, and thus doesn't exist to be modified on the instance.

We could make this clearer by detecting if a device truly doesn't exist, or if it exists, but only in the expanded config (once the profiles have been applied), then still refuse to make the change, but give a clear error message as to why.

### PR DESCRIPTION
**Pull request by monstermunchkin**
This closes #9054.

### CODE REVIEW

File: lxc/config_device.go [hunk 1]
```diff
@@ -244,7 +244,13 @@ func (c *cmdConfigDeviceGet) Run(cmd *cobra.Command, args []string) error {
 
 		dev, ok := inst.Devices[devname]
 		if !ok {
-			return fmt.Errorf(i18n.G("The device doesn't exist"))
+			_, ok = inst.ExpandedDevices[devname]
+			if !ok {
+				return fmt.Errorf(i18n.G("The device doesn't exist"))
+			}
+
+			return fmt.Errorf(i18n.G("Cannot get information on profile device, use `lxc profile device` instead"))
```
Comment (tomponline) [inline lxc/config_device.go:252]: @monstermunchkin thanks for taking a look at this :)

I know that @stgraber has mentioned to me in the past that we don't include references to the `lxc` commands in our API error messages, as it could be that the client is consuming the API directly and not using the `lxc` command.

So how about this: "The device exists in the instance's profile(s)"

File: lxc/config_device.go [hunk 2]
```diff
@@ -484,7 +490,13 @@ func (c *cmdConfigDeviceRemove) Run(cmd *cobra.Command, args []string) error {
 		for _, devname := range args[1:] {
 			_, ok := inst.Devices[devname]
 			if !ok {
-				return fmt.Errorf(i18n.G("The device doesn't exist"))
+				_, ok := inst.ExpandedDevices[devname]
+				if !ok {
+					return fmt.Errorf(i18n.G("The device doesn't exist"))
+				}
+
+				return fmt.Errorf(i18n.G("Cannot remove profile device, use `lxc profile device` instead"))
```
Comment (tomponline) [inline lxc/config_device.go:498]: How about "Device from profile(s) cannot be removed from individual instance"

File: lxc/config_device.go [hunk 3]
```diff
@@ -593,7 +605,12 @@ func (c *cmdConfigDeviceSet) Run(cmd *cobra.Command, args []string) error {
 		}
 		dev, ok := inst.Devices[devname]
 		if !ok {
-			return fmt.Errorf(i18n.G("The device doesn't exist"))
+			_, ok = inst.ExpandedDevices[devname]
+			if !ok {
+				return fmt.Errorf(i18n.G("The device doesn't exist"))
+			}
+
+			return fmt.Errorf(i18n.G("Cannot modify profile device, use `lxc profile device` instead"))
```
Comment (tomponline) [inline lxc/config_device.go:613]: How about "Device from profile(s) cannot be modified for individual instance"

**Review by tomponline — CHANGES_REQUESTED** [review]
I've gone through a few iterations on suggestions for wording, so best to view on github rather than email :)

File: lxc/config_device.go [hunk 4]
```diff
@@ -244,7 +244,13 @@ func (c *cmdConfigDeviceGet) Run(cmd *cobra.Command, args []string) error {
 
 		dev, ok := inst.Devices[devname]
 		if !ok {
-			return fmt.Errorf(i18n.G("The device doesn't exist"))
+			_, ok = inst.ExpandedDevices[devname]
+			if !ok {
+				return fmt.Errorf(i18n.G("The device doesn't exist"))
```
Comment (tomponline) [inline lxc/config_device.go:249]: How about just "Device doesn't exist"

File: lxc/config_device.go [hunk 5]
```diff
@@ -484,7 +490,13 @@ func (c *cmdConfigDeviceRemove) Run(cmd *cobra.Command, args []string) error {
 		for _, devname := range args[1:] {
 			_, ok := inst.Devices[devname]
 			if !ok {
-				return fmt.Errorf(i18n.G("The device doesn't exist"))
+				_, ok := inst.ExpandedDevices[devname]
+				if !ok {
+					return fmt.Errorf(i18n.G("The device doesn't exist"))
```
Comment (tomponline) [inline lxc/config_device.go:495]: How about just "Device doesn't exist"

File: lxc/config_device.go [hunk 6]
```diff
@@ -593,7 +605,12 @@ func (c *cmdConfigDeviceSet) Run(cmd *cobra.Command, args []string) error {
 		}
 		dev, ok := inst.Devices[devname]
 		if !ok {
-			return fmt.Errorf(i18n.G("The device doesn't exist"))
+			_, ok = inst.ExpandedDevices[devname]
+			if !ok {
+				return fmt.Errorf(i18n.G("The device doesn't exist"))
```
Comment (tomponline) [inline lxc/config_device.go:610]: How about just "Device doesn't exist"

**Comment by monstermunchkin** [comment]
@tomponline I changed the "The device doesn't exist" error message everywhere in the file just to be consistent.

**Review by tomponline — APPROVED** [review]
