### PR TITLE
gpu: special case passing all GPUs

### LINKED ISSUE #4683: Issues with GPU passthrough in LXD 3.2
# Required information

 * Distribution: **ubuntu**
 * Distribution version: **16.04**
 * The output of "lxc info" or if that fails: 
   * Kernel version: **4.15.0-15-lowlatency**
   * LXC version: **3.2** candidate
   * LXD version: **3.2** candidate
   * Storage backend in use: **zfs**

# Issue description
Creating a new container with GPU, fail:
**Error: No device minor index detected, and more than one NVIDIA card present**

# Steps to reproduce
```
lxc launch ubuntu:16.04 c1 -c raw.idmap="both 1000 1000" -c nvidia.runtime=true
lxc config device add c1 gtx gpu
```
Previously I had a container with GPU mapped but after the Snap auto-refresh
the container showed the same symptoms. Trying to start that previous container I got the following error:

**Error: No device minor index detected, and more than one NVIDIA card present
Try `lxc info --show-log cuda92` for more info**

```
Name: cuda92
Remote: unix://
Architecture: x86_64
Created: 2018/06/22 09:29 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc cuda92 20180622092922.749 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc cuda92 20180622092922.749 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
lxc cuda92 20180622092922.772 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc cuda92 20180622092922.772 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
lxc cuda92 20180622092924.153 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc cuda92 20180622092924.153 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by brauner**
Closes #4683.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

File: lxd/devices.go [hunk 1]
```diff
@@ -169,7 +170,11 @@ func findNvidiaMinor(pci string) (string, error) {
 	return "", err
 }
 
-func deviceLoadGpu() ([]gpuDevice, []nvidiaGpuDevices, error) {
+func wantsAllGPUs(m map[string]string) bool {
```
Comment (stgraber) [inline lxd/devices.go]: Nit but `deviceWantsAllGPUs` instead? trying to keep things moderately namespaced.

**Comment by brauner** [comment]
@stgraber, good to go
