### PR TITLE
lxd/recover: Use configuration defaults

### LINKED ISSUE #10862: LXD recover doesn't use storage volume defaults logic
The cli for recovering a ZFS pool queries me for the pool name, dataset and then requires me to specify `zfs.pool_name=$dataset` again in the key-values section.

```
This LXD server currently has the following storage pools:
Would you like to recover another storage pool? (yes/no) [default=no]: y
Name of the storage pool: default
Name of the storage backend (btrfs, dir, lvm, zfs): zfs
Source of the storage pool (block device, volume group, dataset, path, ... as applicable): zroot/data/lxd_pools/default
Additional storage pool configuration property (KEY=VALUE, empty when done): 
Would you like to recover another storage pool? (yes/no) [default=no]: 
The recovery process will be scanning the following storage pools:
 - NEW: "default" (backend="zfs", source="zroot/data/lxd_pools/default")
Would you like to continue with scanning for lost volumes? (yes/no) [default=yes]: 
Scanning for unknown volumes...
Error: Failed validation request: Failed mounting pool "default": Cannot mount pool as "zfs.pool_name" is not specified
```

### PR DESCRIPTION
**Pull request by MusicDin**
Extract the defaults generation inside each pool driver's `Create()` function into a separate `PopulateConfig()` function.

On `lxd recover`, the pool's configuration is populated with default values before the configuration gets validated.

Fixes #10862

### CODE REVIEW

**Comment by MusicDin** [comment]
@tomponline

Please check whether:
- [ ] the approach of extracting default configuration from each pool's driver `Create()` function is followed correctly,
- [ ] `PopulateConfig()` function should contain config validation (e.g. is `zfs.pool_name` valid)

In addition, I have avoided changing `config["source"]` to prevent any changes in the current flow of pool's driver `Create()` function.

File: lxd/storage/backend_lxd.go [hunk 1]
```diff
@@ -208,6 +213,12 @@ func (b *lxdBackend) Create(clientType request.ClientType, op *operations.Operat
 		return nil
 	}
 
+	// Populate storage pool configuration with default values
+	err = b.driver.PopulateConfig()
```
Comment (tomponline) [inline lxd/storage/backend_lxd.go:217]: this should be done inside the driver I think.

File: lxd/storage/drivers/driver_btrfs.go [hunk 2]
```diff
@@ -103,6 +103,11 @@ func (d *btrfs) Info() Info {
 	}
 }
 
+// PopulateConfig populates the storage pool's configuration file with the default values.
```
Comment (tomponline) [inline lxd/storage/drivers/driver_btrfs.go:106]: We would want a separate commit per driver for review clarity.

File: lxd/storage/drivers/driver_ceph.go [hunk 3]
```diff
@@ -122,6 +115,17 @@ func (d *ceph) Create() error {
 		}
 	}
 
+	return nil
+}
+
+// Create is called during pool creation and is effectively using an empty driver struct.
+// WARNING: The Create() function cannot rely on any of the struct attributes being set.
+func (d *ceph) Create() error {
+	revert := revert.New()
```
Comment (tomponline) [inline lxd/storage/drivers/driver_ceph.go:124]: I think we should be calling FillConfig from inside Create, as it already can modify the config.

**Comment by tomponline** [comment]
Lets focus on ZFS for now and we can move the logic for generating defaults for the other storage drivers once we've addressed the actual issue we want to with this PR.

**Comment by tomponline** [comment]
This is looking good!

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@MusicDin the tests look good for ZFS, do you want to continue extracting out the logic for the other drivers?

**Comment by MusicDin** [comment]
Yes, I will go one by one, so that it is easier to review the changes. 

Should I also extract the rest of the defaults for the ZFS pool, such as the `size` and potentially `source`?

**Comment by tomponline** [comment]
> Should I also extract the rest of the defaults for the ZFS pool, such as the `size` and potentially `source`?

Yes please.

**Comment by MusicDin** [comment]
@tomponline I suppose that validation should not be part of the `FillConfig()` function?

**Comment by tomponline** [comment]
> @tomponline I suppose that validation should not be part of the `FillConfig()` function?

Which part were you thinking of?

File: lxd/storage/drivers/driver_zfs.go [hunk 4]
```diff
@@ -235,14 +264,6 @@ func (d *zfs) Create() error {
...
-		d.config["size"] = ""
-
-		// Set default pool_name.
-		if d.config["zfs.pool_name"] == "" {
-			d.config["zfs.pool_name"] = d.name
-		}
-
 		// Validate pool_name.
 		if strings.Contains(d.config["zfs.pool_name"], "/") {
 			return fmt.Errorf("zfs.pool_name can't point to a dataset when source isn't set")
```
[the remark this answers is not in the document]
Comment (tomponline) [reply lxd/storage/drivers/driver_zfs.go:269]: Ah, no, lets keep validation until after FillConfig has been applied.

**Comment by MusicDin** [comment]
@tomponline 

Extracted defaults:
- [x] zfs
- [ ] btrfs
- [ ] dir

If there are no comments, I'll do it for the rest (ceph and lvm)

File: lxd/api_internal_recover.go [hunk 5]
```diff
@@ -177,6 +177,12 @@ func internalRecoverScan(s *state.State, userPools []api.StoragePoolsPost, valid
 					return response.SmartError(fmt.Errorf("Failed to initialise unknown pool %q: %w", p.Name, err))
 				}
 
+				// Populate configuration with default values
+				err := pool.Driver().FillConfig()
```
Comment (tomponline) [inline lxd/api_internal_recover.go:181]: So the commit ordering is a little odd here, as we are calling `FillConfig` before its been added to the storage interface and drivers. Please can you order the commits logically so they dont use resources before they exist.

Also, just a small nit, but can you end comments with a full stop. Thanks

**Review by tomponline — CHANGES_REQUESTED** [review]
LGTM, just a couple of small nits.

**Comment by MusicDin** [comment]
@tomponline 

I have fixed the order of commits and added a full stop at the end of comments.
In addition, I have extracted the defaults for:
- [ ] ceph
- [ ] cephfs
- [ ] cephobject
- [ ] lvm

**Comment by MusicDin** [comment]
@tomponline To me the tests look OK. Most failed tests are due to `no space left on device`. Only [this one (TestEndpoints_NetworkSocketBasedActivation)](https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/9929/arch=amd64,backend=dir,compiler=golang-1.18,section=standalone/console) actually failed.

Please take another look, and if there are no other comments, I think we can merge this one?

**Comment by tomponline** [comment]
Please can you rebase on master so you get the new github runner system tests.

**Review by tomponline — APPROVED** [review]
LGTM!
