### PR TITLE
VM: Allow force stop to kill QEMU process if in Error status

### LINKED ISSUE #8958: Bad user experience when qemu crashes
Recently, we've run into an issue where qemu will "crash" when creating VM's with multiple CPUs and a relatively small amount of memory, such as using the `-t c2-m2` option.  That seems to come from a bug in grub or the signed shim in the image and is not the fault of LXD nor Qemu.

However, when qemu does falter, there is no feedback from LXD that there is an issue other than the state says stopped.  I think it would be better if LXD could provide a "broken" state to at least alert that there is a problem in this case.

Also, not sure if this should be a separate bug, but once qemu and LXD get in this state, trying to delete the "broken" instance won't work due to the fact that qemu is actually still running and holding the zfs volume open and so the `zfs destroy` fails.  The error that is presented to the user is scary and unhelpful and a user would have to know to kill the "crashed" qemu process by hand to get out of this mess.

### PR DESCRIPTION
**Pull request by tomponline**
Also fix shutdown lifecycle events for all instance types which was broken for self-initiated shutdowns in https://github.com/lxc/lxd/commit/69ed7f0e091a6652a527667f215e8404bf3b7a93

Also handles "internal-error" from QEMU QMP status request when KVM has crashed.

Behaviour:

```
lxc launch images:ubuntu/focal v1 --vm
lxc ls v1
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| NAME |  STATE  |        IPV4         |                      IPV6                       |      TYPE       | SNAPSHOTS |
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| v1   | RUNNING | 10.98.30.5 (enp5s0) | fd42:f402:8623:5b6b:216:3eff:fe82:72f2 (enp5s0) | VIRTUAL-MACHINE | 0         |
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+

# Simulate QEMU problem by removing QMP socket file.
sudo rm /var/log/lxd/v1/qemu.monitor
# Reload LXD to clear QMP connection cache

lxc ls v1
+------+-------+------+------+-----------------+-----------+
| NAME | STATE | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+------+-------+------+------+-----------------+-----------+
| v1   | ERROR |      |      | VIRTUAL-MACHINE | 0         |
+------+-------+------+------+-----------------+-----------+

mount | grep v1
zfs/virtual-machines/v1 on /var/lib/lxd/storage-pools/zfs/virtual-machines/v1 type zfs (rw,xattr,posixacl)
zfs/virtual-machines/v1 on /var/lib/lxd/storage-pools/zfs/virtual-machines/v1/config.mount type zfs (ro,xattr,posixacl)

lxc start v1
Error: The instance cannot be started as in Error status

lxc stop v1
Error: The instance cannot be cleanly shutdown as in Error status

lxc stop v1 -f
# OK

mount | grep v1
# Nothing

lxc stop v1
Error: The instance is already stopped

lxc start v1
lxc ls v1
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| NAME |  STATE  |        IPV4         |                      IPV6                       |      TYPE       | SNAPSHOTS |
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
| v1   | RUNNING | 10.98.30.5 (enp5s0) | fd42:f402:8623:5b6b:216:3eff:fe82:72f2 (enp5s0) | VIRTUAL-MACHINE | 0         |
+------+---------+---------------------+-------------------------------------------------+-----------------+-----------+
```

Fixes #8958

Associated tests: https://github.com/lxc/lxc-ci/pull/339

### CODE REVIEW

File: lxd/instance/drivers/driver_qemu.go [hunk 1]
```diff
@@ -3277,13 +3277,33 @@ func (d *qemu) pid() (int, error) {
 	return pid, nil
 }
 
+// forceStop kills the QEMU prorcess if running, performs normal device & operation cleanup and sends stop
+// lifecycle event.
+func (d *qemu) forceStop() error {
+	pid, _ := d.pid()
+	if pid > 0 {
+		d.killQemuProcess(pid)
```
Comment (stgraber) [inline lxd/instance/drivers/driver_qemu.go:3285]: Looking at `killQemuProcess` I'm not convinced that it's waiting logic is good enough.

You can only really `Wait` on a process which is one of your children. If LXD was restarted between the VM start time and it being killed, I don't think we'll suitably wait, resulting in us calling onStop, trying to undo the storage while qemu is still in D state trying to flush its writes.

Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:3285]: Yep good point I will relook at this. Thanks

Comment (tomponline) [reply lxd/instance/drivers/driver_qemu.go:3285]: @stgraber it was actually fine because the `onStop()` function performs the correct wait procedure before starting device cleanup. However to improve readability I've put up this PR: https://github.com/lxc/lxd/pull/8978
