### PR TITLE
Bug static ip on multiple bridged nics

### LINKED ISSUE #9719: Adding multiple bridged NICs connected to same managed network breaks static IP allocation
If you have a managed LXD network, say `lxdbr0` that provides DHCP and SLAAC functionality to the network.

Then add 2 NICs to the instance both connected to the same network, e.g.

```
lxc config device add c1 eth0 network=lxdbr0 ipv4.address=192.168.1.2
lxc config device add c2 eth1 network=lxdbr0
```

Adding the 2nd NIC will wipe out the static IP allocation in dnsmasq of the first NIC.

This is a plausible configuration as when using nesting (or VM with containers) you may want to pass into additional NICs connected to the same network to be subsequently used inside another container or as an OVN uplink network (without having IPs configured in the outer instance).

This problem occurs because the dnsmasq host config file LXD generates expects 1 file containing 1 line per instance, but really we need to have that per-instance file support 1 line per NIC.

### PR DESCRIPTION
**Pull request by markylaing**
Appends the device name to files under `networks/<network>/dnsmasq.hosts`. These were previously named solely after the instance (and project) but this caused static IP allocation to break if multiple devices were attached.

Closes #9719

### CODE REVIEW

File: lxd/patches.go [hunk 1]
```diff
@@ -188,6 +190,29 @@ func patchesApply(d *Daemon, stage patchStage) error {
 
 // Patches begin here
 
+func patchDnsmasqEntriesIncludeDeviceName(name string, d *Daemon) error {
+	return d.cluster.InstanceList(nil, func(inst db.Instance, proj db.Project, profiles []api.Profile) error {
```
Comment (stgraber) [inline lxd/patches.go:194]: We should use whatever the equivalent function is to only query the local instances.
This one will list everything in an entire cluster rather than just for the local system.

**Comment by stgraber** [comment]
I think we need to make sure we also do the right thing when we:
 - Remove a device (whether it's renamed, fully removed or it no longer needs a dnsmasq entry)
 - Deletion of the instance properly wipes all those files

File: lxd/patches.go (hunk 1 above)
Comment (markylaing) [reply lxd/patches.go]: There doesn't seem to be a specific `db` function for listing instances on the current node. Instead I've used `d.cluster.GetNodeID` to get the id of the node and passed that into the `InstanceFilter` (first argument of the `InstanceList` function).

**Comment by markylaing** [comment]
> I think we need to make sure we also do the right thing when we:
> 
> * Remove a device (whether it's renamed, fully removed or it no longer needs a dnsmasq entry)
> * Deletion of the instance properly wipes all those files

1. Removing a device: The file is removed [here](https://github.com/lxc/lxd/pull/9790/files#diff-6c03e5a8982ea32839d566d5dc28a47d0b9d52f1f5847ee6eb391858c52635afR64) and the device name is passed in [here](https://github.com/lxc/lxd/pull/9790/files#diff-4852ea74f7ad2af08879be6d9495a75b0e58f814d9f9eb1f82e74485a9a3b7baR817). As far as I can tell it isn't possible to rename a device? I can see how one might be deleted and re-created with a different name but in this case the same `device.Remove` function will be called, so the dnsmasq entry will be removed.
2. Deletion of the instance: Both lxc and qemu drivers remove all devices on instance delete (if not a snapshot; see for [lxc](https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go#L3708), [qemu](https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_qemu.go#L4496)). These functions call `device.Remove` which ensures the files are removed. 

    Renaming an instance: Both the lxc and qemu drivers call `network.UpdateDNSMasqStatic` on instance renaming. This function clears all files under `dnsmasq.hosts` and rebuilds them with the new configuration. It has been updated to pass in the device name ([here](https://github.com/lxc/lxd/pull/9790/files#diff-0522df701d8c2f5be0010ef3ef654eca0817b99fcc460ef812f26db6ba63a341R481)). So the files are renamed immediately when the instance is renamed.

File: lxd/patches.go [hunk 2]
```diff
@@ -188,6 +190,30 @@ func patchesApply(d *Daemon, stage patchStage) error {
 
 // Patches begin here
 
+func patchDnsmasqEntriesIncludeDeviceName(name string, d *Daemon) error {
+	nodeId := strconv.Itoa(int(d.cluster.GetNodeID()))
+	return d.cluster.InstanceList(&db.InstanceFilter{Node: &nodeId}, func(inst db.Instance, proj db.Project, profiles []api.Profile) error {
+		for _, device := range inst.Devices {
+			if device.Type == db.TypeNIC && device.Config["nictype"] == "bridged" && device.Config["network"] != "" {
```
Comment (tomponline) [inline lxd/patches.go:197]: This won't clean up entries that use the parent property rather than network.

Can't we just blow away all the config files and rebuild all nic hosts files to be safe we recreate the correct config?

Comment (tomponline) [reply lxd/patches.go:197]: I'm not sure this patch will work as those with network property don't have nictype.

Comment (stgraber) [reply lxd/patches.go:197]: Yeah, wiping them all may be the best approach, hopefully dnsmasq won't get too mad when that happens (as the instances will still be running during the refresh).

Comment (stgraber) [reply lxd/patches.go:197]: @markylaing can you send a follow up PR to sort that out on Monday?

Comment (tomponline) [reply lxd/patches.go:197]: From memory dnsmasq notices adding or updating files but not removing them so should be OK.
