### PR TITLE
lxd: auto snap create and pruning are in the same task

### LINKED ISSUE #11407: Some snapshots fail with `err="Instance snapshot record count doesn't match instance snapshot volume record count"`
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.2 amd64
```
$ snap list lxd
Name  Version        Rev    Tracking      Publisher   Notes
lxd   5.0.2-838e1b2  24322  5.0/stable/…  canonical✓  -
```

# Issue description

I have a _slow_ machine which runs 2 containers with `snapshots.schedule`:

```
$ lxc profile show sdeziel | grep snapshots
  snapshots.expiry: 3d
  snapshots.schedule: '@daily, @startup'
```

Sometimes, a snapshot fails and the following error is logged:

```
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=error msg="Error creating snapshot" err="Instance snapshot record count doesn't match instance snapshot volume record count" instance=pm project=default snapshot=snap32
```

The LXD debug logs around that failure:

```
sdeziel@ocelot:~$ journalctl --since today -u snap.lxd.daemon | grep -vF a47ef4f5017006a431c519f994486fedda515ebbba26dec47a90c0645283bd50 | grep -E '^Feb 22 14:2[0-6]:'
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="New operation" class=task description="Snapshotting instance" operation=bba50a08-baff-478f-94e2-bb4d9bdf0489 project=
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Creating scheduled instance snapshots"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Started operation" class=task description="Snapshotting instance" operation=bba50a08-baff-478f-94e2-bb4d9bdf0489 project=
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock created" action=create instance=pm/snap32 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Creating instance" ephemeral=false instance=pm/snap32 instanceType=container project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="New operation" class=task description="Cleaning up expired instance snapshots" operation=b07205a8-93bb-4cc9-b307-dcd52a69d904 project=
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Pruning expired instance snapshots"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Started operation" class=task description="Cleaning up expired instance snapshots" operation=b07205a8-93bb-4cc9-b307-dcd52a69d904 project=
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock created" action=delete instance=pm/snap30 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Deleting container" created="2023-02-19 14:25:50.482226021 +0000 UTC" ephemeral=false instance=pm/snap30 instanceType=container project=default used="0001-01-01 00:00:00 +0000 UTC"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="DeleteInstanceSnapshot started" instance=pm/snap30 project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Deleting instance snapshot volume" instance=pm/snap30 project=default snapshotName=snap30 volName=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Created container" ephemeral=false instance=pm/snap32 instanceType=container project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="CreateInstanceSnapshot started" instance=pm/snap32 project=default src=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="CreateInstanceSnapshot finished" instance=pm/snap32 project=default src=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="MountInstance started" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="MountInstance finished" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile started" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="DeleteInstanceSnapshot finished" instance=pm/snap30 project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile finished" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UnmountInstance started" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Skipping unmount as in use" driver=zfs pool=default refCount=1 volName=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UnmountInstance finished" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock finished" action=create err="<nil>" instance=pm/snap32 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock created" action=delete instance=pm/snap32 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Deleting container" created="2023-02-22 14:25:59.189051125 +0000 UTC" ephemeral=false instance=pm/snap32 instanceType=container project=default used="0001-01-01 00:00:00 +0000 UTC"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile started" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="DeleteInstanceSnapshot started" instance=pm/snap32 project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Deleting instance snapshot volume" instance=pm/snap32 project=default snapshotName=snap32 volName=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Skipping unmount as in use" driver=zfs pool=default refCount=1 volName=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile finished" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Deleted container" created="2023-02-19 14:25:50.482226021 +0000 UTC" ephemeral=false instance=pm/snap30 instanceType=container project=default used="0001-01-01 00:00:00 +0000 UTC"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock finished" action=delete err="<nil>" instance=pm/snap30 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Deleted instance snapshot" project=default snapshot=pm/snap30
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Success for operation" class=task description="Cleaning up expired instance snapshots" operation=b07205a8-93bb-4cc9-b307-dcd52a69d904 project=
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Done pruning expired instance snapshots"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="DeleteInstanceSnapshot finished" instance=pm/snap32 project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile started" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Skipping unmount as in use" driver=zfs pool=default refCount=1 volName=pm
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="UpdateInstanceBackupFile finished" instance=pm project=default
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Deleted container" created="2023-02-22 14:25:59.189051125 +0000 UTC" ephemeral=false instance=pm/snap32 instanceType=container project=default used="0001-01-01 00:00:00 +0000 UTC"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Instance operation lock finished" action=delete err="<nil>" instance=pm/snap32 project=default reusable=false
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=error msg="Error creating snapshot" err="Instance snapshot record count doesn't match instance snapshot volume record count" instance=pm project=default snapshot=snap32
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=info msg="Done creating scheduled instance snapshots"
Feb 22 14:25:59 ocelot lxd.daemon[1286]: time="2023-02-22T14:25:59Z" level=debug msg="Success for operation" class=task description="Snapshotting instance" operation=bba50a08-baff-478f-94e2-bb4d9bdf0489 project=
```

and the info of the affected container:

```
sdeziel@ocelot:~$ lxc info pm
Name: pm
Status: RUNNING
Type: container
Architecture: x86_64
PID: 1642
Created: 2022/09/30 15:53 UTC
Last Used: 2023/02/17 16:17 UTC

Resources:
  Processes: 174
  Disk usage:
    redmine: 185.85MiB
    root: 857.84MiB
  CPU usage:
    CPU usage (in seconds): 13303
  Memory usage:
    Memory (current): 429.18MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: veth3770c431
      MAC address: 00:16:3e:1e:bc:32
      MTU: 1500
      Bytes received: 8.63MB
      Bytes sent: 1.75MB
      Packets received: 7145
      Packets sent: 4596
      IP addresses:
        inet:  172.24.21.43/24 (global)
        inet6: 2001:470:b1c3:7941::43/64 (global)
        inet6: fe80::216:3eff:fe1e:bc32/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 68.59kB
      Bytes sent: 68.59kB
      Packets received: 390
      Packets sent: 390
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Snapshots:
+--------+----------------------+----------------------+----------+
|  NAME  |       TAKEN AT       |      EXPIRES AT      | STATEFUL |
+--------+----------------------+----------------------+----------+
| snap31 | 2023/02/21 14:25 UTC | 2023/02/24 14:25 UTC | NO       |
+--------+----------------------+----------------------+----------+
```

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #11407

### CODE REVIEW

File: lxd/instance.go [hunk 1]
```diff
@@ -416,7 +416,68 @@ func instanceLoadNodeProjectAll(ctx context.Context, s *state.State, project str
...
+		case <-ch:
+		}
+	}
+
+	return nil
+}
+
+var instSnapshotsPruneRunning = sync.Map{}
+
+func pruneExpiredInstanceSnapshots(ctx context.Context, d *Daemon, snapshots []instance.Instance) error {
```
Comment (tomponline) [inline lxd/instance.go:459]: Was this function changed or just moved?

File: lxd/instance.go [hunk 2]
```diff
@@ -518,69 +579,12 @@ func autoCreateInstanceSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
 
 		_, _ = op.Wait(ctx)
 		logger.Info("Done creating scheduled instance snapshots")
-	}
-
-	first := true
```
Comment (tomponline) [inline lxd/instance.go:523]: This chunk has been removed, but not clear why?

File: lxd/instance.go (hunk 1 above)
Comment (gabrielmougard) [reply lxd/instance.go:459]: just moved

File: lxd/instance.go [hunk 3]
```diff
@@ -416,7 +416,68 @@ func instanceLoadNodeProjectAll(ctx context.Context, s *state.State, project str
 	return instances, nil
 }
 
-func autoCreateInstanceSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
+func autoCreateInstanceSnapshots(ctx context.Context, d *Daemon, instances []instance.Instance) error {
+	// Make the snapshots.
+	for _, inst := range instances {
+		ch := make(chan error)
```
Comment (tomponline) [inline lxd/instance.go:422]: I reaslise this is just a copy/paste and not your code, but, as a separate commit, I think we have an opportunity to improve this code.

1. Although the `ch` is a channel of `error`s, it always just has nil posted to it, and is infact just used as an indicator that the go routine has ended. So instead I suggest we change this to a `struct{}` type channel and just `defer close(ch)` at the top of the go routine.
2. I'm not sure we should return from this function if part-way through a snapshot when the context is cancelled, instead we should finish the ongoing snapshot and then return. So rather than including the context's Go routine in the select, instead add a check for `ctx.Error() != nil` at the start of each for loop iteration and return if the context has been cancelled.

File: lxd/instance.go (hunk 1 above)
Comment (tomponline) [reply lxd/instance.go:459]: OK, so in the future, to make it easier to review, you can split that into 2 commits or alternatively leave it where it was.

File: lxd/instance.go [hunk 4]
```diff
@@ -416,7 +416,73 @@ func instanceLoadNodeProjectAll(ctx context.Context, s *state.State, project str
...
+
+			err = inst.Snapshot(snapshotName, expiry, false)
+			if err != nil {
+				l.Error("Error creating snapshot", logger.Ctx{"snapshot": snapshotName, "err": err})
+			}
+
+			ch <- struct{}{}
+		}(inst)
+		select {
+		case <-ctx.Done():
```
Comment (tomponline) [inline lxd/instance.go:453]: This bit needs to go otherwise it will still return early when the context is cancelled, just replace with:

```go
<-ch
```

With no need for select at all.

Comment (tomponline) [reply lxd/instance.go:453]: Actually we dont need the go routine at all now, just the ctx.Err check

Comment (tomponline) [reply lxd/instance.go]: @gabrielmougard this part hasn't been addressed yet.

File: lxd/instance.go (hunk 2 above)
Comment (tomponline) [reply lxd/instance.go:523]: @gabrielmougard this question hasn't been answered yet.

**Review by tomponline — CHANGES_REQUESTED** [review]
Nearly there, we just need to check whether the removal of the section that starts:

```go
	first := true
```

Is going to cause a problem, as its removal doesn't seem intentional.

**Comment by gabrielmougard** [comment]
The actual structure is like the following :

```go
func autoCreateInstanceSnapshots(ctx context.Context, d *Daemon, instances []instance.Instance) error {
	...
}

var instSnapshotsPruneRunning = sync.Map{}

func pruneExpiredInstanceSnapshots(ctx context.Context, d *Daemon, snapshots []instance.Instance) error {
	...
}

func autoCreateAndPruneExpiredInstanceSnapshotsTask(d *Daemon) (task.Func, task.Schedule) {
	// `f` creates new scheduled instance snapshots and then, prune the expired ones
	f := func(ctx context.Context) {
		... // (creation bit)

		... // (pruning bit)
	}

	first := true // should be at line 673 
	schedule := func() (time.Duration, error) {
		interval := time.Minute

		if first {
			first = false
			return interval, task.ErrSkip
		}

		return interval, nil
	}

	return f, schedule
}
```

**Review by tomponline — APPROVED** [review]
