### PR TITLE
shared/utils: deal with symlinks

### LINKED ISSUE #4097: [Regression] lxd-2.19: lxd lvm backed containers doesn't start anymore.
After upgrading to lxd-2.19, all containers in my laptop refused to start. The output of it it the
following:
```
$ lxc list
+---------------+---------+------+------+------------+-----------+
|     NAME      |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+------+------+------------+-----------+
| juju-e5092b-0 | STOPPED |      |      | PERSISTENT | 0         |
+---------------+---------+------+------+------------+-----------+
| juju-e5092b-3 | STOPPED |      |      | PERSISTENT | 0         |
+---------------+---------+------+------+------------+-----------+
| juju-e5092b-4 | STOPPED |      |      | PERSISTENT | 0         |
+---------------+---------+------+------+------------+-----------+
| xenial-maas   | STOPPED |      |      | PERSISTENT | 0         |
+---------------+---------+------+------+------------+-----------+
$ lxc start xenial-maas
error: device or resource busy
Try `lxc info --show-log xenial-maas` for more info
```
Containers are lvm backed:
```
$ lxc storage show LXDPool
config:
  lvm.thinpool_name: LXDPool
  lvm.vg_name: bee
  source: bee
  volatile.initial_source: bee
description: ""
name: LXDPool
driver: lvm
used_by:
- /1.0/containers/juju-e5092b-0
- /1.0/containers/juju-e5092b-3
- /1.0/containers/juju-e5092b-4
- /1.0/containers/xenial-maas
- /1.0/images/f4eba5df5f88129cc68d969ae0f3762869ec79c9abc8344a74bb5c932d70b2ad
- /1.0/profiles/default
```
The container tried to restart uses the following profile:
```
$ lxc profile show maas
config:
  limits.cpu: "1"
  limits.memory: 2GB
  raw.lxc: |-
    lxc.cgroup.devices.allow = c 10:237 rwm
    lxc.aa_profile = unconfined
    lxc.cgroup.devices.allow = b 7:* rwm
  security.privileged: "true"
description: ""
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  eth1:
    name: eth1
    nictype: bridged
    parent: virbr0
    type: nic
  eth2:
    name: eth2
    nictype: bridged
    parent: virbr1
    type: nic
  loop-control:
    path: /dev/loop-control
    type: unix-char
  loop0:
    gid: "6"
    path: /dev/loop0
    type: unix-block
  loop1:
    gid: "6"
    path: /dev/loop1
    type: unix-block
  loop2:
    gid: "6"
    path: /dev/loop2
    type: unix-block
  loop3:
    gid: "6"
    path: /dev/loop3
    type: unix-block
  loop4:
    gid: "6"
    path: /dev/loop4
    type: unix-block
  loop5:
    gid: "6"
    path: /dev/loop5
    type: unix-block
  loop6:
    gid: "6"
    path: /dev/loop6
    type: unix-block
  loop7:
    gid: "6"
    path: /dev/loop7
    type: unix-block
name: maas
used_by:
- /1.0/containers/xenial-maas
```
Before upgrading, my set of containers looks like this:
```
$ lxc list
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
|     NAME      |  STATE  |              IPV4              |                    IPV6                    |    TYPE    | SNAPSHOTS |
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| juju-e5092b-0 | RUNNING | 192.168.255.13 (eth0)          |                                            | PERSISTENT | 0         |
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| juju-e5092b-3 | RUNNING | 192.168.255.16 (eth0)          |                                            | PERSISTENT | 0         |
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| juju-e5092b-4 | RUNNING | 192.168.255.17 (eth0)          |                                            | PERSISTENT | 0         |
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
| xenial-maas   | RUNNING | 192.168.255.2 (eth1)           | fde8:a20b:8409:0:216:3eff:febe:108f (eth0) | PERSISTENT | 0         |
|               |         | 192.168.254.2 (eth2)           |                                            |            |           |
|               |         | 192.168.0.59 (eth0)            |                                            |            |           |
+---------------+---------+--------------------------------+--------------------------------------------+------------+-----------+
$ lxc info --show-log xenial-maas
Name: xenial-maas
Remote: unix://
Architecture: x86_64
Created: 2017/11/28 10:48 UTC
Status: Running
Type: persistent
Profiles: default, maas
Pid: 10618
Ips:
  eth2: inet    192.168.254.2   vethE3IJP5
  eth2: inet6   fe80::216:3eff:fed7:7298        vethE3IJP5
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
  eth0: inet    192.168.0.59    vethG0QL1N
  eth0: inet6   fde8:a20b:8409:0:216:3eff:febe:108f     vethG0QL1N
  eth0: inet6   fe80::216:3eff:febe:108f        vethG0QL1N
  eth1: inet    192.168.255.2   vethP9WDGV
  eth1: inet6   fe80::216:3eff:fe2b:feae        vethP9WDGV
Resources:
  Processes: 275
  CPU usage:
    CPU usage (in seconds): 572
  Memory usage:
    Memory (current): 888.78MB
    Memory (peak): 1.11GB
    Swap (current): 8.17MB
    Swap (peak): 2.44MB
  Network usage:
    lo:
      Bytes received: 123.99MB
      Bytes sent: 123.99MB
      Packets received: 291767
      Packets sent: 291767
    eth0:
      Bytes received: 621.50kB
      Bytes sent: 545.86kB
      Packets received: 8304
      Packets sent: 4042
    eth1:
      Bytes received: 250.89kB                                                                                                                                                                                                               
      Bytes sent: 364.95kB                                                                                                                                                                                                                   
      Packets received: 3318                                                                                                                                                                                                                 
      Packets sent: 2738                                                                                                                                                                                                                     
    eth2:                                                                                                                                                                                                                                    
      Bytes received: 5.06kB                                                                                                                                                                                                                 
      Bytes sent: 34.99kB                                                                                                                                                                                                                    
      Packets received: 68                                                                                                                                                                                                                   
      Packets sent: 128                                                                                                                                                                                                                      
                                                                                                                                                                                                                                             
Log:
```
Containers looks the same after upgrading but manually stopping them and restarting shows the error.
Trying any of the other containers fails the same. Creating a new container using the dir storage 
succeeds:
```
$ lxc profile create no-lvm
Profile no-lvm created
$ lxc storage create no-lvm dir
Storage pool no-lvm created
$ lxc profile device add no-lvm root disk path=/ pool=no-lvm
Device root added to no-lvm
$ lxc profile show no-lvm
config: {}
description: ""
devices:
  root:
    path: /
    pool: no-lvm
    type: disk
name: no-lvm
used_by: []
$ lxc launch -p no-lvm ubuntu:xenial test-container
Creating test-container

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach

Starting test-container
$ lxc list
+----------------+---------+------+------+------------+-----------+
|      NAME      |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+------+------+------------+-----------+
| juju-e5092b-0  | STOPPED |      |      | PERSISTENT | 0         |
+----------------+---------+------+------+------------+-----------+
| juju-e5092b-3  | STOPPED |      |      | PERSISTENT | 0         |
+----------------+---------+------+------+------------+-----------+
| juju-e5092b-4  | STOPPED |      |      | PERSISTENT | 0         |
+----------------+---------+------+------+------------+-----------+
| test-container | RUNNING |      |      | PERSISTENT | 0         |
+----------------+---------+------+------+------------+-----------+
| xenial-maas    | STOPPED |      |      | PERSISTENT | 0         |
+----------------+---------+------+------+------------+-----------+
```
Downgrading to 2.18 restores the situation to normal, 2.20 hasn't been tested yet.

### PR DESCRIPTION
**Pull request by brauner**
Closes #4097.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

File: shared/util_linux.go [hunk 1]
```diff
@@ -336,6 +336,15 @@ func GetFileStat(p string) (uid int, gid int, major int, minor int,
...
 
 func parseMountinfo(name string) int {
+	// In case someone uses symlinks we need to look for the actual
+	// mountpoint.
+	actualPath, err := filepath.EvalSymlinks(name)
+	if err != nil {
+		return -1
+	}
+
+	logger.Debugf("Path \"%s\" is pointing to \"%s\"", name, actualPath)
```
Comment (brauner) [inline shared/util_linux.go]: Removing the debug logs.

File: shared/util_linux.go [hunk 2]
```diff
@@ -361,8 +369,9 @@ func parseMountinfo(name string) int {
 
 func IsMountPoint(name string) bool {
 	ret := parseMountinfo(name)
-	if ret >= 0 {
-		return (ret == 1)
+	if ret == 1 {
+		logger.Debugf("Detected that \"%s\" is a mountpoint", name)
```
Comment (stgraber) [inline shared/util_linux.go]: And this one too
