### PR TITLE
Normalize the URLs in the client

### LINKED ISSUE #2112: unexpected end of JSON input
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Yakketty
 * Distribution version: 16.10
 * The output of "lxc info" or if that fails:
~~~yaml
apicompat: 0
auth: trusted
environment:
  addresses:
  - 10.0.1.73:8443
  - '[2001:470:8:85a:d181:7958:65a9:9796]:8443'
  - 10.0.4.1:8443
  - 192.168.122.1:8443
  - 172.17.0.1:8443
  - 10.0.5.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    CERTIFICATE
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-23-generic
  server: lxd
  serverpid: 4807
  serverversion: 2.0.2
  storage: zfs
  storageversion: "5"
config:
  core.https_address: '[::]'
  storage.zfs_pool_name: storage/LXD
public: false
~~~
# Issue description

error: unexpected end of JSON input

# Steps to reproduce

 1. Unknown

# Extra information

## Output of lxc exec --debug

~~~bash
$ lxc exec --debug /bin/bash trusty                                                                                                                                              
DBUG[06-13|11:58:34] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":[],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{"core.https_address":"[::]","storage.zfs_pool_name":"storage/LXD"},"environment":{"addresses":["10.0.1.73:8443","[2001:470:8:85a:d181:7958:65a9:9796]:8443","10.0.4.1:8443","192.168.122.1:8443","172.17.0.1:8443","10.0.5.1:8443"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nCERTIFICATE\n-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.1","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-23-generic","server":"lxd","server_pid":4807,"server_version":"2.0.2","storage":"zfs","storage_version":"5"},"public":false}}
 
DBUG[06-13|11:58:34] Posting {"command":["trusty"],"environment":{"HOME":"/root","TERM":"xterm-256color","USER":"root"},"height":59,"interactive":true,"wait-for-websocket":true,"width":219}
                                                                                                                                                                                              to http://unix.socket/1.0/containers//bin/bash/exec 
                       DBUG[06-13|11:58:34] Raw response:  
                                                           error: unexpected end of JSON input
~~~

## output of lxd in debug mode:

~~~bash
INFO[06-13|12:11:14] handling                                 method=GET url=/1.0 ip=@
DBUG[06-13|12:11:14] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"metadata": {
			"api_extensions": [],
			"api_status": "stable",
			"api_version": "1.0",
			"auth": "trusted",
			"config": {
				"core.https_address": "[::]",
				"storage.zfs_pool_name": "storage/LXD"
			},
			"environment": {
				"addresses": [
					"10.0.1.73:8443",
					"[2001:470:8:85a:d181:7958:65a9:9796]:8443",
					"10.0.4.1:8443",
					"192.168.122.1:8443",
					"172.17.0.1:8443",
					"10.0.5.1:8443"
				],
				"architectures": [
					"x86_64",
					"i686"
				],
				"certificate": "-----BEGIN CERTIFICATE-----\nCERT\n-----END CERTIFICATE-----\n",
				"driver": "lxc",
				"driver_version": "2.0.1",
				"kernel": "Linux",
				"kernel_architecture": "x86_64",
				"kernel_version": "4.4.0-23-generic",
				"server": "lxd",
				"server_pid": 21360,
				"server_version": "2.0.2",
				"storage": "zfs",
				"storage_version": "5"
			},
			"public": false
		}
	} 
INFO[06-13|12:11:15] Received 'interrupt signal', exiting. 
~~~

### PR DESCRIPTION
**Pull request by stgraber**
This avoids generating URLs which Go then drops on the floor.

Closes #2112

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -489,17 +489,32 @@ func (c *Client) websocket(operation string, secret string) (*websocket.Conn, er
 }
 
 func (c *Client) url(elem ...string) string {
+	// Normalize the URL
 	path := strings.Join(elem, "/")
+	entries := []string{}
```
Comment (sean-jc) [inline client.go]: Any reason `path = strings.Replace(path, "//", "/", -1)` wouldn't work?

Comment (stgraber) [inline client.go]: That's because strings.Replace("///", "//", "/", -1) gives you "//" instead of "/".

Comment (sean-jc) [inline client.go]: What about stripping slashes from elem prior to joining?  This would be especially nice if there is a built-in function for transforming slices.

```
entries := []string{}
for entry := range elem {
	append(entries, strings.Replace(entry, "/", "", -1))
}
path := strings.Join(entries, "/")
```

Comment (stgraber) [inline client.go]: Yep, that would work.

Comment (stgraber) [inline client.go]: Actually, no it wouldn't.

Comment (stgraber) [inline client.go]: We have cases where some elements come with a slash in them already and that's on purpose.

Comment (stgraber) [inline client.go]: so your suggestion would fail with my current testcase which is:

c.url("containers//bin/bash")

So that's a single pre-joined element being passed to the function. Dropping all slashes makes it "/1.0/containersbinbash" which is very much invalid.

**Comment by stgraber** [comment]
jenkins: test this please

File: client.go (hunk 1 above)
Comment (sean-jc) [inline client.go]: Bummer.  The only other thing I can think of would be to check for `//` in a loop.  The optimized version would look slightly weird but I think the intent would still be easier to understand than Join+Split+Join.  Most scenarios would be faster, only cases with lots of redundant slashes would be slower.

```
path := strings.Join(elem, "/")
for path = strings.Replace(path, "//", "/", -1); strings.Contains(path, "//"); path = strings.Replace(path, "//", "/", -1) {
}
```

Less optimized but easier to read version:

```
path := strings.Join(elem, "/")
for strings.Contains(path, "//") {
	path = strings.Replace(path, "//", "/", -1)
}
```
