### PR TITLE
lxd/storage/lvm: Pass nouuid for xfs backups

### LINKED ISSUE #5566: lxd export fails with lvm/xfs storage
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04
 * Kernel version: 4.15.0-46-generic
 * LXC version: 3.11 (snap)
 * LXD version: 3.11 (snap)
 * Storage backend in use: LVM with XFS (without thin provisioning)

# Issue description

lxc export c1 c1.tar.xz fails when the storage is lvm and xfs. I don't use thin provisioning, but I don't think it's relevant.
I also try with --optimized-storage --container-only (just in case)

Error: Create backup: Backup storage: Mount /dev/pool_lxc0/containers_snapshot--55c8df9e--6e85--432e--bec7--ab5d8642d2b2 onto /var/snap/lxd/common/lxd/storage-pools/pool0/containers/snapshot-55c8df9e-6e85-432e-bec7-ab5d8642d2b2: invalid argument

# Information to attach
I have look to the various logs files, the only relevant output i found is on /var/log/syslog:
XFS (dm-19): Filesystem has duplicate UUID c6973371-ce32-4068-b5ef-12d69ff33fb5 - can't mount

Googling this kind of problem I found it's possibile to mount with the option -o nouuid or generate a new uuid with xfs_admin tool.  I don't know if relevant...

BTW, now in /var/snap/lxd/common/lxd/backups I have a lots empty dirs. Can I delete them without problems?

### PR DESCRIPTION
**Pull request by stgraber**
Closes #5566

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/storage_lvm.go [hunk 1]
```diff
@@ -1285,6 +1285,13 @@ func (s *storageLvm) doContainerMount(project, name string) (bool, error) {
 	ourMount := false
 	if !shared.IsMountPoint(containerMntPoint) {
 		mountFlags, mountOptions := lxdResolveMountoptions(s.getLvmMountOptions())
+		if snap && lvFsType == "xfs" {
+			idx := strings.Index(mountOptions, "nouuid")
```
Comment (brauner) [inline lxd/storage_lvm.go]: Oh right, we already do this somewhere else in the lvm code. I vaguely remember having troubles with this during snapshots or something.

Comment (stgraber) [reply lxd/storage_lvm.go]: Yeah, we do on snapshotstart, that's where I took it from. The problem is that for backups we don't use the traditional snapshot mountpoints so needed to plumb it to the container mount function.

This code is a giant mess, hopefully @monstermunchkin's rework will make this much easier to deal with.

Short version is, when we create a new container from an image, we want to generate a new UUID, when we mount a container or custom storage volume, no fancy mountflag, when we mount anything else, we need nouuid.
