### PR TITLE
lxd/instance/lxc: Rework raw.lxc handling

### LINKED ISSUE #9093: raw.lxc key does't appened but inserted into container's lxc.conf
# Required information

* LXC version: 4.0.10 ( >= 4.0.7)
* LXD version: 4.17

# Issue description

According to instances.md, configuration key `raw.lxc`  contains "Raw LXC configuration to be appended to the generated one". For LXD 4.17 the strings from `raw.lxc` key does not **appended to** the generated lxc.conf but **inserted somewhere in** that file.
Due to the changes in LXC >= 4.0.7 ([1](https://github.com/lxc/lxc/commit/942b2d318642cc6b596b8d9778daa506a5578a56), [2](https://github.com/lxc/lxc/commit/320061b34fea7d7f280b0a421dddeac7dac7f1bf)) that makes impossible to configure container's network interfaces via LXC keys like `lxc.net.[N].ip[46].*` .

# Steps to reproduce

 1. Create minimal CT:
```
# lxc init images:busybox/1.33.1 raw-lxc-test --storage  default
Creating raw-lxc-test
                                            
The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach
```
 2. Add a physical network interface into CT, and lets LXC set IPv4 address on it via 'raw.lxc':
```
# lxc config device add raw-lxc-test eth0 nic name=eth0 nictype=physical parent=raw-lxc
Device eth0 added to raw-lxc-test
# lxc config set raw-lxc-test raw.lxc="lxc.net.0.ipv4.address=10.0.0.1/24"
```

Resulting CT configuration:
```
# lxc config show raw-lxc-test
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Busybox 1.33.1 amd64 (20210806_06:00)
  image.os: Busybox
  image.release: 1.33.1
  image.serial: "20210806_06:00"
  image.type: squashfs
  image.variant: default
  raw.lxc: lxc.net.0.ipv4.address=10.0.0.1/24
  volatile.apply_template: create
  volatile.base_image: 982fe78bba9b756ea0e53b145ea1180577b1fa15108afc205d3fcf8f04114dcf
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.uuid: de680a53-e263-4a37-9126-f5b15a6b82e2
devices:
  eth0:
    name: eth0
    nictype: physical
    parent: raw-lxc
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 3. Create dummy network interface 'raw-lxc', start a CT. LXC should rename interface to 'eth0' and set IPv4 address on it - but the later one is not happen, there is no IPv4 on eth0 inside CT:
```
# ip link add raw-lxc type dummy
# lxc start raw-lxc-test
# lxc exec raw-lxc-test ip addr show dev eth0
13: eth0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether 52:05:22:cc:80:a0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5005:22ff:fecc:80a0/64 scope link 
       valid_lft forever preferred_lft forever
```
In the generated CT lxc.conf content of the `raw.lxc` key was inserted inside configuration file, not _appended_ to it:
```
# tail /var/log/lxd/raw-lxc-test/lxc.conf
lxc.seccomp.profile = /var/lib/lxd/security/seccomp/raw-lxc-test
lxc.idmap = u 0 1000000 65536
lxc.idmap = g 0 1000000 65536
lxc.mount.auto = shmounts:/var/lib/lxd/shmounts/raw-lxc-test:/dev/.lxd-mounts
lxc.net.0.ipv4.address=10.0.0.1/24
lxc.net.0.type = phys
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.link = raw-lxc
lxc.rootfs.path = dir:/var/lib/lxd/containers/raw-lxc-test/rootfs
```
And in the LXC >= 4.0.7 `lxc.net.0.type` wipes all previous interface configuration - so `lxc.net.0.ipv4.address` is dropped.

 4. Let's imitate the `raw.lxc` value **appending** to the end of generated by LXD lxc.conf file - right according to the documentation.

Stop CT via LXD and delete LXD-specific lines from the generated lxc.conf:
```
# lxc stop raw-lxc-test
# sed -e '/lxc\.hook/ d' -e '/lxc\.seccomp\.profile/ d' -e '/idmap/ d' -i  /var/log/lxd/raw-lxc-test/lxc.conf
```
Move 'raw.lxc' content (`lxc.net.0.ipv4.address=10.0.0.1/24`) to the end of the lxc.conf:
```
# sed -e '/ipv4\.address/ d' -i /var/log/lxd/raw-lxc-test/lxc.conf
# echo "lxc.net.0.ipv4.address=10.0.0.1/24" >> /var/log/lxd/raw-lxc-test/lxc.conf
```
Now the end of the lxc.conf file is following:
```
# tail  /var/log/lxd/raw-lxc-test/lxc.conf
lxc.tty.max = 0
lxc.uts.name = raw-lxc-test
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.mount.auto = shmounts:/var/lib/lxd/shmounts/raw-lxc-test:/dev/.lxd-mounts
lxc.net.0.type = phys
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.link = raw-lxc
lxc.rootfs.path = dir:/var/lib/lxd/containers/raw-lxc-test/rootfs
lxc.net.0.ipv4.address=10.0.0.1/24
```
Start CT via raw LXC and check eth0 configuration:
```
# lxc-start -f /var/log/lxd/raw-lxc-test/lxc.conf raw-lxc-test
# lxc-attach raw-lxc-test ip addr show eth0
14: eth0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether 52:05:22:cc:80:a0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5005:22ff:fecc:80a0/64 scope link 
       valid_lft forever preferred_lft forever
```

### PR DESCRIPTION
**Pull request by stgraber**
We need to make sure that raw.lxc is applied last in the instance's config.
This is quite hard to do because of devices which are mostly dynamic and
added after the initial configuration is generated.

So instead, this creates a separate configuration file which is always
loaded following the main file. To keep validation working properly,
this then moves the validation logic into Update().

Closes #9093

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

File: lxd/instance/drivers/driver_lxc.go [hunk 1]
```diff
@@ -4075,6 +4070,37 @@ func (d *lxc) Update(args db.InstanceArgs, userRequested bool) error {
...
+
+		err = shared.WriteAll(f, []byte(d.expandedConfig["raw.lxc"]))
+		f.Close()
+		defer os.Remove(f.Name())
+		if err != nil {
+			return err
+		}
+
+		// Load the raw config.
+		err = cc.LoadConfigFile(f.Name())
```
Comment (brauner) [inline lxd/instance/drivers/driver_lxc.go:4095]: We should have a version that takes an FD as argument. Then you can generate in-memory config files (memfd, TMobile etc.).

Comment (brauner) [reply lxd/instance/drivers/driver_lxc.go:4095]: *TMobile my ass: tmpfile

Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:4095]: I did wonder about that :)

File: lxd/main_forkconsole.go [hunk 2]
```diff
@@ -74,6 +75,14 @@ func (c *cmdForkconsole) Run(cmd *cobra.Command, args []string) error {
 		return fmt.Errorf("Error opening config file: %q", err)
 	}
 
+	rawConfigPath := fmt.Sprintf("%s.raw", configPath)
```
Comment (tomponline) [inline lxd/main_forkconsole.go:78]: This repetition everywhere that d.LoadConfigFile() is used feels too easy to miss when someone uses `LoadConfigFile` in the future and misses loading the raw file too. Can we have a utility function that contains this logic in one place and replaces all use of `d.LoadConfigFile()` in the LXD code base?

Comment (tomponline) [reply lxd/main_forkconsole.go:78]: Also as a "nice to have", we could make go-lxcs `LoadConfigFile` accept a variadic argument indicating you can pass multiple paths and avoid the duplicated function call.

File: lxd/instance/drivers/driver_lxc.go [hunk 3]
```diff
@@ -2262,6 +2243,20 @@ func (d *lxc) startCommon() (string, []func() error, error) {
 		return "", nil, err
 	}
 
+	// Generate the LXC raw config
```
Comment (tomponline) [inline lxd/instance/drivers/driver_lxc.go:2246]: full stop missing here.

File: lxd/instance/drivers/driver_lxc.go (hunk 1 above)
Comment (tomponline) [reply lxd/instance/drivers/driver_lxc.go:4095]: @stgraber so when validating raw.lxc we don't need to also have the rest of the config available, as it liblxc doesn't do cross-key contextual validation (i.e in the original posters example, specifying an IP address on a NIC that doesn't exist yet)?

**Comment by tomponline** [comment]
See also https://github.com/lxc/lxd/pull/9094#issuecomment-894311983

File: lxd/main_forkconsole.go (hunk 2 above)
Comment (stgraber) [reply lxd/main_forkconsole.go:78]: The latter option sounds good. The former can be done but we'd want to remain in-package as we're trying to keep those forkXYZ codepaths as small as possible and need minimal involvement of goroutines and the like.

File: lxd/instance/drivers/driver_lxc.go (hunk 3 above)
Comment (stgraber) [reply lxd/instance/drivers/driver_lxc.go]: Fixed

File: lxd/main_forkconsole.go (hunk 2 above)
Comment (stgraber) [reply lxd/main_forkconsole.go]: @tomponline I've actually updated the branch now to only load raw.lxc during startup (forkstart/forkmigrate), the other cases should not need it, so it's actually more consistent to just not do it then (otherwise we'd need the C-only forkexec/forkmount to also do it).

**Comment by stgraber** [comment]
jenkins: test this please

File: lxd/main_forkconsole.go (hunk 2 above)
Comment (tomponline) [reply lxd/main_forkconsole.go]: In that case can it just stay being generated just startCommon rather than being added as two separate files, and only loaded in the scenarios where startCommon would be called anyway?

Comment (tomponline) [reply lxd/main_forkconsole.go]: So based on your comment https://github.com/lxc/lxd/pull/9094#commitcomment-54520855 the fix you added in `Update()` handles the validation issue. Then we dont need separate files as we can just only add the raw.lxc at the end in startCommon (for start and migrate scenarios you mention). As for calling it twice, I think other things would also fail in that case, like duplicate device setup conflicts, to not need to worry about that.

**Review by tomponline — CHANGES_REQUESTED** [review]
See https://github.com/lxc/lxd/pull/9095#discussion_r684346614

Just putting this here so it doesn't accidentally get merged, as don't want to introduce another config file unnecessarily.

File: lxd/main_forkconsole.go (hunk 2 above)
Comment (stgraber) [reply lxd/main_forkconsole.go]: @tomponline updated

**Review by tomponline — APPROVED** [review]
Looks good thanks. Just a thought though, does it also need validation at instance create time?

**Comment by stgraber** [comment]
That'd probably make sense and I considered it, it's just a bit annoying having to repeat that logic and in 99% of cases, creation is followed with start, so the error will occur anyway. It's more problematic when the config or profile is changed.

**Comment by stgraber** [comment]
@tomponline should be good to go
